// This file is generated

I_short_name_0 = [
", Abraham Abrahamsson",
", Adam Philipsson",
", Agnes",
", Agnes",
", Agnes",
", Agnes",
", Agnes",
", Agnes",
", Agnes Johansdotter",
", Agnes Josefsdotter",
", Agnes J\u00f6ransdotter",
", Agnes Mattsdotter",
", Agnes Mickelsdotter",
", Agnes M\u00e5rtensdotter",
", Agneta Jacobsdotter",
", Agneta Knutsdotter",
", Agneta Mattsdotter",
", Agneta Michelsdotter",
", Agneta Olofsdotter",
", Agneta P\u00e5hlsdotter",
", Agnetha Hendrichsdotter",
", Agnetha Sigfredsdotter",
", Agnetta Pettersdotter",
", Agnis",
", Agnis",
", Agnis",
", Agnis",
", Anders Ersson",
", Anders Henrichsson",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna Andersdotter",
", Anna Clemetsdotter",
", Anna Cnutsdotter",
", Anna Danielsdotter",
", Anna Erichsdotter",
", Anna Frantzdotter",
", Anna Gabrielintyt\u00e4r",
", Anna Hansdotter",
", Anna Hendrichsdotter",
", Anna Henrichsdotter",
", Anna Henricsdotter",
", Anna Johansdotter",
", Anna Johansdotter",
", Anna Johansdotter",
", Anna Johansdotter",
", Anna J\u00f6nsdotter",
", Anna J\u00f6ransdotter",
", Anna Matsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna Michelsdotter",
", Anna M\u00e5rtensdotter",
", Anna Nilsdotter",
", Anna Olofsdotter",
", Anna Olofsdotter",
", Anna Paulsdotter",
", Anna Pedersdotter",
", Anna Pedhersdotter",
", Anna Pehrsdotter",
", Anna P\u00e5hlsdotter",
", Anna Thomasdotter",
", Anna Thomasdotter",
", Anna Thomasdotter",
", Anna Agnetta J\u00f6ransdotter",
", Anna Maria J\u00f6ransdotter",
", Annika Pettersdotter",
", Ari",
", Arvid",
", Barbara Thomasdotter",
", Barbro",
", Barbro Eriksdotter",
", Bartolomeus Johannis",
", Beata",
", Beata",
", Beata",
", Beata",
", Beata Eliae",
", Beata Erichsdotter",
", Beata Eriksdotter",
", Beata Eriksdotter",
", Beata Hendricsdotter",
", Beata Henricsdotter",
", Beata Henricsdotter",
", Beata Johansdotter",
", Beata Mattsdotter",
", Beata Mattsdotter",
", Beatha Jacobsdotter",
", Beatha Johansdotter",
", Beatha Johansdotter",
", Birgit Thomasdotter",
", Brigita",
", Brigitha",
", Brigitta",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita Andersdotter",
", Brita Brusiusdotter",
", Brita Eskelsdotter",
", Brita Hendricsdotter",
", Brita Henricsdotter",
", Brita Hindrichsdotter",
", Brita Jacobsdotter",
", Brita J\u00f6ransdotter",
", Brita Knutsdotter",
", Brita Larsdotter",
", Brita Matsdotter",
", Brita Mattsdotter",
", Brita Mattsdotter",
", Brita Mattsdotter",
", Brita M\u00e5rtensdotter",
", Brita Olsdotter",
", Brita Philipsdotter",
", Brita P\u00e5hlsdotter",
", Brita P\u00e5hlsdotter",
", Brita P\u00e5hlsdotter",
", Brita Sigfridsdotter",
", Brita Simonsdotter",
", Brita Thomasdotter",
", Brita Thomasdotter",
", Brita Thomasdotter",
", Britha Hendersdotter",
", Britha M\u00e5nsdotter",
", Caisa",
", Caisa",
", Caisa Andersdotter",
", Caisa Ericsdotter",
", Caisa Henricsdotter",
", Caisa Henricsdotter",
", Caisa Henricsdotter",
", Caisa Jacobsdoter",
", Caisa Mattsdotter",
", Caisa Mattsdotter",
", Caisa Olofsdotter",
", Carin",
", Carin",
", Carin",
", Carin",
", Carin Clemetsdotter",
", Carin Henrichsdotter",
", Carin Larsdotter",
", Carin Mattsdotter",
", Carin Mattsdotter",
", Carin Olofsdotter",
", Carin P\u00e5hlsdotter",
", Carin Sigfridsdotter",
", Catarina Philipsdotter",
", Catharina",
", Catharina",
", Catharina J\u00f6ransdotter",
", Catharina Larsdotter",
", Chirstin",
", Chirstin",
", Chirstin Andersdotter",
", Chirstin Ericsdotter",
", Chirstin Henrichsdotter",
", Chirstin J\u00f6ransdotter",
", Chirstin Marcusdotter",
", Chirstin Mattsdotter",
", Chirstin Mattsdotter",
", Chirstin Olsdotter",
", Chirstin P\u00e5hlsdotter",
", Chirstin Sigfredsdotter",
", Christina",
", Christina Ericsdotter",
", Christina Johansdotter",
", Clara",
", Clara J\u00f6ransdotter",
", Clara Mattsdotter",
", Clara Peersdotter",
", Clemet Bertilsson",
", Daniel Abrahami",
", Didrik Persson",
", Dorde",
", Dorde Erichsdotter",
", Dorde Mattsdotter",
", Dordi",
", Dordi Mattsdotter",
", Dorothea",
", Dorothea Marcusdotter",
", Dorothea Mattsdotter",
", Dorothea Olofsdotter",
", Dorothea Thomasdotter",
", Elin",
", Elin",
", Elin",
", Elin",
", Elin",
", Elin",
", Elin",
", Elin Filpusdotter",
", Elin Hendersdotter",
", Elin Hendricsdotter",
", Elin J\u00f6ransdotter",
", Elin Larsdotter",
", Elin Larsdotter",
", Elin Mattsdotter",
", Elin Pavelsdotter",
", Elin P\u00e5lsdotter",
", Elina Juhantyt\u00e4r",
", Elisabet Jacobsdotter",
", Elisabeth",
", Elisabeth Hindricksdotter",
", Elisabeth Jacobsdotter",
", Elisabeth Mattsdotter",
", Elisabeth Nisiusdotter",
", Elisbeth J\u00f6ransdotter",
", Eric Abj\u00f6rnsson",
", Erich Johansson",
", Erich Petersson",
", Euphemia",
", Euphemia Bertelsdotter",
", Euphemia Eskilsdotter",
", Filpus Ivarsson",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud Andersdotter",
", Gertrud Andersdotter",
", Gertrud Brusiusdotter",
", Gertrud Erichsdotter",
", Gertrud Eskelsdotter",
", Gertrud Hendersdotter",
", Gertrud J\u00f6nsdotter",
", Gertrud J\u00f6ransdotter",
", Gertrud J\u00f6ransdotter",
", Gertrud J\u00f6ransdotter",
", Gertrud Larsdotter",
", Gertrud Mattsdotter",
", Gertrud M\u00e5rthensdotter",
", Gertrud Olofsdotter",
", Gertrud Pedersdotter",
", Gertrud Simonsdotter",
", Hebla",
", Hedvig Simonsdotter",
", Helena",
", Helga Henricsdotter",
", Helga Larsdotter",
", Helga Mattsdotter",
", Helga Peersdotter",
", Helga Thomasdotter",
", Hemming P\u00e5hlsson",
", Henric Josephsson",
", Henrich Bertilsson",
", Henrich Henrichsson",
", Henrich Pedersson",
", Henrich Sigfredsson",
", Inge Ingesson",
", Ingebog Simonsdotter",
", Ingeborg",
", Ingeborg",
", Ingeborg",
", Ingeborg Urbanusdotter",
", Ingrid Ingesdotter",
", Jeremias",
", Johan Johansson",
", Johan J\u00f6ransson",
", Johan Larsson",
", Johan Mattsson",
", Johanna",
", Johanna",
", Johanna Johansdotter",
", Johanna Sigfridsdotter",
", Johanna Simonsdotter",
", Joseph Nilsson",
", Judith Ericsdotter",
", J\u00f6ns",
", J\u00f6ns Bengtsson",
", J\u00f6ran",
", J\u00f6ran Eskilsson",
", J\u00f6ran Hansson",
", J\u00f6ran Jacobsson",
", J\u00f6ran Lukasson",
", J\u00f6ran Sigfridsson",
", Kaisa",
", Kaisa",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin Grelsdotter",
", Karin Hinrichsdotter",
", Karin J\u00f6ransdotter",
", Karin J\u00f6ransdotter",
", Karin Larsdotter",
", Karin Markusdotter",
", Karin Mattsdotter",
", Karin Mattsdotter",
", Katarina",
", Katarina",
", Katarina Petrusdotter",
", Kirstin",
", Kirstin",
", Kirstin",
", Kirstin",
", Kirstin",
", Kirstin",
", Kirstin",
", Kirstin Andersdotter",
", Kirstin Jacobsdotter",
", Kristin Michelsdotter",
", Kristina Henriksdotter",
", Kristina Ingesdotter",
", Lars Hindrichsson",
", Lastika",
", Leena",
", Lisa",
", Lisa",
", Lisa",
", Lisa",
", Lisa",
", Lisa",
", Lisa",
", Lisa",
", Lisa Andersdotter",
", Lisa Ersdotter",
", Lisa Henricsdotter",
", Lisa Hindrichsdotter",
", Lisa Johansdotter",
", Lisa Johansdotter",
", Lisa Johansdotter",
", Lisa Johansdotter",
", Lisa Johansdotter",
", Lisa J\u00f6ransdotter",
", Lisa Larsdotter",
", Lisa Samuelsdotter",
", Lisa Sigfredsdotter",
", Lisbeth Eskilsdotter",
", Lisbetha",
", Lucia Henrichsdotter",
", Lydeke",
", Madele Peersdotter",
", Magdalena M\u00e5rtensdotter",
", Maija Stiina Heikintyt\u00e4r",
", Maisa",
", Maisa",
", Maisa Eskellsdotter",
", Maisa Eskelsdotter",
", Maisa Hindersdotter",
", Maisa J\u00f6ransdotter",
", Maisa Marcusdotter",
", Malin",
", Malin Erichsdotter",
", Malin Eriksdotter",
", Marcus Marcusson",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta Ericsdotter",
", Margareta Henricsdotter",
", Margareta Henriksdotter",
", Margareta Hindrichsdotter",
", Margareta J\u00f6nsdotter",
", Margareta J\u00f6ransdotter",
", Margareta Larsdotter",
", Margareta Mattsdotter",
", Margareta Nilsdotter",
", Margareta Sunesdotter",
", Margaretha",
", Margaretha",
", Margeta",
", Margeta",
", Margeta",
", Margeta",
", Margeta Hendersdotter",
", Margeta Henrichsdotter",
", Margeta Mattsdotter",
", Margeta Nilsdotter",
", Margetha",
", Margetha",
", Margetha Henrichsdotter",
", Margetha Henrichsdotter",
", Margetha Marcusdotter",
", Margreta",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria Andersdotter",
", Maria Andersdotter",
", Maria Clemensdotter",
", Maria Cnutsdotter",
", Maria Ericsdotter",
", Maria Eskelsdotter",
", Maria Henricsdotter",
", Maria Hindrichsdotter",
", Maria Hindricsdotter",
", Maria Hinricsdotter",
", Maria Israelsdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria J\u00f6ransdotter",
", Maria J\u00f6ransdotter",
", Maria J\u00f6ransdotter",
", Maria J\u00f6ransdotter",
", Maria Larsdotter",
", Maria Marcusdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria M\u00e5rtensdoter",
", Maria M\u00e5rtensdotter",
", Maria P\u00e5hlsdotter",
", Maria Sigfridsdotter",
", Maria Simonsdotter",
", Maria Simonsdotter",
", Maria Thomasdotter",
", Maria Thomasdotter",
", Markus Jacobsson",
", Matti Matinpoika",
", Matts",
", Matts Erichsson",
", Matts Larsson",
", Matts Mattsson",
", Matts Mattsson",
", Matts Mattsson",
", Matts Olofsson",
", Michel Hinckasson",
", Michel J\u00f6ransson",
", M\u00e5rten",
", M\u00e5rten J\u00f6ransson",
", M\u00e4rta",
", N",
", N Henriksdotter",
", N Olofsdotter",
", Niina",
", Per Mattson",
", Peter Matsson",
", Pia",
", P\u00e5l P\u00e5lsson",
", Ragnell",
", Samuel J\u00f6ransson",
", Sara",
", Sara Henricsdotter",
", Scolastica Henriksdotter",
", Sigfridus Martini",
", Simon Ambrosiusson",
", Sisilia",
", Sofia",
", Sofia Henrichsdotter",
", Sofia Jacobsdotter",
", Sofia Jacobsdotter",
", Sofia Johansdotter",
", Sofia Juhontyt\u00e4r",
", Sofia J\u00f6ransdotter",
", Sofia Matintyt\u00e4r",
", Sofia Olofsdotter",
", Sofia Sigfredsdotter",
", Sophia",
", Sophia",
", Sophia",
", Sophia",
", Sophia",
", Sophia",
", Sophia Andersdotter",
", Sophia Clemetsdotter",
", Sophia Danielsdotter",
", Sophia Eskelsdotter",
", Sophia Hendrichsdotter",
", Sophia Henrichsdotter",
", Sophia Henrichsdotter",
", Sophia Henrichsdotter",
", Sophia Johansdotter",
", Sophia Johansdotter",
", Sophia Larsdotter",
", Sophia Larsdotter",
", Sophia Mathsdotter",
", Sophia M\u00e5rtensdotter",
", Sophia Olofsdotter",
", Sophia Pehrsdotter",
", Sophia Sigfredsdotter",
", Sophia Simonsdotter",
", Sten Henriksson",
", Stephanus Johansson",
", Stina Johansdotter",
", Sunnifva Markusdoter",
", Susanna Thomasdotter",
", Terttu",
", Thomas",
", Thomas Thomasson",
", Thomas Thomasson",
", Tomas Bertilsson",
", Tuve M\u00e5nsson",
", Ursula Peersdotter",
", Valborg Eskelsdotter",
", Valborg Hendersdotter",
", Valborg Mattsdotter",
", Valborg M\u00e5rtensdotter",
", Valborgh",
", Veijo",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg Andersdotter",
", Walborg Axelsdotter",
", Walborg Bertilsdotter",
", Walborg Erichsdotter",
", Walborg Erichsdotter",
", Walborg Ericsdotter",
", Walborg Eskilsdotter",
", Walborg Grelsdotter",
", Walborg Henrichsdotter",
", Walborg Henricsdotter",
", Walborg Henriksdotter",
", Walborg Jacobsdotter",
", Walborg Jacobsdotter",
", Walborg Johansdotter",
", Walborg J\u00f6rensdotter",
", Walborg Larsdotter",
", Walborg Mattsdotter",
", Walborg Petersdotter",
", Walborg P\u00e5hlsdotter",
", Walborg Sigfredsdotter",
", Walborg Sigridsdotter",
", Walborg Stephansdotter",
"Aakkola, Grels Henrichsson",
"Aakkola, Henrich Grelsson",
"Aakkola, Henrik Mattsson",
"Aakkola, Hindrich Hendersson",
"Aakkola, J\u00f6ran Mattsson",
"Aakkola, Maria J\u00f6ransdotter",
"Aakkola, Matts Hendersson",
"Acka, Anders",
"Acka, Lucas",
"Ackoila, Lasse",
"Ackoila, Matts Larsson",
"Akkanen, Anders Andersson",
"Akkanen, Anders Andersson",
"Akkanen, Anna Bertilsdotter",
"Akkanen, Anna Johansdotter",
"Akkanen, Bertill Larsson",
"Akkanen, Brita Lucasdotter",
"Akkanen, Carin Larsdotter",
"Akkanen, Catharina Bertsdotter",
"Akkanen, Helena Simonsdotter",
"Akkanen, Johan Johansson",
"Akkanen, Johan Johansson",
"Akkanen, Johan Lucasson",
"Akkanen, Lars Bertilsson",
"Akkanen, Lukas Andersson",
"Akkanen, Maria Lucasdotter",
"Akkanen, Peter Andersson",
"Akkanen, Riitta Heikintyt\u00e4r",
"Akkanen, Simon Andersson",
"Akkanen, Walborg",
"Akkanen, Walborg Petersdotter",
"Ala-Hinkkala, Hedvig Simontyt\u00e4r",
"Alakangas, Anna Maria Akselintyt\u00e4r",
"Alanen, Eric Ericsson",
"Alanen, Erich M\u00e5rtensson",
"Alanen, Eskell Henrichsson",
"Alanen, Henrich Erichsson",
"Alanen, Henrich Thomasson",
"Alanen, Henricus Henrichsson",
"Alanen, Johanna Heikintyt\u00e4r",
"Alanen, J\u00f6ran Erichsson",
"Alanen, Kirstin M\u00e5rtensdotter",
"Alanen, Michael Erichsson",
"Alanen, M\u00e5rten J\u00f6ransson",
"Alanen, M\u00e5rthen Henrichsson",
"Alanen, Thomas Nilsson",
"Amnelin, Anna",
"Ancherus, Erik Arvidsson",
"Ancherus, Johanna Ericsdotter",
"Anttila, Anders Eskelsson",
"Anttila, Anna Jacobsdotter",
"Anttila, Chirstin Johansdotter",
"Anttila, Johan Andersson",
"Anttila, Lisa Jacobsdotter",
"Anttila, Matts J\u00f6ransson",
"Anttila, M\u00e5rten Simonsson",
"Anttila, Simon J\u00f6ransson",
"Anttonen, Anna Pettersdotter",
"Anttonen, Maria Mattsdotter",
"Anttonen, Maria Ristontyt\u00e4r",
"Anttonen, Peter",
"Apiala, J\u00f6ran Mattsson",
"Apiala, Kirstin J\u00f6ransdotter",
"Apiala, Margareta J\u00f6ransdotter",
"Apiala, Maria J\u00f6ransdotter",
"Arvaja, Olof Hansson",
"Balk, M\u00e5ns Nilsson",
"Barck, Maria Samuelsdotter",
"Barck, Samuel Eriksson",
"Barkare, Jacob",
"Bergman, Margaretha",
"Birkman, Elias Henrici",
"Birkman, Gustaf Eliae",
"Birkman, Henrik Henriksson",
"Birkman, Henrik Jacobsson",
"Bj\u00f6rnram till Isn\u00e4s, Anna Engelbrektintyt\u00e4r",
"Bj\u00f6rnram till Isn\u00e4s, Engelbrekt Larsson",
"Bl\u00e5field, Anna Gustavsdotter",
"Bl\u00e5field, Bengt J\u00f6nsson",
"Bl\u00e5field, Gustaf Ivarsson",
"Bl\u00e5field, Gustaf Nilsson",
"Bl\u00e5field, Ivar Gustafsson",
"Bl\u00e5field, Mickel Bengtsson",
"Bl\u00e5field, Nils Michelsson",
"Broke, Ingeborg Larsdotter",
"Broke, Lars Pedersson",
"Broman, Matts Josephsson",
"B\u00e4ck, Hedvig",
"B\u00f6\u00f6k, Elisabet Johansdotter",
"B\u00f6\u00f6k, Johan Johansson",
"B\u00f6\u00f6k, Johannes Bartholdi",
"B\u00f6\u00f6k, Thomas Johansson",
"Calle, D\u00f6nhoff",
"Cavall, Otto Gustafsson",
"Collmanna, Carin Johansdotter",
"Crawford (Williams), Elsie Ellen",
"Cuitti, Agnetha Mattsdotter",
"Cuitti, Matts J\u00f6ransson",
"Cuitti, Sophia Mattsdotter",
"Damfeldt, Stephan M\u00e5rtensson",
"Dj\u00e4kn, Bj\u00f6rn Pedersson",
"Dj\u00e4kn, Erengisle Bj\u00f6rnsson",
"Dj\u00e4kn, Klaus Lydekesson",
"Dj\u00e4kn, M\u00e4rta Erengilsdotter",
"Dj\u00e4kn, M\u00e4rta Klasdotter",
"Dufva till N\u00e4set, Jacob Bengtsson",
"D\u00f6nsby i Karis, Dynius Magnusson",
"D\u00f6nsby i Karis, Henrik Dyniusson",
"D\u00f6nsby i Karis, Magnus Dyniusson",
"D\u00f6nsby i Karis, Marietta Henriksdotter",
"Edesniemi, Anders Johansson",
"Edesniemi, Antti Antinpoika",
"Edesniemi, Maija Liisa Antintyt\u00e4r",
"Eeva, Abraham",
"Eeva, Abraham Andersson",
"Eeva, Anders Abrahamsson",
"Eeva, Anna Mattsdotter",
"Eeva, Aune Paavontyt\u00e4r",
"Eeva, Lars Abrahamsson",
"Eeva, Matts Larsson",
"Eeva, Paul Tobiasson",
"Eeva, Tobias Abrahamsson",
"Ekbom, Johanna",
"Ekel\u00f6f, Margareta Eriksdotter",
"Ekel\u00f6f i G\u00e4sterby, Erik Larsson",
"Elfvenberg, Susanna Elisabet",
"Elg, Anna Carlsdotter",
"Erkkil\u00e4, Elias Erkinpoika",
"Erkkil\u00e4, Eric Ericsson",
"Erkkil\u00e4, Helena Eliaantyt\u00e4r",
"Erkkil\u00e4, Leena Eliaantyt\u00e4r",
"Eskola, Eskell",
"Eskola, Johan Mattsson",
"Eskola, Johan Simonsson",
"Eskola, J\u00f6ns Sigfredsson",
"Eskola, J\u00f6ns Thomasson",
"Eskola, Lisa Johansdotter",
"Eskola, Margetha Pehrsdotter",
"Eskola, Maria Juhontyt\u00e4r",
"Eskola, Maria Mattsdotter",
"Eskola, Markku Matinpoika",
"Eskola, Matts J\u00f6nsson",
"Eskola, Matts Pehrsson",
"Eskola, Matts Pehrsson",
"Eskola, Pehr Mattsson",
"Eskola, Petrus Mattsson",
"Eskola, Sigfred Eskelsson",
"Eskola, Sofia Mattsdotter",
"Eskola, Stina Markuntyt\u00e4r",
"Eskola, Thomas J\u00f6nsson",
"Fincke, Elin G\u00f6dekesdotter",
"Fincke, G\u00f6deke",
"Fincke, G\u00f6deke den gamble",
"Fincke, Henrik",
"Fincke, Metta G\u00f6dekesdotter",
"Finnil\u00e4, Kirstin Philipsdotter",
"Finnil\u00e4, Philip Jacobsson",
"Fleming, Brita Persdotter",
"Fleming, Erik Hermansson",
"Fleming, Henrik Klasson",
"Fleming, Johan Henriksson",
"Fleming, Klaus Pedersson",
"Fleming, Magnus Klasson",
"Fleming, Peder",
"Fleming af Torlax, Brita Johansdotter",
"Fleming till Vijais i Rimito, Per Eriksson",
"Fleming till Villn\u00e4s, Herman Magnusson",
"Forssk\u00e5hl, Anna Charlotta Jacobsdotter",
"Forssk\u00e5hl, Jakob Johansson",
"Forssk\u00e5hl, Jakob Simonsson",
"Forssk\u00e5hl, Johan Jacobsson",
"Forssk\u00e5hl, Simon Sigfridi",
"Friis, Christina Henriksdotter",
"Friis, Henrich",
"Garp, Anders",
"Garp, J\u00f6ns Andersson",
"Garp, Kristina J\u00f6nsdotter",
"Greek, Brita Jacobsdotter",
"Greek, Brita Simonsdotter",
"Greek i Helsingfors, Jakob",
"Grip, Eric Michelsson",
"Grip, Johanna Sofia Erkintyt\u00e4r",
"Gr\u00f6nfelt, Bertil Mattsson",
"Gr\u00f6nfelt, Brita Bertilsdotter",
"Guthrie (Williams), Mayme Mildred",
"Haatainen, Anna Adamsdotter",
"Hahkalainen, Per",
"Haikonen, Anna Juhontyt\u00e4r",
"Haikonen, Bertil J\u00f6ransson",
"Haikonen, J\u00f6ran Bertilsson",
"Haikonen, J\u00f6ran Thomasson",
"Haikonen, Katri Simontyt\u00e4r",
"Haikonen, Simo Yrj\u00f6npoika",
"Hainari, Dionisius Peersson",
"Hakokanto, Olof Nilsson",
"Hakolahti, Per Sigfridsson",
"Haljala, Anders Simonsson",
"Haljala, Christina Andersdotter",
"Haljala, Simon Thomasson",
"Halonen, Benjam Benjamsson",
"Halonen, Benjamin Johansson",
"Halonen, Catharina Benjaminsdotter",
"Hampaala, Clemet Mikelsson",
"Hampaala, Henrik Marcusson",
"Hampaala, Johan J\u00f6ransson",
"Hampaala, J\u00f6ran Mattsson",
"Hampaala, Marcus Thomasson",
"Hampaala, Matts Hendersson",
"Hampaala, Thomas Clemetson",
"Hannin, Pehr",
"Hannin, Pehr Pehrsson",
"Hannukainen, Anna",
"Harola, J\u00f6ran Eskelsson",
"Harola, Maria J\u00f6ransdotter",
"Harvonen, Walborg Hindrichsdotter",
"Hassi, Ambrosius Thomasson",
"Hassi, J\u00f6ran Thomasson",
"Hassi, Maria Simonsdotter",
"Hassi, Matts Brusiusson",
"Hassi, Simon J\u00f6ransson",
"Hassi, Thomas Mattsson",
"Hassi, Thomas Olsson",
"Hatakka, Carin Paulsdotter",
"Hatakka, Catharina Christersdotter",
"Hatakka, Christer Christersson",
"Hatakka, Christer Henricsson",
"Hatakka, Hindrich",
"Hatakka, Maria Michelsdotter",
"Hatakka, Michel Christersson",
"Hauhalainen, Claes Jacobsson",
"Heikkil\u00e4, Grels Henriksson",
"Heikkil\u00e4, Henrik J\u00f6nsson",
"Heikkil\u00e4, Henrik Nilsson",
"Heikkil\u00e4, Hindrich Sigfredsson",
"Heikkil\u00e4, J\u00f6ns",
"Heikkil\u00e4, J\u00f6ran Larsson",
"Heikkil\u00e4, Maria Grelsdotter",
"Heikkil\u00e4, Maria Hindrichsdotter",
"Heikkil\u00e4, Maria Michelsdotter",
"Heikkil\u00e4, Maria Michelsdotter",
"Heikkil\u00e4, Michel Eskilsson",
"Heikkil\u00e4, Michel J\u00f6ransson",
"Heikkil\u00e4, Nils Henriksson",
"Heikkonen, Anna",
"Heikkonen, Brita Hansdotter",
"Heikkonen, Catharina Henricsdotter",
"Heikkonen, Elin Sigfredsdotter",
"Heikkonen, Hans",
"Heikkonen, Johan",
"Heikkonen, Sigfred Johansson",
"Heikkonen, Sophia Mattsdotter",
"Heikniemi, Edla Lydia Kallentyt\u00e4r",
"Heikniemi, Kalle Aataminpoika",
"Heiskanen, Elisabeth Johansdotter",
"Heiskanen, Johan J\u00f6ransson",
"Hentonen, Anders J\u00f6ransson",
"Hentonen, Anna",
"Hentonen, Clemet",
"Hentonen, Helena Lisa Petersdotter",
"Hentonen, J\u00f6ran",
"Hentonen, Peter Andersson",
"Hentonen, Walborg Clemetsdotter",
"Herkepaeus, Laurentius Andreasson",
"Herra, Gertrud Simonsdotter",
"Hiiri, Catharina Olofsdotter",
"Hiiri, Elma Elina",
"Hiiri, Georg Henricsson",
"Hiiri, Henric J\u00f6ransson",
"Hiiri, Johan J\u00f6ransson",
"Hiiri, Juho Juhonpoika",
"Hiiri, Juho Juhonpoika",
"Hiiri, Juho Juhonpoika",
"Hiiri, J\u00f6ran Thomasson",
"Hiiri, Katri Juhontyt\u00e4r",
"Hiiri, Laina Kaarin",
"Hiiri, Olof Thomasson",
"Hiiri, Thomas",
"Hiiri, Tuomas Simonpoika",
"Hiiri, Tuomas Tuomaanpoika",
"Hiiri, Tuomas Tuomaanpoika",
"Hinkka, Erik Sigfridsson",
"Hinkka, Michel Michelsson",
"Hinkka, Sigfrid Michelsson",
"Hinkkala, Maria J\u00f6ransdotter",
"Hinkkala, Valborg Eriksdotter",
"Hirvel\u00e4, Eeva Margareta Matintyt\u00e4r",
"Hoffman, Margareta",
"Hohtari, Carl Martinsson",
"Hohtari, Carl Petersson",
"Hohtari, Johan Petersson",
"Hohtari, Juhana Riitanpoika",
"Hohtari, Liisa Juhontyt\u00e4r",
"Hohtari, Maria Riitantyt\u00e4r",
"Hohtari, Matti Kaarlonpoika",
"Hohtari, Matts Petersson",
"Hohtari, M\u00e5rten Carlsson",
"Hohtari, Peter",
"Hohtari, Peter Matthsson",
"Hohtari, Riitta Matintyt\u00e4r",
"Hoikka, Saara",
"Hoivala, Helena Larsdotter",
"Hoivala, Lars Thomasson",
"Hokka, Ambrosius Persson",
"Hokka, Jacob Knutsson",
"Hokka, Knut Jacobsson",
"Hokka, Knut Mattsson",
"Hokka, Maria Margaretha M\u00e5rtensdotter",
"Hokka, Matts Brusiusson",
"Hokka, M\u00e5rten Knutsson",
"Hokka, Oloff Persson",
"Hokka, Peder Olsson",
"Hokkanen, Carin Nilsdotter",
"Hokkanen, Johan Cnuthsson",
"Hokkanen, Lars Nilsson",
"Hokkanen, Lasse",
"Hokkanen, Matts Johansson",
"Hokkanen, Nils Larsson",
"Hokkanen, Nils Larsson",
"Hokkanen, Sofia Mattsdotter",
"Hopia, Anders Andersson",
"Hopia, Anders Christersson",
"Hopia, Christer",
"Hopia, Elisabeth",
"Hopia, Maria Matintyt\u00e4r",
"Hopia, Matts Andersson",
"Horn af Kanckas till Toijala i Halikko, Cecilia Jacobsdotter",
"Horn af \u00c5minne, Olof Mattsson",
"Horn till Toijala i Halikko, Jakob Olofsson",
"Hosikainen, Walborg",
"Hoskari, Jacob Mattsson",
"Hoskari, Jacob Mattsson",
"Hoskari, Matts Jacobsson",
"Hoskari, Matts Michelsson",
"Hoskari, Walborg Jacobsdotter",
"Hotokka, Madlena Christoffersdotter",
"Huikuri, Bengt M\u00e5rtensson",
"Huikuri, Hedvig Johansdotter",
"Huikuri, Helena Johansdotter",
"Huikuri, Henrich Mattsson",
"Huikuri, Johan Henricsson",
"Huikuri, J\u00f6ran Bengtsson",
"Huikuri, Maria Mattsdotter",
"Huikuri, Matts Simonsson",
"Huikuri, M\u00e5rthen Marcusson",
"Huikuri, Simon J\u00f6ransson",
"Hujala, Eeva Juhontyt\u00e4r",
"Hujala, Johan Mattsson",
"Hujala, Matts M\u00e5rtensson",
"Hujala, M\u00e5rten Thomasson",
"Hujala, Thomas Clemetsson",
"Hukki, Lars Larsson",
"Hulipas, Erasmus Frantzon",
"Hulipas, Frantz J\u00f6ransson",
"Hulipas, Henrich Simonsson",
"Hulipas, Henrik Johansson",
"Hulipas, Johan Hendersson",
"Hulipas, Johan Johansson",
"Hulipas, J\u00f6ran Thomasson",
"Hulipas, Kirstin Simonsdotter",
"Hulipas, Maria Johansdotter",
"Hulipas, Matts Erasmusson",
"Hulipas, Simo Heikinpoika",
"Hulipas, Simon Rasmusson",
"Humalainen, Katarina Johansdotter",
"Huntila, Matts S\u00f6fringsson",
"Huovila, Carl Jacobsson",
"Huovila, Jacob Thomasson",
"Huovila, Maria Carlsdotter",
"Huovila, Olof Olofsson",
"Huovila, Thomas Olofsson",
"Huovinen, Gertrud Hansdotter",
"Huppunen, Bertil Eskelsson",
"Huppunen, Brigitta",
"Huppunen, Eskell",
"Huppunen, Helena Bertilsdotter",
"Huppunen, Walborg Bertilsdotter",
"Huuhka, Anders J\u00f6ransson",
"Huuhka, Anna Cnutsdotter",
"Huuhka, Ingeborg Mattsdotter",
"Huuhka, Matts",
"Huuhka, Sophia",
"Huuska, Brita Henricsdotter",
"Hynninen, Johanna",
"Hyrynen, Maria",
"Hyv\u00f6nen, Anders P\u00e5hlsson",
"Hyv\u00f6nen, Henrik Andersson",
"Hyv\u00f6nen, Matts Henricsson",
"Hyyryl\u00e4, Hindrich M\u00e5rthensson",
"Hyyryl\u00e4, Matts Henrichsson",
"Hyyryl\u00e4, Matts Mattsson",
"Hyyti\u00e4inen, Agnetha",
"H\u00e4kkinen, Anders Cristiansson",
"H\u00e4kkinen, Cnunuth Michelsson",
"H\u00e4kkinen, Elin Erichsdotter",
"H\u00e4kkinen, Elin Simonsdotter",
"H\u00e4kkinen, Maria Andersdotter",
"H\u00e4kkinen, Michel Michelsson",
"H\u00e4kkinen, Michel P\u00e5hlsson",
"H\u00e4kkinen, P\u00e5hl",
"H\u00e4kli, Brita",
"H\u00e4kli, Stephan Bertilsson",
"H\u00e4m\u00e4l\u00e4inen, Helena Simonsdotter",
"H\u00e4m\u00e4l\u00e4inen, Jacob Simonsson",
"H\u00e4m\u00e4l\u00e4inen, Simon",
"H\u00e4m\u00e4l\u00e4inen, Simon Jacobsson",
"H\u00e4nnik\u00e4inen, Beatha Petersdotter",
"H\u00e4nnik\u00e4inen, Liisa Mikontyt\u00e4r",
"H\u00e4nnik\u00e4inen, Petter",
"H\u00e4nninen, Andreas Petersson",
"H\u00e4nninen, Antti Juhonpoika",
"H\u00e4nninen, Eeva Antintyt\u00e4r",
"H\u00e4nninen, Erich Henrichsson",
"H\u00e4nninen, Henrich Henrichsson",
"H\u00e4nninen, Henrich Mattsson",
"H\u00e4nninen, Henrich Thomasson",
"H\u00e4nninen, Johan Andersson",
"H\u00e4nninen, Liisa Matintyt\u00e4r",
"H\u00e4nninen, Matts Johansson",
"H\u00e4nninen, Matts Mattsson",
"H\u00e4nninen, Olof",
"H\u00e4nninen, Peter Petersson",
"H\u00e4nninen, Peter Petersson",
"H\u00e4nninen, Thomas Henrichsson",
"H\u00e4t\u00f6nen, Maria",
"H\u00e4t\u00f6nen, Maria Mattsdotter",
"H\u00e4t\u00f6nen, Matts",
"H\u00f6rts\u00e4n\u00e4, Clemet Henricsson",
"H\u00f6rts\u00e4n\u00e4, Eskel Staffansson",
"H\u00f6rts\u00e4n\u00e4, Eskil Clemetsson",
"H\u00f6rts\u00e4n\u00e4, J\u00f6ran Eskelsson",
"H\u00f6rts\u00e4n\u00e4, Staffan Eskilsson",
"i Fr\u00f6jdb\u00f6le, M\u00e5rten J\u00f6nsson",
"i G\u00e4sterby, Lasse",
"i H\u00e4rton\u00e4s, Margareta",
"i Strand i \u00c4lg\u00e5, N Salomonsdotter",
"i Strand i \u00c4lg\u00e5, Salomon",
"Ihalainen, Adam Mattsson",
"Ihalainen, Anna Martintyt\u00e4r",
"Ihalainen, Christer",
"Ihalainen, Maria Christersdotter",
"Ihalainen, Maria Reinholdsdotter",
"Ihalainen, Martin Adamsson",
"Ihalainen, Matts",
"Ihalainen, Matts Reinholdsson",
"Ihalainen, Reinhold Mattsson",
"Iili\u00e4inen, Brita",
"Ij\u00e4s, Anna Danielsdotter",
"Ij\u00e4s, Daniel",
"Ij\u00e4s, Daniel Gabrielsson",
"Ij\u00e4s, Daniel Gabrielsson",
"Ij\u00e4s, Eeva",
"Ij\u00e4s, Gabriel Danielsson",
"Ij\u00e4s, Gabriel Danielsson",
"Ikonen, Anna Wendela",
"Ikonen, V\u00e4in\u00f6",
"Immonen, Carin Henrichsdotter",
"Immonen, Henrick Michelsson",
"Immonen, Michel",
"Inkinen, Aina Aliina",
"Inkinen, Anders Christersson",
"Inkinen, Anna Andersdotter",
"Inkinen, Anna Eskellsdotter",
"Inkinen, Anna Heinrichsdotter",
"Inkinen, Aune Paavontyt\u00e4r",
"Inkinen, Brita Mattsdotter",
"Inkinen, Christer Jacobsson",
"Inkinen, Heinrich Heinrichsson",
"Inkinen, Heinrich Johansson",
"Inkinen, Helena Andersdotter",
"Inkinen, Henric Henricsson",
"Inkinen, Henric Lucasson",
"Inkinen, Henric Mattsson",
"Inkinen, Henrich",
"Inkinen, Jacob",
"Inkinen, Jacob Christersson",
"Inkinen, Jacob Mattsson",
"Inkinen, Johan Henricsson",
"Inkinen, Lena Petersdotter",
"Inkinen, Lucas",
"Inkinen, Maria",
"Inkinen, Maria Henricsdotter",
"Inkinen, Maria Mattsdotter",
"Inkinen, Matti Juhonpoika",
"Inkinen, Matts",
"Inkinen, Matts Jacobsson",
"Inkinen, Matts Lucasson",
"Inkinen, Paavo Yrj\u00f6npoika",
"Inkinen, Peter Henricsson",
"Iso-Attila, Clas Marcusson",
"Iso-Attila, Ivar Mattsson",
"Iso-Attila, Sunniva Sigfridstotter",
"Iso-Attila, Walborg Ivarsdotter",
"Iso-Attila, Walborg Thomasdotter",
"Isotalo, David J\u00f6ransson",
"Isotalo, Hedvig Elisabet Kallentyt\u00e4r",
"Isotalo, Johan M\u00e5rtensson",
"Isotalo, J\u00f6ran Davidsson",
"Isotalo, Kalle Taavetinpoika",
"Isotalo, Maria Johansdotter",
"Isotalo, M\u00e5rten J\u00f6ransson",
"Ivala, Christina Johansdotter",
"Ivala, Jacob Thomasson",
"Ivala, Johan Jacobsson",
"Ivala, Johan Johansson",
"Ivala, Joonas Matinpoika",
"Ivala, Matts Clemetsson",
"Ivala, Thomas Mattsson",
"Jaakkola, Erich Andersson",
"Jaakkola, Jacob Mattsson",
"Jaakkola, Juho Jaakonpoika",
"Jaakkola, Margetha Mattsdotter",
"Jaakkola, Maria Mattsdotter",
"Jaakkola, Matts Jacobsson",
"Javanainen, Amalia M\u00e5rtensdotter",
"Javanainen, Gertrud J\u00f6ransdotter",
"Javanainen, M\u00e5rten",
"Javanainen, Walborg M\u00e5rtensdotter",
"Jermolajeff, Anna Iivanantyt\u00e4r",
"Joensuu, Walborg Mattsdotter",
"Jokela, Juho Joonaanpoika",
"Jokela, Maija-Liisa Juhontyt\u00e4r",
"Jortikka, Anna Johansdotter",
"Jortikka, Carin Johansdotter",
"Jortikka, Carin Stephensdotter",
"Jortikka, Johan",
"Jortikka, Stephan Christersson",
"Jussila, Erik Eriksson",
"Jussila, Erik Mikilsson",
"Jussila, Eskill J\u00f6ransson",
"Jussila, Henrich Peersson",
"Jussila, Johan Eskilsson",
"Jussila, J\u00f6ns Thomasson",
"Jussila, J\u00f6ran Knutsson",
"Jussila, J\u00f6ran Thomasson",
"Jussila, Knuth Hendersson",
"Jussila, Margaretha J\u00f6ransdotter",
"Jussila, Simon Eriksson",
"Jussila, Thomas Simonsson",
"J\u00e4hdyspohja, Henrich J\u00f6ransson",
"J\u00e4hdyspohja, J\u00f6ran Larsson",
"J\u00e4ppinen, Aina",
"J\u00e4ppinen, Anders Andersson",
"J\u00e4ppinen, Anders Grelsson",
"J\u00e4ppinen, Antti Antinpoika",
"J\u00e4ppinen, Brita Grelsdotter",
"J\u00e4ppinen, Eija Inkeri",
"J\u00e4ppinen, Grels",
"J\u00e4ppinen, Grels Grelsson",
"J\u00e4ppinen, Grels Michelsson",
"J\u00e4ppinen, Heikki Antinpoika",
"J\u00e4ppinen, Heimo Einari",
"J\u00e4ppinen, Helena",
"J\u00e4ppinen, Henrik Anselm",
"J\u00e4ppinen, Hilma Maria",
"J\u00e4ppinen, Johan Johansson",
"J\u00e4ppinen, Johan Mattsson",
"J\u00e4ppinen, Maria Mikontyt\u00e4r",
"J\u00e4ppinen, Matti Mikonpoika",
"J\u00e4ppinen, Matti Mikonpoika",
"J\u00e4ppinen, Matts Grelsson",
"J\u00e4ppinen, Michel Grelsson",
"J\u00e4ppinen, Michel Johansson",
"J\u00e4ppinen, Mikko Matinpoika",
"J\u00e4ppinen, Varpu Matintyt\u00e4r",
"J\u00e4ppinen, Varpu Mikontyt\u00e4r",
"J\u00e4ppinen, William",
"J\u00e4rfgren, Jacob Jonasson",
"J\u00e4rfgren, Jonas Bengtsson",
"J\u00e4rvenp\u00e4\u00e4, Vilhelmina Juhontyt\u00e4r",
"J\u00e4rvensivu, Eric Johan Johansson",
"J\u00e4rvensivu, Johan Mattsson",
"J\u00e4rvensivu, Juho Kustaa Erkinpoika",
"J\u00e4rvensivu, Kalle Fredrik Kallenpoika",
"J\u00e4rvensivu, Kalle Kustaa Juhonpoika",
"J\u00e4rvensivu, Matts Johansson",
"J\u00e4rvinen, Anian Juhonpoika",
"J\u00e4rvinen, Anni",
"J\u00e4rvinen, Elma Elina",
"J\u00e4rvinen, Heikki Johannes",
"J\u00e4rvinen, Valma Ranni",
"J\u00e4\u00e4skel\u00e4inen, Helena",
"J\u00e4\u00e4skel\u00e4inen, Maria Hindricsdotter",
"Kaasalainen, Anders Johansson",
"Kaasalainen, Anna Johansdotter",
"Kaasalainen, Anna Pehrsdotter",
"Kaasalainen, Anna Stephansdotter",
"Kaasalainen, Brita",
"Kaasalainen, Brita Johansdotter",
"Kaasalainen, Carin J\u00f6ransdotter",
"Kaasalainen, Catharina J\u00f6ransdotter",
"Kaasalainen, Catharina Mattsdotter",
"Kaasalainen, Elisabeth",
"Kaasalainen, Elisabetha",
"Kaasalainen, Gustaf",
"Kaasalainen, Helena J\u00f6ransdotter",
"Kaasalainen, Hindrich",
"Kaasalainen, Johan",
"Kaasalainen, Johan Mattsson",
"Kaasalainen, J\u00f6ran",
"Kaasalainen, J\u00f6ran J\u00f6ransson",
"Kaasalainen, J\u00f6ran Mattson",
"Kaasalainen, J\u00f6ran Michelsson",
"Kaasalainen, Maria",
"Kaasalainen, Maria",
"Kaasalainen, Maria Mattsdotter",
"Kaasalainen, Maria Michelsdotter",
"Kaasalainen, Maria Mikontyt\u00e4r",
"Kaasalainen, Maria Petersdotter",
"Kaasalainen, Martin",
"Kaasalainen, Matthias Cnutsson",
"Kaasalainen, Matts",
"Kaasalainen, Matts Johansson",
"Kaasalainen, Michel",
"Kaasalainen, Michel J\u00f6ransson",
"Kaasalainen, Pehr",
"Kaasalainen, Stephan Hinrdichson",
"Kaasalainen, Stephan Stephansson",
"Kaasalainen, Walborg Johansdotter",
"Kaasalainen, Walborg Martinsdotter",
"Kahonen, Maria Pettersdotter",
"Kaipom\u00e4ki, Axel Johansson",
"Kaipom\u00e4ki, Chirstin Axelsdotter",
"Kaipom\u00e4ki, Eric Johansson",
"Kaipom\u00e4ki, Johan Larsson",
"Kaipom\u00e4ki, J\u00f6ns Larsson",
"Kaipom\u00e4ki, Lars Johansson",
"Kaitiainen, Maria Petersdotter",
"Kallio, Liisa Matintyt\u00e4r",
"Kallio, Samuli Samulinpoika",
"Kalliom\u00e4ki, Samuli Yrj\u00f6npoika",
"Kalliom\u00e4ki, Vilhelmiina Samulintyt\u00e4r",
"Kallonen, Yrj\u00f6 Juhonpoika",
"Kammonen, Pentti",
"Kanninen, Anna Bertilsdotter",
"Kanninen, Bertil Andersson",
"Kanninen, Magdalena Bertilsdotter",
"Kantala, J\u00f6ran Olofsson",
"Kantala, Maria J\u00f6ransdotter",
"Karikko, Erich Grelsson",
"Karikko, Erik Johansson",
"Karikko, Grels Eriksson",
"Karikko, J\u00f6ns Nilsson",
"Karikko, Margareta Samuelsdotter",
"Karikko, Rosina Samuelsdotter",
"Karikko, Samuel Eriksson",
"Karilainen, Anders",
"Karilainen, Anna",
"Karilainen, Anna Michelsdotter",
"Karilainen, Catharina",
"Karilainen, Elisabeth",
"Karilainen, Elisabeth",
"Karilainen, Elisabeth J\u00f6ransdotter",
"Karilainen, Matts",
"Karilainen, Michel Andersson",
"Karjalainen, J\u00f6ran",
"Karjula, Thomas Simonsson",
"Karonen, Helena Pehrsdotter",
"Karpinen, Anna Varpu Heikintyt\u00e4r",
"Karpinen, Henrik Matinpoika",
"Karvanen, Walborg Mickelsdotter",
"Karvia, Anders Andersson",
"Karvia, Anders Clemetsson",
"Karvia, Anders J\u00f6ransson",
"Karvia, Anna Stina Antintyt\u00e4r",
"Karvia, Cirstin Andersdotter",
"Karvia, Clemet Ersson",
"Karvia, Erik Grelsson",
"Karvia, Erik Nilsson",
"Karvia, Grels Erichsson",
"Karvia, Nils Olsson",
"Karvinen, Helena",
"Karvinen, Helena",
"Karvinen, Johan",
"Karvinen, Matts Johansson",
"Karvinen, Matts Mattsson",
"Kasoin, Cnuth",
"Kaukinen, Anna",
"Kaukinen, Maria Matintyt\u00e4r",
"Kaukinen, Simon",
"Kaukinen, Staffan Simonsson",
"Kaukinen, Walborg Staffansdotter",
"Kaukola, Saara Israelsdotter",
"Kaura, Johanna Michelsdotter",
"Kavala, Nils Dionisiusson",
"Kavala, Oluff Persson",
"Kavala, Per Oluffson",
"Keikkala, Clemet Mattsson",
"Keikkala, Matts Thomasson",
"Keikkala, Thomas Olsson",
"Keikkala, Thomas Thomasson",
"Kekki, Anna Matintyt\u00e4r",
"Kekki, Carin M\u00e5rtensdotter",
"Kekkonen, Henric Johansson",
"Kekkonen, Johan Henricsson",
"Kekkonen, Joseph Johansson",
"Kekkonen, Joseph Josephsson",
"Kekkonen, J\u00f6ns Larsson",
"Kekkonen, Olof",
"Kekkonen, Walborg Josephsdotter",
"Kemppi, Catharina Petersdotter",
"Kemppi, Pehr J\u00f6ransson",
"Keppil\u00e4, Kirsti Matintyt\u00e4r",
"Kerppola, Sofia Jacobsdotter",
"Kerppola, Thomas Johansson",
"Ketarin, Grels Henrichss",
"Kettunen, Anders Henricsson",
"Kettunen, Maria Andersdotter",
"Kienala, Anders Johansson",
"Kienala, Erich Larsson",
"Kienala, Israel Andersson",
"Kienala, Johan Ericsson",
"Kierros, Bertil Mattsson",
"Kierros, Henrich Mattsson",
"Kierros, Margareta Bertilsdotter",
"Kierros, Matts Hindersson",
"Kihlala, Maria Henricsdoter",
"Kihlala, Maria Johansdotter",
"Kiiski, Brita",
"Kiiski, Maria Mattsdotter",
"Kiiski, Paul Johansson",
"Kiiski, Thomas",
"Kiiski, Walborg Thomasdotter",
"Kiiveri, Johan",
"Kilpel\u00e4inen, Ingeborg Petersdotter",
"Kilpel\u00e4inen, Lars",
"Kilpel\u00e4inen, Peter Larsson",
"Kinkkunen, Elisabeth",
"Kinnari, Brigitta Hindricksdotter",
"Kinnari, Maria",
"Kinnari, Maria Stephansdotter",
"Kirsta, Isac Henricsson",
"Kitunen, Anna M\u00e5rtensdotter",
"Kitunen, Walborg Olofsdotter",
"Kivioja, Jonas Adamsson",
"Knepp, Simon Andersson",
"Knuutila, Henrich Henrichsson",
"Knuutila, Henrik M\u00e5nsson",
"Knuutila, M\u00e5ns Matsson",
"Knuutila, Samuel Henrichsson",
"Koiranen, Brita",
"Koivisto, Anna Henricsdotter",
"Koivisto, Henric Olofsson",
"Koivisto, Henrich Olofsson",
"Koivisto, Olof Jacobsson",
"Koivisto, Olof Olofsson",
"Koivuniemi, J\u00f6ren Mattsson",
"Koivuniemi, Matts Pehrsson",
"Koivuniemi, Peder",
"Kokko, Knut Nilsson",
"Kokko, Nils Bertilsson",
"Kolehma, Anna Eliasdotter",
"Kolehma, Elias J\u00f6ransson",
"Kolhi, Anna Gustafsdotter",
"Kolhi, Gustaf Johansson",
"Kolhi, Johan Olofsson",
"Kolhi, Maria Henricsdotter",
"Kolienp\u00e4\u00e4, Oleff Laurisson",
"Kolkka, Carin Michelsdotter",
"Kolkkanen, Helena Georgsdotter",
"Kontti, Gustaf Andersson",
"Kopok, Maria",
"Koppanen, Anna Maria Juhontyt\u00e4r",
"Koppanen, Juho Matinpoika",
"Koppanen, Matti Tuomaanpoika",
"Koppanen, Matti Tuomaanpoika",
"Koppanen, Paul Andersson",
"Koppanen, Thomas Paulsson",
"Koppanen, Tuomas Matinpoika",
"Koppeloj\u00e4rvi, Kustaava Manuntyt\u00e4r",
"Koppeloj\u00e4rvi, Maria Tapanintyt\u00e4r",
"Koppeloj\u00e4rvi, Stephan Thomasson",
"Koppeloj\u00e4rvi, Thomas Stephansson",
"Kopra, Maria",
"Korkka, Agnetha Petersdotter",
"Korpelainen, Kaarina Matintyt\u00e4r",
"Korpi, Eskill Augustinsson",
"Korppila, Lisa Michelsdotter",
"Korpula, Anna Henrikcsdotter",
"Korpula, Carin J\u00f6ransdotter",
"Korpula, Hendrich Erichsson",
"Korpula, Henric Simonsson",
"Korpula, Henrich Mattsson",
"Korpula, J\u00f6ran Henricsson",
"Korpula, Simon Henricsson",
"Koski, Bertil Thomasson",
"Koski, Gertrud Bertilsdotter",
"Koski, J\u00f6ran M\u00e5rtensson",
"Koski, Walborg J\u00f6ransdotter",
"Kotonen, Carin Simonsdotter",
"Kotonen, Johan J\u00f6ransson",
"Kotonen, J\u00f6ran",
"Kotonen, Simon Johansson",
"Kotti, Anna Antintyt\u00e4r",
"Kottila, Johan P\u00e5hlsson",
"Kottila, Maria Johansdotter",
"Kuggb\u00f6le, Brita Sigfridsdotter",
"Kuggb\u00f6le, Sigfrid",
"Kuisma, Agneta",
"Kuisma, Paavo",
"Kukko, Abram",
"Kukko, Agnetha J\u00f6ransdotter",
"Kukko, Anna Abramsdotter",
"Kukko, Anna Bertelsdotter",
"Kukko, Anna Johansdotter",
"Kukko, Bertel",
"Kukko, Bertel",
"Kukko, Brita Abramsdotter",
"Kukko, Christer Johansson",
"Kukko, Christer J\u00f6ransson",
"Kukko, Georg Christersson",
"Kukko, Georg Johansson",
"Kukko, Johan Christersson",
"Kukko, Maria",
"Kukko, Maria",
"Kukko, Maria Christersdotter",
"Kukko, Maria J\u00f6ransdotter",
"Kukko, Philip",
"Kukko, Walborg Bertelsdotter",
"Kukkonen, Margaretha",
"Kukkonen, Matts",
"Kukkonen, Matts Mattsson",
"Kukkula, Justinus Justinuksenpoika",
"Kulkas, Johan Michelsson",
"Kulkas, J\u00f6ran Johansson",
"Kulkas, J\u00f6ran J\u00f6ransson",
"Kulkas, J\u00f6ran Mattsson",
"Kulkas, Matts J\u00f6ransson",
"Kulkas, Michel Simonsson",
"Kulkas, Olof",
"Kulkas, Simon Olsson",
"Kulkas, Walborg J\u00f6ransdotter",
"Kultanen, Helena Mattsdotter",
"Kultanen, Mathias J\u00f6ransson",
"Kupo, Elisabeth Henricsdotter",
"Kupo, Henric Jacobsson",
"Kupo, Jacob",
"Kurikka, Anders Christersson",
"Kurikka, Christer Matsson",
"Kurikka, Maria Matthiasdotter",
"Kurikka, Mathias Andersson",
"Kuronen, Anders Henricsson",
"Kuronen, Anna",
"Kuronen, Elisabeth Andersdotter",
"Kuronen, Henric",
"Kurra, Henric Johansson",
"Kurra, Sofia Johansdotter",
"Kurrinen, Maria Samuelsdotter",
"Kurrinen, Samuel Petersson",
"Kutinlahti, Henrich Michelsson",
"Kutinlahti, J\u00f6ran Henrichsson",
"Kuuppo, Brita Jacobsdotter",
"Kuusj\u00e4rvi, Elias Olofsson",
"Kuusj\u00e4rvi, Sofia Eliasdotter",
"Kyll\u00f6nen, Maria Michelsdotter",
"Kyll\u00f6nen, Walborg",
"Kylm\u00e4, Walborg",
"Kylm\u00e4melli, Manu Tuomaanpoika",
"Kylm\u00e4melli, Thomas Mattsson",
"Kym\u00e4l\u00e4inen, Carin",
"Kyyr\u00f6, Anna Eskontyt\u00e4r",
"Kyyr\u00f6, Eskil Johansson",
"Kyyr\u00f6, Hindrich Mattsson",
"Kyyr\u00f6, Johan",
"Kyyr\u00f6, Matts Hendricsson",
"K\u00e4h\u00f6nen, Walborg Ericsdotter",
"K\u00e4nk\u00e4nen, Agnetha Mattsdotter",
"K\u00e4nk\u00e4nen, Mathias Petersson",
"K\u00e4nk\u00e4nen, Peter Simonsson",
"K\u00e4nk\u00e4nen, Simon",
"K\u00e4ppi, Anders Mattsson",
"K\u00e4ppi, Anna Henricsdotter",
"K\u00e4ppi, Maria Andersdotter",
"K\u00e4ppi, Matts",
"K\u00f6lhi, Margareta",
"K\u00f6mi, Eskel Larsson",
"K\u00f6mi, Eskell P\u00e5fwelsson",
"K\u00f6mi, Hendrich Eskilsson",
"K\u00f6mi, Johan Larsson",
"K\u00f6mi, Lars",
"K\u00f6mi, Lars Eskelsson",
"K\u00f6mi, Lars Larsson",
"K\u00f6mi, Matts Henrichsson",
"K\u00f6mi, P\u00e5hl Larsson",
"K\u00f6mi, Walborg Henrichsdotter",
"K\u00f6ntter, Sigfrid",
"K\u00f6ntt\u00e4ri, J\u00f6ran Larsson",
"K\u00f6ntt\u00e4ri, Kirstin J\u00f6ransdotter",
"K\u00f6ntt\u00e4ri, Lars Sigfridsson",
"K\u00f6yk\u00e4np\u00e4\u00e4, Maria Samuelsdotter",
"Laaksi, Akseli Erkki",
"Laaksi, Caisa J\u00f6ransdotter",
"Laaksi, Emanuel Johansson",
"Laaksi, Hendrich Olofsson",
"Laaksi, Johan Johansson",
"Laaksi, Johan Thomasson",
"Laaksi, J\u00f6ren Ohlsson",
"Laaksi, J\u00f6ren P\u00e5fwelsson",
"Laaksi, Maria Henricsdotter",
"Laaksi, Matts P\u00e5hlsson",
"Laaksi, Olof P\u00e5hlsson",
"Laaksi, P\u00e5fwel J\u00f6ransson",
"Laaksi, P\u00e5hl Bertilsson",
"Laaksi, Thomas J\u00f6ransson",
"Laaksi, Thomas Thomasson",
"Laalahti, Henrich Olsson",
"Laalahti, Henrik Michelsson",
"Laalahti, Michel Henriksson",
"Laalahti, Olof Henrichsson",
"Laalahti, Valborg Henriksdotter",
"Laasola, Gudmund Henrichsson",
"Lahnajoki, Anna Loviisa Kallentyt\u00e4r",
"Lahnajoki, Carl Johansson",
"Lahnajoki, Heta Kristiina Erkintyt\u00e4r",
"Lankinen, Carin Mattsdotter",
"Lapakko, Margaretha B\u00e4rtilsdotter",
"Lappalainen, Anna Simonsdotter",
"Lappalainen, Carin Johansdotter",
"Lappalainen, Elisabeth",
"Lappalainen, Helena Henrichsdotter",
"Lappalainen, Henrich",
"Lappalainen, Johan",
"Lappalainen, Johan Larsson",
"Lappalainen, Lars",
"Lappalainen, Maria",
"Lappalainen, Maria Tuomaantyt\u00e4r",
"Lappalainen, Simon Johansson",
"Lappi, Carin Mattsdotter",
"Lappi, Matts Pedhersson",
"Laurikainen, Maria",
"Laurila, Anna Henricsdotter",
"Laurila, Anna Mattsdotter",
"Laurila, Cnut Eskilsson",
"Laurila, Eskil Ericsson",
"Laurila, Filipus Marcusson",
"Laurila, Henrich Claesson",
"Laurila, Karin Thomasdotter",
"Laurila, Lars Cnutsson",
"Laurila, Marcus Larsson",
"Laurila, Matts Mattsson",
"Laurila, Thomas Filipusson",
"Leini\u00e4inen, Bertil Olofsson",
"Leini\u00e4inen, Maria Bertilsdotter",
"Leini\u00e4inen, Olof",
"Lepola, Pentti",
"Lepp\u00e4j\u00e4rvi, Stina Liisa Kustaantyt\u00e4r",
"Lepp\u00e4nen, Anders",
"Lepp\u00e4nen, Brita Larsdotter",
"Lepp\u00e4nen, Carin Thomasdotter",
"Lepp\u00e4nen, Lars Andersson",
"Lepp\u00e4nen, Pekka Tuomaanpoika",
"Liimatta, Hanna",
"Lilius, Maria Elisabeth",
"Lintu, Lars P\u00e5hlsson",
"Lintula, Bengt Larsson",
"Lintula, Bertil Bengtsson",
"Lintula, Jacob Simonsson",
"Lintula, Lisa Simonsdotter",
"Lintula, Lisa Thuresdotter",
"Lintula, Simon Bertilsson",
"Lintula, Simon Thuresson",
"Lintunen, Carin Adamsdotter",
"Lipponen, Brita Mattsdotter",
"Lipponen, Matts",
"Lipponen, Matts Mattsson",
"Lius, Anders",
"Lius, Maria Andersdotter",
"Lius, Matts Andersson",
"Liuttula, Margareta Thomasdotter",
"Loimusalo, Veikko Aulis",
"Loponen, Carin Thomasdotter",
"Loponen, Henric",
"Loponen, Maria",
"Loponen, Thomas Henricsson",
"Lukkari, Anna Carlsdotter",
"Lukkari, Carl J\u00f6ransson",
"Lukkari, Hendrich Thomasson",
"Lukkari, J\u00f6ren Larsson",
"Lukkari, Lars Hindersson",
"Lukkari, Tomas Nilsson",
"Luostarinen, Walborg",
"Luukkanen, Anna Cnutsdotter",
"Luukkanen, Anna Mattsdotter",
"Luukkanen, Bertill",
"Luukkanen, Brita",
"Luukkanen, Elisabeth Eskilsdotter",
"Luukkanen, Eskil J\u00f6ransson",
"Luukkanen, Helga Helena",
"Luukkanen, Maria Stephansdotter",
"Luukkanen, Mats Bertilsson",
"Luukkanen, Simon Bertilsson",
"Luukkanen, Stephan Simosson",
"Luukkanen, Stephan Stephansson",
"Lydick, J\u00f6ns Olsson",
"Lydick, Nils",
"Lydick, Oleff Nilsson",
"L\u00e5ng, Anna Thomasdotter",
"L\u00e5ng, Matts Hansson",
"L\u00e4tt, Isaacus Nicolai",
"L\u00e4tt, Isac Isaaci",
"L\u00e4tt, Walborg Isacsdotter",
"L\u00e4tti, Brita",
"L\u00e4tti, Helena Eskelsdotter",
"L\u00e4tti, Nils Olofsson",
"L\u00e4ttil\u00e4, Anna Maria J\u00f6ransdotter",
"L\u00e4ttil\u00e4, J\u00f6ran Mattsson",
"L\u00e4ttil\u00e4, J\u00f6ran Thomasson",
"L\u00e4ttil\u00e4, Lasse Eriksson",
"L\u00e4ttil\u00e4, Matts J\u00f6ransson",
"L\u00e4ttil\u00e4, Simon Larsson",
"L\u00e4ttil\u00e4, Thomas Simonsson",
"L\u00e4\u00e4veri, Brigita Mathiae",
"L\u00e4\u00e4veri, Mathias Staffansson",
"L\u00f6yt\u00e4n\u00e4, Anna Stephansdotter",
"L\u00f6yt\u00e4n\u00e4, Carin Jacobsdotter",
"L\u00f6yt\u00e4n\u00e4, Hindrich Staffansson",
"L\u00f6yt\u00e4n\u00e4, Staffan Henrichsson",
"Maijala, Anna Liisa Juhontyt\u00e4r",
"Maijala, Jacob Thomasson",
"Maijala, Juho Yrj\u00f6npoika",
"Maijala, Maria Jacobsdotter",
"Maijala, Thomas Nilsson",
"Maijala, Yrj\u00f6 Juhonpoika",
"Makkara, Eeva Matintyt\u00e4r",
"Makkonen, Catharina Pettersdotter",
"Makkonen, Henric Mattsson",
"Makkonen, Matts",
"Mannikainen, Maija-Liisa",
"Mannikainen, Maila",
"Mannikainen, P\u00e5hl Hindricsson",
"Mannikainen, Simo",
"Manninen, Carin Isacsdotter",
"Manninen, Henrich Mattsson",
"Manninen, Isac Henrichsson",
"Manninen, Jacob",
"Manninen, Lasse",
"Manninen, Matts Jacobsson",
"Marttila, Cnuth Brusiusson",
"Marttila, Elin Mattsdotter",
"Marttila, Erich Knutsson",
"Marttila, Henrich Johansson",
"Marttila, Johan Sigfredsson",
"Marttila, Marcus M\u00e5rtensson",
"Marttila, Matts Cnuthsson",
"Marttila, Matts Erichsson",
"Marttila, M\u00e5rten Markusson",
"Marttila, Sigfred M\u00e5rtensson",
"Marttila, Simon Henrichsson",
"Marttila, Simon Simonsson",
"Marttinen, Henrik",
"Marttinen, Henrik Henriksson",
"Marttinen, Johan Mattsson",
"Marttinen, J\u00f6ns",
"Marttinen, Lars Hendersson",
"Marttinen, Margeta Johansdotter",
"Marttinen, Matts Johansson",
"Matikainen, Walborg",
"Matilainen, Mauno",
"Mattila, Anders J\u00f6ransson",
"Mattila, Eskill Thomasson",
"Mattila, Hedvig Kallentyt\u00e4r",
"Mattila, Ida Juhontyt\u00e4r",
"Mattila, Juho Yrj\u00f6npoika",
"Mattila, Juho Kustaa Juhonpoika",
"Mattila, Juho Oskar Juhonpoika",
"Mattila, J\u00f6ran Andersson",
"Mattila, J\u00f6ran J\u00f6ransson",
"Mattila, J\u00f6ran Mattsson",
"Mattila, Kalle Kustaanpoika",
"Mattila, Maria J\u00f6ransdotter",
"Mattila, Matts Henrici",
"Mattila, Matts Staffansson",
"Mattila, Staffan Eskelsson",
"Mattila, Thomas Mattsson",
"Mattila, Yrj\u00f6 Yrj\u00f6npoika",
"Maunula, Anna J\u00f6ransdotter",
"Maunula, Escill M\u00e5nsson",
"Maunula, Johan Samuelsson",
"Maunula, J\u00f6ran Ericsson",
"Maunula, J\u00f6ran Escilsson",
"Maunula, Magnus Henricsson",
"Maunula, Magnus Mattsson",
"Maunula, Maria Thomasdotter",
"Maunula, Matts Escilsson",
"Maunula, Matts Magnusson",
"Maunula, Olof Mattsson",
"Maunula, Samuel J\u00f6ransson",
"Maunula, Thomas Olofsson",
"Maunula, Walborg Johansdotter",
"Melin, Maria",
"Melli, Bengt Mattsson",
"Melli, Magnus Bengtsson",
"Melli, Margetha Magnusdotter",
"Melli, Matts Persson",
"Melli, Matts Simonsson",
"Melli, Per",
"Melli, Simon Thomasson",
"Melli, Thomas Henricsson",
"Melli, Thomas Thomasson",
"Melli, Walborg Simonsdotter",
"Meltonen, Maria Mattsdotter",
"Meltonen, Matts",
"Mentu, Andreas Larsson",
"Mentu, Maria Andersdotter",
"Meskanen, Anna",
"Meskanen, Anna Johansdotter",
"Meskanen, Carin J\u00f6ransdotter",
"Meskanen, Carin Simonsdotter",
"Meskanen, Johan",
"Meskanen, J\u00f6ran Simonsson",
"Meskanen, Simon Matsson",
"Mexberg, Gabriel Henricsson",
"Mexberg, Hedvig Kaapontyt\u00e4r",
"Mexberg, Hendrich",
"Mikkola, Adam Samuelsson",
"Mikkola, Erkki Juho Aataminpoika",
"Mikkola, Matts Michelsson",
"Mikkola, Michel J\u00f6nsson",
"Mikkola, P\u00e5hl Mattsson",
"Mikkola, Sophia P\u00e5hlsdotter",
"Mikkola, Walborg Marcusdotter",
"Minkkinen, Hindrich Larsson",
"Minkkinen, J\u00f6ran Mattsson",
"Minkkinen, J\u00f6ran Mattsson",
"Minkkinen, Matts Hendersson",
"Minkkinen, Matts J\u00f6ransson",
"Moisio, Aino",
"Moisio, Juho Vilhelm Kustaanpoika",
"Moksu, Anna Elia'dotter",
"Moksu, Elias Nilsson",
"Mong\u00e5, Johan Johansson",
"Mononen, Brita Johansdotter",
"Mononen, Clemet Mattsson",
"Mononen, Henrich Mattsson",
"Mononen, Johan Henrichsson",
"Mononen, Matts",
"Mononen, Matts Clemetsson",
"Montonen, Catharina",
"Mosalainen, Anders Henricsson",
"Muikonen, Maria Christersdotter",
"Muli, Brita Petersdotter",
"Muli, Johan Johansson",
"Muli, Johan Lucasson",
"Muli, Johan Lucasson",
"Muli, Lucas Johansson",
"Muli, Lukas",
"Muli, Maria Petersdotter",
"Muli, Peter",
"Muli, Walborg Johansdotter",
"Muli, Walborg Lukasdotter",
"Mulkola, Maria Claesdotter",
"Mulli, Elisabetha Ericsdotter",
"Mulli, Erich Mattsson",
"Mulli, J\u00f6ran",
"Mulli, Matts Sigfredsson",
"Mulli, Sigfres Thomasson",
"Mulli, Thomas J\u00f6ransson",
"Mullikka, Hedvig Jacobsdotter",
"Mullikka, Jacob Johansson",
"Mullikka, Johan J\u00f6ransson",
"Multia, Kirstin Thomasdotter",
"Murtom\u00e4ki, Eskil Johansson",
"Murtom\u00e4ki, Fredrika Tuomaantyt\u00e4r",
"Murtom\u00e4ki, Thomas Eskilsson",
"Murtom\u00e4ki, Tuomas Tuomaanpoika",
"Musakka, Brigita Mattsdotter",
"Musakka, Catharina",
"Musakka, Elisabeth P\u00e5hlsdotter",
"Musakka, Maria Petersdotter",
"Musakka, Matts",
"Musakka, Matts",
"Musakka, Matts Mattsson",
"Musakka, Peter Mattsson",
"Musakka, P\u00e5hl",
"Musakka, Walborg",
"Musakka, Walborg Andersdotter",
"Mustonen, Anna",
"Mustonen, Carin Johansdotter",
"Mustonen, Catharina J\u00f6ransdotter",
"Mustonen, Henric Larsson",
"Mustonen, Henric Larsson",
"Mustonen, Johan",
"Mustonen, J\u00f6ran",
"Mustonen, J\u00f6ran",
"Mustonen, Kaisa Matintyt\u00e4r",
"Mustonen, Lars Henricsson",
"Mustonen, Matti Heikinpoika",
"Mustonen, Matts",
"Mustonen, Walborg J\u00f6ransdotter",
"Mustonen, Walborg Mattsdotter",
"Mutkari, Elisabeth Michelsdotter",
"Mutkari, Michel",
"Muuransuo, Kalle Aataminpoika",
"Muuriainen, Maria",
"Muurla i \u00c5bo, Margareta Nilsdotter",
"M\u00e4kel\u00e4, Kaarle Henrik Samulinpoika",
"M\u00e4kel\u00e4, Samuli Tuomaanpoika",
"M\u00e4kel\u00e4, Tuomas Manunpoika",
"M\u00e4kel\u00e4inen, Helga Helena Frantzdotter",
"M\u00e4ki, Henrich Sigfridsson",
"M\u00e4ki, Maria Henrichsdotter",
"M\u00e4ki, Sigfred Henrichsson",
"M\u00e4ki-Siukola, Kustaa Adolf Joonaanpoika",
"M\u00e4mmi, J\u00f6ran Thomasson",
"M\u00e4mmi, Lars Larsson",
"M\u00e4mmi, Thomas J\u00f6ransson",
"M\u00e4mmi, Thomas Larsson",
"M\u00e4nts\u00e4, Nils Larsson",
"M\u00e4nts\u00e4, Thomas Nilsson",
"M\u00e4ntt\u00e4, Caisa Mattsdotter",
"M\u00e4ntt\u00e4, Elin Mattsdotter",
"M\u00e4ntt\u00e4, Helena Markuksentyt\u00e4r",
"M\u00e4ntt\u00e4, Heta Kristiina Juhontyt\u00e4r",
"M\u00e4ntt\u00e4, Johan Johansson",
"M\u00e4ntt\u00e4, Johan Marcusson",
"M\u00e4ntt\u00e4, Juho Markuksenpoika",
"M\u00e4ntt\u00e4, Marcus Mattsson",
"M\u00e4ntt\u00e4, Marcus Thomasson",
"M\u00e4ntt\u00e4, Maria Johansdotter",
"M\u00e4ntt\u00e4, Maria Mattsdotter",
"M\u00e4ntt\u00e4, Matts Johansson",
"M\u00e4ntt\u00e4, Sigfred Johansson",
"M\u00e4ntt\u00e4, Thomas Thomasson",
"M\u00e4ntt\u00e4, Thomas Thomasson",
"M\u00e4ntt\u00e4, Walborg Sigfredsdotter",
"M\u00e4\u00e4tt\u00e4nen, Adam Larsson",
"M\u00e4\u00e4tt\u00e4nen, Cnut Michelsson",
"M\u00e4\u00e4tt\u00e4nen, Henric Adamsson",
"M\u00e4\u00e4tt\u00e4nen, J\u00f6ran Paulsson",
"M\u00e4\u00e4tt\u00e4nen, Lars Larsson",
"M\u00e4\u00e4tt\u00e4nen, Sara Cnutsdotter",
"M\u00e4\u00e4tt\u00e4nen, Walborg Henricsdotter",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N Knutsdotter",
"Naskali, Elias Thomasson",
"Naskali, Staffan",
"Naskali, Thomas Staffansson",
"Naskali, Walborg Eliasdotter",
"Natt och Dag, Margareta Tuvesdotter",
"Natukka, Agnis M\u00e5rtensdotter",
"Natukka, Elin Pehrsdotter",
"Natukka, Henrich Clemetsson",
"Natukka, M\u00e5rten Hendersson",
"Natukka, Peer M\u00e5rtensson",
"Nenonen, Erich",
"Nenonen, Hans",
"Nenonen, Henrich Pehrsson",
"Nenonen, Johan Mattsson",
"Nenonen, Joseph Mattsson",
"Nenonen, Maria Ericsdotter",
"Nenonen, Matts Henricsson",
"Nenonen, Per Hansson",
"Neo, Walborg",
"Niemi, Henrich Mattsson",
"Niemi, Matts Henrichsson",
"Nifvenia, Carin Haqvinidotter",
"Nihti, Maria Bertilsdotter",
"Nihtil\u00e4, Henric Larsson",
"Nihtil\u00e4, J\u00f6ran Henriksson",
"Niikkula, Niels J\u00f6rensson",
"Niikkula, Sigfred Nielsson",
"Niikkula, Thomas Sigfredsson",
"Niikkula, Thomas Thomasson",
"Niikkula, Walborg Thomasdotter",
"Niinim\u00e4ki, Eric Jacobsson",
"Nikin-Eskola, Kalle Matinpoika",
"Nikin-Eskola, Matti Simonpoika",
"Nikin-Eskola, Vilhelmiina Kallentyt\u00e4r",
"Nikkil\u00e4, Anna Isacsdotter",
"Nikkil\u00e4, Bertill Cnuthsson",
"Nikkil\u00e4, Chirstin Johansdotter",
"Nikkil\u00e4, Christina Urbanusdotter",
"Nikkil\u00e4, Cnuth Nilsson",
"Nikkil\u00e4, Henrich Thomasson",
"Nikkil\u00e4, Isach Bertillsson",
"Nikkil\u00e4, Jacob Thomasson",
"Nikkil\u00e4, Kirstin Hindrichsdotter",
"Nikkil\u00e4, Maria Thomasdotter",
"Nikkil\u00e4, Matts Nilsson",
"Nikkil\u00e4, Nils Clemetsson",
"Nikkil\u00e4, Nils Knutsson",
"Nikkil\u00e4, Thomas Isacsson",
"Nikkil\u00e4, Urbanus Mattsson",
"Niukkanen, Nils",
"Niukkanen, Walborg Nilsdotter",
"Niuta, Brita Petersdotter",
"Niuta, Peter",
"Nokelainen, Carin Pettersdotter",
"Nokelainen, Catharina Johansdotter",
"Nokelainen, Elisabeth Henricsdotter",
"Nokelainen, Helena Olofsdotter",
"Nokelainen, Henric",
"Nokelainen, Johan",
"Nokelainen, Johan Johansson",
"Nokelainen, Maria J\u00f6ransdotter",
"Nokelainen, Maria Olovsdotter",
"Nokelainen, Matts",
"Nokelainen, Olov Mattsson",
"Nokelainen, Olov Petersson",
"Nokelainen, Peter",
"Nokelainen, Petter Henricsson",
"Nokre, Anna Mattsdotter",
"Nokre, Anna Tuomaantyt\u00e4r",
"Nokre, Hindric",
"Nokre, Johan Mattsson",
"Nokre, J\u00f6ran Hindricsson",
"Nokre, Maria Tahvontyt\u00e4r",
"Nokre, Matts J\u00f6ransson",
"Nokre, Stephan Mattsson",
"Nokre, Tuomas Juhonpoika",
"Nolo, Hendric",
"Nolo, Juho Juhonpoika",
"Nolo, J\u00f6ran Hendricsson",
"Nolo, Katri Juhontyt\u00e4r",
"Nolo, Maria J\u00f6ransdotter",
"Nuora, Anna",
"Nuottiniemi, Maria Isacsdotter",
"Nuottiniemi, Maria Mattsdotter",
"Nuottiniemi, Matheus Josephsson",
"Nurkka, Maria",
"Nyman, Antti Kustaa Antinpoika",
"Nyyss\u00f6nen, Maria Larsdotter",
"N\u00e4nnim\u00e4inen, Anna Mattsdotter",
"N\u00e4nnim\u00e4inen, Carin J\u00f6ransdotter",
"N\u00e4nnim\u00e4inen, J\u00f6ran",
"N\u00e4nnim\u00e4inen, Maria J\u00f6ransdotter",
"N\u00e4ppil\u00e4, Anders Simonsson",
"N\u00e4ppil\u00e4, J\u00f6ran Andersson",
"N\u00e4ri\u00e4inen, Heinrich Petersson",
"N\u00e4ri\u00e4inen, Peter Cnutsson",
"N\u00e4ri\u00e4inen, Peter Petersson",
"N\u00e4ri\u00e4inen, Simon Heinrichsson",
"N\u00e4ri\u00e4inen, Varpu Yrj\u00f6ntyt\u00e4r",
"N\u00e4ri\u00e4inen, Yrj\u00f6 Simonpoika",
"N\u00e4rv\u00e4, Elias Jacobsson",
"Olkinuora, Agnetha Simonsdotter",
"Olkinuora, Simon",
"Ollikainen, Anna Henricsdotter",
"Oranen, Anders Johansson",
"Oranen, Anna Andersdotter",
"Oranen, Johan",
"Ouni, Bertill Mattsson",
"Ouni, Johan Sigfridsson",
"Ouni, Sigfrid Thomasson",
"Ouni, Thomas Bertilsson",
"Paajanen, Anna Mattsdotter",
"Paajanen, Brigitta M\u00e5rtensdotter",
"Paajanen, Gregorius Mattsson",
"Paajanen, Henric Johansson",
"Paajanen, Johan Johansson",
"Paajanen, Johan Sigfredsson",
"Paajanen, Korius",
"Paajanen, Lisa Henriksdotter",
"Paajanen, Maria Gregoriusdotter",
"Paajanen, Maria J\u00f6ransdotter",
"Paajanen, Matts Gregoriusson",
"Paajanen, M\u00e5rten",
"Paajanen, Sigfred Gregoriusson",
"Paajanen, Walborg",
"Paakkanen, Anna Stephansdotter",
"Paakkanen, Joseph",
"Paakkanen, Stephan Josephsson",
"Paakkari, Jacob Thomasson",
"Paakkari, Michel Jacobsson",
"Paakkari, P\u00e5hl Michelson",
"Paakkari, Walborg Michelssotter",
"Paavilainen, Anna",
"Paavilainen, Maria Walborg Hindricsdotter",
"Paavola, Johan Larsson",
"Paavola, Stina Matintyt\u00e4r",
"Padustaipale, Anna Thomasdotter",
"Padustaipale, Henric Simonsson",
"Padustaipale, Maria Mattsdotter",
"Padustaipale, Matts Thomasson",
"Padustaipale, Per Erichsson",
"Padustaipale, Simon Peersson",
"Padustaipale, Thomas Simonsson",
"Pajari, Catharina Adamsdotter",
"Pakarinen, Anders J\u00f6ransson",
"Pakarinen, Anna Andersdotter",
"Pakarinen, Elisabeth",
"Pakarinen, Ingeborg",
"Pakarinen, J\u00f6ran Pettersson",
"Pakom\u00e4ki, Adam Staphansson",
"Palander, Abraham Axelio",
"Palander, Lisa Pehrsdotter",
"Palander, Petrus",
"Palander, Petter Pettersson",
"Pamppanen, Walborg",
"Pappinen, Simon Bertilsson",
"Papunen, Maria Larsdotter",
"Parkkali, Catharina Zachariasdotter",
"Parkkali, Zacharias Jacobsson",
"Parpola, Caisa Ericsdotter",
"Parpola, Maria J\u00f6ransdotter",
"Parpola, Sophia J\u00f6ransdotter",
"Partanen, Hindrich",
"Partanen, Stephan Hindrichsson",
"Partanen, Walborg Staffansdotter",
"Paso, Anna Sigfredsdotter",
"Pauhari, Eric Olofsson",
"Pauhari, Grels Thomasson",
"Pauhari, Henrich M\u00e5rtensson",
"Pauhari, Johan Olofsson",
"Pauhari, M\u00e5rten Ericsson",
"Pauhari, Olof",
"Pauhari, Olof Johansson",
"Pauhari, Thomas Henrichsson",
"Paukku, Anna Petersdotter",
"Paukku, Peter Henricsson",
"Paussu, Aatami Juhonpoika",
"Paussu, Johan Petersson",
"Paussu, Katri Aatamintyt\u00e4r",
"Paussu, Peter",
"Paussu, Peter P\u00e5hlsson",
"Paussu, P\u00e5hl Petersson",
"Pehu, Henric Thomasson",
"Pehu, Peder",
"Pehu, Thomas Pedersson",
"Pekkala, Abraham Juhonpoika",
"Pekkala, Aino Anna-Liisa",
"Pekkala, Axel Eriksson",
"Pekkala, Einar Arvid",
"Pekkala, Erik Axselsson",
"Pekkala, Juho Akselinpoika",
"Pellikainen, Erick",
"Pellikainen, Magdalena Helena Ericsdotter",
"Peltonen, Maria Pekantyt\u00e4r",
"Peltonen, Pekka",
"Pennanen, Carin Mattsdotter",
"Pennanen, Johan",
"Pennanen, Lars",
"Pennanen, Matts Larsson",
"Penttil\u00e4, Matts J\u00f6ransson",
"Penttinen, Catharina Mattsdotter",
"Penttinen, Matts",
"Perttula, Anders Christersson",
"Perttula, Bertel Erichsson",
"Perttula, Bertill M\u00e5rtensson",
"Perttula, Erich Simonsson",
"Perttula, Johan Bertilsson",
"Perttula, Lisa Bertilsdotter",
"Perttula, Maria Andersdotter",
"Perttula, Maria Simonsdotter",
"Perttula, Simon Johansson",
"Perttula, Simon M\u00e5rtensson",
"Pihlajalahti, Frans Jacobsson",
"Pihlajalahti, Johan J\u00f6ransson",
"Pihlajalahti, J\u00f6ran P\u00e4rsson",
"Pihlajalahti, Kirstin Johansdotter",
"Pihlajalahti, Petter Fransson",
"Pihlstr\u00f6m, Maria Ericsdotter",
"Piiparinen, Anna Andersdotter",
"Piippu, Catharina Johansdotter",
"Pirttisarka, Emanuel Matinpoika",
"Pitk\u00e4nen, Helena Juhontyt\u00e4r",
"Pitk\u00e4nen, Juho Simonpoika",
"Pitk\u00e4nen, J\u00f6ran Andersson",
"Pitk\u00e4nen, Maria Gabrielsdotter",
"Pitk\u00e4nen, Maria Pettersdotter",
"Pitk\u00e4nen, Petter",
"Pitk\u00e4nen, Simon J\u00f6ransson",
"Pitk\u00e4nen, Simon Simonsson",
"Pohjalainen, Anna Petersdotter",
"Pohjalainen, Johan J\u00f6ransson",
"Pohjalainen, Johan Michelsson",
"Pohjalainen, J\u00f6ran Jonasson",
"Pohjalainen, Maria Michelsdotter",
"Pohjalainen, Michel",
"Pohjalainen, Michel Johansson",
"Pohjalainen, Simon",
"Pohjalainen, Varpu Juhontyt\u00e4r",
"Pohjaslahti, Brita Ericsdotter",
"Pohjaslahti, Eric Henricsson",
"Pokkinen, Elisabeth",
"Posti, Elin Isacsdotter",
"Posti, Isach Mattsson",
"Posti, Matts Peersson",
"Posti, Sigfrid Isacsson",
"Puikkonen, Agnetha Christersdotter",
"Puikkonen, Christer Henricsson",
"Puikkonen, Henric Mattsson",
"Puikkonen, Lisa Mattsdotter",
"Puikkonen, Matts",
"Pulakka, Maria Andersdotter",
"Pulkki, Brita Nilsdotter",
"Pulkkinen, Lempi Maria Viljamintyt\u00e4r",
"Pullinen, Catarina Matsdotter",
"Puolakainen, Anders Michelsson",
"Puolakainen, Anna Andersdotter",
"Puolakainen, Michel Michelsson",
"Puolakainen, Michel Oloffsson",
"Puolakainen, Oloff Brusiusson",
"Puputti, Catharina Samuelsdotter",
"Puputti, Lena Pehrsdotter",
"Pusa, Aapro Heikinpoika",
"Pusa, Agnetha J\u00f6ransdotter",
"Pusa, Anna",
"Pusa, Anna J\u00f6ransdotter",
"Pusa, Anna Mattsdotter",
"Pusa, Anna M\u00e5rtensdotter",
"Pusa, Elisabeth Johansdotter",
"Pusa, Elisabeth Simonsdotter",
"Pusa, Georg Simonsson",
"Pusa, Ilmari",
"Pusa, Johan M\u00e5rtensson",
"Pusa, J\u00f6ran Simonsson",
"Pusa, Lisa J\u00f6ransdotter",
"Pusa, Maria",
"Pusa, Maria M\u00e5rtensdotter",
"Pusa, Matts M\u00e5rtensson",
"Pusa, M\u00e5rten Thomasson",
"Pusa, Simon",
"Pusa, Simon Simonsson",
"Pusa, Simon Simonsson",
"Pusa, Walborg",
"Puukka, Catharina",
"Pyk\u00e4list\u00f6, Heta Liisa Juhontyt\u00e4r",
"Pylkki, Anders Henricsson",
"Pylkki, Antti Johan Antinpoika",
"Pylkki, Benjamin Antinpoika",
"Pylkki, Henric Johansson",
"Pylkki, Johan J\u00f6ransson",
"Pylkki, Juho Erik Antinpoika",
"Pylkki, J\u00f6ran Henricsson",
"Pylkki, Maria Henricsdotter",
"Pyykk\u00f6, Walborg Michelsdotter",
"P\u00e4rri, Clemet Jacobsson",
"P\u00e4rri, Hendrich Olofsson",
"P\u00e4rri, Johanna Kustaava Simontyt\u00e4r",
"P\u00e4rri, J\u00f6ran Thomasson",
"P\u00e4rri, Maria Heikintyt\u00e4r",
"P\u00e4rri, Walborg Clementsdotter",
"P\u00e4rssinen, Adam Andersson",
"P\u00e4rssinen, Anders Johansson",
"P\u00e4rssinen, Anders Mattsson",
"P\u00e4rssinen, Anna",
"P\u00e4rssinen, Anna Matthsdotter",
"P\u00e4rssinen, Anna Michelsdotter",
"P\u00e4rssinen, Brita Mattsdotter",
"P\u00e4rssinen, Elisabeth",
"P\u00e4rssinen, Irja Ester",
"P\u00e4rssinen, Johan Adamsson",
"P\u00e4rssinen, Johan Michelsson",
"P\u00e4rssinen, Johan Petersson",
"P\u00e4rssinen, Juho",
"P\u00e4rssinen, Juho Juhonpoika",
"P\u00e4rssinen, Juho Mikonpoika",
"P\u00e4rssinen, Lisa Hendricsdotter",
"P\u00e4rssinen, Maria Johansdotter",
"P\u00e4rssinen, Maria J\u00f6ransdotter",
"P\u00e4rssinen, Matths Johansson",
"P\u00e4rssinen, Matts",
"P\u00e4rssinen, Matts Adamsson",
"P\u00e4rssinen, Matts Stephansson",
"P\u00e4rssinen, Michel",
"P\u00e4rssinen, Michel Johansson",
"P\u00e4rssinen, Mikko Juhonpoika",
"P\u00e4rssinen, Paul Mattsson",
"P\u00e4rssinen, Riitta Paulintyt\u00e4r",
"P\u00e4rssinen, Stephan Johansson",
"P\u00e4rssinen, Toivo",
"P\u00e4rssinen, Varpu Antintyt\u00e4r",
"P\u00e4rssinen, Walborg Simonsdotter",
"P\u00f6h\u00f6, Johan Larsson",
"P\u00f6h\u00f6, J\u00f6ran Petersson",
"P\u00f6h\u00f6, Lars J\u00f6ransson",
"P\u00f6h\u00f6, Walborg Larsdotter",
"P\u00f6ll\u00e4kk\u00e4, J\u00f6ran Andersson",
"P\u00f6yh\u00f6nen, Maria",
"P\u00f6ysti, Anna",
"Raami, Johan",
"Raami, Johan Mattsson",
"Raami, J\u00f6ran",
"Raami, Katri Juhontyt\u00e4r",
"Raami, Maria Matthsdotter",
"Raami, Matths Mattsson",
"Raami, Matts Johansson",
"Raami, Matts Sigfredsson",
"Raami, Sigfred J\u00f6ransson",
"Rahm i Strand i \u00c4lg\u00e5, Salomon Torstensson",
"Rainio, Hans J\u00f6nsson",
"Rainio, Johan Hansson",
"Rainio, Lisbetha Johansdotter",
"Raiskinm\u00e4ki, Juho Yrj\u00f6npoika",
"Raiskinm\u00e4ki, Liisa Juhontyt\u00e4r",
"Rajalahti, Gustaf Grelsson",
"Rajalahti, Lisa Gustafsdotter",
"Rakkolainen, Walborg",
"Ram, Margareta Torstensdotter",
"Ram, Torsten Ingelsson",
"Ram, Torsten Salomonsson",
"Rampa, Anders",
"Rampa, Bertil Larsson",
"Rampa, Cnut",
"Rampa, Lars",
"Rampa, Matts Cnutsson",
"Rampa, Matts Mattsson",
"Rampa, Walborg Bertilsdotter",
"Rampa, Walborg Mattsdotter",
"Rantalainen, Johan",
"Rantalainen, Maria Johansdotter",
"Rasi, Eric Mattsson",
"Rasi, Maria Mattsdotter",
"Rasi, Matts Henricsson",
"Rasi, Matts Mattsson",
"Rasi, Valpuri Erkintyt\u00e4r",
"Raukola, Lisa Thuronis",
"Raukola, Matts Henriksson",
"Raumannus, Jacobus Pauli",
"Rautia, Mikil Nilsson",
"Rautiainen, Anna Maununtyt\u00e4r",
"Rautiainen, Bertil Andersson",
"Rautiainen, Brita Thomasdotter",
"Rautiainen, Henric",
"Rautiainen, Johan Johansson",
"Rautiainen, Johan Magnusson",
"Rautiainen, J\u00f6ran J\u00f6ransson",
"Rautiainen, Loviisa Matintyt\u00e4r",
"Rautiainen, Magnus",
"Rautiainen, Magnus Johansson",
"Rautiainen, Magnus Simonsson",
"Rautiainen, Maria Henricstotter",
"Rautiainen, Maria Yrj\u00f6ntyt\u00e4r",
"Rautiainen, Simon Magnusson",
"Rautiainen, Thomas Henricsson",
"Rautiainen, Walborg Thomasdotter",
"Reinikka, Chirstin Mattsdotter",
"Reinikka, Johan J\u00f6ransson",
"Reinikka, Kristiina Juhontyt\u00e4r",
"Rekola, Grels Sigfridsson",
"Rekola, Jacob Mattsson",
"Rekola, J\u00f6ren Grelsson",
"Rekola, Margeta Thomasdotter",
"Rekola, Maria M\u00e5rtensdotter",
"Rekola, Matts Thomasson",
"Rekola, Matts Thomasson",
"Rekola, M\u00e5rten Thomasson",
"Rekola, Sigfrid Knutsson",
"Rekola, Thomas Grelsson",
"Rekola, Thomas J\u00f6ransson",
"Riekkola, Anna Henricsdotter",
"Riekkola, Chirstin Michelsdotter",
"Riekkola, Johan Sigfredsson",
"Riekkola, Joseph P\u00e5hlsson",
"Riekkola, Michel Sigfredsson",
"Riekkola, Sigfred Simonsson",
"Riekkola, Simon Josephsson",
"Riekkola, Walborg Johansdotter",
"Riiko, Elin J\u00f6ransdotter",
"Riiko, J\u00f6ran Olofsson",
"Ripainen, Carin Christersdotter",
"Ristsepp\u00e4, Anna Mattsdotter",
"Ristsepp\u00e4, Mathias Simonsson",
"Ristsepp\u00e4, Simon Eskelsson",
"Roini, Olaus",
"Roini, Walborg Petersdotter",
"Romu, Mikko Villenpoika",
"Romu, Sirkka Maria",
"Romu, Sylvi Hedvig",
"Roos, Johannes Eliae",
"Roponen, Alexander Thomasson",
"Roponen, Elisabeth Thomasdotter",
"Roponen, Thomas",
"Roponen, Thomas Thomasson",
"Rosted (Williams), Bertha Lempi Eugenia",
"Rouhiainen, Maria",
"Ruolahti, Ingeborg Johansdotter",
"Ruuna, Helga",
"Ruuna, Peter",
"Ruuna, Walborg Petersdotter",
"Ruuska, Aatami Aataminpoika",
"Ruuska, Maria",
"R\u00e4hm\u00f6nen, Brita Johansdotter",
"R\u00e4hm\u00f6nen, Daniel",
"R\u00e4hm\u00f6nen, Johan Danielsson",
"R\u00e4m\u00f6, Abraham Mattsson",
"R\u00e4m\u00f6, Abraham Stephansson",
"R\u00e4m\u00f6, Anders J\u00f6ransson",
"R\u00e4m\u00f6, Hetti Vilpuntyt\u00e4r",
"R\u00e4m\u00f6, Juho Tuomaanpoika",
"R\u00e4m\u00f6, J\u00f6ran J\u00f6ransson",
"R\u00e4m\u00f6, J\u00f6ran Mattsson",
"R\u00e4m\u00f6, Maria Abrahamsdotter",
"R\u00e4m\u00f6, Marianna Tuomaantyt\u00e4r",
"R\u00e4m\u00f6, Mathias J\u00f6ransson",
"R\u00e4m\u00f6, Matts",
"R\u00e4m\u00f6, Matts Hendriksson",
"R\u00e4m\u00f6, Michel Abrahamsson",
"R\u00e4m\u00f6, Stephan Andersson",
"R\u00e4m\u00f6, Tuomas Mikonpoika",
"R\u00e4m\u00f6, Tuomas Tuomaanpoika",
"R\u00e4nn\u00e4li, Adam Petersson",
"R\u00e4nn\u00e4li, Agnetha Adamsdotter",
"R\u00e4nn\u00e4li, Matts",
"R\u00e4nn\u00e4li, Peter Matsson",
"R\u00e4tt\u00f6, Carin P\u00e5hlsdotter",
"R\u00e4tt\u00f6, Elina",
"R\u00f6ring, Henrik Johansson",
"R\u00f6ring, Johan Mattsson",
"R\u00f6ring, Maria Henriksdotter",
"Saarikko, Thomas Pehrsson",
"Saarikko, Thomas Thomasson",
"Sahraj\u00e4rvi, Dionisius M\u00e5rthensson",
"Sahraj\u00e4rvi, Eric J\u00f6ransson",
"Sahraj\u00e4rvi, Henrich Nilsson",
"Sahraj\u00e4rvi, J\u00f6ran Ericsson",
"Sahraj\u00e4rvi, J\u00f6ran Hendersson",
"Sahraj\u00e4rvi, M\u00e5rten Marcusson",
"Saikkonen, Elina",
"Saira, Erik Simonsson",
"Saira, Eskil Ericsson",
"Saira, Hedvig Michelsdotter",
"Saira, Michel Eskilsson",
"Salen, Johanna Thomasdotter",
"Salen, Thomas Grelsson",
"Sallinen, Lars",
"Sallinen, Lars Larsson",
"Sallinen, Walborg Larsdotter",
"Salvenius, Anders Johan",
"Salvenius, Christina Elisabeth Andersdotter",
"Salvenius, Erik Mattson",
"Sandb\u00e4ck, Matts Mattsson",
"Sandb\u00e4ck, Yrj\u00f6 Matinpoika",
"Savolainen, Anna J\u00f6ransdotter",
"Savolainen, Antti Luukkaanpoika",
"Savolainen, Bertil",
"Savolainen, Carin",
"Savolainen, Elsa Elli Juhontyt\u00e4r",
"Savolainen, Eric",
"Savolainen, Helena Hindrichsdotter",
"Savolainen, Helena P\u00e4rsdotter",
"Savolainen, Hindrich Hindrichsson",
"Savolainen, Hindrich P\u00e5hlsson",
"Savolainen, Johan",
"Savolainen, Johan Bertilsson",
"Savolainen, Johan Johansson",
"Savolainen, Johan Johasson",
"Savolainen, Johan Johasson",
"Savolainen, Johan Lucasson",
"Savolainen, Liisa Antintyt\u00e4r",
"Savolainen, Lucas Johansson",
"Savolainen, Lucas Johansson",
"Savolainen, Maria",
"Savolainen, Maria Heikintyt\u00e4r",
"Savolainen, Maria Johansdotter",
"Savolainen, Maria Johansdotter",
"Savolainen, Pehr",
"Savolainen, Walborg Augustsdotter",
"Savolainen, Walborg Ericsdotter",
"Savolainen, Walborg Henricsdotter",
"Saxberg, Maria Heikintyt\u00e4r",
"Sepp\u00e4, Eskel Thomasson",
"Sepp\u00e4, Thomas",
"Sepp\u00e4l\u00e4, Chirstin Simonsdotter",
"Sepp\u00e4l\u00e4, Johan J\u00f6ransson",
"Sepp\u00e4l\u00e4, Simon Johansson",
"Sepp\u00e4nen, Anna Hindricksdotter",
"Sepp\u00e4nen, Hindrick M\u00e5rtensson",
"Sepp\u00e4nen, Maria",
"Sepp\u00e4nen, Maria Gabrielsdotter",
"Seurasalmi, Anders J\u00f6ransson",
"Seurasalmi, Eva Andersdotter",
"Siikala, Erich Thomasson",
"Siikala, Henrik Eriksson",
"Siikala, J\u00f6ran M\u00e5rtensson",
"Siikala, Lisa M\u00e5rtensdotter",
"Siikala, Maria J\u00f6ransdotter",
"Siikala, M\u00e5rten Sigfredsson",
"Siikala, Sigfred Henricsson",
"Siikala, Thomas Thomasson",
"Sikanen, Christer Erichsson",
"Sikanen, Erik J\u00f6ransson",
"Sikanen, J\u00f6ran Cnuthsson",
"Sikanen, Knut Nisiusson",
"Sillanp\u00e4\u00e4, Akseli",
"Simola, Caisa Samuelsdotter",
"Simola, Samuel Johansson",
"Simolin, Henric",
"Simolin, Ulrika Henricsdotter",
"Sipil\u00e4inen, Katarina Tuomaantyt\u00e4r",
"Sipil\u00e4inen, Margaretha Mattsdotter",
"Sirkkala, Chirstin Sigfredsdotter",
"Sirkkala, Eskil Michelsson",
"Sirkkala, Eskill J\u00f6ransson",
"Sirkkala, J\u00f6ran Eskilsson",
"Sirkkala, Maria Samuelsdotter",
"Sirkkala, Maria Sigfredsdotter",
"Sirkkala, Sigfred Eskilsson",
"Siukola, Brita J\u00f6ransdotter",
"Siukola, Chirstin Johansdotter",
"Siukola, Christina Johansdotter",
"Siukola, Heta Jaakontyt\u00e4r",
"Siukola, Johan Johansson",
"Siukola, Johannes Johansson",
"Siukola, Jonas Jacobsson",
"Siukola, J\u00f6ran Thomasson",
"Siukola, Lena Johansdotter",
"Siukola, Maria Elisabet Joonaantyt\u00e4r",
"Siukola, Philipus J\u00f6ransson",
"Siukola, Thomas Philipsson",
"Siuro, Erich Olofsson",
"Siuro, Olof Johansson",
"Siurola, Clemet Thuresson",
"Siurola, Henrich Thomasson",
"Siurola, Olof Tordsson",
"Siurola, Sigfrid Olofsson",
"Siurola, Thomas Clemetsson",
"Siurola, Thomas Henriksson",
"Siurola, Thure Clemetsson",
"Siurola, Thure Thomasson",
"Siurola, Tord Sigfridsson",
"Sjundby, Brita Bertilsdotter",
"Skalm, Claes Andersson",
"Skugge, Anna",
"Skytt\u00e4l\u00e4, Matts Bertilsson",
"Smedh, Dionisius Gudmundsson",
"Smedh, Sigfred",
"Somppi, Brita Pehrsdotter",
"Somppi, Henrich Mattsson",
"Somppi, Matts Erichsson",
"Somppi, Peder Pedersson",
"Somppi, Per Persson",
"Sontikka, Maria",
"Sorola, Valborg Clasdotter",
"Sotku, Anders Andersson",
"Sotku, Jacob",
"Sotku, Lisa Matthsdotter",
"Sotku, Matths Jacobsson",
"Sparf, Benjamin Mattsson",
"Sparf, Hedvig Benjaminsdotter",
"Speitz, Christina J\u00f6ransdotter",
"Speitz, Henrik Jacobsson",
"Speitz, J\u00f6ran Henriksson",
"Stierna, Elin M\u00e5rtensdotter",
"Stierna, M\u00e5rten Ericsson",
"Stiernkors i Fr\u00f6jdb\u00f6le, Erik M\u00e5rtensson",
"Stjernkors, Ivar Axelsson",
"Stolpe, Johannes Adamsson",
"Strandman, Andreas",
"Strandman, Andreas Andre\u00e6",
"Suikkanen, Anna",
"Suinu, Clemeth",
"Suinu, Henrich",
"Suinu, M\u00e5rten Henricsson",
"Suluslahti, Lisa Henrichsdotter",
"Sundstr\u00f6m, Henrik Mattsson",
"Sundstr\u00f6m, Maria Elisabeth Henricsdotter",
"Suolaxius, Axelius Theodorici",
"Suomatka, Michel J\u00f6nsson",
"Susi, Maria Nicolaisdotter",
"Suutari, Anders",
"Suutari, Britha Andersdotter",
"Suutari, Catharina Petersdotter",
"Suutari, J\u00f6ran Andersson",
"Suutari, Maria J\u00f6ransdotter",
"Suutari, Peter Olofsson",
"S\u00e4rkikanta, Heikki Juhani",
"S\u00e4rkinen, Maria",
"Taavettila, Elisabeth Johansdotter",
"Taavettila, Johan Michelsson",
"Taavettila, Michel Michelsson",
"Taavettila, Walborg Michelsdotter",
"Taipale, Herman Aapronpoika",
"Talikainen, Brita Sigfredsdotter",
"Talikainen, Sigfred",
"Talonpoika, Elisabeth J\u00f6ransdotter",
"Talonpoika, Jacob Staffansson",
"Talonpoika, J\u00f6ran Jacobsson",
"Talonpoika, Maria",
"Tanninen, Kaarina Tuomaantyt\u00e4r",
"Tarkkala, Johan Johansson",
"Tarkkala, J\u00f6ran Johansson",
"Tasainen, Henrik Persson",
"Tasainen, Valborg Henriksdotter",
"Tavela, Axel Hansson",
"Tavela, Carin Axelsdotter",
"Tavela, Hans Bengtsson",
"Tavela, Sofia Axelsdotter",
"Tawast, J\u00f6ns Olofsson",
"Tawast, Katarina Nilsdotter",
"Tawast, Margit J\u00f6nsdotter",
"Tawast, Nils Olofsson",
"Tawast, Olof J\u00f6nsson",
"Tawast, Valborg J\u00f6nsdotter",
"Techtonia, Elisabeth Jacobsdotter",
"Teerijoki, Eric Johansson",
"Teerijoki, Johan Henricsson",
"Teerijoki, Johan Jacobsson",
"Teerijoki, Maria Eriksdotter",
"Tehi, Maria Simonsdotter",
"Tehi, Simon Andersson",
"Teit, Gregorius Martini",
"Tepponen, Anders Ericsson",
"Tepponen, Anna Andersdotter",
"Tepponen, Eric",
"Tervanen, Eric",
"Tervanen, Johan Ericsson",
"Tervanen, Walborg Johansdotter",
"Tihver\u00e4inen, Anders",
"Tihver\u00e4inen, Anna Heikintyt\u00e4r",
"Tihver\u00e4inen, Catharina Johansdotter",
"Tihver\u00e4inen, Heikki Matinpoika",
"Tihver\u00e4inen, Henric",
"Tihver\u00e4inen, Henric Henricsson",
"Tihver\u00e4inen, Johan Johansson",
"Tihver\u00e4inen, Johan Johansson",
"Tihver\u00e4inen, Johan Simonsson",
"Tihver\u00e4inen, Juho Heikinpoika",
"Tihver\u00e4inen, Kaarina Maununtyt\u00e4r",
"Tihver\u00e4inen, Magnus Stephansson",
"Tihver\u00e4inen, Matti Heikinpoika",
"Tihver\u00e4inen, Simon Johansson",
"Tihver\u00e4inen, Stephan Johansson",
"Tiira, Walborg Petersdotter",
"Tikka, Brita Mattsdotter",
"Tikka, Matts",
"till Aln\u00e4s, Christofer Bertilsson",
"till Aln\u00e4s, Elin Helena Kristoffersdotter",
"till Moisio, J\u00f6ns Mickelsson",
"till Viurila, Elseby M\u00e5nsdotter",
"Tirkkonen, Olga Maria Kaarlontyt\u00e4r",
"Toikka, Catharina Mattsdotter",
"Toikka, Matts",
"Toiviainen, Elisabeth Syringsdotter",
"Toiviainen, Syring",
"Tomperi, Aarne",
"Tomperi, Aili",
"Tomperi, Anders Johansson",
"Tomperi, Anna Liisa",
"Tomperi, Ilmi Ilona",
"Tomperi, Johan",
"Tomperi, Johan Mattsson",
"Tomperi, Juho Yrj\u00f6npoika",
"Tomperi, Juho Yrj\u00f6npoika",
"Tomperi, J\u00f6ran Johansson",
"Tomperi, Matts Andersson",
"Tomperi, Raija Leena",
"Tomperi, Reijo",
"Tomperi, Seppo",
"Tomperi, Toini Sivi\u00e4",
"Tomperi, Vilho",
"Tomperi, Yrj\u00f6 Juhonpoika",
"Tontti, Elisabeta",
"Torkkeli, J\u00f6ran",
"Torkkeli, Maria",
"Torkkeli, Walborg J\u00f6ransdotter",
"Tuna, Maria",
"Tunkelo, Johan Johansson",
"Tuokko, Anna Tahvontyt\u00e4r",
"Tuokko, Pauli Heikinpoika",
"Tuomaala, Bertill J\u00f6ransson",
"Tuomaala, Brita Bertilsdotter",
"Tuomaala, Erich Thomasson",
"Tuomaala, J\u00f6ran Erichsson",
"Tuomaala, Thomas Thomasson",
"Tuomela, Erkki Ensio",
"Tuomela, Lea Annikki",
"Tuominen, Aili Sisko",
"Tuottinen, Knut",
"Tuottinen, Thomas J\u00f6nsson",
"Turkki, Maria P\u00e5hlsdotter",
"Turkkinen, Thomas Abrahamsson",
"Turve, Helena",
"Ty\u00f6r\u00f6, Caisa Thomasdotter",
"Ty\u00f6r\u00f6, Thomas Olofsson",
"T\u00f6rnqvist, Johan",
"T\u00f6rnqvist, Johan Johansson",
"T\u00f6rnqvist, Johanna Johansdotter",
"T\u00f6yr\u00e4niemi, Anna Mattsdotter",
"Udd, Matts Mattsson",
"Ulkolainen, Anna J\u00f6ransdotter",
"Ulkolainen, J\u00f6ran",
"Unkila, Caisa Hinrichsdotter",
"Uotila, Anders Mattsson",
"Uotila, Lasse J\u00f6nsson",
"Uotila, Matts Andersson",
"Uotila, Matts Larsson",
"Ursin, Catharina",
"Uuranniemi, Lena Thomasdotter",
"Vaitti, Helena Mattsdotter",
"Vaitti, Johan Mattsson",
"Vaitti, Matthias Johansson",
"Vaitti, Matts Andersson",
"Vaitti, Matts Mattsson",
"Vanhanen, Anders Johansson",
"Vanhanen, Brita Petersdotter",
"Vanhanen, Catharina",
"Vanhanen, Catharina Mattsdotter",
"Vanhanen, Grels",
"Vanhanen, Johan",
"Vanhanen, Maria Grelsdotter",
"Vanhanen, Peter Andersson",
"Vanhanen, Simon P\u00e5hlsson",
"Vaskelainen",
"Vaskelainen, J\u00f6ran",
"Vaskelainen, Walborg J\u00f6ransdotter",
"Vehkoo, Lisa Eliasdotter",
"Veitikka, Walborg Staffansdotter",
"Ventonen, Maria Jacobsdotter",
"Vessari, Anders Mattsson",
"Vessari, Brita Andreasdotter",
"Vessari, Hedvig Henricsdotter",
"Vessari, Henrik Andersson",
"Vessari, Lars Peersson",
"Vessari, Margeta Peersdotter",
"Vessari, Matts Peersson",
"Vessari, Olof Larsson",
"Vessari, Peer Olsson",
"Vessari, Per",
"Viiala, Erika Joonaantyt\u00e4r",
"Viiala, Johan Ersson",
"Viisas, Knut Thomasson",
"Viisas, Thomas",
"Viitaniemi, Erich Erichsson",
"Viitaniemi, Erik",
"Vilkki, Beatha Bertilsdotter",
"Vilkki, Bertill",
"Vilkkil\u00e4, Johan Svensson",
"Vilkkil\u00e4, J\u00f6ran M\u00e5rtensson",
"Vilkkil\u00e4, M\u00e5rten Johansson",
"Vilkkil\u00e4, M\u00e5rten J\u00f6ransson",
"Virkki, Walborg",
"Virolainen, Anna Tuomaantyt\u00e4r",
"Virolainen, Brita Jacobsdotter",
"Virolainen, Carin",
"Virolainen, Carin P\u00e5hlsdotter",
"Virolainen, Jacob",
"Virolainen, Maria Mattsdotter",
"Virolainen, Matts",
"Virolainen, P\u00e5hl Mattsson",
"Virtanen, Ida Otteliana",
"Virtanen, Kalle Kustaa Kallenpoika",
"Viskari, Elin Mattsdotter",
"Viskari, Erich",
"Viskari, Jacob Ericsson",
"Viskari, Matts Thomasson",
"Viskari, Thomas Jacobsson",
"Visuvesi, Lasse Erichsson",
"Visuvesi, Marcus Thomasson",
"Visuvesi, Thomas Larsson",
"Vuohelainen, Bertyl Jacobsson",
"Vuohelainen, Bertyl J\u00f6ransson",
"Vuohelainen, Elisabeth J\u00f6ransdotter",
"Vuohelainen, Georg Bertylsson",
"Vuohelainen, Helena Jacobsdotter",
"Vuohelainen, Jacob Henricsson",
"Vuohelainen, J\u00f6ran",
"Vuohelainen, Lisa Bertylsdotter",
"Vuohelainen, Maria",
"Vuohelainen, Maria J\u00f6ransdotter",
"V\u00e4likara, Maria Henriksdotter",
"V\u00e4lkki, N Persdotter",
"V\u00e4lkki, Olof Nilsson",
"V\u00e4lkky, Maria Henrichsdotter",
"Welling, Catharina Olofsdotter",
"Wikar, Hans Hansson",
"Wikar, Magdalena Hansdotter",
"Williams, Arthur Oliver",
"Williams, John Ellis",
"Williams, Otto Albert",
"Williams, Rudolf Toivo",
"Williams, Wells Eldon",
"Wilsten, Carl",
"Wilsten, Carl",
"Wilsten, Susanna Carlsdotter",
"Wisi\u00e6, Maria Knutsdotter",
"Wolffelt, Ebba Juliana",
"Ylinen, Anna Henricsdotter",
"Ylinen, Anna Thomasdotter",
"Ylinen, Chirstin J\u00f6ransdotter",
"Ylinen, Henric Ericsson",
"Ylinen, Henric Mattsson",
"Ylinen, Henrich Eskelsson",
"Ylinen, Henrich Mattsson",
"Ylinen, Henrich M\u00e5rtensson",
"Ylinen, Joonas Heikinpoika",
"Ylinen, J\u00f6ran Henricsson",
"Ylinen, Maria Samuelsdotter",
"Ylinen, Matthias Matthsson",
"Ylinen, Matts Henricsson",
"Ylinen, Samuel Mattsson",
"Ylinen, Sophia Henriksdotter",
"Ylinen, Walborg Henrichsdotter",
"Ylistalo, Malin Thomasdotter",
"Ylistalo, Thomas Marcusson",
"Ylti\u00e4, Leena Tuomaantyt\u00e4r",
"Ylti\u00e4, Thomas Sigfredsson",
"Yl\u00e4-H\u00e4kkinen, Elin J\u00f6ransdotter",
"Yl\u00e4-H\u00e4kkinen, Erich Mattsson",
"Yl\u00e4-H\u00e4kkinen, Gabriel J\u00f6ransson",
"Yl\u00e4-H\u00e4kkinen, J\u00f6ran Eriksson",
"Yl\u00e4-H\u00e4kkinen, Lisa Gabrielsdotter",
"Yl\u00e4-Marttila, Johanna Johansdotter",
"Yl\u00e4-Nikkil\u00e4, Heikki Matinpoika",
"Yl\u00e4-Nikkil\u00e4, Johanna Heikintyt\u00e4r",
"Yl\u00e4-Nikkil\u00e4, Matth\u00e6us Jacobi",
"Yl\u00e4-Nikkil\u00e4, Matts Mattsson",
"Yrj\u00f6l\u00e4, Amanda Mathilda Erkintyt\u00e4r",
"Yrj\u00f6l\u00e4, Anna J\u00f6ransdotter",
"Yrj\u00f6l\u00e4, Carl Henrik Yrj\u00f6npoika",
"Yrj\u00f6l\u00e4, Elias Erkinpoika",
"Yrj\u00f6l\u00e4, Eric J\u00f6ransson",
"Yrj\u00f6l\u00e4, J\u00f6ran J\u00f6ransson",
"Yrj\u00f6l\u00e4, J\u00f6ran M\u00e5rtensson",
"Yrj\u00f6l\u00e4, Lisa Jacobsdotter",
"\u00c4hrlig, Anna",
"\u00c4ij\u00f6, Anna",
"\u00c4ij\u00f6, Anna Christersdotter",
"\u00c4ij\u00f6, Christer",
"\u00c4ij\u00f6, Helena Johansdotter",
"\u00c4ij\u00f6, J\u00f6ran Christersson",
"\u00c4ij\u00f6, Maria",
"\u00c4ij\u00f6, Maria J\u00f6ransdotter",
"\u00c4ij\u00f6, Maria Thomasdotter",
"\u00c4ij\u00f6, Simon J\u00f6ransson",
"\u00c4ij\u00f6, Walborg Simonsdotter",
"\u00c4nkk\u00e4, Helena Ericsdotter",
"\u00c4nkk\u00e4, Johan Hemmingsson",
"\u00c4nkk\u00e4, Maria Ericsdotter"
]
Dwr.ScriptLoaded('dwr_db_I_short_name_0.js');
