// This file is generated

I_death_place_0 = [
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Kivioja, Hassi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Onnistaipale, Orivesi, Suomi",
"Visuvesi, Ruovesi, Suomi",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Mullikka, Viiala, J\u00e4ms\u00e4, Suomi",
"",
"Kekkonen, Ruovesi, Suomi",
"Hampaala, Pakkala, Sahalahti, Kangasala, Suomi",
"",
"Niikkula, Koivuniemi, Orivesi, Suomi",
"Karvia, Kyl\u00e4noja, Orivesi, Suomi",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4n rustholli, Kokko, Urjala, Suomi",
"",
"Melli, Melli, Juupajoki, Suomi",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Haljala, Puukkoinen, Kuhmoinen, Suomi",
"Siikala, Laasola, Orivesi, Suomi",
"Rautu, Luovutettu Karjala",
"",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"",
"",
"Pietil\u00e4, J\u00e4ms\u00e4, Suomi",
"Kopsamo, Juupajoki, Suomi",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Heinsaari, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Niemen rustholli, T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"Hassi, Hassi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Knuutila, Er\u00e4slahti, Orivesi, Suomi",
"Saarij\u00e4rvi, Suomi",
"Iitti, Suomi",
"",
"",
"Raiskinm\u00e4ki, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Kangasala, Suomi",
"Ylinen, Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vilakkala, Sakkola, Luovutettu Karjala",
"",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"",
"Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"",
"Yrj\u00f6l\u00e4, Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Rekolan rustholli, Heponiemi, Kangasala, Suomi",
"",
"Kopsamo, Juupajoki, Suomi",
"Maunula, Pehula, Orivesi, Suomi",
"Suolahti, Keuruu, Suomi",
"Sakari, Kiukoila, Lopotti, J\u00e4ms\u00e4, Suomi",
"",
"Kurikka, Kavantsaari, Antrea, Luovutettu Karjala",
"Holman kartano, Holma, Orivesi, Suomi",
"",
"Porvola, Juupajoki, Suomi",
"Suluslahti, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Hy\u00f6m\u00e4ki, Hauho, H\u00e4meenlinna, Suomi",
"",
"Nuottiniemi, Mustaj\u00e4rvi, Ruovesi, Suomi",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Karkku, Vammala, Sastamala, Suomi",
"",
"",
"",
"Finnil\u00e4, Maakeski, Padasjoki, Suomi",
"Hulipas, Juupajoki, Suomi",
"Rainio, Karkku, Vammala, Sastamala, Suomi",
"",
"Rekolan rustholli, Heponiemi, Kangasala, Suomi",
"Rakkolanjoki, Vahviala, Luovutettu Karjala",
"Ylinen, Kytt\u00e4l\u00e4, Tampere, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"",
"",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Kurkela, Nurmii, Muolaa, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Kurkela, Ikaalinen, Suomi",
"",
"",
"",
"",
"Hassi, Hassi, J\u00e4ms\u00e4, Suomi",
"Kokkola, Suomi",
"",
"",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Kurikka, Kavantsaari, Antrea, Luovutettu Karjala",
"",
"",
"Liettu, Niemenkyl\u00e4, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Kuoreniemi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Kolhi, Savo, Orivesi, Suomi",
"",
"Mulli, Laasola, Orivesi, Suomi",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"M\u00e4kel\u00e4, Valkealuomi, J\u00e4ms\u00e4, Suomi",
"Karikko, Pet\u00e4j\u00e4vesi, Suomi",
"Hannola, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ilola, Muolaa, Luovutettu Karjala",
"Korpula, Korpula, Ruovesi, Suomi",
"",
"",
"",
"",
"Pohja, Kuhmalahti, Kangasala, Suomi",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"",
"Manninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"Mikkola, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Hassi, Hassi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4n rustholli, Kokko, Urjala, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Hirvij\u00e4rvi, Juupajoki, Suomi",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Mulli, Laasola, Orivesi, Suomi",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Kontu, Antrea, Luovutettu Karjala",
"",
"",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Hanninen, Hannila, Antrea, Luovutettu Karjala",
"Ouni, Ouninpohja, J\u00e4ms\u00e4, Suomi",
"",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Tolsterniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"",
"Ylti\u00e4, Pihlajavesi, Keuruu, Suomi",
"Hokka, Auttoinen, Padasjoki, Suomi",
"Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"Hoivala, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Loila, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Tukholma, Ruotsi",
"",
"Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Hulipas, Juupajoki, Suomi",
"",
"",
"Ikaalinen, Suomi",
"",
"",
"",
"",
"",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"Sepp\u00e4l\u00e4, Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Mulli, Laasola, Orivesi, Suomi",
"Kekkonen, Ruovesi, Suomi",
"Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"K\u00f6ntt\u00e4ri, Suolahti, Keuruu, Suomi",
"",
"Pet\u00e4j\u00e4vesi, Suomi",
"Tuomaala, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Valkeam\u00e4ki, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"Pietil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"Sikanen, Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"Hoivala, H\u00f6ytee, Juupajoki, Suomi",
"",
"",
"Suolahti, Keuruu, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"",
"",
"",
"",
"",
"Laurila, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"Haavisto, Orivesi, Suomi",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"",
"",
"Padustaipale, Orivesi, Suomi",
"Asunta, Keuruu, Suomi",
"V\u00e4h\u00e4-K\u00f6mi, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"Nihtil\u00e4, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"Vilakkala, Sakkola, Luovutettu Karjala",
"",
"",
"",
"",
"Niemen rustholli, T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Vuosalmi, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"",
"",
"",
"",
"Rautio, Sahalahti, Kangasala, Suomi",
"M\u00e4kel\u00e4, Valkealuomi, J\u00e4ms\u00e4, Suomi",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"Simsi\u00f6, Simsi\u00f6, Pihlajavesi, Keuruu, Suomi",
"",
"",
"Hankavesi, \u00c4ht\u00e4ri, Suomi",
"",
"",
"Sipoo, Suomi",
"",
"",
"",
"",
"Mikkola, Juokslahti, J\u00e4ms\u00e4, Suomi",
"",
"Anttila, Korvenkyl\u00e4, J\u00e4ms\u00e4, Suomi",
"Seppola, J\u00e4ms\u00e4, Suomi",
"Kurra, Pitk\u00e4nen, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"",
"",
"",
"Pehula, Orivesi, Suomi",
"",
"",
"",
"",
"",
"Hulipas, Juupajoki, Suomi",
"",
"",
"Pehula, Orivesi, Suomi",
"",
"",
"",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"L\u00e5ngila, R\u00e4yrinki, Veteli, Suomi",
"",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"Suolahti, Keuruu, Suomi",
"",
"",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"P\u00e4k\u00e4ri, Keuruu, Suomi",
"Penttil\u00e4, Hurttala, Hattula, Suomi",
"Lylyj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Hulipas, Juupajoki, Suomi",
"Hulipas, Juupajoki, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"Viialan puustelli, Kaipola, J\u00e4ms\u00e4, Suomi",
"Kaukola, Niemola, J\u00e4ms\u00e4, Suomi",
"",
"Asunta, Keuruu, Suomi",
"Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"Juokslahti, J\u00e4ms\u00e4, Suomi",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"Simola, Toivila, J\u00e4ms\u00e4, Suomi",
"Aakkola, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"Posti, Loila, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"",
"Jussila, Rautio, Sahalahti, Kangasala, Suomi",
"Manninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Pohjaslahti, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"L\u00e4ttil\u00e4, Tapiala, Kuhmoinen, Suomi",
"",
"",
"",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"Riiska, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Keuruu, Suomi",
"Hokka, Auttoinen, Padasjoki, Suomi",
"",
"V\u00e4lkkil\u00e4, Urjala, Suomi",
"",
"",
"",
"",
"",
"Ruovesi, Suomi",
"",
"",
"Siurola, Raikku, Kangasala, Suomi",
"",
"Kokkola, Suomi",
"Rasi, Pohja, Kuhmalahti, Kangasala, Suomi",
"",
"",
"",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Hyyryl\u00e4, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Liettu, Niemenkyl\u00e4, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sakkola, Luovutettu Karjala",
"P\u00f6h\u00f6, Rahikkala, Antrea, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Pakom\u00e4ki, Yl\u00e4-Partala, Jokioinen, J\u00e4ms\u00e4, Suomi",
"Maunula, Kopsamo, Juupajoki, Suomi",
"Vilakkala, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Hannila, Antrea, Luovutettu Karjala",
"Pylkki, Juupajoki, Suomi",
"Heikkil\u00e4, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Niemi, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Viialan puustelli, Kaipola, J\u00e4ms\u00e4, Suomi",
"",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"Naappila, Orivesi, Suomi",
"Yl\u00e4-Rekola, Vierel\u00e4, Tervala, J\u00e4ms\u00e4, Suomi",
"Viialan puustelli, Kaipola, J\u00e4ms\u00e4, Suomi",
"Siikala, Laasola, Orivesi, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nihtil\u00e4, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Keuruu, Suomi",
"Pappinen, Lapinlahti, Sakkola, Luovutettu Karjala",
"Alavus, Suomi",
"",
"",
"",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Siuro, Oriveden kyl\u00e4, Orivesi, Suomi",
"L\u00e4ttil\u00e4, Tapiala, Kuhmoinen, Suomi",
"",
"L\u00e4ngelm\u00e4ki, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kivioja, Hassi, J\u00e4ms\u00e4, Suomi",
"Ampiala, Keuruu, Suomi",
"Harola, Talviainen, Orivesi, Suomi",
"",
"",
"",
"Maunula, Pehula, Orivesi, Suomi",
"",
"",
"",
"Viialan puustelli, Kaipola, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Hulipas, Juupajoki, Suomi",
"",
"",
"",
"",
"Ilola, Muolaa, Luovutettu Karjala",
"",
"",
"",
"Aseme, Honkala, J\u00e4ms\u00e4, Suomi",
"",
"Tapiala, Kuhmoinen, Suomi",
"",
"",
"Helsinki, Suomi",
"",
"",
"Kuusj\u00e4rvi, Kuusj\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Seppola, J\u00e4ms\u00e4, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Tavela, Tursola, Kangasala, Suomi",
"Eerola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Kutinlahti, Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"",
"Anttila, Korvenkyl\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"Kopsamo, Juupajoki, Suomi",
"Jaarlan rustholli, Jaarila, H\u00f6ytee, Juupajoki, Suomi",
"Kurra, Pitk\u00e4nen, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Niikkula, Koivuniemi, Orivesi, Suomi",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Parpola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Kaukola, Niemola, J\u00e4ms\u00e4, Suomi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Kierros, Vehkoo, Multia, Suomi",
"Hovila, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Anttila, Korvenkyl\u00e4, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-H\u00e4kkinen, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Asunta, Keuruu, Suomi",
"Karikko, Pet\u00e4j\u00e4vesi, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"Pakom\u00e4ki, Yl\u00e4-Partala, Jokioinen, J\u00e4ms\u00e4, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"",
"",
"",
"Iso-Attila, Attila, Orivesi, Suomi",
"",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Porvoo, Suomi",
"",
"",
"",
"",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Unkila, Padustaipale, Orivesi, Suomi",
"H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"Sukkila, Juupajoki, Suomi",
"Mulli, Laasola, Orivesi, Suomi",
"",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"Kontu, Antrea, Luovutettu Karjala",
"Aseme, Honkala, J\u00e4ms\u00e4, Suomi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Karvia, Kyl\u00e4noja, Orivesi, Suomi",
"",
"Nikkil\u00e4n rustholli, Kokko, Urjala, Suomi",
"Mullikka, Viiala, J\u00e4ms\u00e4, Suomi",
"Sukkila, Juupajoki, Suomi",
"Riekkola, Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ylinen, Kytt\u00e4l\u00e4, Tampere, Suomi",
"Huntilan rustholli, Huntila, P\u00e4lk\u00e4ne, Suomi",
"Aakkola, Orivesi, Suomi",
"",
"",
"",
"",
"Kulkas, Sorila, Aitolahti, Tampere, Suomi",
"Hannila, Antrea, Luovutettu Karjala",
"Noitermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Aakkola, Orivesi, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Mattila, Tursola, Kangasala, Suomi",
"Yl\u00e4-Nikki, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Hulipas, Juupajoki, Suomi",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Porvola, Juupajoki, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Heikkil\u00e4n rustholli, Tuittula, Hauho, H\u00e4meenlinna, Suomi",
"Iitti, Suomi",
"",
"",
"Kerppola, Kangasala, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"L\u00e4ngelm\u00e4ki, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"Anttila, Hoivala, H\u00f6ytee, Juupajoki, Suomi",
"Jaarlan rustholli, Jaarila, H\u00f6ytee, Juupajoki, Suomi",
"Anttila, Hoivala, H\u00f6ytee, Juupajoki, Suomi",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-H\u00e4kkinen, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Yl\u00e4-H\u00e4kkinen, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Mullikka, Viiala, J\u00e4ms\u00e4, Suomi",
"",
"",
"S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"",
"",
"Taipale, Mets\u00e4pirtti, Luovutettu Karjala",
"Tavela, Tursola, Kangasala, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"Tavela, Tursola, Kangasala, Suomi",
"Tavela, Tursola, Kangasala, Suomi",
"",
"",
"",
"",
"Sipoo, Suomi",
"",
"Sipoo, Suomi",
"",
"",
"",
"",
"Ruovesi, Suomi",
"",
"Korpula, Korpula, Ruovesi, Suomi",
"",
"",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"",
"Hulipas, Juupajoki, Suomi",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"Hartwick Township, Osceola County, Michigan, USA",
"",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"Turku, Suomi",
"",
"Parainen, Suomi",
"",
"",
"",
"",
"Gesterby, Sipoo, Suomi",
"Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"Viialan puustelli, Kaipola, J\u00e4ms\u00e4, Suomi",
"Kosela, Mets\u00e4pirtti, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Sirki\u00e4nsaari, Rautu, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Kosela, Mets\u00e4pirtti, Luovutettu Karjala",
"Kosela, Mets\u00e4pirtti, Luovutettu Karjala",
"Viisjoki, Mets\u00e4pirtti, Luovutettu Karjala",
"Saaroinen, Mets\u00e4pirtti, Luovutettu Karjala",
"Ilola, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"",
"Lylyj\u00e4rvi, Juupajoki, Suomi",
"Eskola, Vehkalahti, Orivesi, Suomi",
"",
"",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Hokka, Auttoinen, Padasjoki, Suomi",
"Finnil\u00e4, Maakeski, Padasjoki, Suomi",
"",
"Halikko, Salo, Suomi",
"",
"",
"Tukholma, Ruotsi",
"",
"Tukholma, Ruotsi",
"R\u00e4\u00e4veli, Viro",
"Viljainen, Rym\u00e4ttyl\u00e4, Naantali, Suomi",
"",
"Yrj\u00f6l\u00e4, Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"Sauvo, Suomi",
"Sauvo, Suomi",
"Rantala, Ilola, Sahalahti, Kangasala, Suomi",
"Porras, Hauho, H\u00e4meenlinna, Suomi",
"",
"",
"",
"",
"",
"Helsinki, Suomi",
"",
"",
"",
"",
"Cadillac, Wexford County, Michigan, USA",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kelja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"",
"",
"",
"Haljala, Puukkoinen, Kuhmoinen, Suomi",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"Haljala, Puukkoinen, Kuhmoinen, Suomi",
"Punnus, Muolaa, Luovutettu Karjala",
"Punnus, Muolaa, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"",
"",
"Tunkelon rustholli, Tunkelo, Orivesi, Suomi",
"Hampaala, Pakkala, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"Harola, Talviainen, Orivesi, Suomi",
"Maunula, Pehula, Orivesi, Suomi",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Hassi, Hassi, J\u00e4ms\u00e4, Suomi",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"",
"Hassi, Hassi, J\u00e4ms\u00e4, Suomi",
"Hassi, Hassi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Kosela, Mets\u00e4pirtti, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"",
"Riiska, Sakkola, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Kangasala, Suomi",
"Heikkil\u00e4n rustholli, Huhti, Urjala, Suomi",
"",
"",
"Heikkil\u00e4, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"Heikkil\u00e4, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Heikkil\u00e4n rustholli, Huhti, Urjala, Suomi",
"",
"Kottila, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Heikkil\u00e4, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"Valkeam\u00e4ki, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiviniemi, Sakkola, Luovutettu Karjala",
"",
"Noisniemi, Vuoksela, Luovutettu Karjala",
"Noisniemi, Vuoksela, Luovutettu Karjala",
"Noisniemi, Vuoksela, Luovutettu Karjala",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Miisua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vuole, Inkeri, Ven\u00e4j\u00e4",
"",
"Hauho, H\u00e4meenlinna, Suomi",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Mannila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kaarlela, Kokkola, Suomi",
"Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Lintulan rustholli, Paalila, Kangasala, Suomi",
"",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Suomaseman rustholli, Suomasema, Orivesi, Suomi",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"",
"",
"Hokka, Auttoinen, Padasjoki, Suomi",
"",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"",
"Hokka, Auttoinen, Padasjoki, Suomi",
"",
"",
"Ala-Mononen, Monoskyl\u00e4, Virrat, Suomi",
"Asunta, Keuruu, Suomi",
"",
"",
"Tarhap\u00e4\u00e4, Multia, Suomi",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Kutinlahti, Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Toijala, Halikko, Salo, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Uura, Multia, Suomi",
"Muolaa, Luovutettu Karjala",
"",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"",
"",
"Nihtil\u00e4, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Hulipas, Juupajoki, Suomi",
"",
"Hulipas, Juupajoki, Suomi",
"Hulipas, Juupajoki, Suomi",
"",
"Hulipas, Juupajoki, Suomi",
"",
"Lylyj\u00e4rvi, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Kopsamo, Juupajoki, Suomi",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"Hulipas, Juupajoki, Suomi",
"",
"Huntilan rustholli, Huntila, P\u00e4lk\u00e4ne, Suomi",
"Huovila, V\u00e4lkkil\u00e4, Urjala, Suomi",
"V\u00e4lkkil\u00e4, Urjala, Suomi",
"Ikaala, Urjala, Suomi",
"",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Makkola, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Punnus, Muolaa, Luovutettu Karjala",
"",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Noitermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Hiitola, Luovutettu Karjala",
"",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Vehmais, Rautu, Luovutettu Karjala",
"",
"",
"",
"Ruovesi, Suomi",
"",
"",
"Hyyryl\u00e4, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kilpola, Hiitola, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Huhti, Rautu, Luovutettu Karjala",
"Kuuttila, Savilahti - Pohjankyl\u00e4, Antrea, Luovutettu Karjala",
"Koprala, Heinjoki, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kirsta, Ritoniemi, Ruovesi, Suomi",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"",
"Hannila, Antrea, Luovutettu Karjala",
"Hannila, Antrea, Luovutettu Karjala",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"",
"Muolaan hovi, Muolaan kirkonkyl\u00e4, Muolaa, Luovutettu Karjala",
"",
"V\u00e4h\u00e4talo, H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"",
"Onnistaipale, Orivesi, Suomi",
"",
"Kemi\u00f6, Kemi\u00f6nsaari, Suomi",
"Gesterby, Sipoo, Suomi",
"",
"",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Helsinki, Suomi",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Huittinen, Suomi",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Mulkoila, Orivesi, Suomi",
"Iso-Attila, Attila, Orivesi, Suomi",
"",
"",
"",
"Ikaala, Urjala, Suomi",
"K\u00f6nkk\u00f6l\u00e4, Seppola, J\u00e4ms\u00e4, Suomi",
"H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"Ikaala, Urjala, Suomi",
"Ikaalan rustholli, Ikaala, Urjala, Suomi",
"Jaakkola, Naappila, Orivesi, Suomi",
"H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"Viialan puustelli, Kaipola, J\u00e4ms\u00e4, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Sakari, Kiukoila, Lopotti, J\u00e4ms\u00e4, Suomi",
"",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"",
"Naappila, Orivesi, Suomi",
"Ruokonen, Orivesi, Suomi",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Paavola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Jaakkola, Naappila, Orivesi, Suomi",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Huittinen, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Uusi-Juhola, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"",
"Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Rautio, Sahalahti, Kangasala, Suomi",
"Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Tunkelon rustholli, Tunkelo, Orivesi, Suomi",
"",
"",
"",
"",
"Tryyk\u00e4rinmaa, Huittinen, Suomi",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Pori, Suomi",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rieskala, Huittinen, Suomi",
"Huittinen, Suomi",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tryyk\u00e4rinmaa, Huittinen, Suomi",
"Tampere, Suomi",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tryyk\u00e4rinmaa, Huittinen, Suomi",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Uurainen, Suomi",
"Mannila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Helsinki, Suomi",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"K\u00f6nkk\u00f6l\u00e4, Seppola, J\u00e4ms\u00e4, Suomi",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"Riihihuhti torp., Moiskala, J\u00e4ms\u00e4, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Halli, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00f6j\u00e4rvi, Suomi",
"Heikurila, Heinjoki, Luovutettu Karjala",
"",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Ostamo, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kunnianiemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiiverinnotko, Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haitermaa, Sakkola, Luovutettu Karjala",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kunnianiemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"",
"Pekkala, Suolahti, Keuruu, Suomi",
"\u00c4nkk\u00e4 torp., Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kiviniemi, Sakkola, Luovutettu Karjala",
"Kalliom\u00e4ki, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Pihlajavesi, Keuruu, Suomi",
"Kallio, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Ehikki, Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Karhola, Sakkola, Luovutettu Karjala",
"",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Hakola, Ruhala, Ruovesi, Suomi",
"Ritoniemi, Ritoniemi, Ruovesi, Suomi",
"Pet\u00e4j\u00e4vesi, Suomi",
"Pet\u00e4j\u00e4vesi, Suomi",
"",
"",
"",
"",
"Karikko, Pet\u00e4j\u00e4vesi, Suomi",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tolsterniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kyl\u00e4noja, Orivesi, Suomi",
"Karvia, Kyl\u00e4noja, Orivesi, Suomi",
"Kyl\u00e4noja, Orivesi, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"Kyl\u00e4noja, Orivesi, Suomi",
"",
"",
"",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"Heikurila, Heinjoki, Luovutettu Karjala",
"",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Moiniemi, Muolaa, Luovutettu Karjala",
"Lahnajoki, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Heinjoki, Heinjoki, Luovutettu Karjala",
"",
"",
"",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"",
"",
"",
"",
"Riiska, Sakkola, Luovutettu Karjala",
"",
"Kekkonen, Ruovesi, Suomi",
"",
"Ruovesi, Suomi",
"",
"",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Kemppinen, Kontu, J\u00e4\u00e4ski, Luovutettu Karjala",
"Ikaalan rustholli, Ikaala, Urjala, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"Kangasala, Suomi",
"Ruovesi, Suomi",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kaukola, Niemola, J\u00e4ms\u00e4, Suomi",
"",
"Kaukola, Niemola, J\u00e4ms\u00e4, Suomi",
"",
"Kierros, Vehkoo, Multia, Suomi",
"",
"Kutinlahti, Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"",
"Teerijoki, Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"Vehmais, Rautu, Luovutettu Karjala",
"Sakkola, Luovutettu Karjala",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Kirsta, Ritoniemi, Ruovesi, Suomi",
"Ylti\u00e4, Pihlajavesi, Keuruu, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jokela, Partala torp., Jokioinen, J\u00e4ms\u00e4, Suomi",
"",
"Knuutila, Er\u00e4slahti, Orivesi, Suomi",
"",
"",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Sukkila, Juupajoki, Suomi",
"Kihlala, Juupajoki, Suomi",
"Sukkila, Juupajoki, Suomi",
"Sukkila, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Kolehmam\u00e4ki, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Kolhi, Savo, Orivesi, Suomi",
"Savo, Orivesi, Suomi",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Loponen, Lapinlahti, Sakkola, Luovutettu Karjala",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"Melli, Juupajoki, Suomi",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"H\u00e4meenkyr\u00f6, Suomi",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"",
"S\u00e4yn\u00e4tj\u00e4rvi, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"Korpula, Korpula, Ruovesi, Suomi",
"",
"Korpula, Korpula, Ruovesi, Suomi",
"Korpula, Korpula, Ruovesi, Suomi",
"Korpula, Korpula, Ruovesi, Suomi",
"",
"",
"Teisko, Tampere, Suomi",
"Koski, Karjula, Kuru, Yl\u00f6j\u00e4rvi, Suomi",
"Keuruu, Suomi",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kottila, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Vinni, Hahkala, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Riiska, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Kulkas, Sorila, Aitolahti, Tampere, Suomi",
"",
"Kulkas, Sorila, Aitolahti, Tampere, Suomi",
"Kulkas, Sorila, Aitolahti, Tampere, Suomi",
"",
"",
"",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Kultanen, Hattula, Muolaa, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kurikka, Kavantsaari, Antrea, Luovutettu Karjala",
"Kavantsaari, Antrea, Luovutettu Karjala",
"Kuuttila, Savilahti - Pohjankyl\u00e4, Antrea, Luovutettu Karjala",
"Kurikka, Kavantsaari, Antrea, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kolhi, Kolhi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"Kutinlahti, Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"Kutinlahti, Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kuusj\u00e4rvi, Kuusj\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Orivesi, Suomi",
"Kylm\u00e4melli, Melli, Juupajoki, Suomi",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kuusaa, Muolaa, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Merola, Muolaa, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Moiniemi, Muolaa, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Yskj\u00e4rvi, Muolaa, Luovutettu Karjala",
"Kiviniemi, Sakkola, Luovutettu Karjala",
"Noisniemi, Vuoksela, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Kiviniemi, Sakkola, Luovutettu Karjala",
"Pellonper\u00e4, Kurvila, Heinjoki, Luovutettu Karjala",
"V\u00e4h\u00e4-K\u00f6mi, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"V\u00e4h\u00e4-K\u00f6mi, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Simsi\u00f6, Simsi\u00f6, Pihlajavesi, Keuruu, Suomi",
"",
"V\u00e4h\u00e4-K\u00f6mi, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"Kalliom\u00e4ki, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Pihlajavesi, Keuruu, Suomi",
"K\u00f6ntt\u00e4ri, Suolahti, Keuruu, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Keuruu, Suomi",
"Siikala, Laasola, Orivesi, Suomi",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Liettu, Niemenkyl\u00e4, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Tuomaala, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Kolhi, Kolhi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Sepp\u00e4l\u00e4, Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Manskivi, Luomaj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Apilakoski, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Lahnajoki, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kuusaa, Muolaa, Luovutettu Karjala",
"K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"",
"",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Laurila, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"Laurila, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"Pappinen, Lapinlahti, Sakkola, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pappinen, Lapinlahti, Sakkola, Luovutettu Karjala",
"",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"Lintulan rustholli, Paalila, Kangasala, Suomi",
"",
"",
"",
"Moiniemi, Muolaa, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Tolsterniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Pekkala, Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Terenttil\u00e4, Mets\u00e4pirtti, Luovutettu Karjala",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"Tapanila, Tehi, Kuhmoinen, Suomi",
"",
"",
"",
"",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Uotila, Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"",
"",
"Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Veteli, Suomi",
"Keuruu, Suomi",
"",
"Ylinen, Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"L\u00e4tin ratsutila, Myllykyl\u00e4, Sammatti, Lohja, Suomi",
"Haljala, Puukkoinen, Kuhmoinen, Suomi",
"L\u00e4ttil\u00e4, Tapiala, Kuhmoinen, Suomi",
"",
"",
"",
"",
"",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"Vuosalmi, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Kolehmam\u00e4ki, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Nokia, Suomi",
"",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"H\u00e4meenkyr\u00f6, Suomi",
"Kirsta, Ritoniemi, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"",
"Yl\u00e4-H\u00e4kkinen, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ala-Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"J\u00e4rvenp\u00e4\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"Mattila, Tursola, Kangasala, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Melli, Melli, Juupajoki, Suomi",
"Maunula, Kopsamo, Juupajoki, Suomi",
"Maunula, Kopsamo, Juupajoki, Suomi",
"Maunula, Pehula, Orivesi, Suomi",
"Maunula, Kopsamo, Juupajoki, Suomi",
"",
"Maunula, Kopsamo, Juupajoki, Suomi",
"Pehula, Orivesi, Suomi",
"Lylyj\u00e4rvi, Juupajoki, Suomi",
"Maunula, Pehula, Orivesi, Suomi",
"",
"",
"",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"Kylm\u00e4melli, Melli, Juupajoki, Suomi",
"",
"Melli, Melli, Juupajoki, Suomi",
"",
"",
"Perttula, Kopsamo, Juupajoki, Suomi",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Orjansaari, Rautu, Luovutettu Karjala",
"Palkeala, Rautu, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Urjala, Suomi",
"Ikaalan rustholli, Ikaala, Urjala, Suomi",
"",
"Ala-Mella, Patala, J\u00e4ms\u00e4, Suomi",
"Apilakoski, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Mikkola, Juokslahti, J\u00e4ms\u00e4, Suomi",
"",
"Mikkola, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Mikkola, Juokslahti, J\u00e4ms\u00e4, Suomi",
"",
"",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"",
"",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Keuruu, Suomi",
"Uura, Multia, Suomi",
"",
"Rekola, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"",
"",
"Virrat, Suomi",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Valkeam\u00e4ki, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Tolsterniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Katila, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rasi, Pohja, Kuhmalahti, Kangasala, Suomi",
"Lylyj\u00e4rvi, Juupajoki, Suomi",
"Mulli, Laasola, Orivesi, Suomi",
"",
"Laasola, Orivesi, Suomi",
"",
"",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Mullikka, Viiala, J\u00e4ms\u00e4, Suomi",
"Viiala, J\u00e4ms\u00e4, Suomi",
"Ylti\u00e4, Pihlajavesi, Keuruu, Suomi",
"Murtom\u00e4ki, Haapam\u00e4ki, Keuruu, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Murtom\u00e4ki, Haapam\u00e4ki, Keuruu, Suomi",
"Murtom\u00e4ki, Haapam\u00e4ki, Keuruu, Suomi",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Noitermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Mustosenmaa, Heikurila, Heinjoki, Luovutettu Karjala",
"",
"",
"Heinsaari, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Koprala, Heinjoki, Luovutettu Karjala",
"Heikurila, Heinjoki, Luovutettu Karjala",
"Heikurila, Heinjoki, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kaukola, Niemola, J\u00e4ms\u00e4, Suomi",
"Riiska, Sakkola, Luovutettu Karjala",
"",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"V\u00e4likara, Salmenkyl\u00e4, Pihlajavesi, Keuruu, Suomi",
"",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Uura, Multia, Suomi",
"Multianniemi, Multia, Suomi",
"",
"",
"Hulipas, Juupajoki, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Murtom\u00e4ki, Haapam\u00e4ki, Keuruu, Suomi",
"Hulipas, Juupajoki, Suomi",
"Kolhi, Kolhi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Kolhi, Kolhi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Keuruu, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Ala-Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ilola, Muolaa, Luovutettu Karjala",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vuohensalo, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"Haukkavaara, Hiitola, Luovutettu Karjala",
"",
"",
"",
"",
"Tolsterniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Tolsterniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Suomi",
"",
"Siikala, Laasola, Orivesi, Suomi",
"",
"",
"Natukka, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Tiusala, Valkealahti, Keuruu, Suomi",
"",
"",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Nenonen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"Vuosalmi, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"",
"Niemen rustholli, T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"Ruovesi, Suomi",
"",
"Kuhmoinen, Suomi",
"Kuhmoinen, Suomi",
"",
"Koivuniemi, Orivesi, Suomi",
"",
"Naappila, Orivesi, Suomi",
"Naappila, Orivesi, Suomi",
"Kuikka, S\u00e4yryl\u00e4, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Nikki, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huovila, V\u00e4lkkil\u00e4, Urjala, Suomi",
"",
"Haavisto, Orivesi, Suomi",
"",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kopsamo, Juupajoki, Suomi",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4n rustholli, Kokko, Urjala, Suomi",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Noitermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Matiskala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Noitermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Noitermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Kirsta, Ritoniemi, Ruovesi, Suomi",
"Nuottiniemi, Mustaj\u00e4rvi, Ruovesi, Suomi",
"",
"",
"V\u00e4h\u00e4-K\u00f6mi, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Valkeam\u00e4ki, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Hinkkala, Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"Kiiverinnotko, Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Paattila, Seppola, J\u00e4ms\u00e4, Suomi",
"Ouni, Ouninpohja, J\u00e4ms\u00e4, Suomi",
"",
"",
"Heikurila, Heinjoki, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"Heinjoen tilattomat, Heinjoki, Heinjoki, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Heikurila, Heinjoki, Luovutettu Karjala",
"Pellonper\u00e4, Kurvila, Heinjoki, Luovutettu Karjala",
"Pellonper\u00e4, Kurvila, Heinjoki, Luovutettu Karjala",
"",
"Paakkarila, Antrea, Luovutettu Karjala",
"",
"P\u00f6h\u00f6, Rahikkala, Antrea, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Paavola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pehula, Orivesi, Suomi",
"Unkila, Padustaipale, Orivesi, Suomi",
"Koivisto, Sukkila, Juupajoki, Suomi",
"Mestauspaikka, Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"Padustaipale, Orivesi, Suomi",
"Padustaipale, Orivesi, Suomi",
"Haparainen, Sakkola, Luovutettu Karjala",
"Katila, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Katila, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Seurasalmi, Rauhalahti, Kuhmoinen, Suomi",
"K\u00f6ntt\u00e4ri, Suolahti, Keuruu, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Raivattala, Hiitola, Luovutettu Karjala",
"Eskola, Vehkalahti, Orivesi, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"Siikala, Laasola, Orivesi, Suomi",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kunnianiemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Huhti, Urjala, Suomi",
"",
"",
"",
"",
"",
"Pauhari, Urjalankyl\u00e4, Urjala, Suomi",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Palkeala, Rautu, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"Sirki\u00e4nsaari, Rautu, Luovutettu Karjala",
"",
"",
"",
"Ehikki, Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Pekkala, Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Ehikki, Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Penttil\u00e4, Hurttala, Hattula, Suomi",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Perttula, Kopsamo, Juupajoki, Suomi",
"",
"",
"Perttula, Siitama, Orivesi, Suomi",
"",
"Padustaipale, Orivesi, Suomi",
"Hulipas, Juupajoki, Suomi",
"Kopsamo, Juupajoki, Suomi",
"Kopsamo, Juupajoki, Suomi",
"",
"",
"Pihlajalahti, Kuhmoinen, Suomi",
"Pihlajalahti, Kuhmoinen, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Pihlajalahti, Kuhmoinen, Suomi",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Hulipas, Juupajoki, Suomi",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sortanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Palkeala, Rautu, Luovutettu Karjala",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"",
"Pohjaslahti, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Murtom\u00e4ki, Haapam\u00e4ki, Keuruu, Suomi",
"Posti, Loila, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Posti, Loila, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Ylti\u00e4, Pihlajavesi, Keuruu, Suomi",
"Saaroinen, Mets\u00e4pirtti, Luovutettu Karjala",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Paakkarila, Antrea, Luovutettu Karjala",
"Cadillac, Wexford County, Michigan, USA",
"Punnus, Muolaa, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Viisjoki, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Palkeala, Rautu, Luovutettu Karjala",
"Vehmais, Rautu, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Kiiverinnotko, Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Kellari, Kopsamo, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"Kihlala, Juupajoki, Suomi",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Huittinen, Suomi",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kelja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rautu, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vesiniitty, Huittinen, Suomi",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"P\u00f6h\u00f6, Rahikkala, Antrea, Luovutettu Karjala",
"Rahikkala, Antrea, Luovutettu Karjala",
"Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Heinjoki, Heinjoki, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Sortanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Karkku, Vammala, Sastamala, Suomi",
"Rainio, Karkku, Vammala, Sastamala, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Raiskinm\u00e4ki, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Kallio, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Viljainen, Rym\u00e4ttyl\u00e4, Naantali, Suomi",
"Ruotsi",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rasi, Pohja, Kuhmalahti, Kangasala, Suomi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Rasi, Pohja, Kuhmalahti, Kangasala, Suomi",
"Rasi, Pohja, Kuhmalahti, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"Pirkkala, Suomi",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"",
"Raiskinm\u00e4ki, Reinikka, Pihlajavesi, Keuruu, Suomi",
"",
"Kerppola, Kangasala, Suomi",
"",
"Rekola, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"V\u00e4h\u00e4-K\u00f6mi, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"S\u00e4llinlahti, Pihlajavesi, Keuruu, Suomi",
"Rekolan rustholli, Heponiemi, Kangasala, Suomi",
"Rekola, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"",
"Rekola, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"",
"",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Riekkola, Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Pori, Suomi",
"Keuruu, Suomi",
"Pet\u00e4j\u00e4rvi, Sakkola, Luovutettu Karjala",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"",
"",
"Cadillac, Wexford County, Michigan, USA",
"Heinjoki, Heinjoki, Luovutettu Karjala",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"Kunnianiemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Cadillac, Wexford County, Michigan, USA",
"Moiniemi, Muolaa, Luovutettu Karjala",
"",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuusaa, Muolaa, Luovutettu Karjala",
"",
"Lippainmaa, Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Moiniemi, Muolaa, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"",
"Riiska, Sakkola, Luovutettu Karjala",
"",
"Heikurila, Heinjoki, Luovutettu Karjala",
"Kokkola, Suomi",
"Kokkola, Suomi",
"",
"",
"Hoivala, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Ikaala, Urjala, Suomi",
"Karppilan rustholli, Kokko, Urjala, Suomi",
"",
"Saaroinen, Mets\u00e4pirtti, Luovutettu Karjala",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Jussila, Rautio, Sahalahti, Kangasala, Suomi",
"V\u00e4likara, Salmenkyl\u00e4, Pihlajavesi, Keuruu, Suomi",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Noitermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiiverinnotko, Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Norsjoki, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Seurasalmi, Rauhalahti, Kuhmoinen, Suomi",
"Seurasalmi, Rauhalahti, Kuhmoinen, Suomi",
"",
"",
"Siikala, Laasola, Orivesi, Suomi",
"Heikkil\u00e4, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Kolhi, Savo, Orivesi, Suomi",
"Siikala, Laasola, Orivesi, Suomi",
"",
"",
"Kopsamo, Juupajoki, Suomi",
"Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"",
"",
"Sillanp\u00e4\u00e4, Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Lahnajoki, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Simola, Toivila, J\u00e4ms\u00e4, Suomi",
"Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Seurasalmi, Rauhalahti, Kuhmoinen, Suomi",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"Parpola, Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"Kangasala, Suomi",
"",
"",
"Siurola, Raikku, Kangasala, Suomi",
"Kangasala, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"",
"",
"",
"Kyrkstad, Lohja, Suomi",
"Kytt\u00e4l\u00e4, Tampere, Suomi",
"",
"Hankavesi, \u00c4ht\u00e4ri, Suomi",
"",
"V\u00e4likara, Salmenkyl\u00e4, Pihlajavesi, Keuruu, Suomi",
"Kirkonm\u00e4ki, Keuruu, Suomi",
"Keuruu, Suomi",
"",
"",
"",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jokela, Partala torp., Jokioinen, J\u00e4ms\u00e4, Suomi",
"Ala-Rekola, Vierel\u00e4, Tervala, J\u00e4ms\u00e4, Suomi",
"Eerola, Keij\u00e4rvi, Yl\u00f6j\u00e4rvi, Suomi",
"S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Jokioinen, J\u00e4ms\u00e4, Suomi",
"Pastoraatti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pastoraatti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"L\u00e4ngelm\u00e4ki, Suomi",
"Tarhia, Keuruu, Suomi",
"",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haitermaa, Sakkola, Luovutettu Karjala",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Keuruu, Suomi",
"Asunta, Keuruu, Suomi",
"",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Taipale, Suoj\u00e4rvi, Keuruu, Suomi",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Hannola, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Matiskala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Riiska, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pattoinen, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Parpola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Parpola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Jutikkala, Jutikkala, Saarioispuoli, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"",
"",
"Niemen rustholli, T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"",
"Tavela, Tursola, Kangasala, Suomi",
"Parainen, Suomi",
"Suomi",
"",
"Turku, Suomi",
"",
"",
"Pekkala, Suolahti, Keuruu, Suomi",
"Teerijoki, Oriveden kyl\u00e4, Orivesi, Suomi",
"Teerijoki, Oriveden kyl\u00e4, Orivesi, Suomi",
"Teerijoki, Oriveden kyl\u00e4, Orivesi, Suomi",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Kuhmoinen, Suomi",
"P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Ampiala, Keuruu, Suomi",
"Tarhap\u00e4\u00e4, Multia, Suomi",
"",
"",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Valkeam\u00e4ki, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Soini, Suomi",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiviniemi, Sakkola, Luovutettu Karjala",
"Aln\u00e4s, Ritvala, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"",
"",
"",
"Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Kurkela, Nurmii, Muolaa, Luovutettu Karjala",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pori, Suomi",
"Helsinki, Suomi",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pori, Suomi",
"",
"G\u00f6teborg, Ruotsi",
"\u00c4ht\u00e4ri, Suomi",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kopsala, Hiitola, Luovutettu Karjala",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"\u00c4ht\u00e4ri, Suomi",
"Sein\u00e4joki, Suomi",
"Pappila, S\u00e4rkilahti, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Kurkela, Nurmii, Muolaa, Luovutettu Karjala",
"Taipale, Mets\u00e4pirtti, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ruhala, Ruovesi, Suomi",
"",
"Ilola, Sahalahti, Kangasala, Suomi",
"Kangasala, Suomi",
"M\u00e4kil\u00e4, Sahalahti, Kangasala, Suomi",
"Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"N\u00e4ttil\u00e4, Patala, J\u00e4ms\u00e4, Suomi",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"",
"",
"Jaakkola, Naappila, Orivesi, Suomi",
"",
"",
"Kalliom\u00e4ki, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Tuomaala, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"",
"Turku, Suomi",
"",
"",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Noisniemi, Vuoksela, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Hattula, Muolaa, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ehikki, Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"J\u00e4ms\u00e4, Suomi",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Purpua, Haparainen, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Vuohensalo, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Kiiverinnotko, Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"V\u00e4likara, Salmenkyl\u00e4, Pihlajavesi, Keuruu, Suomi",
"",
"",
"Kutinlahti, Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"Orjansaari, Rautu, Luovutettu Karjala",
"",
"Kokkola, Suomi",
"Elkins, Washington County, Arkansas, USA",
"Grand Rapids, Kent County, Michigan, USA",
"Niles, Berrien County, Michigan, USA",
"Avondale, Evart, Osceola County, Michigan, USA",
"Williamston, Ingham County, Michigan, USA",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Keuruu, Suomi",
"",
"",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Manskivi, Luomaj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ylinen, Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ylinen, Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ylinen, Kytt\u00e4l\u00e4, Tampere, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Visuvesi, Ruovesi, Suomi",
"Visuvesi, Ruovesi, Suomi",
"Raiskinm\u00e4ki, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Ylti\u00e4, Pihlajavesi, Keuruu, Suomi",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Yl\u00e4-H\u00e4kkinen, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Yl\u00e4-H\u00e4kkinen, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Murtom\u00e4ki, Haapam\u00e4ki, Keuruu, Suomi",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Hirvij\u00e4rvi, Juupajoki, Suomi",
"Storg\u00e5rd, Kyl\u00e4noja, Orivesi, Suomi",
"",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Naappila, Orivesi, Suomi",
"Urjala, Suomi",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kaukola, Niemola, J\u00e4ms\u00e4, Suomi",
"Lahnajoki, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Jokela, Partala torp., Jokioinen, J\u00e4ms\u00e4, Suomi"
]
Dwr.ScriptLoaded('dwr_db_I_death_place_0.js');
