// This file is generated

F_marr_place_0 = [
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"Kottila, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Pappila, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Patala, J\u00e4ms\u00e4, Suomi",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"",
"Heikkil\u00e4, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"Tauriala, Seppola, J\u00e4ms\u00e4, Suomi",
"",
"",
"Visuvesi, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Hauho, H\u00e4meenlinna, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Honkala, J\u00e4ms\u00e4, Suomi",
"Mikkola, Juokslahti, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Virkaj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"",
"Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Rahikkala, Antrea, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Hulipas, Juupajoki, Suomi",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Hoivala, H\u00f6ytee, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Varala, Kangasala, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"L\u00f6yt\u00e4n\u00e4, Teisko, Tampere, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Ritoniemi, Ritoniemi, Ruovesi, Suomi",
"",
"",
"",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Storminiemi, Ruovesi, Suomi",
"",
"Hulipas, Juupajoki, Suomi",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Lylyj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Kotaj\u00e4rvi, Kuhmoinen, Suomi",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Viiksanlahti, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Hatakkala, Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Lupra, Sakkola, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"",
"Eskola, Vehkalahti, Orivesi, Suomi",
"Porvola, Juupajoki, Suomi",
"",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Kuusj\u00e4rvi, Kuusj\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"",
"S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"",
"",
"",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Yl\u00e4puusti, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"",
"",
"L\u00e4ttil\u00e4, Tapiala, Kuhmoinen, Suomi",
"",
"Punnus, Muolaa, Luovutettu Karjala",
"",
"",
"",
"Rautio, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"Laasola, Orivesi, Suomi",
"",
"",
"",
"",
"Sakkola, Luovutettu Karjala",
"",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Hauho, H\u00e4meenlinna, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Kunnianiemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"P\u00f6lh\u00f6l\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Watikkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haitermaa, Sakkola, Luovutettu Karjala",
"Kopsala, Hiitola, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"Auttoinen, Padasjoki, Suomi",
"",
"",
"",
"",
"",
"Ampiala, Keuruu, Suomi",
"Vilhula, Multia, Suomi",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Perttula, Kopsamo, Juupajoki, Suomi",
"",
"",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Kopsamo, Juupajoki, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"P\u00f6lh\u00f6l\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Hannila, Antrea, Luovutettu Karjala",
"Heikurila, Heinjoki, Luovutettu Karjala",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Manninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Kirsta, Ritoniemi, Ruovesi, Suomi",
"",
"",
"",
"Hannila, Antrea, Luovutettu Karjala",
"",
"Muolaan hovi, Muolaan kirkonkyl\u00e4, Muolaa, Luovutettu Karjala",
"",
"",
"",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"",
"Ojaniemi, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"Sakkolan pappila, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Hannukkala, Hiitola, Luovutettu Karjala",
"Rauralaniemi, Hiitola, Luovutettu Karjala",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Ruudala, Huittula, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Unkila, Padustaipale, Orivesi, Suomi",
"V\u00e4lkkil\u00e4, Urjala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Hokka, Auttoinen, Padasjoki, Suomi",
"Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Naappila, Orivesi, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"",
"Jokela, Partala torp., Jokioinen, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Huittinen, Suomi",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haitermaa, Sakkola, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"Ikaala, Urjala, Suomi",
"Ilola torp, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"",
"",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Kunnianiemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rven kirkonkyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Makkola, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Karikko, Pet\u00e4j\u00e4vesi, Suomi",
"Karikko, Pet\u00e4j\u00e4vesi, Suomi",
"",
"",
"",
"Pihlajavesi, Keuruu, Suomi",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"",
"Pet\u00e4j\u00e4vesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Raivattala, Hiitola, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Hakola, Ruhala, Ruovesi, Suomi",
"",
"",
"Lottola, Antrea, Luovutettu Karjala",
"",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"Ruovesi, Suomi",
"",
"",
"",
"",
"\u00c4nkk\u00e4 torp, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Kiviniemi, Sakkola, Luovutettu Karjala",
"",
"",
"",
"",
"Nuottiniemi, Mustaj\u00e4rvi, Ruovesi, Suomi",
"",
"Niemi, Juokslahti, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"Padustaipale, Orivesi, Suomi",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Laasola, Orivesi, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"Melli, Melli, Juupajoki, Suomi",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vanhajaama, Mets\u00e4pirtti, Luovutettu Karjala",
"Taipale, Mets\u00e4pirtti, Luovutettu Karjala",
"Koukunniemi, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Raaju, Mets\u00e4pirtti, Luovutettu Karjala",
"Volossula, Sakkola, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"Maunula, Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Purpua, Haparainen, Sakkola, Luovutettu Karjala",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Ala-Jaarila, H\u00f6ytee, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kurikka, Kavantsaari, Antrea, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kolhi, Kolhi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Asunta, Keuruu, Suomi",
"Tarhap\u00e4\u00e4, Multia, Suomi",
"V\u00e4lkky, Keuruu, Suomi",
"",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Savo, Orivesi, Suomi",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Kurkela, Nurmii, Muolaa, Luovutettu Karjala",
"",
"Ilola, Muolaa, Luovutettu Karjala",
"",
"Merola, Muolaa, Luovutettu Karjala",
"",
"Kottila, Kiviniemi, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Rekola, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"",
"",
"",
"",
"K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"",
"",
"",
"",
"",
"Kuoreven kirkko, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Salkinoja, Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"",
"",
"H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Kaukola, Niemola, J\u00e4ms\u00e4, Suomi",
"",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Perkj\u00e4rvi, Muolaa, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Huhti, Rautu, Luovutettu Karjala",
"",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Niemen rustholli, T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"",
"Kuhmalahti, Kangasala, Suomi",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"Ojaniemi, Sakkola, Luovutettu Karjala",
"Pet\u00e4j\u00e4rvi, Sakkola, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Pohja, Kuhmalahti, Kangasala, Suomi",
"Kyl\u00e4noja, Orivesi, Suomi",
"",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"",
"",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Kortesuo, Kokkila, Juupajoki, Suomi",
"Pylkki, Juupajoki, Suomi",
"Hulipas, Juupajoki, Suomi",
"",
"",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Tavela, Tursola, Kangasala, Suomi",
"",
"",
"",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"Kopsamo, Juupajoki, Suomi",
"Pehula, Orivesi, Suomi",
"",
"",
"",
"Pappila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Hulipas, Juupajoki, Suomi",
"",
"",
"",
"",
"Padustaipale, Orivesi, Suomi",
"",
"",
"",
"Pehula, Orivesi, Suomi",
"",
"Harola, Talviainen, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Kokko, Urjala, Suomi",
"Honkolan s\u00e4teriratsutila, Honkola, Urjala, Suomi",
"",
"",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"Lahnajoki, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Pihkala, Heinjoki, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"",
"Ruovesi, Suomi",
"H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Murtom\u00e4ki, Haapam\u00e4ki, Keuruu, Suomi",
"",
"",
"",
"Kuninkaanristi, Vuoksela, Luovutettu Karjala",
"",
"Heikurila, Heinjoki, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Pihkala, Heinjoki, Luovutettu Karjala",
"Heinjoki, Luovutettu Karjala",
"",
"",
"Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Lepp\u00e4j\u00e4rvi, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"",
"",
"J\u00e4rvenp\u00e4\u00e4, Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Apilakoski, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Hirvel\u00e4, Valkealuomi, J\u00e4ms\u00e4, Suomi",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Joensuu, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kurra, Pitk\u00e4nen, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Tolsterniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Naappila, Orivesi, Suomi",
"",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Karhola, Sakkola, Luovutettu Karjala",
"",
"",
"",
"",
"Valkj\u00e4rvi, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Norsjoki, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyynikkil\u00e4n pappila, Pappilankulma, Ruovesi, Suomi",
"Kellari, Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiiverinnotko, Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiiverinnotko, Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Ouni, Ouninpohja, J\u00e4ms\u00e4, Suomi",
"",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"K\u00e4\u00e4ntym\u00e4, Heinjoki, Luovutettu Karjala",
"",
"",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Seurasalmi, Rauhalahti, Kuhmoinen, Suomi",
"",
"",
"",
"",
"",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Suolahti, Keuruu, Suomi",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"Kuoksj\u00e4rvi, Hiitola, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Rautu, Luovutettu Karjala",
"",
"",
"",
"Keuruu, Suomi",
"Kivij\u00e4rvi, Suolahti, Keuruu, Suomi",
"Suolahti, Keuruu, Suomi",
"Kuitula, Kuitulanper\u00e4, Pet\u00e4j\u00e4vesi, Suomi",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"Suolahti, Keuruu, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"",
"",
"",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"Kopsamo, Juupajoki, Suomi",
"Nikkil\u00e4, Haavisto, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Norsjoki, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4puusti, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Pylkki, Juupajoki, Suomi",
"",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"Porvola, Juupajoki, Suomi",
"Aakkola, Orivesi, Suomi",
"",
"",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Kelja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rven kirkonkyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Kiurula, J\u00e4\u00e4ski, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Raiskinm\u00e4ki, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Korpula, Korpula, Ruovesi, Suomi",
"",
"",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"P\u00f6lh\u00f6l\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Lupra, Sakkola, Luovutettu Karjala",
"",
"Mulkoila, Orivesi, Suomi",
"",
"",
"Vehoniemi, Kangasala, Suomi",
"",
"",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rven kirkonkyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kolehmam\u00e4ki, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"Kerppola, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Orola, Muolaa, Luovutettu Karjala",
"Vuosalmi, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"",
"",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"",
"",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Moiniemi, Muolaa, Luovutettu Karjala",
"",
"",
"USA",
"Kuusaa, Muolaa, Luovutettu Karjala",
"",
"Peikola, Muolaa, Luovutettu Karjala",
"Ilola, Muolaa, Luovutettu Karjala",
"",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Punnus, Muolaa, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Oinala, Muolaa, Luovutettu Karjala",
"Koprala, Heinjoki, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Kokkola, Suomi",
"",
"",
"",
"",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"Sukkila, Juupajoki, Suomi",
"",
"",
"",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"",
"",
"Mets\u00e4pirtti, Luovutettu Karjala",
"Pappila, Hiukkaa, J\u00e4ms\u00e4, Suomi",
"Messukyl\u00e4, Tampere, Suomi",
"Suomaseman rustholli, Suomasema, Orivesi, Suomi",
"",
"",
"V\u00e4likara, Salmenkyl\u00e4, Pihlajavesi, Keuruu, Suomi",
"",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Miisua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vuohensalo, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"",
"",
"",
"Kopsamo, Juupajoki, Suomi",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Niemel\u00e4, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"",
"",
"",
"Laasola, Orivesi, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"R\u00e4ih\u00e4, Pet\u00e4j\u00e4vesi, Suomi",
"Turku, Suomi",
"",
"",
"",
"",
"L\u00e4ngelm\u00e4ki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Varala, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Niemi, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Vuohela, Kaipola, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Seurasalmi, Rauhalahti, Kuhmoinen, Suomi",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Suomaseman rustholli, Suomasema, Orivesi, Suomi",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Kallio, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kihlala, Juupajoki, Suomi",
"Teerijoki, Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Valkeam\u00e4ki, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Hattula, Muolaa, Luovutettu Karjala",
"",
"Muolaa, Luovutettu Karjala",
"",
"",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Pohja, Kuhmalahti, Kangasala, Suomi",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"",
"",
"Hauho, H\u00e4meenlinna, Suomi",
"Iso-Heikkil\u00e4, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"Kemppil\u00e4, Antrea, Luovutettu Karjala",
"Kinnil\u00e4, Rouhiala, J\u00e4\u00e4ski, Luovutettu Karjala",
"",
"",
"",
"Ivaskansaari, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Lylyj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"Suluslahti, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Purpua, Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Pylkki, Juupajoki, Suomi",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Keuruu, Suomi",
"Ylti\u00e4, Pihlajavesi, Keuruu, Suomi",
"",
"Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kolhi, Kolhi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"K\u00f6nkk\u00f6l\u00e4, Seppola, J\u00e4ms\u00e4, Suomi",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
""
]
Dwr.ScriptLoaded('dwr_db_F_marr_place_0.js');
