// This file is generated

P_type_0 = [
"Katuosoite",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Valtio tai liittovaltio",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Oppilaitos",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"L\u00e4\u00e4ni tai osavaltio",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Piirikunta",
"Kyl\u00e4",
"Kaupunki",
"Kyl\u00e4",
"Kyl\u00e4",
"Oppilaitos",
"Kaupunki",
"Hautausmaa",
"Hautausmaa",
"L\u00e4\u00e4ni tai osavaltio",
"Kyl\u00e4",
"Kaupunki",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kaupunki",
"Kyl\u00e4",
"Oppilaitos",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Organisaatio",
"Kaupunki",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Organisaatio",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kaupunki",
"Paikkakunta",
"Tila tai talo",
"Taajama",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Laitos",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Maakunta",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Seurakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Rakennus tai torppa",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tuntematon",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Rakennus tai torppa",
"Tila tai talo",
"Oppilaitos",
"Paikkakunta",
"Organisaatio",
"Kyl\u00e4",
"Kulmakunta",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tuntematon",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Organisaatio",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Maakunta",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Oppilaitos",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Seurakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Organisaatio",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Piirikunta",
"L\u00e4\u00e4ni tai osavaltio",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Oppilaitos",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Seurakunta",
"Paikkakunta",
"Rakennus tai torppa",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Organisaatio",
"Hautausmaa",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Organisaatio",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Seurakunta",
"Hautausmaa",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Linna",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Piirikunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Hautausmaa",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Seurakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kulmakunta",
"Rakennus tai torppa",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kirkko",
"Paikkakunta",
"Paikkakunta",
"Kirkko",
"Seurakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Seurakunta",
"Kirkko",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kulmakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Seurakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Kaupunki",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Seurakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Alue",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kulmakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Oppilaitos",
"Tila tai talo",
"Kyl\u00e4",
"Organisaatio",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Alue",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kirkko",
"Seurakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Seurakunta",
"Kaupunki",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Hautausmaa",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Organisaatio",
"L\u00e4\u00e4ni tai osavaltio",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Oppilaitos",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Seurakunta",
"Alue",
"Paikkakunta",
"Oppilaitos",
"Oppilaitos",
"L\u00e4\u00e4ni tai osavaltio",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Piirikunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Piirikunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Kirkko",
"Kyl\u00e4",
"Kyl\u00e4",
"Kulmakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tuntematon",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Kaupunki",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Katuosoite",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kaupunki",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tuntematon",
"Kyl\u00e4",
"Kyl\u00e4",
"Kulmakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Hautausmaa",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kirkko",
"Kyl\u00e4",
"Seurakunta",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Piirikunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kirkko",
"Paikkakunta",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tuntematon",
"Kulmakunta",
"Tila tai talo",
"Paikkakunta",
"Kirkko",
"Tila tai talo",
"Kulmakunta",
"Kyl\u00e4",
"Kulmakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kirkko",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Seurakunta",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Seurakunta",
"Paikkakunta",
"Kirkko",
"Seurakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Maakunta",
"Organisaatio",
"Paikkakunta",
"Kyl\u00e4",
"Organisaatio",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Organisaatio",
"Tila tai talo",
"L\u00e4\u00e4ni tai osavaltio",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Laitos",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Valtio tai liittovaltio",
"Seurakunta",
"Hautausmaa",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kyl\u00e4",
"Paikkakunta",
"Seurakunta",
"Kirkko",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Seurakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kirkko",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Rakennus tai torppa",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Valtio tai liittovaltio",
"Kyl\u00e4",
"Kirkko",
"Organisaatio",
"Seurakunta",
"Paikkakunta",
"Paikkakunta",
"Seurakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kaupunki",
"Kyl\u00e4",
"Kyl\u00e4",
"Kirkko",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kirkko",
"Seurakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kirkko",
"Hautausmaa",
"Kyl\u00e4",
"Tila tai talo",
"Seurakunta",
"Valtio tai liittovaltio",
"Organisaatio",
"Valtio tai liittovaltio",
"Valtio tai liittovaltio",
"L\u00e4\u00e4ni tai osavaltio",
"L\u00e4\u00e4ni tai osavaltio",
"L\u00e4\u00e4ni tai osavaltio",
"Rakennus tai torppa",
"Oppilaitos",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Rakennus tai torppa",
"Kyl\u00e4",
"Laitos",
"Tila tai talo",
"Paikkakunta",
"Kulmakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Kirkko",
"Seurakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Maakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Maakunta",
"Paikkakunta",
"Seurakunta",
"Seurakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Organisaatio",
"Organisaatio",
"Seurakunta",
"Tila tai talo",
"Tila tai talo",
"Kulmakunta",
"Kyl\u00e4",
"Piirikunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Organisaatio",
"Organisaatio",
"Organisaatio",
"Valtio tai liittovaltio",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Organisaatio",
"Organisaatio",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Valtio tai liittovaltio",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Vesist\u00f6n osa",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Organisaatio",
"Tila tai talo",
"Kyl\u00e4",
"Tuntematon",
"Seurakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kaupunki",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Oppilaitos",
"Organisaatio",
"Organisaatio",
"Oppilaitos",
"Linna",
"Seurakunta",
"Tila tai talo",
"Paikkakunta",
"Organisaatio",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Organisaatio",
"Tila tai talo",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Maakunta",
"Paikkakunta",
"Kirkko",
"Kyl\u00e4",
"Valtio tai liittovaltio",
"Kyl\u00e4",
"Paikkakunta",
"Maakunta",
"Organisaatio",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Organisaatio",
"Organisaatio",
"Tuntematon",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Laitos",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Maakunta",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Valtio tai liittovaltio",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Linna",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Oppilaitos",
"Tila tai talo",
"Kyl\u00e4",
"Valtio tai liittovaltio",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Maakunta",
"Organisaatio",
"Kyl\u00e4",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Piirikunta",
"Kyl\u00e4",
"Valtio tai liittovaltio",
"Tila tai talo",
"Piirikunta",
"Kaupunki",
"Oppilaitos",
"Kaupunki",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Maakunta",
"Tila tai talo",
"Oppilaitos",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Rakennus tai torppa",
"Paikkakunta"
]
Dwr.ScriptLoaded('dwr_db_P_type_0.js');
