// This file is generated

F_name_0 = [
", Adam Philipsson ja , Maria Simonsdotter muodostama perhe",
", Anders Ersson ja Kottila, Maria Johansdotter muodostama perhe",
"Perhe is\u00e4lle , Arvid",
", Bartolomeus Johannis ja , Malin muodostama perhe",
", Daniel Abrahami ja , Anna Thomasdotter muodostama perhe",
", Didrik Persson ja , Barbro Eriksdotter muodostama perhe",
", Didrik Persson ja , Brita muodostama perhe",
", Didrik Persson ja , Malin Eriksdotter muodostama perhe",
", Eric Abj\u00f6rnsson ja Tawast, Margit J\u00f6nsdotter muodostama perhe",
", Erich Johansson ja , Anna Olofsdotter muodostama perhe",
", Filpus Ivarsson ja Fincke, Elin G\u00f6dekesdotter muodostama perhe",
", Henrich Pedersson ja , Helga Larsdotter muodostama perhe",
"Perhe is\u00e4lle , Henrich Sigfredsson",
"Perhe is\u00e4lle , Inge Ingesson",
", Johan Johansson ja Heikkil\u00e4, Maria Hindrichsdotter muodostama perhe",
", Johan Larsson ja , Maria Johansdotter muodostama perhe",
"Perhe \u00e4idille , Johanna",
", J\u00f6ns ja N, N muodostama perhe",
"Perhe is\u00e4lle , J\u00f6ns Bengtsson",
"Perhe is\u00e4lle , J\u00f6ran",
", J\u00f6ran Hansson ja Riiko, Elin J\u00f6ransdotter muodostama perhe",
", J\u00f6ran Jacobsson ja Iso-Attila, Walborg Ivarsdotter muodostama perhe",
"Perhe is\u00e4lle , J\u00f6ran Lukasson",
", J\u00f6ran Sigfridsson ja , Anna Thomasdotter muodostama perhe",
", Lars Hindrichsson ja , Clara J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle , Lydeke",
", Marcus Marcusson ja Ylinen, Maria Samuelsdotter muodostama perhe",
"Perhe \u00e4idille , Maria Johansdotter",
", Markus Jacobsson ja Iso-Attila, Walborg Thomasdotter muodostama perhe",
", Matti Matinpoika ja Grip, Johanna Sofia Erkintyt\u00e4r muodostama perhe",
"Perhe is\u00e4lle , Matts",
", Matts Larsson ja Iso-Attila, Sunniva Sigfridstotter muodostama perhe",
"Perhe is\u00e4lle , Matts Mattsson",
", Matts Mattsson ja Hokkanen, Carin Nilsdotter muodostama perhe",
", Matts Mattsson ja Ivala, Christina Johansdotter muodostama perhe",
", Matts Olofsson ja , Margareta Sunesdotter muodostama perhe",
"Perhe is\u00e4lle , Michel Hinckasson",
", Michel J\u00f6ransson ja Kierros, Margareta Bertilsdotter muodostama perhe",
", M\u00e5rten ja Koski, Gertrud Bertilsdotter muodostama perhe",
", Per Mattson ja , Brita muodostama perhe",
"Perhe is\u00e4lle , Peter Matsson",
", P\u00e5l P\u00e5lsson ja Koski, Gertrud Bertilsdotter muodostama perhe",
", Sigfridus Martini ja , N Henriksdotter muodostama perhe",
", Simon Ambrosiusson ja Greek, Brita Jacobsdotter muodostama perhe",
", Sten Henriksson ja Tasainen, Valborg Henriksdotter muodostama perhe",
", Stephanus Johansson ja , Maria Andersdotter muodostama perhe",
", Thomas ja Iso-Attila, Walborg Ivarsdotter muodostama perhe",
", Thomas Thomasson ja P\u00f6h\u00f6, Walborg Larsdotter muodostama perhe",
", Tomas Bertilsson ja Tasainen, Valborg Henriksdotter muodostama perhe",
", Tuve M\u00e5nsson ja Horn af Kanckas till Toijala i Halikko, Cecilia Jacobsdotter muodostama perhe",
", Veijo ja , Leena muodostama perhe",
"Acka, Anders ja Inkinen, Maria muodostama perhe",
"Perhe is\u00e4lle Acka, Lucas",
"Akkanen, Anders Andersson ja Musakka, Walborg muodostama perhe",
"Akkanen, Anders Andersson ja Vuohelainen, Maria muodostama perhe",
"Akkanen, Bertill Larsson ja Inkinen, Anna Eskellsdotter muodostama perhe",
"Akkanen, Johan Johansson ja Karilainen, Anna Michelsdotter muodostama perhe",
"Akkanen, Johan Johansson ja Karilainen, Elisabeth muodostama perhe",
"Akkanen, Johan Johansson ja Kukko, Anna Bertelsdotter muodostama perhe",
"Akkanen, Johan Lucasson ja Savolainen, Helena Hindrichsdotter muodostama perhe",
"Akkanen, Lars Bertilsson ja , Maria Simonsdotter muodostama perhe",
"Akkanen, Lukas Andersson ja Vuohelainen, Elisabeth J\u00f6ransdotter muodostama perhe",
"Akkanen, Peter Andersson ja Akkanen, Anna Johansdotter muodostama perhe",
"Akkanen, Simon Andersson ja P\u00e4rssinen, Anna Michelsdotter muodostama perhe",
"Ancherus, Erik Arvidsson ja , Anna Danielsdotter muodostama perhe",
"Ancherus, Erik Arvidsson ja , Katarina Petrusdotter muodostama perhe",
"Anttonen, Peter ja Ruuska, Maria muodostama perhe",
"Apiala, J\u00f6ran Mattsson ja , Agneta Knutsdotter muodostama perhe",
"Perhe is\u00e4lle Arvaja, Olof Hansson",
"Balk, M\u00e5ns Nilsson ja Fleming af Torlax, Brita Johansdotter muodostama perhe",
"Barck, Samuel Eriksson ja Ancherus, Johanna Ericsdotter muodostama perhe",
"Barkare, Jacob ja N, N muodostama perhe",
"Birkman, Elias Henrici ja Raukola, Lisa Thuronis muodostama perhe",
"Birkman, Gustaf Eliae ja Kerppola, Sofia Jacobsdotter muodostama perhe",
"Birkman, Gustaf Eliae ja L\u00f6yt\u00e4n\u00e4, Carin Jacobsdotter muodostama perhe",
"Birkman, Henrik Henriksson ja , Sofia Johansdotter muodostama perhe",
"Birkman, Henrik Jacobsson ja Tavela, Sofia Axelsdotter muodostama perhe",
"Bj\u00f6rnram till Isn\u00e4s, Engelbrekt Larsson ja Natt och Dag, Margareta Tuvesdotter muodostama perhe",
"Bl\u00e5field, Bengt J\u00f6nsson ja , Beata Eriksdotter muodostama perhe",
"Bl\u00e5field, Gustaf Ivarsson ja Wolffelt, Ebba Juliana muodostama perhe",
"Bl\u00e5field, Gustaf Nilsson ja Kuggb\u00f6le, Brita Sigfridsdotter muodostama perhe",
"Bl\u00e5field, Ivar Gustafsson ja Greek, Brita Simonsdotter muodostama perhe",
"Bl\u00e5field, Mickel Bengtsson ja , Brita muodostama perhe",
"Bl\u00e5field, Nils Michelsson ja Broke, Ingeborg Larsdotter muodostama perhe",
"Perhe is\u00e4lle Broke, Lars Pedersson",
"Calle, D\u00f6nhoff ja Dj\u00e4kn, M\u00e4rta Klasdotter muodostama perhe",
"Dj\u00e4kn, Bj\u00f6rn Pedersson ja , Ingrid Ingesdotter muodostama perhe",
"Dj\u00e4kn, Erengisle Bj\u00f6rnsson ja , Karin muodostama perhe",
"Dj\u00e4kn, Klaus Lydekesson ja Garp, Kristina J\u00f6nsdotter muodostama perhe",
"Dufva till N\u00e4set, Jacob Bengtsson ja Natt och Dag, Margareta Tuvesdotter muodostama perhe",
"Perhe is\u00e4lle D\u00f6nsby i Karis, Dynius Magnusson",
"D\u00f6nsby i Karis, Henrik Dyniusson ja , Ingeborg muodostama perhe",
"Perhe is\u00e4lle D\u00f6nsby i Karis, Magnus Dyniusson",
"Edesniemi, Anders Johansson ja , Lisa Johansdotter muodostama perhe",
"Edesniemi, Antti Antinpoika ja , Maija Stiina Heikintyt\u00e4r muodostama perhe",
"Edesniemi, Antti Antinpoika ja Hujala, Eeva Juhontyt\u00e4r muodostama perhe",
"Eeva, Abraham ja N, N muodostama perhe",
"Eeva, Abraham Andersson ja Kurrinen, Maria Samuelsdotter muodostama perhe",
"Eeva, Abraham Andersson ja Pitk\u00e4nen, Maria Gabrielsdotter muodostama perhe",
"Eeva, Anders Abrahamsson ja Korkka, Agnetha Petersdotter muodostama perhe",
"Eeva, Lars Abrahamsson ja , Maria muodostama perhe",
"Eeva, Matts Larsson ja Hatakka, Catharina Christersdotter muodostama perhe",
"Eeva, Paul Tobiasson ja Puolakainen, Anna Andersdotter muodostama perhe",
"Eeva, Tobias Abrahamsson ja Ollikainen, Anna Henricsdotter muodostama perhe",
"Eeva, Tobias Abrahamsson ja Puikkonen, Agnetha Christersdotter muodostama perhe",
"Ekel\u00f6f i G\u00e4sterby, Erik Larsson ja D\u00f6nsby i Karis, Marietta Henriksdotter muodostama perhe",
"Fincke, G\u00f6deke ja Tawast, Katarina Nilsdotter muodostama perhe",
"Perhe is\u00e4lle Fincke, G\u00f6deke den gamble",
"Fincke, Henrik ja Fincke, Metta G\u00f6dekesdotter muodostama perhe",
"Finnil\u00e4, Philip Jacobsson ja , Beata Eliae muodostama perhe",
"Fleming, Erik Hermansson ja Bj\u00f6rnram till Isn\u00e4s, Anna Engelbrektintyt\u00e4r muodostama perhe",
"Fleming, Henrik Klasson ja Tawast, Valborg J\u00f6nsdotter muodostama perhe",
"Fleming, Henrik Klasson ja till Viurila, Elseby M\u00e5nsdotter muodostama perhe",
"Fleming, Johan Henriksson ja Dj\u00e4kn, M\u00e4rta Erengilsdotter muodostama perhe",
"Perhe is\u00e4lle Fleming, Klaus Pedersson",
"Fleming, Magnus Klasson ja , Elin muodostama perhe",
"Fleming, Peder ja , Christina muodostama perhe",
"Fleming till Vijais i Rimito, Per Eriksson ja Muurla i \u00c5bo, Margareta Nilsdotter muodostama perhe",
"Fleming till Vijais i Rimito, Per Eriksson ja Ram, Margareta Torstensdotter muodostama perhe",
"Fleming till Villn\u00e4s, Herman Magnusson ja , Elin Filpusdotter muodostama perhe",
"Forssk\u00e5hl, Jakob Johansson ja , Sofia Juhontyt\u00e4r muodostama perhe",
"Forssk\u00e5hl, Jakob Johansson ja R\u00f6ring, Maria Henriksdotter muodostama perhe",
"Forssk\u00e5hl, Jakob Simonsson ja Bl\u00e5field, Anna Gustavsdotter muodostama perhe",
"Forssk\u00e5hl, Johan Jacobsson ja , Annika Pettersdotter muodostama perhe",
"Forssk\u00e5hl, Simon Sigfridi ja , Brita Larsdotter muodostama perhe",
"Perhe is\u00e4lle Garp, Anders",
"Perhe is\u00e4lle Garp, J\u00f6ns Andersson",
"Greek i Helsingfors, Jakob ja Gr\u00f6nfelt, Brita Bertilsdotter muodostama perhe",
"Grip, Eric Michelsson ja , Johanna Johansdotter muodostama perhe",
"Gr\u00f6nfelt, Bertil Mattsson ja Ekel\u00f6f, Margareta Eriksdotter muodostama perhe",
"Perhe is\u00e4lle Hahkalainen, Per",
"Haikonen, Bertil J\u00f6ransson ja Pusa, Elisabeth Johansdotter muodostama perhe",
"Haikonen, J\u00f6ran Bertilsson ja H\u00e4m\u00e4l\u00e4inen, Helena Simonsdotter muodostama perhe",
"Haikonen, J\u00f6ran Thomasson ja Paajanen, Anna Mattsdotter muodostama perhe",
"Haikonen, Simo Yrj\u00f6npoika ja Pohjalainen, Varpu Juhontyt\u00e4r muodostama perhe",
"Haikonen, Simo Yrj\u00f6npoika ja Virolainen, Anna Tuomaantyt\u00e4r muodostama perhe",
"Perhe is\u00e4lle Hakolahti, Per Sigfridsson",
"Haljala, Anders Simonsson ja L\u00e4ttil\u00e4, Anna Maria J\u00f6ransdotter muodostama perhe",
"Haljala, Simon Thomasson ja , Agnetha Hendrichsdotter muodostama perhe",
"Halonen, Benjam Benjamsson ja Huppunen, Brigitta muodostama perhe",
"Halonen, Benjamin Johansson ja Pullinen, Catarina Matsdotter muodostama perhe",
"Perhe is\u00e4lle Hampaala, Clemet Mikelsson",
"Hampaala, Henrik Marcusson ja , Barbara Thomasdotter muodostama perhe",
"Hampaala, Johan J\u00f6ransson ja Jussila, Margaretha J\u00f6ransdotter muodostama perhe",
"Hampaala, J\u00f6ran Mattsson ja , Ingeborg muodostama perhe",
"Hampaala, J\u00f6ran Mattsson ja , Maisa muodostama perhe",
"Perhe is\u00e4lle Hampaala, Marcus Thomasson",
"Hampaala, Matts Hendersson ja , Agnes Mattsdotter muodostama perhe",
"Perhe is\u00e4lle Hampaala, Thomas Clemetson",
"Hannin, Pehr ja , Carin Mattsdotter muodostama perhe",
"Hannin, Pehr Pehrsson ja , Carin P\u00e5hlsdotter muodostama perhe",
"Perhe is\u00e4lle Hassi, Ambrosius Thomasson",
"Hassi, J\u00f6ran Thomasson ja , Brita muodostama perhe",
"Perhe is\u00e4lle Hassi, Matts Brusiusson",
"Hassi, Simon J\u00f6ransson ja , Caisa Ericsdotter muodostama perhe",
"Hassi, Thomas Mattsson ja , Anna muodostama perhe",
"Perhe is\u00e4lle Hassi, Thomas Olsson",
"Hatakka, Christer Christersson ja Paukku, Anna Petersdotter muodostama perhe",
"Hatakka, Christer Henricsson ja Huuska, Brita Henricsdotter muodostama perhe",
"Perhe is\u00e4lle Hatakka, Hindrich",
"Hatakka, Michel Christersson ja Immonen, Carin Henrichsdotter muodostama perhe",
"Hauhalainen, Claes Jacobsson ja , Anna Hansdotter muodostama perhe",
"Heikkil\u00e4, Grels Henriksson ja , Anna muodostama perhe",
"Perhe is\u00e4lle Heikkil\u00e4, Henrik J\u00f6nsson",
"Heikkil\u00e4, Henrik Nilsson ja , Birgit Thomasdotter muodostama perhe",
"Heikkil\u00e4, Hindrich Sigfredsson ja , Maria Johansdotter muodostama perhe",
"Perhe is\u00e4lle Heikkil\u00e4, J\u00f6ns",
"Heikkil\u00e4, Michel Eskilsson ja , Christina Johansdotter muodostama perhe",
"Perhe is\u00e4lle Heikkil\u00e4, Nils Henriksson",
"Heikkonen, Hans ja Savolainen, Maria muodostama perhe",
"Heikkonen, Johan ja , Brita Simonsdotter muodostama perhe",
"Heikkonen, Sigfred Johansson ja Heikkonen, Sophia Mattsdotter muodostama perhe",
"Heikkonen, Sigfred Johansson ja K\u00e4ppi, Anna Henricsdotter muodostama perhe",
"Heikkonen, Sigfred Johansson ja Virkki, Walborg muodostama perhe",
"Heikniemi, Kalle Aataminpoika ja Viiala, Erika Joonaantyt\u00e4r muodostama perhe",
"Heiskanen, Johan J\u00f6ransson ja Piippu, Catharina Johansdotter muodostama perhe",
"Hentonen, Anders J\u00f6ransson ja Pellikainen, Magdalena Helena Ericsdotter muodostama perhe",
"Perhe is\u00e4lle Hentonen, Clemet",
"Hentonen, J\u00f6ran ja Kylm\u00e4, Walborg muodostama perhe",
"Hentonen, Peter Andersson ja Liimatta, Hanna muodostama perhe",
"Herkepaeus, Laurentius Andreasson ja , Anna Thomasdotter muodostama perhe",
"Hiiri, Georg Henricsson ja Luukkanen, Anna Mattsdotter muodostama perhe",
"Hiiri, Henric J\u00f6ransson ja Kukko, Anna Abramsdotter muodostama perhe",
"Hiiri, Johan J\u00f6ransson ja Kukko, Maria J\u00f6ransdotter muodostama perhe",
"Hiiri, Juho Juhonpoika ja Hohtari, Maria Riitantyt\u00e4r muodostama perhe",
"Hiiri, Juho Juhonpoika ja Hopia, Maria Matintyt\u00e4r muodostama perhe",
"Hiiri, Juho Juhonpoika ja Lappalainen, Maria Tuomaantyt\u00e4r muodostama perhe",
"Hiiri, Juho Juhonpoika ja Nokre, Anna Tuomaantyt\u00e4r muodostama perhe",
"Hiiri, J\u00f6ran Thomasson ja Hopia, Elisabeth muodostama perhe",
"Hiiri, J\u00f6ran Thomasson ja Kyll\u00f6nen, Maria Michelsdotter muodostama perhe",
"Hiiri, Olof Thomasson ja , Brigitta muodostama perhe",
"Hiiri, Olof Thomasson ja Kanninen, Magdalena Bertilsdotter muodostama perhe",
"Hiiri, Thomas ja , Anna muodostama perhe",
"Hiiri, Tuomas Simonpoika ja Inkinen, Aune Paavontyt\u00e4r muodostama perhe",
"Hiiri, Tuomas Tuomaanpoika ja H\u00e4nnik\u00e4inen, Liisa Mikontyt\u00e4r muodostama perhe",
"Hiiri, Tuomas Tuomaanpoika ja Tirkkonen, Olga Maria Kaarlontyt\u00e4r muodostama perhe",
"Hinkka, Erik Sigfridsson ja , Margeta Hendersdotter muodostama perhe",
"Perhe is\u00e4lle Hinkka, Michel Michelsson",
"Perhe is\u00e4lle Hinkka, Sigfrid Michelsson",
"Hohtari, Carl Martinsson ja Kaasalainen, Brita Johansdotter muodostama perhe",
"Hohtari, Carl Martinsson ja Kaasalainen, Maria muodostama perhe",
"Hohtari, Carl Petersson ja Kaasalainen, Walborg Martinsdotter muodostama perhe",
"Hohtari, Johan Petersson ja Akkanen, Walborg Petersdotter muodostama perhe",
"Hohtari, Matti Kaarlonpoika ja Haikonen, Katri Simontyt\u00e4r muodostama perhe",
"Hohtari, Matti Kaarlonpoika ja Savolainen, Maria Heikintyt\u00e4r muodostama perhe",
"Hohtari, Matts Petersson ja Pusa, Anna M\u00e5rtensdotter muodostama perhe",
"Hohtari, M\u00e5rten Carlsson ja Suutari, Catharina Petersdotter muodostama perhe",
"Hohtari, Peter ja Turve, Helena muodostama perhe",
"Hohtari, Peter Matthsson ja Sotku, Lisa Matthsdotter muodostama perhe",
"Perhe \u00e4idille Hohtari, Riitta Matintyt\u00e4r",
"Perhe is\u00e4lle Hokka, Ambrosius Persson",
"Hokka, Jacob Knutsson ja , Beata muodostama perhe",
"Hokka, Jacob Knutsson ja , Lisa muodostama perhe",
"Hokka, Knut Jacobsson ja , Chirstin Ericsdotter muodostama perhe",
"Hokka, Knut Mattsson ja , Margareta Larsdotter muodostama perhe",
"Hokka, Matts Brusiusson ja , Margareta muodostama perhe",
"Hokka, M\u00e5rten Knutsson ja Finnil\u00e4, Kirstin Philipsdotter muodostama perhe",
"Perhe is\u00e4lle Hokka, Oloff Persson",
"Perhe is\u00e4lle Hokka, Peder Olsson",
"Hokkanen, Johan Cnuthsson ja , Sophia Pehrsdotter muodostama perhe",
"Perhe is\u00e4lle Hokkanen, Lars",
"Hokkanen, Lars Nilsson ja , Carin Henrichsdotter muodostama perhe",
"Hokkanen, Matts Johansson ja Tervanen, Walborg Johansdotter muodostama perhe",
"Hokkanen, Matts Johansson ja Vehkoo, Lisa Eliasdotter muodostama perhe",
"Hokkanen, Nils Larsson ja , Chirstin Olsdotter muodostama perhe",
"Hokkanen, Nils Larsson ja , Maria Eskelsdotter muodostama perhe",
"Hokkanen, Nils Larsson ja Koski, Walborg J\u00f6ransdotter muodostama perhe",
"Hopia, Anders Andersson ja Nokre, Anna Mattsdotter muodostama perhe",
"Hopia, Anders Christersson ja \u00c4ij\u00f6, Maria J\u00f6ransdotter muodostama perhe",
"Hopia, Christer ja , Elisabeth Jacobsdotter muodostama perhe",
"Hopia, Matts Andersson ja Pusa, Lisa J\u00f6ransdotter muodostama perhe",
"Horn af \u00c5minne, Olof Mattsson ja , Katarina muodostama perhe",
"Horn till Toijala i Halikko, Jakob Olofsson ja , Kristina Ingesdotter muodostama perhe",
"Hoskari, Jacob Mattsson ja , Anna Mattsdotter muodostama perhe",
"Hoskari, Jacob Mattsson ja , Maria muodostama perhe",
"Hoskari, Matts Jacobsson ja , Elin muodostama perhe",
"Hoskari, Matts Jacobsson ja , Ragnell muodostama perhe",
"Perhe is\u00e4lle Hoskari, Matts Michelsson",
"Hujala, Johan Mattsson ja Haljala, Christina Andersdotter muodostama perhe",
"Hujala, Matts M\u00e5rtensson ja Hassi, Maria Simonsdotter muodostama perhe",
"Hujala, Matts M\u00e5rtensson ja Ruolahti, Ingeborg Johansdotter muodostama perhe",
"Hujala, M\u00e5rten Thomasson ja , Agnis muodostama perhe",
"Hujala, M\u00e5rten Thomasson ja , Gertrud Andersdotter muodostama perhe",
"Hujala, Thomas Clemetsson ja , Lisa muodostama perhe",
"Hukki, Lars Larsson ja , Maria Larsdotter muodostama perhe",
"Huovila, Carl Jacobsson ja Nikkil\u00e4, Christina Urbanusdotter muodostama perhe",
"Huovila, Jacob Thomasson ja , Ingeborg muodostama perhe",
"Huovila, Jacob Thomasson ja , Margareta muodostama perhe",
"Perhe is\u00e4lle Huovila, Olof Olofsson",
"Huovila, Thomas Olofsson ja , Judith Ericsdotter muodostama perhe",
"Perhe is\u00e4lle Huppunen, Bertil Eskelsson",
"Huppunen, Eskell ja , Maria Mattsdotter muodostama perhe",
"Huuhka, Anders J\u00f6ransson ja Kyll\u00f6nen, Walborg muodostama perhe",
"Huuhka, Anders J\u00f6ransson ja K\u00e4h\u00f6nen, Walborg Ericsdotter muodostama perhe",
"Huuhka, Matts ja Iili\u00e4inen, Brita muodostama perhe",
"H\u00e4kkinen, Anders Cristiansson ja , Maria P\u00e5hlsdotter muodostama perhe",
"H\u00e4kkinen, Anders Cristiansson ja Huovinen, Gertrud Hansdotter muodostama perhe",
"H\u00e4kkinen, Cnunuth Michelsson ja , Kirstin muodostama perhe",
"H\u00e4kkinen, Michel Michelsson ja , Kirstin muodostama perhe",
"H\u00e4kkinen, Michel P\u00e5hlsson ja , Elin Larsdotter muodostama perhe",
"Perhe is\u00e4lle H\u00e4kkinen, P\u00e5hl",
"H\u00e4kli, Stephan Bertilsson ja Karilainen, Catharina muodostama perhe",
"H\u00e4m\u00e4l\u00e4inen, Jacob Simonsson ja Kaasalainen, Catharina J\u00f6ransdotter muodostama perhe",
"H\u00e4m\u00e4l\u00e4inen, Simon ja Turve, Helena muodostama perhe",
"H\u00e4m\u00e4l\u00e4inen, Simon Jacobsson ja Nokelainen, Catharina Johansdotter muodostama perhe",
"H\u00e4nnik\u00e4inen, Petter ja , Agnetta Pettersdotter muodostama perhe",
"H\u00e4nninen, Andreas Petersson ja Kurikka, Maria Matthiasdotter muodostama perhe",
"H\u00e4nninen, Antti Juhonpoika ja Mustonen, Kaisa Matintyt\u00e4r muodostama perhe",
"H\u00e4nninen, Johan Andersson ja Vaitti, Helena Mattsdotter muodostama perhe",
"H\u00e4nninen, Peter Petersson ja , Maria Hinricsdotter muodostama perhe",
"H\u00e4nninen, Peter Petersson ja , Walborg Petersdotter muodostama perhe",
"H\u00e4t\u00f6nen, Matts ja R\u00e4tt\u00f6, Carin P\u00e5hlsdotter muodostama perhe",
"i Fr\u00f6jdb\u00f6le, M\u00e5rten J\u00f6nsson ja , Brita muodostama perhe",
"i G\u00e4sterby, Lasse ja i H\u00e4rton\u00e4s, Margareta muodostama perhe",
"i Strand i \u00c4lg\u00e5, Salomon ja N, N muodostama perhe",
"Ihalainen, Adam Mattsson ja Kaasalainen, Anna Johansdotter muodostama perhe",
"Ihalainen, Adam Mattsson ja Suutari, Maria J\u00f6ransdotter muodostama perhe",
"Ihalainen, Christer ja Kym\u00e4l\u00e4inen, Carin muodostama perhe",
"Ihalainen, Christer ja Roini, Walborg Petersdotter muodostama perhe",
"Ihalainen, Martin Adamsson ja Viskari, Elin Mattsdotter muodostama perhe",
"Perhe is\u00e4lle Ihalainen, Matts",
"Ihalainen, Matts Reinholdsson ja Vaskelainen, Walborg J\u00f6ransdotter muodostama perhe",
"Ihalainen, Reinhold Mattsson ja , Carin Mattsdotter muodostama perhe",
"Ihalainen, Reinhold Mattsson ja Ulkolainen, Anna J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle Ij\u00e4s, Daniel",
"Ij\u00e4s, Daniel Gabrielsson ja Huuhka, Sophia muodostama perhe",
"Ij\u00e4s, Daniel Gabrielsson ja Lankinen, Carin Mattsdotter muodostama perhe",
"Ij\u00e4s, Daniel Gabrielsson ja Nokelainen, Maria Olovsdotter muodostama perhe",
"Ij\u00e4s, Daniel Gabrielsson ja S\u00e4rkinen, Maria muodostama perhe",
"Ij\u00e4s, Gabriel Danielsson ja Kuisma, Agneta muodostama perhe",
"Ij\u00e4s, Gabriel Danielsson ja Rakkolainen, Walborg muodostama perhe",
"Ij\u00e4s, Gabriel Danielsson ja Savolainen, Helena P\u00e4rsdotter muodostama perhe",
"Ij\u00e4s, Gabriel Danielsson ja Tuna, Maria muodostama perhe",
"Ikonen, V\u00e4in\u00f6 ja Tomperi, Aili muodostama perhe",
"Immonen, Henrick Michelsson ja Meltonen, Maria Mattsdotter muodostama perhe",
"Immonen, Michel ja , Dorothea Olofsdotter muodostama perhe",
"Inkinen, Anders Christersson ja P\u00e4rssinen, Anna muodostama perhe",
"Inkinen, Christer Jacobsson ja Kaasalainen, Helena J\u00f6ransdotter muodostama perhe",
"Inkinen, Heinrich Heinrichsson ja Luukkanen, Helga Helena muodostama perhe",
"Inkinen, Heinrich Johansson ja Karilainen, Elisabeth muodostama perhe",
"Inkinen, Henric Henricsson ja Rautiainen, Brita Thomasdotter muodostama perhe",
"Inkinen, Henric Lucasson ja Pusa, Maria M\u00e5rtensdotter muodostama perhe",
"Inkinen, Henric Mattsson ja Paajanen, Maria Gregoriusdotter muodostama perhe",
"Perhe is\u00e4lle Inkinen, Henrich",
"Inkinen, Jacob ja Mustonen, Catharina J\u00f6ransdotter muodostama perhe",
"Inkinen, Jacob Christersson ja Rampa, Walborg Bertilsdotter muodostama perhe",
"Inkinen, Jacob Mattsson ja , Anna muodostama perhe",
"Inkinen, Jacob Mattsson ja Hoikka, Saara muodostama perhe",
"Inkinen, Jacob Mattsson ja Pusa, Walborg muodostama perhe",
"Inkinen, Johan Henricsson ja Kinnari, Brigitta Hindricksdotter muodostama perhe",
"Perhe is\u00e4lle Inkinen, Lucas",
"Inkinen, Matti Juhonpoika ja Nolo, Katri Juhontyt\u00e4r muodostama perhe",
"Perhe is\u00e4lle Inkinen, Matts",
"Inkinen, Matts Jacobsson ja Rantalainen, Maria Johansdotter muodostama perhe",
"Inkinen, Matts Lucasson ja Rautiainen, Maria Henricstotter muodostama perhe",
"Inkinen, Paavo Yrj\u00f6npoika ja Akkanen, Riitta Heikintyt\u00e4r muodostama perhe",
"Inkinen, Paavo Yrj\u00f6npoika ja Rautiainen, Maria Yrj\u00f6ntyt\u00e4r muodostama perhe",
"Inkinen, Peter Henricsson ja Inkinen, Anna Heinrichsdotter muodostama perhe",
"Inkinen, Peter Henricsson ja N\u00e4nnim\u00e4inen, Anna Mattsdotter muodostama perhe",
"Iso-Attila, Clas Marcusson ja , Maria Sigfridsdotter muodostama perhe",
"Iso-Attila, Ivar Mattsson ja , Margareta Hindrichsdotter muodostama perhe",
"Isotalo, David J\u00f6ransson ja Salen, Johanna Thomasdotter muodostama perhe",
"Isotalo, J\u00f6ran Davidsson ja Huovila, Maria Carlsdotter muodostama perhe",
"Isotalo, Kalle Taavetinpoika ja Keppil\u00e4, Kirsti Matintyt\u00e4r muodostama perhe",
"Isotalo, Kalle Taavetinpoika ja Mexberg, Hedvig Kaapontyt\u00e4r muodostama perhe",
"Ivala, Jacob Thomasson ja , Beata Mattsdotter muodostama perhe",
"Ivala, Jacob Thomasson ja Pihlajalahti, Kirstin Johansdotter muodostama perhe",
"Ivala, Johan Jacobsson ja , Sophia Johansdotter muodostama perhe",
"Ivala, Johan Jacobsson ja , Stina Johansdotter muodostama perhe",
"Ivala, Johan Johansson ja Hokka, Maria Margaretha M\u00e5rtensdotter muodostama perhe",
"Ivala, Joonas Matinpoika ja Edesniemi, Maija Liisa Antintyt\u00e4r muodostama perhe",
"Ivala, Matts Clemetsson ja , Sophia muodostama perhe",
"Ivala, Thomas Mattsson ja , Anna J\u00f6ransdotter muodostama perhe",
"Ivala, Thomas Mattsson ja , Maria Mattsdotter muodostama perhe",
"Jaakkola, Juho Jaakonpoika ja Karvia, Anna Stina Antintyt\u00e4r muodostama perhe",
"Perhe is\u00e4lle Javanainen, M\u00e5rten",
"Jokela, Juho Joonaanpoika ja Grip, Johanna Sofia Erkintyt\u00e4r muodostama perhe",
"Jortikka, Johan ja Paavilainen, Anna muodostama perhe",
"Jortikka, Stephan Christersson ja , Lisa Larsdotter muodostama perhe",
"Perhe is\u00e4lle Jussila, Erik Eriksson",
"Perhe is\u00e4lle Jussila, Erik Mikilsson",
"Jussila, J\u00f6ran Thomasson ja , Helga Thomasdotter muodostama perhe",
"Jussila, Simon Eriksson ja , Brita Jacobsdotter muodostama perhe",
"Jussila, Thomas Simonsson ja , Maisa Eskelsdotter muodostama perhe",
"J\u00e4ppinen, Anders Andersson ja Musakka, Walborg Andersdotter muodostama perhe",
"J\u00e4ppinen, Anders Grelsson ja Kuronen, Anna muodostama perhe",
"J\u00e4ppinen, Antti Antinpoika ja Anttonen, Maria Ristontyt\u00e4r muodostama perhe",
"J\u00e4ppinen, Grels ja , Margaretha muodostama perhe",
"J\u00e4ppinen, Grels Grelsson ja Mutkari, Elisabeth Michelsdotter muodostama perhe",
"J\u00e4ppinen, Grels Michelsson ja Pakarinen, Anna Andersdotter muodostama perhe",
"J\u00e4ppinen, Heikki Antinpoika ja J\u00e4ppinen, Maria Mikontyt\u00e4r muodostama perhe",
"J\u00e4ppinen, Heikki Antinpoika ja Rautiainen, Loviisa Matintyt\u00e4r muodostama perhe",
"J\u00e4ppinen, Heimo Einari ja P\u00e4rssinen, Irja Ester muodostama perhe",
"J\u00e4ppinen, Johan Johansson ja Lipponen, Brita Mattsdotter muodostama perhe",
"J\u00e4ppinen, Johan Johansson ja Paso, Anna Sigfredsdotter muodostama perhe",
"J\u00e4ppinen, Johan Mattsson ja Kupo, Elisabeth Henricsdotter muodostama perhe",
"J\u00e4ppinen, Matti Mikonpoika ja Hohtari, Liisa Juhontyt\u00e4r muodostama perhe",
"J\u00e4ppinen, Matti Mikonpoika ja Jermolajeff, Anna Iivanantyt\u00e4r muodostama perhe",
"J\u00e4ppinen, Matts Grelsson ja , Anna Agnetta J\u00f6ransdotter muodostama perhe",
"J\u00e4ppinen, Matts Grelsson ja , Walborg muodostama perhe",
"J\u00e4ppinen, Michel Grelsson ja Akkanen, Brita Lucasdotter muodostama perhe",
"J\u00e4ppinen, Michel Johansson ja Kaasalainen, Anna Stephansdotter muodostama perhe",
"J\u00e4ppinen, Mikko Matinpoika ja N\u00e4ri\u00e4inen, Varpu Yrj\u00f6ntyt\u00e4r muodostama perhe",
"J\u00e4ppinen, William ja Hiiri, Elma Elina muodostama perhe",
"J\u00e4ppinen, William ja Tomperi, Ilmi Ilona muodostama perhe",
"J\u00e4rvensivu, Eric Johan Johansson ja Ylinen, Maria Samuelsdotter muodostama perhe",
"J\u00e4rvensivu, Johan Mattsson ja Kulkas, Walborg J\u00f6ransdotter muodostama perhe",
"J\u00e4rvensivu, Juho Kustaa Erkinpoika ja Isotalo, Hedvig Elisabet Kallentyt\u00e4r muodostama perhe",
"J\u00e4rvensivu, Kalle Fredrik Kallenpoika ja Jokela, Maija-Liisa Juhontyt\u00e4r muodostama perhe",
"J\u00e4rvensivu, Kalle Kustaa Juhonpoika ja Mattila, Hedvig Kallentyt\u00e4r muodostama perhe",
"J\u00e4rvensivu, Matts Johansson ja , Lisa Andersdotter muodostama perhe",
"Kaasalainen, Anders Johansson ja Toiviainen, Elisabeth Syringsdotter muodostama perhe",
"Perhe is\u00e4lle Kaasalainen, Gustaf",
"Kaasalainen, Hindrich ja , Anna muodostama perhe",
"Kaasalainen, Hindrich ja , Elisabeth Hindricksdotter muodostama perhe",
"Kaasalainen, Johan ja Luukkanen, Anna Cnutsdotter muodostama perhe",
"Kaasalainen, Johan Mattsson ja Ruuna, Helga muodostama perhe",
"Kaasalainen, J\u00f6ran ja Hentonen, Walborg Clemetsdotter muodostama perhe",
"Kaasalainen, J\u00f6ran J\u00f6ransson ja Javanainen, Walborg M\u00e5rtensdotter muodostama perhe",
"Kaasalainen, J\u00f6ran Mattson ja Luukkanen, Brita muodostama perhe",
"Kaasalainen, J\u00f6ran Michelsson ja Akkanen, Catharina Bertsdotter muodostama perhe",
"Kaasalainen, Martin ja P\u00f6ysti, Anna muodostama perhe",
"Kaasalainen, Matthias Cnutsson ja Lepp\u00e4nen, Brita Larsdotter muodostama perhe",
"Perhe is\u00e4lle Kaasalainen, Matts",
"Kaasalainen, Matts Johansson ja Partanen, Walborg Staffansdotter muodostama perhe",
"Kaasalainen, Michel ja N, N muodostama perhe",
"Kaasalainen, Michel J\u00f6ransson ja Lappalainen, Maria muodostama perhe",
"Perhe is\u00e4lle Kaasalainen, Pehr",
"Kaasalainen, Stephan Hinrdichson ja N\u00e4nnim\u00e4inen, Carin J\u00f6ransdotter muodostama perhe",
"Kaasalainen, Stephan Stephansson ja Huppunen, Helena Bertilsdotter muodostama perhe",
"Kaipom\u00e4ki, Axel Johansson ja Karikko, Rosina Samuelsdotter muodostama perhe",
"Kaipom\u00e4ki, Johan Larsson ja , Chirstin muodostama perhe",
"Kaipom\u00e4ki, J\u00f6ns Larsson ja , Anna Andersdotter muodostama perhe",
"Kaipom\u00e4ki, Lars Johansson ja , Carin muodostama perhe",
"Kallio, Samuli Samulinpoika ja Raiskinm\u00e4ki, Liisa Juhontyt\u00e4r muodostama perhe",
"Kalliom\u00e4ki, Samuli Yrj\u00f6npoika ja Kallio, Liisa Matintyt\u00e4r muodostama perhe",
"Kallonen, Yrj\u00f6 Juhonpoika ja Viskari, Elin Mattsdotter muodostama perhe",
"Kanninen, Bertil Andersson ja , Maria Mattsdotter muodostama perhe",
"Karikko, Erich Grelsson ja , Brita Olsdotter muodostama perhe",
"Karikko, Erik Johansson ja , Elin Larsdotter muodostama perhe",
"Karikko, Erik Johansson ja , Gertrud muodostama perhe",
"Karikko, Grels Eriksson ja , Dorde Erichsdotter muodostama perhe",
"Perhe is\u00e4lle Karikko, J\u00f6ns Nilsson",
"Karikko, Samuel Eriksson ja , Sophia Sigfredsdotter muodostama perhe",
"Karilainen, Anders ja \u00c4ij\u00f6, Maria muodostama perhe",
"Perhe is\u00e4lle Karilainen, Matts",
"Karilainen, Michel Andersson ja Pusa, Anna J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle Karjalainen, J\u00f6ran",
"Perhe is\u00e4lle Karjula, Thomas Simonsson",
"Karpinen, Henrik Matinpoika ja P\u00e4rssinen, Riitta Paulintyt\u00e4r muodostama perhe",
"Karvia, Anders Andersson ja Yrj\u00f6l\u00e4, Anna J\u00f6ransdotter muodostama perhe",
"Karvia, Anders Clemetsson ja , Walborg Erichsdotter muodostama perhe",
"Karvia, Anders J\u00f6ransson ja Karvia, Cirstin Andersdotter muodostama perhe",
"Karvia, Clemet Ersson ja , Karin muodostama perhe",
"Karvia, Erik Grelsson ja , Agneta Jacobsdotter muodostama perhe",
"Karvia, Erik Grelsson ja , Brita muodostama perhe",
"Perhe is\u00e4lle Karvia, Erik Nilsson",
"Karvia, Grels Erichsson ja , Malin Erichsdotter muodostama perhe",
"Perhe is\u00e4lle Karvia, Nils Olsson",
"Perhe is\u00e4lle Karvinen, Johan",
"Karvinen, Matts Johansson ja Vilkki, Beatha Bertilsdotter muodostama perhe",
"Karvinen, Matts Mattsson ja Ij\u00e4s, Anna Danielsdotter muodostama perhe",
"Kasoin, Cnuth ja Parkkali, Catharina Zachariasdotter muodostama perhe",
"Perhe is\u00e4lle Kaukinen, Simon",
"Kaukinen, Staffan Simonsson ja Kanninen, Anna Bertilsdotter muodostama perhe",
"Keikkala, Clemet Mattsson ja , Gertrud muodostama perhe",
"Keikkala, Clemet Mattsson ja , Maria muodostama perhe",
"Keikkala, Matts Thomasson ja , Ingebog Simonsdotter muodostama perhe",
"Perhe is\u00e4lle Keikkala, Thomas Olsson",
"Perhe is\u00e4lle Keikkala, Thomas Thomasson",
"Kemppi, Pehr J\u00f6ransson ja , Carin Larsdotter muodostama perhe",
"Kemppi, Pehr J\u00f6ransson ja , Walborg Andersdotter muodostama perhe",
"Kerppola, Thomas Johansson ja Anttila, Anna Jacobsdotter muodostama perhe",
"Kettunen, Anders Henricsson ja Pakarinen, Ingeborg muodostama perhe",
"Kierros, Bertil Mattsson ja , Sophia Larsdotter muodostama perhe",
"Kierros, Henrich Mattsson ja , Anna Pedhersdotter muodostama perhe",
"Kierros, Matts Hindersson ja , Brita muodostama perhe",
"Kierros, Matts Hindersson ja , Margareta muodostama perhe",
"Kiiski, Paul Johansson ja Tikka, Brita Mattsdotter muodostama perhe",
"Kiiski, Thomas ja Pitk\u00e4nen, Maria Pettersdotter muodostama perhe",
"Kiiveri, Johan ja Kaasalainen, Walborg Johansdotter muodostama perhe",
"Kilpel\u00e4inen, Lars ja Luostarinen, Walborg muodostama perhe",
"Kilpel\u00e4inen, Peter Larsson ja Mustonen, Walborg J\u00f6ransdotter muodostama perhe",
"Kivioja, Jonas Adamsson ja Sparf, Hedvig Benjaminsdotter muodostama perhe",
"Perhe is\u00e4lle Knepp, Simon Andersson",
"Knuutila, Henrich Henrichsson ja , Anna Clemetsdotter muodostama perhe",
"Knuutila, Henrik M\u00e5nsson ja , Brita muodostama perhe",
"Knuutila, Henrik M\u00e5nsson ja , Valborg Mattsdotter muodostama perhe",
"Knuutila, M\u00e5ns Matsson ja , Margareta Nilsdotter muodostama perhe",
"Knuutila, Samuel Henrichsson ja Rasi, Maria Mattsdotter muodostama perhe",
"Knuutila, Samuel Henrichsson ja Sirkkala, Maria Sigfredsdotter muodostama perhe",
"Perhe is\u00e4lle Kokko, Knut Nilsson",
"Perhe is\u00e4lle Kokko, Nils Bertilsson",
"Kolehma, Elias J\u00f6ransson ja L\u00f6yt\u00e4n\u00e4, Anna Stephansdotter muodostama perhe",
"Perhe is\u00e4lle Kolienp\u00e4\u00e4, Oleff Laurisson",
"Koppanen, Juho Matinpoika ja Paussu, Katri Aatamintyt\u00e4r muodostama perhe",
"Koppanen, Matti Tuomaanpoika ja Eeva, Aune Paavontyt\u00e4r muodostama perhe",
"Koppanen, Matti Tuomaanpoika ja Loponen, Maria muodostama perhe",
"Koppanen, Matti Tuomaanpoika ja Tuokko, Anna Tahvontyt\u00e4r muodostama perhe",
"Koppanen, Paul Andersson ja Papunen, Maria Larsdotter muodostama perhe",
"Koppanen, Thomas Paulsson ja Suutari, Britha Andersdotter muodostama perhe",
"Koppanen, Tuomas Matinpoika ja Korpelainen, Kaarina Matintyt\u00e4r muodostama perhe",
"Koppanen, Tuomas Matinpoika ja Makkara, Eeva Matintyt\u00e4r muodostama perhe",
"Koppanen, Tuomas Matinpoika ja Raami, Katri Juhontyt\u00e4r muodostama perhe",
"Koppanen, Tuomas Matinpoika ja Sipil\u00e4inen, Katarina Tuomaantyt\u00e4r muodostama perhe",
"Koski, Bertil Thomasson ja , Anna muodostama perhe",
"Koski, J\u00f6ran M\u00e5rtensson ja , Valborg Hendersdotter muodostama perhe",
"Kotonen, Johan J\u00f6ransson ja Mustonen, Walborg Mattsdotter muodostama perhe",
"Kotonen, J\u00f6ran ja H\u00e4kli, Brita muodostama perhe",
"Kotonen, Simon Johansson ja Virolainen, Brita Jacobsdotter muodostama perhe",
"Kottila, Johan P\u00e5hlsson ja Heikkil\u00e4, Maria Michelsdotter muodostama perhe",
"Perhe is\u00e4lle Kuggb\u00f6le, Sigfrid",
"Kuisma, Paavo ja Tomperi, Anna Liisa muodostama perhe",
"Kukko, Abram ja Talonpoika, Maria muodostama perhe",
"Kukko, Bertel ja Kukko, Maria muodostama perhe",
"Kukko, Bertel ja Kukkonen, Margaretha muodostama perhe",
"Kukko, Christer Johansson ja Anttonen, Anna Pettersdotter muodostama perhe",
"Kukko, Christer Johansson ja Nihti, Maria Bertilsdotter muodostama perhe",
"Kukko, Christer J\u00f6ransson ja Akkanen, Maria Lucasdotter muodostama perhe",
"Kukko, Georg Christersson ja Ihalainen, Maria Reinholdsdotter muodostama perhe",
"Kukko, Georg Johansson ja Leini\u00e4inen, Maria Bertilsdotter muodostama perhe",
"Kukko, Johan Christersson ja Savolainen, Walborg Henricsdotter muodostama perhe",
"Kukko, Philip ja , Margareta muodostama perhe",
"Perhe is\u00e4lle Kukkonen, Matts",
"Perhe is\u00e4lle Kukkonen, Matts Mattsson",
"Kulkas, Johan Michelsson ja , Maisa Eskellsdotter muodostama perhe",
"Kulkas, J\u00f6ran Johansson ja , Gertrud muodostama perhe",
"Kulkas, J\u00f6ran J\u00f6ransson ja , Lisa muodostama perhe",
"Kulkas, J\u00f6ran Mattsson ja , Walborg Mattsdotter muodostama perhe",
"Kulkas, Matts J\u00f6ransson ja Lintula, Lisa Thuresdotter muodostama perhe",
"Kulkas, Michel Simonsson ja , Karin muodostama perhe",
"Perhe is\u00e4lle Kulkas, Olof",
"Perhe is\u00e4lle Kulkas, Simon Olsson",
"Kultanen, Mathias J\u00f6ransson ja Virolainen, Maria Mattsdotter muodostama perhe",
"Kupo, Henric Jacobsson ja \u00c4ij\u00f6, Anna Christersdotter muodostama perhe",
"Kupo, Jacob ja Kaasalainen, Elisabeth muodostama perhe",
"Kurikka, Anders Christersson ja , Brita Andersdotter muodostama perhe",
"Kurikka, Christer Matsson ja , Anna Paulsdotter muodostama perhe",
"Kurikka, Mathias Andersson ja , Beata Henricsdotter muodostama perhe",
"Kuronen, Anders Henricsson ja Rampa, Walborg Mattsdotter muodostama perhe",
"Kuronen, Anders Henricsson ja Vanhanen, Catharina muodostama perhe",
"Kuronen, Henric ja Karvinen, Helena muodostama perhe",
"Kurrinen, Samuel Petersson ja Bergman, Margaretha muodostama perhe",
"Kutinlahti, Henrich Michelsson ja , Sofia J\u00f6ransdotter muodostama perhe",
"Kutinlahti, Henrich Michelsson ja Mikkola, Walborg Marcusdotter muodostama perhe",
"Kutinlahti, J\u00f6ran Henrichsson ja Hokkanen, Sofia Mattsdotter muodostama perhe",
"Kutinlahti, J\u00f6ran Henrichsson ja V\u00e4lkky, Maria Henrichsdotter muodostama perhe",
"Kyyr\u00f6, Eskil Johansson ja Pyykk\u00f6, Walborg Michelsdotter muodostama perhe",
"Kyyr\u00f6, Eskil Johansson ja Saira, Hedvig Michelsdotter muodostama perhe",
"Kyyr\u00f6, Hindrich Mattsson ja Toikka, Catharina Mattsdotter muodostama perhe",
"Kyyr\u00f6, Johan ja H\u00e4t\u00f6nen, Maria muodostama perhe",
"Kyyr\u00f6, Matts Hendricsson ja Kahonen, Maria Pettersdotter muodostama perhe",
"K\u00e4nk\u00e4nen, Mathias Petersson ja , Catharina muodostama perhe",
"K\u00e4nk\u00e4nen, Peter Simonsson ja Kultanen, Helena Mattsdotter muodostama perhe",
"K\u00e4nk\u00e4nen, Simon ja , Catarina Philipsdotter muodostama perhe",
"K\u00e4ppi, Anders Mattsson ja Heikkonen, Elin Sigfredsdotter muodostama perhe",
"K\u00e4ppi, Matts ja Kaitiainen, Maria Petersdotter muodostama perhe",
"K\u00f6mi, Eskel Larsson ja Nyyss\u00f6nen, Maria Larsdotter muodostama perhe",
"K\u00f6mi, Eskell P\u00e5fwelsson ja Lappi, Carin Mattsdotter muodostama perhe",
"K\u00f6mi, Hendrich Eskilsson ja Rekola, Maria M\u00e5rtensdotter muodostama perhe",
"K\u00f6mi, Johan Larsson ja Riiko, Elin J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle K\u00f6mi, Lars",
"K\u00f6mi, Lars Eskelsson ja , Gertrud Hendersdotter muodostama perhe",
"K\u00f6mi, Lars Larsson ja , Anna J\u00f6nsdotter muodostama perhe",
"K\u00f6mi, Matts Henrichsson ja Uuranniemi, Lena Thomasdotter muodostama perhe",
"K\u00f6mi, P\u00e5hl Larsson ja , Agnis muodostama perhe",
"K\u00f6mi, P\u00e5hl Larsson ja , Margareta muodostama perhe",
"Perhe is\u00e4lle K\u00f6ntter, Sigfrid",
"K\u00f6ntt\u00e4ri, J\u00f6ran Larsson ja , Elin J\u00f6ransdotter muodostama perhe",
"K\u00f6ntt\u00e4ri, J\u00f6ran Larsson ja H\u00e4kkinen, Elin Erichsdotter muodostama perhe",
"K\u00f6ntt\u00e4ri, Lars Sigfridsson ja , Anna Nilsdotter muodostama perhe",
"Laaksi, J\u00f6ren P\u00e5fwelsson ja , Anna Frantzdotter muodostama perhe",
"Laaksi, Matts P\u00e5hlsson ja , Dorothea Marcusdotter muodostama perhe",
"Laaksi, P\u00e5fwel J\u00f6ransson ja , Brita Sigfridsdotter muodostama perhe",
"Perhe is\u00e4lle Laaksi, P\u00e5hl Bertilsson",
"Perhe is\u00e4lle Laalahti, Henrik Michelsson",
"Perhe is\u00e4lle Laalahti, Michel Henriksson",
"Perhe is\u00e4lle Lappalainen, Henrich",
"Lappalainen, Johan ja , Brigita muodostama perhe",
"Lappalainen, Johan Larsson ja , Maria Mattsdotter muodostama perhe",
"Lappalainen, Johan Larsson ja J\u00e4\u00e4skel\u00e4inen, Maria Hindricsdotter muodostama perhe",
"Lappalainen, Johan Larsson ja Pamppanen, Walborg muodostama perhe",
"Lappalainen, Lars ja Melin, Maria muodostama perhe",
"Lappalainen, Simon Johansson ja Susi, Maria Nicolaisdotter muodostama perhe",
"Lappi, Matts Pedhersson ja , Clara J\u00f6ransdotter muodostama perhe",
"Leini\u00e4inen, Bertil Olofsson ja H\u00e4nnik\u00e4inen, Beatha Petersdotter muodostama perhe",
"Leini\u00e4inen, Olof ja , Maria Mattsdotter muodostama perhe",
"Lepp\u00e4nen, Anders ja Kaasalainen, Maria muodostama perhe",
"Lepp\u00e4nen, Lars Andersson ja Nolo, Maria J\u00f6ransdotter muodostama perhe",
"Lepp\u00e4nen, Pekka Tuomaanpoika ja Kotti, Anna Antintyt\u00e4r muodostama perhe",
"Perhe is\u00e4lle Lintu, Lars P\u00e5hlsson",
"Perhe is\u00e4lle Lintula, Bengt Larsson",
"Perhe is\u00e4lle Lintula, Bertil Bengtsson",
"Lintula, Jacob Simonsson ja , Sophia muodostama perhe",
"Lintula, Jacob Simonsson ja T\u00f6yr\u00e4niemi, Anna Mattsdotter muodostama perhe",
"Lintula, Simon Bertilsson ja , Margeta muodostama perhe",
"Lintula, Simon Thuresson ja Hinkkala, Maria J\u00f6ransdotter muodostama perhe",
"Lipponen, Matts ja N, N muodostama perhe",
"Lipponen, Matts Mattsson ja H\u00e4kkinen, Maria Andersdotter muodostama perhe",
"Lius, Anders ja Musakka, Catharina muodostama perhe",
"Loimusalo, Veikko Aulis ja Pekkala, Aino Anna-Liisa muodostama perhe",
"Perhe \u00e4idille Loponen, Carin Thomasdotter",
"Loponen, Henric ja Kolkka, Carin Michelsdotter muodostama perhe",
"Loponen, Thomas Henricsson ja Pulakka, Maria Andersdotter muodostama perhe",
"Loponen, Thomas Henricsson ja Roponen, Elisabeth Thomasdotter muodostama perhe",
"Lukkari, Carl J\u00f6ransson ja , Lisa muodostama perhe",
"Lukkari, Hendrich Thomasson ja , Gertrud Pedersdotter muodostama perhe",
"Lukkari, J\u00f6ren Larsson ja , Sophia muodostama perhe",
"Lukkari, Lars Hindersson ja , Walborg muodostama perhe",
"Perhe is\u00e4lle Lukkari, Tomas Nilsson",
"Luukkanen, Bertill ja Makkonen, Catharina Pettersdotter muodostama perhe",
"Luukkanen, Eskil J\u00f6ransson ja Torkkeli, Walborg J\u00f6ransdotter muodostama perhe",
"Luukkanen, Mats Bertilsson ja Lius, Maria Andersdotter muodostama perhe",
"Luukkanen, Simon Bertilsson ja Nokelainen, Carin Pettersdotter muodostama perhe",
"Luukkanen, Stephan Simosson ja Musakka, Maria Petersdotter muodostama perhe",
"Luukkanen, Stephan Stephansson ja Akkanen, Helena Simonsdotter muodostama perhe",
"L\u00e5ng, Matts Hansson ja , Karin Markusdotter muodostama perhe",
"L\u00e4ttil\u00e4, J\u00f6ran Mattsson ja , Maria M\u00e5rtensdotter muodostama perhe",
"L\u00e4ttil\u00e4, J\u00f6ran Mattsson ja , Walborg muodostama perhe",
"L\u00e4ttil\u00e4, J\u00f6ran Thomasson ja , Maisa Marcusdotter muodostama perhe",
"Perhe is\u00e4lle L\u00e4ttil\u00e4, Lasse Eriksson",
"L\u00e4ttil\u00e4, Matts J\u00f6ransson ja , Margareta muodostama perhe",
"L\u00e4ttil\u00e4, Simon Larsson ja , Margareta Ericsdotter muodostama perhe",
"L\u00e4ttil\u00e4, Thomas Simonsson ja , Anna Thomasdotter muodostama perhe",
"L\u00e4\u00e4veri, Mathias Staffansson ja , Helena muodostama perhe",
"L\u00e4\u00e4veri, Mathias Staffansson ja Kiiski, Brita muodostama perhe",
"L\u00e4\u00e4veri, Mathias Staffansson ja Neo, Walborg muodostama perhe",
"L\u00f6yt\u00e4n\u00e4, Hindrich Staffansson ja , Brita muodostama perhe",
"L\u00f6yt\u00e4n\u00e4, Hindrich Staffansson ja , Karin muodostama perhe",
"L\u00f6yt\u00e4n\u00e4, Staffan Henrichsson ja , Kaisa muodostama perhe",
"Maijala, Jacob Thomasson ja , Beata Mattsdotter muodostama perhe",
"Maijala, Juho Yrj\u00f6npoika ja Karvia, Anna Stina Antintyt\u00e4r muodostama perhe",
"Maijala, Thomas Nilsson ja , Valborg M\u00e5rtensdotter muodostama perhe",
"Maijala, Yrj\u00f6 Juhonpoika ja Rasi, Valpuri Erkintyt\u00e4r muodostama perhe",
"Mannikainen, P\u00e5hl Hindricsson ja Kupo, Elisabeth Henricsdotter muodostama perhe",
"Mannikainen, Simo ja J\u00e4ppinen, Hilma Maria muodostama perhe",
"Marttila, Cnuth Brusiusson ja Vessari, Margeta Peersdotter muodostama perhe",
"Marttila, Erich Knutsson ja , Karin Hinrichsdotter muodostama perhe",
"Marttila, Matts Erichsson ja , Walborg Larsdotter muodostama perhe",
"Perhe is\u00e4lle Marttinen, Henrik",
"Perhe is\u00e4lle Marttinen, Henrik Henriksson",
"Marttinen, Lars Hendersson ja , Helga Peersdotter muodostama perhe",
"Mattila, Kalle Kustaanpoika ja Ala-Hinkkala, Hedvig Simontyt\u00e4r muodostama perhe",
"Mattila, Kalle Kustaanpoika ja Maijala, Anna Liisa Juhontyt\u00e4r muodostama perhe",
"Mattila, Matts Henrici ja Raukola, Lisa Thuronis muodostama perhe",
"Maunula, Eskill M\u00e5nsson ja , Karin muodostama perhe",
"Maunula, Magnus Mattsson ja , Gertrud Brusiusdotter muodostama perhe",
"Maunula, Matts Eskelsson ja , Kristin Michelsdotter muodostama perhe",
"Maunula, Matts Eskelsson ja Rassi, Kirstin Simonsdotter muodostama perhe",
"Perhe is\u00e4lle Meltonen, Matts",
"Mentu, Andreas Larsson ja , Catharina Larsdotter muodostama perhe",
"Meskanen, Johan ja , Maria Clemensdotter muodostama perhe",
"Meskanen, J\u00f6ran Simonsson ja Puikkonen, Lisa Mattsdotter muodostama perhe",
"Meskanen, Simon Matsson ja , Gertrud Mattsdotter muodostama perhe",
"Mexberg, Gabriel Henricsson ja Barck, Maria Samuelsdotter muodostama perhe",
"Mexberg, Gabriel Henricsson ja \u00c4hrlig, Anna muodostama perhe",
"Mexberg, Hendrich ja , Maria muodostama perhe",
"Mexberg, Hendrich ja Skugge, Anna muodostama perhe",
"Minkkinen, Hindrich Larsson ja , Anna muodostama perhe",
"Minkkinen, J\u00f6ran Mattsson ja , Anna muodostama perhe",
"Minkkinen, J\u00f6ran Mattsson ja Reinikka, Chirstin Mattsdotter muodostama perhe",
"Minkkinen, Matts Hendersson ja , Brita muodostama perhe",
"Minkkinen, Matts J\u00f6ransson ja , Anna Cnutsdotter muodostama perhe",
"Moksu, Elias Nilsson ja , Kirstin Andersdotter muodostama perhe",
"Mong\u00e5, Johan Johansson ja Saikkonen, Elina muodostama perhe",
"Perhe is\u00e4lle Mononen, Clemet Mattsson",
"Mononen, Henrich Mattsson ja , Margareta muodostama perhe",
"Mononen, Johan Henrichsson ja Hokkanen, Carin Nilsdotter muodostama perhe",
"Perhe is\u00e4lle Mononen, Matts",
"Mononen, Matts Clemetsson ja , Elin P\u00e5lsdotter muodostama perhe",
"Mosalainen, Anders Henricsson ja Heikkonen, Brita Hansdotter muodostama perhe",
"Muli, Johan Johansson ja Kotonen, Carin Simonsdotter muodostama perhe",
"Muli, Johan Lucasson ja Karvanen, Walborg Mickelsdotter muodostama perhe",
"Muli, Johan Lucasson ja Pennanen, Carin Mattsdotter muodostama perhe",
"Muli, Johan Lucasson ja P\u00e4rssinen, Walborg Simonsdotter muodostama perhe",
"Muli, Lucas Johansson ja Kilpel\u00e4inen, Ingeborg Petersdotter muodostama perhe",
"Perhe is\u00e4lle Muli, Lukas",
"Muli, Peter ja Kukko, Anna Johansdotter muodostama perhe",
"Murtom\u00e4ki, Eskil Johansson ja Posti, Elin Isacsdotter muodostama perhe",
"Murtom\u00e4ki, Thomas Eskilsson ja Yl\u00e4-H\u00e4kkinen, Lisa Gabrielsdotter muodostama perhe",
"Murtom\u00e4ki, Tuomas Tuomaanpoika ja M\u00e4ntt\u00e4, Helena Markuksentyt\u00e4r muodostama perhe",
"Musakka, Matts ja Hyrynen, Maria muodostama perhe",
"Musakka, Matts ja Karonen, Helena Pehrsdotter muodostama perhe",
"Musakka, Peter Mattsson ja , Anna muodostama perhe",
"Musakka, Peter Mattsson ja Jortikka, Carin Johansdotter muodostama perhe",
"Perhe is\u00e4lle Musakka, P\u00e5hl",
"Mustonen, Henric Larsson ja J\u00e4\u00e4skel\u00e4inen, Helena muodostama perhe",
"Mustonen, Henric Larsson ja Paakkanen, Anna Stephansdotter muodostama perhe",
"Mustonen, Henric Larsson ja R\u00e4tt\u00f6, Elina muodostama perhe",
"Perhe is\u00e4lle Mustonen, Johan",
"Perhe is\u00e4lle Mustonen, J\u00f6ran",
"Mustonen, J\u00f6ran ja , Anna muodostama perhe",
"Mustonen, Lars Henricsson ja Paajanen, Brigitta M\u00e5rtensdotter muodostama perhe",
"Mustonen, Matti Heikinpoika ja Kaukinen, Maria Matintyt\u00e4r muodostama perhe",
"Mustonen, Matts ja Kukko, Maria muodostama perhe",
"Mutkari, Michel ja Pakarinen, Elisabeth muodostama perhe",
"Muuransuo, Kalle Aataminpoika ja Jokela, Maija-Liisa Juhontyt\u00e4r muodostama perhe",
"M\u00e4ki, Henrich Sigfridsson ja Rekola, Margeta Thomasdotter muodostama perhe",
"M\u00e4ki, Sigfred Henrichsson ja , Margeta Nilsdotter muodostama perhe",
"M\u00e4mmi, J\u00f6ran Thomasson ja Hoskari, Walborg Jacobsdotter muodostama perhe",
"M\u00e4mmi, Lars Larsson ja , Barbro muodostama perhe",
"M\u00e4mmi, Thomas J\u00f6ransson ja Moksu, Anna Elia'dotter muodostama perhe",
"M\u00e4mmi, Thomas Larsson ja , Walborg Johansdotter muodostama perhe",
"Perhe is\u00e4lle M\u00e4nts\u00e4, Nils Larsson",
"Perhe is\u00e4lle M\u00e4nts\u00e4, Thomas Nilsson",
"M\u00e4ntt\u00e4, Johan Marcusson ja , Brita Henricsdotter muodostama perhe",
"M\u00e4ntt\u00e4, Johan Marcusson ja , Carin Olofsdotter muodostama perhe",
"M\u00e4ntt\u00e4, Marcus Mattsson ja Vessari, Hedvig Henricsdotter muodostama perhe",
"M\u00e4ntt\u00e4, Marcus Thomasson ja Rainio, Lisbetha Johansdotter muodostama perhe",
"M\u00e4ntt\u00e4, Matts Johansson ja Taavettila, Walborg Michelsdotter muodostama perhe",
"M\u00e4ntt\u00e4, Thomas Thomasson ja , Chirstin Mattsdotter muodostama perhe",
"M\u00e4ntt\u00e4, Thomas Thomasson ja , Clara Mattsdotter muodostama perhe",
"M\u00e4\u00e4tt\u00e4nen, Adam Larsson ja Luukkanen, Elisabeth Eskilsdotter muodostama perhe",
"M\u00e4\u00e4tt\u00e4nen, Cnut Michelsson ja , Brita P\u00e5hlsdotter muodostama perhe",
"M\u00e4\u00e4tt\u00e4nen, Henric Adamsson ja Lappalainen, Carin Johansdotter muodostama perhe",
"M\u00e4\u00e4tt\u00e4nen, J\u00f6ran Paulsson ja Inkinen, Lena Petersdotter muodostama perhe",
"M\u00e4\u00e4tt\u00e4nen, Lars Larsson ja \u00c4ij\u00f6, Helena Johansdotter muodostama perhe",
"Perhe \u00e4idille N, N",
"N, N ja , Catharina Larsdotter muodostama perhe",
"N, N ja Inkinen, Aune Paavontyt\u00e4r muodostama perhe",
"Naskali, Elias Thomasson ja Muli, Brita Petersdotter muodostama perhe",
"Naskali, Staffan ja , Catharina muodostama perhe",
"Naskali, Thomas Staffansson ja Karilainen, Elisabeth J\u00f6ransdotter muodostama perhe",
"Nenonen, Erich ja , Chirstin Andersdotter muodostama perhe",
"Niemi, Henrich Mattsson ja , Anna muodostama perhe",
"Niemi, Henrich Mattsson ja , Hebla muodostama perhe",
"Niemi, Matts Henrichsson ja Tavela, Carin Axelsdotter muodostama perhe",
"Nihtil\u00e4, Henric Larsson ja , Gertrud J\u00f6ransdotter muodostama perhe",
"Nihtil\u00e4, J\u00f6ran Henriksson ja Korppila, Lisa Michelsdotter muodostama perhe",
"Nihtil\u00e4, J\u00f6ran Henriksson ja Tehi, Maria Simonsdotter muodostama perhe",
"Niinim\u00e4ki, Eric Jacobsson ja , Maria J\u00f6ransdotter muodostama perhe",
"Nikkil\u00e4, Matts Nilsson ja , Walborg Ericsdotter muodostama perhe",
"Perhe is\u00e4lle Nikkil\u00e4, Nils Knutsson",
"Nikkil\u00e4, Urbanus Mattsson ja , Agneta Mattsdotter muodostama perhe",
"Nikkil\u00e4, Urbanus Mattsson ja , Caisa Henricsdotter muodostama perhe",
"Perhe is\u00e4lle Niukkanen, Nils",
"Niuta, Peter ja Karilainen, Anna muodostama perhe",
"Nokelainen, Henric ja L\u00e4tti, Brita muodostama perhe",
"Nokelainen, Johan ja Niukkanen, Walborg Nilsdotter muodostama perhe",
"Nokelainen, Johan Johansson ja Huuhka, Anna Cnutsdotter muodostama perhe",
"Nokelainen, Johan Johansson ja Mustonen, Anna muodostama perhe",
"Nokelainen, Matts ja Hannukainen, Anna muodostama perhe",
"Nokelainen, Olov Mattsson ja Huppunen, Walborg Bertilsdotter muodostama perhe",
"Nokelainen, Olov Petersson ja Jortikka, Anna Johansdotter muodostama perhe",
"Nokelainen, Olov Petersson ja Sipil\u00e4inen, Margaretha Mattsdotter muodostama perhe",
"Nokelainen, Peter ja Pusa, Maria muodostama perhe",
"Nokelainen, Petter Henricsson ja Pusa, Anna muodostama perhe",
"Perhe is\u00e4lle Nokre, Hindric",
"Nokre, Johan Mattsson ja Inkinen, Maria Henricsdotter muodostama perhe",
"Nokre, J\u00f6ran Hindricsson ja Savolainen, Carin muodostama perhe",
"Nokre, J\u00f6ran Hindricsson ja Veitikka, Walborg Staffansdotter muodostama perhe",
"Nokre, Matts J\u00f6ransson ja Meskanen, Carin Simonsdotter muodostama perhe",
"Nokre, Stephan Mattsson ja Vanhanen, Brita Petersdotter muodostama perhe",
"Nokre, Tuomas Juhonpoika ja Tihver\u00e4inen, Kaarina Maununtyt\u00e4r muodostama perhe",
"Perhe is\u00e4lle Nolo, Hendric",
"Nolo, Juho Juhonpoika ja Tihver\u00e4inen, Anna Heikintyt\u00e4r muodostama perhe",
"Nolo, J\u00f6ran Hendricsson ja P\u00e4rssinen, Brita Mattsdotter muodostama perhe",
"N\u00e4nnim\u00e4inen, J\u00f6ran ja , Elisabeth Mattsdotter muodostama perhe",
"N\u00e4ppil\u00e4, Anders Simonsson ja , Elisabet Jacobsdotter muodostama perhe",
"N\u00e4ppil\u00e4, J\u00f6ran Andersson ja Hinkkala, Valborg Eriksdotter muodostama perhe",
"N\u00e4ri\u00e4inen, Heinrich Petersson ja Pusa, Elisabeth Simonsdotter muodostama perhe",
"N\u00e4ri\u00e4inen, Peter Cnutsson ja Kaasalainen, Walborg Johansdotter muodostama perhe",
"N\u00e4ri\u00e4inen, Peter Cnutsson ja P\u00e4rssinen, Maria Johansdotter muodostama perhe",
"N\u00e4ri\u00e4inen, Peter Petersson ja Olkinuora, Agnetha Simonsdotter muodostama perhe",
"N\u00e4ri\u00e4inen, Simon Heinrichsson ja Kaasalainen, Maria Mikontyt\u00e4r muodostama perhe",
"N\u00e4ri\u00e4inen, Simon Heinrichsson ja Vuohelainen, Lisa Bertylsdotter muodostama perhe",
"N\u00e4ri\u00e4inen, Yrj\u00f6 Simonpoika ja P\u00e4rssinen, Varpu Antintyt\u00e4r muodostama perhe",
"N\u00e4rv\u00e4, Elias Jacobsson ja , Maria Sigfridsdotter muodostama perhe",
"Olkinuora, Simon ja Nurkka, Maria muodostama perhe",
"Oranen, Anders Johansson ja Penttinen, Catharina Mattsdotter muodostama perhe",
"Oranen, Johan ja Kinkkunen, Elisabeth muodostama perhe",
"Ouni, Bertill Mattsson ja , Dorde muodostama perhe",
"Ouni, Johan Sigfridsson ja , Sofia Jacobsdotter muodostama perhe",
"Ouni, Sigfrid Thomasson ja , Carin Sigfridsdotter muodostama perhe",
"Ouni, Thomas Bertilsson ja , Elin muodostama perhe",
"Paajanen, Gregorius Mattsson ja Musakka, Brigita Mattsdotter muodostama perhe",
"Paajanen, Henric Johansson ja Inkinen, Helena Andersdotter muodostama perhe",
"Paajanen, Johan Johansson ja Kuronen, Elisabeth Andersdotter muodostama perhe",
"Paajanen, Johan Sigfredsson ja Kukko, Brita Abramsdotter muodostama perhe",
"Paajanen, Korius ja Tontti, Elisabeta muodostama perhe",
"Paajanen, Matts Gregoriusson ja Montonen, Catharina muodostama perhe",
"Paajanen, M\u00e5rten ja Saikkonen, Elina muodostama perhe",
"Paajanen, Sigfred Gregoriusson ja Lappalainen, Helena Henrichsdotter muodostama perhe",
"Paakkanen, Joseph ja K\u00f6lhi, Margareta muodostama perhe",
"Paakkanen, Stephan Josephsson ja Kaura, Johanna Michelsdotter muodostama perhe",
"Paakkanen, Stephan Josephsson ja Rouhiainen, Maria muodostama perhe",
"Perhe is\u00e4lle Paakkari, Jacob Thomasson",
"Paakkari, Michel Jacobsson ja Pulkki, Brita Nilsdotter muodostama perhe",
"Pakarinen, Anders J\u00f6ransson ja Muli, Maria Petersdotter muodostama perhe",
"Pakarinen, J\u00f6ran Pettersson ja Kopra, Maria muodostama perhe",
"Pakom\u00e4ki, Adam Staphansson ja Seurasalmi, Eva Andersdotter muodostama perhe",
"Palander, Abraham Axelio ja , Gertrud muodostama perhe",
"Palander, Abraham Axelio ja , Katarina muodostama perhe",
"Palander, Abraham Axelio ja , Margareta muodostama perhe",
"Palander, Abraham Axelio ja Humalainen, Katarina Johansdotter muodostama perhe",
"Palander, Petrus ja Techtonia, Elisabeth Jacobsdotter muodostama perhe",
"Palander, Petter Pettersson ja Kaipom\u00e4ki, Chirstin Axelsdotter muodostama perhe",
"Palander, Petter Pettersson ja K\u00f6ntt\u00e4ri, Kirstin J\u00f6ransdotter muodostama perhe",
"Pappinen, Simon Bertilsson ja H\u00e4nnik\u00e4inen, Beatha Petersdotter muodostama perhe",
"Parkkali, Zacharias Jacobsson ja M\u00e4kel\u00e4inen, Helga Helena Frantzdotter muodostama perhe",
"Perhe is\u00e4lle Partanen, Hindrich",
"Partanen, Stephan Hindrichsson ja , Carin muodostama perhe",
"Partanen, Stephan Hindrichsson ja Musakka, Elisabeth P\u00e5hlsdotter muodostama perhe",
"Perhe is\u00e4lle Pauhari, Eric Olofsson",
"Pauhari, Grels Thomasson ja Heikkil\u00e4, Maria Grelsdotter muodostama perhe",
"Pauhari, Henrich M\u00e5rtensson ja , Valborg Eskelsdotter muodostama perhe",
"Perhe is\u00e4lle Pauhari, Johan Olofsson",
"Perhe is\u00e4lle Pauhari, M\u00e5rten Ericsson",
"Perhe is\u00e4lle Pauhari, Olof",
"Perhe is\u00e4lle Pauhari, Olof Johansson",
"Pauhari, Thomas Henrichsson ja , Helga Mattsdotter muodostama perhe",
"Paukku, Peter Henricsson ja Kinnari, Maria Stephansdotter muodostama perhe",
"Paussu, Aatami Juhonpoika ja Ihalainen, Anna Martintyt\u00e4r muodostama perhe",
"Paussu, Aatami Juhonpoika ja Kekki, Anna Matintyt\u00e4r muodostama perhe",
"Paussu, Johan Petersson ja R\u00e4nn\u00e4li, Agnetha Adamsdotter muodostama perhe",
"Paussu, Peter ja Mentu, Maria Andersdotter muodostama perhe",
"Paussu, Peter P\u00e5hlsson ja Hatakka, Maria Michelsdotter muodostama perhe",
"Paussu, P\u00e5hl Petersson ja Eeva, Anna Mattsdotter muodostama perhe",
"Pekkala, Abraham Juhonpoika ja Kalliom\u00e4ki, Vilhelmiina Samulintyt\u00e4r muodostama perhe",
"Pekkala, Abraham Juhonpoika ja Saxberg, Maria Heikintyt\u00e4r muodostama perhe",
"Pekkala, Axel Eriksson ja , Hedvig Simonsdotter muodostama perhe",
"Pekkala, Axel Eriksson ja , Maria Mattsdotter muodostama perhe",
"Pekkala, Einar Arvid ja Virtanen, Ida Otteliana muodostama perhe",
"Pekkala, Erik Axselsson ja Palander, Lisa Pehrsdotter muodostama perhe",
"Pekkala, Juho Akselinpoika ja Murtom\u00e4ki, Fredrika Tuomaantyt\u00e4r muodostama perhe",
"Pellikainen, Erick ja , Beatha Johansdotter muodostama perhe",
"Perhe is\u00e4lle Peltonen, Pekka",
"Pennanen, Johan ja Savolainen, Maria Johansdotter muodostama perhe",
"Pennanen, Lars ja L\u00e4tti, Helena Eskelsdotter muodostama perhe",
"Pennanen, Matts Larsson ja Heiskanen, Elisabeth Johansdotter muodostama perhe",
"Penttinen, Matts ja Heikkonen, Anna muodostama perhe",
"Perhe is\u00e4lle Pihlajalahti, Frans Jacobsson",
"Pihlajalahti, Johan J\u00f6ransson ja , Maria Johansdotter muodostama perhe",
"Pihlajalahti, Peer Fransson ja , Gertrud muodostama perhe",
"Pihlajalahti, Peer Fransson ja , Walborg muodostama perhe",
"Pihlajalahti, Yrj\u00f6 Pekanpoika ja , Walborg muodostama perhe",
"Pitk\u00e4nen, Juho Simonpoika ja Rautiainen, Anna Maununtyt\u00e4r muodostama perhe",
"Pitk\u00e4nen, J\u00f6ran Andersson ja Sepp\u00e4nen, Anna Hindricksdotter muodostama perhe",
"Pitk\u00e4nen, Petter ja Puukka, Catharina muodostama perhe",
"Pitk\u00e4nen, Simon J\u00f6ransson ja Vanhanen, Catharina Mattsdotter muodostama perhe",
"Pitk\u00e4nen, Simon J\u00f6ransson ja \u00c4ij\u00f6, Walborg Simonsdotter muodostama perhe",
"Pitk\u00e4nen, Simon Simonsson ja Raami, Maria Matthsdotter muodostama perhe",
"Pohjalainen, Johan J\u00f6ransson ja Tihver\u00e4inen, Catharina Johansdotter muodostama perhe",
"Pohjalainen, Johan J\u00f6ransson ja Tiira, Walborg Petersdotter muodostama perhe",
"Pohjalainen, Johan Michelsson ja Torkkeli, Maria muodostama perhe",
"Pohjalainen, J\u00f6ran Jonasson ja Paajanen, Maria J\u00f6ransdotter muodostama perhe",
"Pohjalainen, Michel ja , Anna muodostama perhe",
"Pohjalainen, Michel Johansson ja Talonpoika, Elisabeth J\u00f6ransdotter muodostama perhe",
"Pohjalainen, Simon ja H\u00e4kli, Brita muodostama perhe",
"Posti, Isach Mattsson ja , Chirstin P\u00e5hlsdotter muodostama perhe",
"Posti, Matts Peersson ja , Maisa muodostama perhe",
"Posti, Sigfrid Isacsson ja Nenonen, Maria Ericsdotter muodostama perhe",
"Puikkonen, Christer Henricsson ja Hatakka, Carin Paulsdotter muodostama perhe",
"Puikkonen, Christer Henricsson ja Sallinen, Walborg Larsdotter muodostama perhe",
"Puikkonen, Henric Mattsson ja Rautiainen, Walborg Thomasdotter muodostama perhe",
"Puikkonen, Matts ja Lepp\u00e4nen, Carin Thomasdotter muodostama perhe",
"Puolakainen, Anders Michelsson ja Ventonen, Maria Jacobsdotter muodostama perhe",
"Puolakainen, Michel Michelsson ja Piiparinen, Anna Andersdotter muodostama perhe",
"Puolakainen, Michel Oloffsson ja Pohjalainen, Anna Petersdotter muodostama perhe",
"Puolakainen, Oloff Brusiusson ja Hynninen, Johanna muodostama perhe",
"Puolakainen, Oloff Brusiusson ja Kiiski, Maria Mattsdotter muodostama perhe",
"Pusa, Aapro Heikinpoika ja J\u00e4ppinen, Varpu Mikontyt\u00e4r muodostama perhe",
"Pusa, Georg Simonsson ja Pohjalainen, Maria Michelsdotter muodostama perhe",
"Pusa, Ilmari ja Romu, Sirkka Maria muodostama perhe",
"Pusa, Johan M\u00e5rtensson ja Toiviainen, Elisabeth Syringsdotter muodostama perhe",
"Pusa, J\u00f6ran Simonsson ja , Maria Hindricsdotter muodostama perhe",
"Pusa, Matts M\u00e5rtensson ja Tikka, Brita Mattsdotter muodostama perhe",
"Pusa, Matts M\u00e5rtensson ja \u00c4ij\u00f6, Maria Thomasdotter muodostama perhe",
"Pusa, M\u00e5rten Thomasson ja Nokelainen, Elisabeth Henricsdotter muodostama perhe",
"Perhe is\u00e4lle Pusa, Simon",
"Pusa, Simon Simonsson ja Matikainen, Walborg muodostama perhe",
"Pusa, Simon Simonsson ja Sepp\u00e4nen, Maria Gabrielsdotter muodostama perhe",
"Pusa, Simon Simonsson ja Vuohelainen, Helena Jacobsdotter muodostama perhe",
"P\u00e4rssinen, Adam Andersson ja Oranen, Anna Andersdotter muodostama perhe",
"P\u00e4rssinen, Anders Johansson ja N\u00e4nnim\u00e4inen, Maria J\u00f6ransdotter muodostama perhe",
"P\u00e4rssinen, Anders Mattsson ja Muli, Walborg Johansdotter muodostama perhe",
"P\u00e4rssinen, Johan Adamsson ja P\u00e4rssinen, Maria J\u00f6ransdotter muodostama perhe",
"P\u00e4rssinen, Johan Michelsson ja , Catharina J\u00f6ransdotter muodostama perhe",
"P\u00e4rssinen, Johan Petersson ja Herra, Gertrud Simonsdotter muodostama perhe",
"P\u00e4rssinen, Johan Petersson ja \u00c4ij\u00f6, Anna muodostama perhe",
"Perhe is\u00e4lle P\u00e4rssinen, Juho",
"P\u00e4rssinen, Juho Juhonpoika ja Javanainen, Gertrud J\u00f6ransdotter muodostama perhe",
"P\u00e4rssinen, Juho Mikonpoika ja Haikonen, Anna Juhontyt\u00e4r muodostama perhe",
"P\u00e4rssinen, Matths Johansson ja Laurikainen, Maria muodostama perhe",
"P\u00e4rssinen, Matths Johansson ja Savolainen, Walborg Augustsdotter muodostama perhe",
"Perhe is\u00e4lle P\u00e4rssinen, Matts",
"P\u00e4rssinen, Matts Adamsson ja M\u00e4\u00e4tt\u00e4nen, Walborg Henricsdotter muodostama perhe",
"P\u00e4rssinen, Matts Stephansson ja Inkinen, Brita Mattsdotter muodostama perhe",
"P\u00e4rssinen, Michel ja N, N muodostama perhe",
"P\u00e4rssinen, Michel Johansson ja Akkanen, Anna Bertilsdotter muodostama perhe",
"P\u00e4rssinen, Mikko Juhonpoika ja Tanninen, Kaarina Tuomaantyt\u00e4r muodostama perhe",
"P\u00e4rssinen, Paul Mattsson ja P\u00e4rssinen, Anna Matthsdotter muodostama perhe",
"P\u00e4rssinen, Stephan Johansson ja Nuora, Anna muodostama perhe",
"P\u00e4rssinen, Toivo ja Inkinen, Aina Aliina muodostama perhe",
"P\u00f6h\u00f6, J\u00f6ran Petersson ja , Maria muodostama perhe",
"P\u00f6h\u00f6, Lars J\u00f6ransson ja Paakkari, Walborg Michelssotter muodostama perhe",
"P\u00f6ll\u00e4kk\u00e4, J\u00f6ran Andersson ja Ulkolainen, Anna J\u00f6ransdotter muodostama perhe",
"Raami, Johan ja Kitunen, Walborg Olofsdotter muodostama perhe",
"Raami, Johan Mattsson ja Pusa, Anna Mattsdotter muodostama perhe",
"Perhe is\u00e4lle Raami, J\u00f6ran",
"Raami, Matths Mattsson ja Kukko, Agnetha J\u00f6ransdotter muodostama perhe",
"Raami, Matts Johansson ja Mustonen, Catharina J\u00f6ransdotter muodostama perhe",
"Raami, Matts Sigfredsson ja Virolainen, Carin muodostama perhe",
"Raami, Sigfred J\u00f6ransson ja Kettunen, Maria Andersdotter muodostama perhe",
"Perhe is\u00e4lle Rahm i Strand i \u00c4lg\u00e5, Salomon Torstensson",
"Rainio, Hans J\u00f6nsson ja , Beata muodostama perhe",
"Rainio, Johan Hansson ja , Beata Eriksdotter muodostama perhe",
"Rainio, Johan Hansson ja , Margareta muodostama perhe",
"Raiskinm\u00e4ki, Juho Yrj\u00f6npoika ja Ylti\u00e4, Leena Tuomaantyt\u00e4r muodostama perhe",
"Ram, Torsten Ingelsson ja i Strand i \u00c4lg\u00e5, N Salomonsdotter muodostama perhe",
"Ram, Torsten Salomonsson ja Fleming af Torlax, Brita Johansdotter muodostama perhe",
"Rampa, Anders ja Ruuna, Walborg Petersdotter muodostama perhe",
"Rampa, Bertil Larsson ja Ihalainen, Maria Christersdotter muodostama perhe",
"Rampa, Bertil Larsson ja Kaasalainen, Catharina Mattsdotter muodostama perhe",
"Perhe is\u00e4lle Rampa, Cnut",
"Rampa, Lars ja Karilainen, Catharina muodostama perhe",
"Rampa, Matts Cnutsson ja Kaasalainen, Elisabetha muodostama perhe",
"Rampa, Matts Cnutsson ja Karvinen, Helena muodostama perhe",
"Rampa, Matts Cnutsson ja P\u00e4rssinen, Lisa Hendricsdotter muodostama perhe",
"Rantalainen, Johan ja Paajanen, Walborg muodostama perhe",
"Rasi, Eric Mattsson ja Mulkola, Maria Claesdotter muodostama perhe",
"Rasi, Matts Henricsson ja , Brita Thomasdotter muodostama perhe",
"Rasi, Matts Mattsson ja , Margareta J\u00f6ransdotter muodostama perhe",
"Raukola, Matts Henriksson ja , Maria J\u00f6ransdotter muodostama perhe",
"Raumannus, Jacobus Pauli ja Speitz, Christina J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle Rautia, Mikil Nilsson",
"Rautiainen, Bertil Andersson ja Paukku, Anna Petersdotter muodostama perhe",
"Rautiainen, Henric ja Paavilainen, Maria Walborg Hindricsdotter muodostama perhe",
"Rautiainen, Johan Johansson ja Hohtari, Riitta Matintyt\u00e4r muodostama perhe",
"Rautiainen, Johan Magnusson ja Inkinen, Anna Andersdotter muodostama perhe",
"Rautiainen, J\u00f6ran J\u00f6ransson ja Pusa, Agnetha J\u00f6ransdotter muodostama perhe",
"Rautiainen, Magnus ja , Anna muodostama perhe",
"Rautiainen, Magnus Johansson ja Hentonen, Helena Lisa Petersdotter muodostama perhe",
"Rautiainen, Magnus Simonsson ja R\u00e4hm\u00f6nen, Brita Johansdotter muodostama perhe",
"Rautiainen, Simon Magnusson ja Kukko, Walborg Bertelsdotter muodostama perhe",
"Rautiainen, Thomas Henricsson ja Hiiri, Catharina Olofsdotter muodostama perhe",
"Rautiainen, Thomas Henricsson ja Savolainen, Anna J\u00f6ransdotter muodostama perhe",
"Reinikka, Johan J\u00f6ransson ja Kolehma, Anna Eliasdotter muodostama perhe",
"Reinikka, Johan J\u00f6ransson ja K\u00f6mi, Walborg Henrichsdotter muodostama perhe",
"Rekola, Grels Sigfridsson ja Laalahti, Valborg Henriksdotter muodostama perhe",
"Rekola, Jacob Mattsson ja Anttila, Anna Jacobsdotter muodostama perhe",
"Rekola, J\u00f6ren Grelsson ja , Gertrud J\u00f6ransdotter muodostama perhe",
"Rekola, Matts Thomasson ja , Anna Mattsdotter muodostama perhe",
"Rekola, Matts Thomasson ja , Beata Hendricsdotter muodostama perhe",
"Rekola, Matts Thomasson ja , Caisa Jacobsdoter muodostama perhe",
"Rekola, Matts Thomasson ja , Margetha Marcusdotter muodostama perhe",
"Rekola, M\u00e5rten Thomasson ja Mononen, Brita Johansdotter muodostama perhe",
"Perhe is\u00e4lle Rekola, Sigfrid Knutsson",
"Rekola, Thomas Grelsson ja , Brita muodostama perhe",
"Rekola, Thomas J\u00f6ransson ja , Beata muodostama perhe",
"Riiko, J\u00f6ran Olofsson ja , Maria Ericsdotter muodostama perhe",
"Ristsepp\u00e4, Mathias Simonsson ja Kolkkanen, Helena Georgsdotter muodostama perhe",
"Ristsepp\u00e4, Mathias Simonsson ja L\u00e4\u00e4veri, Brigita Mathiae muodostama perhe",
"Ristsepp\u00e4, Simon Eskelsson ja Kaukinen, Anna muodostama perhe",
"Roini, Olaus ja Piippu, Catharina Johansdotter muodostama perhe",
"Romu, Mikko Villenpoika ja R\u00e4m\u00f6, Marianna Tuomaantyt\u00e4r muodostama perhe",
"Roponen, Thomas ja Lapakko, Margaretha B\u00e4rtilsdotter muodostama perhe",
"Ruuna, Peter ja Welling, Catharina Olofsdotter muodostama perhe",
"Ruuska, Aatami Aataminpoika ja P\u00e4rssinen, Varpu Antintyt\u00e4r muodostama perhe",
"R\u00e4hm\u00f6nen, Daniel ja Koiranen, Brita muodostama perhe",
"R\u00e4hm\u00f6nen, Johan Danielsson ja Meskanen, Anna Johansdotter muodostama perhe",
"R\u00e4m\u00f6, Abraham Mattsson ja Lappalainen, Anna Simonsdotter muodostama perhe",
"R\u00e4m\u00f6, Abraham Stephansson ja K\u00e4nk\u00e4nen, Agnetha Mattsdotter muodostama perhe",
"R\u00e4m\u00f6, Anders J\u00f6ransson ja Kaukinen, Walborg Staffansdotter muodostama perhe",
"R\u00e4m\u00f6, Juho Tuomaanpoika ja J\u00e4ppinen, Maria Mikontyt\u00e4r muodostama perhe",
"R\u00e4m\u00f6, Juho Tuomaanpoika ja Pulkkinen, Lempi Maria Viljamintyt\u00e4r muodostama perhe",
"R\u00e4m\u00f6, J\u00f6ran J\u00f6ransson ja Lintunen, Carin Adamsdotter muodostama perhe",
"R\u00e4m\u00f6, J\u00f6ran Mattsson ja Hotokka, Madlena Christoffersdotter muodostama perhe",
"R\u00e4m\u00f6, Mathias J\u00f6ransson ja Hyyti\u00e4inen, Agnetha muodostama perhe",
"R\u00e4m\u00f6, Mathias J\u00f6ransson ja H\u00e4t\u00f6nen, Maria Mattsdotter muodostama perhe",
"Perhe is\u00e4lle R\u00e4m\u00f6, Matts",
"R\u00e4m\u00f6, Matts Hendriksson ja Lappalainen, Anna Simonsdotter muodostama perhe",
"R\u00e4m\u00f6, Michel Abrahamsson ja R\u00e4m\u00f6, Maria Abrahamsdotter muodostama perhe",
"R\u00e4m\u00f6, Stephan Andersson ja Halonen, Catharina Benjaminsdotter muodostama perhe",
"R\u00e4m\u00f6, Tuomas Mikonpoika ja Kyyr\u00f6, Anna Eskontyt\u00e4r muodostama perhe",
"R\u00e4m\u00f6, Tuomas Mikonpoika ja R\u00e4m\u00f6, Hetti Vilpuntyt\u00e4r muodostama perhe",
"R\u00e4m\u00f6, Tuomas Tuomaanpoika ja H\u00e4nninen, Eeva Antintyt\u00e4r muodostama perhe",
"R\u00e4nn\u00e4li, Adam Petersson ja Meskanen, Carin J\u00f6ransdotter muodostama perhe",
"R\u00e4nn\u00e4li, Matts ja Kekki, Carin M\u00e5rtensdotter muodostama perhe",
"R\u00e4nn\u00e4li, Peter Matsson ja Meskanen, Anna muodostama perhe",
"R\u00e4nn\u00e4li, Peter Matsson ja Muuriainen, Maria muodostama perhe",
"R\u00f6ring, Henrik Johansson ja Wikar, Magdalena Hansdotter muodostama perhe",
"R\u00f6ring, Johan Mattsson ja , Margareta J\u00f6nsdotter muodostama perhe",
"Saira, Erik Simonsson ja Sepp\u00e4nen, Maria muodostama perhe",
"Saira, Eskil Ericsson ja M\u00e4\u00e4tt\u00e4nen, Sara Cnutsdotter muodostama perhe",
"Saira, Michel Eskilsson ja P\u00f6yh\u00f6nen, Maria muodostama perhe",
"Saira, Michel Eskilsson ja Ristsepp\u00e4, Anna Mattsdotter muodostama perhe",
"Salen, Thomas Grelsson ja Barck, Maria Samuelsdotter muodostama perhe",
"Sallinen, Lars ja , Dorothea Mattsdotter muodostama perhe",
"Sallinen, Lars Larsson ja Jortikka, Carin Stephensdotter muodostama perhe",
"Sandb\u00e4ck, Matts Mattsson ja , Maria Mattsdotter muodostama perhe",
"Sandb\u00e4ck, Matts Mattsson ja V\u00e4likara, Maria Henriksdotter muodostama perhe",
"Sandb\u00e4ck, Yrj\u00f6 Matinpoika ja , Anna Gabrielintyt\u00e4r muodostama perhe",
"Sandb\u00e4ck, Yrj\u00f6 Matinpoika ja Reinikka, Kristiina Juhontyt\u00e4r muodostama perhe",
"Savolainen, Antti Luukkaanpoika ja Savolainen, Elsa Elli Juhontyt\u00e4r muodostama perhe",
"Savolainen, Bertil ja Suikkanen, Anna muodostama perhe",
"Savolainen, Eric ja , Walborg P\u00e5hlsdotter muodostama perhe",
"Savolainen, Hindrich Hindrichsson ja Talikainen, Brita Sigfredsdotter muodostama perhe",
"Savolainen, Hindrich P\u00e5hlsson ja Muli, Walborg Lukasdotter muodostama perhe",
"Savolainen, Johan ja Akkanen, Walborg muodostama perhe",
"Savolainen, Johan Bertilsson ja Virolainen, Carin P\u00e5hlsdotter muodostama perhe",
"Savolainen, Johan Johansson ja Paajanen, Lisa Henriksdotter muodostama perhe",
"Savolainen, Johan Johasson ja Haatainen, Anna Adamsdotter muodostama perhe",
"Savolainen, Johan Johasson ja Ij\u00e4s, Eeva muodostama perhe",
"Savolainen, Johan Johasson ja Kaasalainen, Maria Michelsdotter muodostama perhe",
"Savolainen, Johan Lucasson ja Naskali, Walborg Eliasdotter muodostama perhe",
"Savolainen, Lucas Johansson ja Kaasalainen, Maria Mattsdotter muodostama perhe",
"Savolainen, Lucas Johansson ja Vuohelainen, Maria J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle Savolainen, Pehr",
"Sepp\u00e4, Eskel Thomasson ja Anttonen, Maria Mattsdotter muodostama perhe",
"Perhe is\u00e4lle Sepp\u00e4, Thomas",
"Sepp\u00e4nen, Hindrick M\u00e5rtensson ja Kaasalainen, Anna Pehrsdotter muodostama perhe",
"Seurasalmi, Anders J\u00f6ransson ja Simolin, Ulrika Henricsdotter muodostama perhe",
"Sillanp\u00e4\u00e4, Akseli ja Hiiri, Laina Kaarin muodostama perhe",
"Simolin, Henric ja , Sara Henricsdotter muodostama perhe",
"Perhe is\u00e4lle Sirkkala, Eskil Michelsson",
"Sirkkala, Eskill J\u00f6ransson ja , Gertrud muodostama perhe",
"Sirkkala, J\u00f6ran Eskilsson ja , Agneta P\u00e5hlsdotter muodostama perhe",
"Sirkkala, Sigfred Eskilsson ja , Sophia Henrichsdotter muodostama perhe",
"Siurola, Clemet Thuresson ja , Brita Mattsdotter muodostama perhe",
"Siurola, Henrich Thomasson ja , Kirstin muodostama perhe",
"Perhe is\u00e4lle Siurola, Olof Tordsson",
"Perhe is\u00e4lle Siurola, Sigfrid Olofsson",
"Siurola, Thomas Clemetsson ja , Brita Eskelsdotter muodostama perhe",
"Siurola, Thomas Henriksson ja , Beata muodostama perhe",
"Siurola, Thomas Henriksson ja , Margareta Henriksdotter muodostama perhe",
"Siurola, Thure Clemetsson ja Lintula, Lisa Simonsdotter muodostama perhe",
"Siurola, Thure Thomasson ja , Maria J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle Siurola, Tord Sigfridsson",
"Skalm, Claes Andersson ja Greek, Brita Jacobsdotter muodostama perhe",
"Skytt\u00e4l\u00e4, Matts Bertilsson ja , Beata Henricsdotter muodostama perhe",
"Skytt\u00e4l\u00e4, Matts Bertilsson ja , Margareta muodostama perhe",
"Perhe is\u00e4lle Smedh, Sigfred",
"Somppi, Henrich Mattsson ja M\u00e4ki, Maria Henrichsdotter muodostama perhe",
"Somppi, Matts Erichsson ja Somppi, Brita Pehrsdotter muodostama perhe",
"Somppi, Peder Pedersson ja , Britha Hendersdotter muodostama perhe",
"Somppi, Per Persson ja , Helga Larsdotter muodostama perhe",
"Sotku, Anders Andersson ja Musakka, Walborg Andersdotter muodostama perhe",
"Sotku, Jacob ja Hosikainen, Walborg muodostama perhe",
"Sotku, Matths Jacobsson ja Kiiski, Walborg Thomasdotter muodostama perhe",
"Sparf, Benjamin Mattsson ja , Maria Johansdotter muodostama perhe",
"Sparf, Benjamin Mattsson ja \u00c4nkk\u00e4, Maria Ericsdotter muodostama perhe",
"Speitz, Henrik Jacobsson ja Liuttula, Margareta Thomasdotter muodostama perhe",
"Speitz, J\u00f6ran Henriksson ja till Aln\u00e4s, Elin Helena Kristoffersdotter muodostama perhe",
"Stierna, M\u00e5rten Ericsson ja , Anna Pedersdotter muodostama perhe",
"Stiernkors i Fr\u00f6jdb\u00f6le, Erik M\u00e5rtensson ja Fleming, Brita Persdotter muodostama perhe",
"Stiernkors i Fr\u00f6jdb\u00f6le, Erik M\u00e5rtensson ja Sjundby, Brita Bertilsdotter muodostama perhe",
"Stjernkors, Ivar Axelsson ja , Brita Larsdotter muodostama perhe",
"Stolpe, Johannes Adamsson ja Simolin, Ulrika Henricsdotter muodostama perhe",
"Strandman, Andreas ja Ursin, Catharina muodostama perhe",
"Strandman, Andreas Andre\u00e6 ja B\u00e4ck, Hedvig muodostama perhe",
"Suolaxius, Axelius Theodorici ja , Scolastica Henriksdotter muodostama perhe",
"Perhe is\u00e4lle Suomatka, Michel J\u00f6nsson",
"Suutari, Anders ja , Anna Henrichsdotter muodostama perhe",
"Suutari, J\u00f6ran Andersson ja Kaasalainen, Brita muodostama perhe",
"Suutari, Peter Olofsson ja Kaasalainen, Maria Petersdotter muodostama perhe",
"Taavettila, Johan Michelsson ja , Lisa Johansdotter muodostama perhe",
"Taavettila, Michel Michelsson ja , Gertrud Eskelsdotter muodostama perhe",
"Taipale, Herman Aapronpoika ja Kalliom\u00e4ki, Vilhelmiina Samulintyt\u00e4r muodostama perhe",
"Perhe is\u00e4lle Talikainen, Sigfred",
"Talonpoika, Jacob Staffansson ja , Brita Philipsdotter muodostama perhe",
"Talonpoika, J\u00f6ran Jacobsson ja Nokelainen, Helena Olofsdotter muodostama perhe",
"Tasainen, Henrik Persson ja , Agnes muodostama perhe",
"Tasainen, Henrik Persson ja , M\u00e4rta muodostama perhe",
"Tavela, Axel Hansson ja , Margareta muodostama perhe",
"Tavela, Axel Hansson ja Sorola, Valborg Clasdotter muodostama perhe",
"Tavela, Hans Bengtsson ja , Agneta Michelsdotter muodostama perhe",
"Tavela, Hans Bengtsson ja , Elin Pavelsdotter muodostama perhe",
"Tavela, Hans Bengtsson ja , Karin muodostama perhe",
"Tawast, J\u00f6ns Olofsson ja Dj\u00e4kn, M\u00e4rta Klasdotter muodostama perhe",
"Tawast, Nils Olofsson ja N, N Knutsdotter muodostama perhe",
"Tawast, Olof J\u00f6nsson ja , Karin muodostama perhe",
"Tehi, Simon Andersson ja , Sophia Mathsdotter muodostama perhe",
"Tehi, Simon Andersson ja Lukkari, Anna Carlsdotter muodostama perhe",
"Teit, Gregorius Martini ja Liuttula, Margareta Thomasdotter muodostama perhe",
"Tepponen, Anders Ericsson ja Wilsten, Susanna Carlsdotter muodostama perhe",
"Tepponen, Eric ja , Elisabeth muodostama perhe",
"Tervanen, Eric ja , Elin muodostama perhe",
"Tervanen, Johan Ericsson ja , Anna muodostama perhe",
"Tervanen, Johan Ericsson ja , Maria Thomasdotter muodostama perhe",
"Perhe is\u00e4lle Tihver\u00e4inen, Anders",
"Tihver\u00e4inen, Heikki Matinpoika ja Pitk\u00e4nen, Helena Juhontyt\u00e4r muodostama perhe",
"Tihver\u00e4inen, Henric ja Akkanen, Carin Larsdotter muodostama perhe",
"Tihver\u00e4inen, Henric Henricsson ja Tepponen, Anna Andersdotter muodostama perhe",
"Tihver\u00e4inen, Johan Johansson ja , Margaretha muodostama perhe",
"Tihver\u00e4inen, Johan Johansson ja Puputti, Catharina Samuelsdotter muodostama perhe",
"Tihver\u00e4inen, Johan Simonsson ja Kyll\u00f6nen, Walborg muodostama perhe",
"Tihver\u00e4inen, Juho Heikinpoika ja Koppanen, Anna Maria Juhontyt\u00e4r muodostama perhe",
"Tihver\u00e4inen, Magnus Stephansson ja Luukkanen, Maria Stephansdotter muodostama perhe",
"Tihver\u00e4inen, Matti Heikinpoika ja J\u00e4ppinen, Varpu Matintyt\u00e4r muodostama perhe",
"Tihver\u00e4inen, Matti Heikinpoika ja Nokre, Maria Tahvontyt\u00e4r muodostama perhe",
"Tihver\u00e4inen, Simon Johansson ja Heikkonen, Brita Hansdotter muodostama perhe",
"Tihver\u00e4inen, Stephan Johansson ja P\u00e4rssinen, Elisabeth muodostama perhe",
"Tikka, Matts ja Hentonen, Anna muodostama perhe",
"till Aln\u00e4s, Christofer Bertilsson ja , Kristina Henriksdotter muodostama perhe",
"till Moisio, J\u00f6ns Mickelsson ja Bj\u00f6rnram till Isn\u00e4s, Anna Engelbrektintyt\u00e4r muodostama perhe",
"Toikka, Matts ja , Brigitha muodostama perhe",
"Toikka, Matts ja Turkki, Maria P\u00e5hlsdotter muodostama perhe",
"Toiviainen, Syring ja Kuuppo, Brita Jacobsdotter muodostama perhe",
"Tomperi, Aarne ja Romu, Sylvi Hedvig muodostama perhe",
"Tomperi, Anders Johansson ja , Maria muodostama perhe",
"Tomperi, Anders Johansson ja Mustonen, Carin Johansdotter muodostama perhe",
"Perhe is\u00e4lle Tomperi, Johan",
"Tomperi, Johan Mattsson ja Rampa, Walborg Bertilsdotter muodostama perhe",
"Tomperi, Juho Yrj\u00f6npoika ja Hiiri, Katri Juhontyt\u00e4r muodostama perhe",
"Tomperi, Juho Yrj\u00f6npoika ja Karpinen, Anna Varpu Heikintyt\u00e4r muodostama perhe",
"Tomperi, J\u00f6ran Johansson ja Inkinen, Lena Petersdotter muodostama perhe",
"Tomperi, J\u00f6ran Johansson ja Puputti, Lena Pehrsdotter muodostama perhe",
"Tomperi, Matts Andersson ja Savolainen, Maria Johansdotter muodostama perhe",
"Tomperi, Yrj\u00f6 Juhonpoika ja Savolainen, Liisa Antintyt\u00e4r muodostama perhe",
"Torkkeli, J\u00f6ran ja Pokkinen, Elisabeth muodostama perhe",
"Tunkelo, Johan Johansson ja Maijala, Maria Jacobsdotter muodostama perhe",
"Tuokko, Pauli Heikinpoika ja Karpinen, Anna Varpu Heikintyt\u00e4r muodostama perhe",
"Tuomela, Erkki Ensio ja Tomperi, Toini Sivi\u00e4 muodostama perhe",
"Perhe is\u00e4lle Tuottinen, Knut",
"Turkkinen, Thomas Abrahamsson ja Loponen, Carin Thomasdotter muodostama perhe",
"Udd, Matts Mattsson ja , Lisa Johansdotter muodostama perhe",
"Ulkolainen, J\u00f6ran ja Ripainen, Carin Christersdotter muodostama perhe",
"Vaitti, Johan Mattsson ja Kemppi, Catharina Petersdotter muodostama perhe",
"Vaitti, Matthias Johansson ja P\u00f6h\u00f6, Walborg Larsdotter muodostama perhe",
"Vaitti, Matts Andersson ja , Anna Johansdotter muodostama perhe",
"Vaitti, Matts Mattsson ja , Anna Matsdotter muodostama perhe",
"Vanhanen, Anders Johansson ja Harvonen, Walborg Hindrichsdotter muodostama perhe",
"Vanhanen, Anders Johansson ja Niuta, Brita Petersdotter muodostama perhe",
"Vanhanen, Grels ja Kopok, Maria muodostama perhe",
"Perhe is\u00e4lle Vanhanen, Johan",
"Vanhanen, Peter Andersson ja Savolainen, Maria Johansdotter muodostama perhe",
"Vanhanen, Simon P\u00e5hlsson ja Karonen, Helena Pehrsdotter muodostama perhe",
"Vaskelainen ja Peltonen, Maria Pekantyt\u00e4r muodostama perhe",
"Vaskelainen, J\u00f6ran ja N, N muodostama perhe",
"Vaskelainen, J\u00f6ran ja Vanhanen, Maria Grelsdotter muodostama perhe",
"Vessari, Anders Mattsson ja , Maria Marcusdotter muodostama perhe",
"Vessari, Henrik Andersson ja Eskola, Maria Mattsdotter muodostama perhe",
"Vessari, Lars Peersson ja , Karin J\u00f6ransdotter muodostama perhe",
"Vessari, Matts Peersson ja , Brita muodostama perhe",
"Vessari, Matts Peersson ja Suluslahti, Lisa Henrichsdotter muodostama perhe",
"Vessari, Olof Larsson ja , Susanna Thomasdotter muodostama perhe",
"Vessari, Peer Olsson ja , Karin Larsdotter muodostama perhe",
"Vessari, Peer Olsson ja , Kirstin muodostama perhe",
"Perhe is\u00e4lle Vessari, Per",
"Viiala, Johan Ersson ja , Lisa Ersdotter muodostama perhe",
"Vilkki, Bertill ja , Johanna Simonsdotter muodostama perhe",
"Vilkkil\u00e4, Johan Svensson ja , Anna muodostama perhe",
"Vilkkil\u00e4, Johan Svensson ja Stierna, Elin M\u00e5rtensdotter muodostama perhe",
"Vilkkil\u00e4, J\u00f6ran M\u00e5rtensson ja , Anna Mattsdotter muodostama perhe",
"Vilkkil\u00e4, M\u00e5rten Johansson ja , Walborg Bertilsdotter muodostama perhe",
"Vilkkil\u00e4, M\u00e5rten J\u00f6ransson ja , Sophia Larsdotter muodostama perhe",
"Virolainen, Jacob ja Ruuna, Walborg Petersdotter muodostama perhe",
"Virolainen, Matts ja Ikonen, Anna Wendela muodostama perhe",
"Virolainen, P\u00e5hl Mattsson ja Nokelainen, Maria J\u00f6ransdotter muodostama perhe",
"Virtanen, Kalle Kustaa Kallenpoika ja Heikniemi, Edla Lydia Kallentyt\u00e4r muodostama perhe",
"Perhe is\u00e4lle Viskari, Erich",
"Viskari, Jacob Ericsson ja Muikonen, Maria Christersdotter muodostama perhe",
"Viskari, Matts Thomasson ja K\u00e4ppi, Maria Andersdotter muodostama perhe",
"Viskari, Matts Thomasson ja Pajari, Catharina Adamsdotter muodostama perhe",
"Viskari, Thomas Jacobsson ja J\u00e4ppinen, Brita Grelsdotter muodostama perhe",
"Vuohelainen, Bertyl Jacobsson ja Huuhka, Ingeborg Mattsdotter muodostama perhe",
"Vuohelainen, Bertyl J\u00f6ransson ja Kaasalainen, Carin J\u00f6ransdotter muodostama perhe",
"Vuohelainen, Georg Bertylsson ja Kukko, Maria Christersdotter muodostama perhe",
"Vuohelainen, Jacob Henricsson ja Javanainen, Amalia M\u00e5rtensdotter muodostama perhe",
"Vuohelainen, J\u00f6ran ja , Maria Mattsdotter muodostama perhe",
"Vuohelainen, J\u00f6ran ja Lappalainen, Elisabeth muodostama perhe",
"Vuohelainen, J\u00f6ran ja N, N muodostama perhe",
"V\u00e4lkki, Olof Nilsson ja V\u00e4lkki, N Persdotter muodostama perhe",
"Wikar, Hans Hansson ja , Brita muodostama perhe",
"Wilsten, Carl ja Heikkonen, Catharina Henricsdotter muodostama perhe",
"Wilsten, Carl ja Kinnari, Maria muodostama perhe",
"Ylinen, Samuel Mattsson ja , Walborg Henricsdotter muodostama perhe",
"Ylti\u00e4, Thomas Sigfredsson ja Kitunen, Anna M\u00e5rtensdotter muodostama perhe",
"Ylti\u00e4, Thomas Sigfredsson ja Multia, Kirstin Thomasdotter muodostama perhe",
"Ylti\u00e4, Thomas Sigfredsson ja Taavettila, Elisabeth Johansdotter muodostama perhe",
"Yl\u00e4-H\u00e4kkinen, Erich Mattsson ja , Elin Hendricsdotter muodostama perhe",
"Yl\u00e4-H\u00e4kkinen, Erich Mattsson ja , Sophia Olofsdotter muodostama perhe",
"Yl\u00e4-H\u00e4kkinen, Gabriel J\u00f6ransson ja Apiala, Margareta J\u00f6ransdotter muodostama perhe",
"Yl\u00e4-H\u00e4kkinen, J\u00f6ran Eriksson ja Apiala, Kirstin J\u00f6ransdotter muodostama perhe",
"Yl\u00e4-H\u00e4kkinen, J\u00f6ran Eriksson ja Marttila, Elin Mattsdotter muodostama perhe",
"Yrj\u00f6l\u00e4, Carl Henrik Yrj\u00f6npoika ja Isotalo, Hedvig Elisabet Kallentyt\u00e4r muodostama perhe",
"Yrj\u00f6l\u00e4, J\u00f6ran J\u00f6ransson ja Forssk\u00e5hl, Anna Charlotta Jacobsdotter muodostama perhe",
"Yrj\u00f6l\u00e4, J\u00f6ran M\u00e5rtensson ja Sirkkala, Maria Samuelsdotter muodostama perhe",
"\u00c4ij\u00f6, Christer ja Sontikka, Maria muodostama perhe",
"\u00c4ij\u00f6, J\u00f6ran Christersson ja Inkinen, Maria Mattsdotter muodostama perhe",
"\u00c4ij\u00f6, Simon J\u00f6ransson ja Savolainen, Walborg Ericsdotter muodostama perhe"
]
Dwr.ScriptLoaded('dwr_db_F_name_0.js');
