// This file is generated

I_short_name_0 = [
", Adam Philipsson",
", Agnes",
", Agnes Mattsdotter",
", Agneta Jacobsdotter",
", Agneta Knutsdotter",
", Agneta Mattsdotter",
", Agneta Michelsdotter",
", Agneta P\u00e5hlsdotter",
", Agnetha Hendrichsdotter",
", Agnetta Pettersdotter",
", Agnis",
", Agnis",
", Anders Ersson",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna Andersdotter",
", Anna Clemetsdotter",
", Anna Cnutsdotter",
", Anna Danielsdotter",
", Anna Frantzdotter",
", Anna Gabrielintyt\u00e4r",
", Anna Hansdotter",
", Anna Henrichsdotter",
", Anna Johansdotter",
", Anna Johansdotter",
", Anna J\u00f6nsdotter",
", Anna J\u00f6ransdotter",
", Anna Matsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna Nilsdotter",
", Anna Olofsdotter",
", Anna Paulsdotter",
", Anna Pedersdotter",
", Anna Pedhersdotter",
", Anna Thomasdotter",
", Anna Thomasdotter",
", Anna Agnetta J\u00f6ransdotter",
", Annika Pettersdotter",
", Ari",
", Arvid",
", Barbara Thomasdotter",
", Barbro",
", Barbro Eriksdotter",
", Bartolomeus Johannis",
", Beata",
", Beata",
", Beata",
", Beata",
", Beata Eliae",
", Beata Eriksdotter",
", Beata Eriksdotter",
", Beata Hendricsdotter",
", Beata Henricsdotter",
", Beata Henricsdotter",
", Beata Johansdotter",
", Beata Mattsdotter",
", Beata Mattsdotter",
", Beatha Johansdotter",
", Birgit Thomasdotter",
", Brigita",
", Brigitha",
", Brigitta",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita Andersdotter",
", Brita Eskelsdotter",
", Brita Henricsdotter",
", Brita Jacobsdotter",
", Brita Knutsdotter",
", Brita Larsdotter",
", Brita Mattsdotter",
", Brita Olsdotter",
", Brita Philipsdotter",
", Brita P\u00e5hlsdotter",
", Brita Sigfridsdotter",
", Brita Simonsdotter",
", Brita Thomasdotter",
", Britha Hendersdotter",
", Caisa Ericsdotter",
", Caisa Henricsdotter",
", Caisa Jacobsdoter",
", Carin",
", Carin",
", Carin Henrichsdotter",
", Carin Larsdotter",
", Carin Mattsdotter",
", Carin Mattsdotter",
", Carin Olofsdotter",
", Carin P\u00e5hlsdotter",
", Carin Sigfridsdotter",
", Catarina Philipsdotter",
", Catharina",
", Catharina",
", Catharina J\u00f6ransdotter",
", Catharina Larsdotter",
", Chirstin",
", Chirstin Andersdotter",
", Chirstin Ericsdotter",
", Chirstin Mattsdotter",
", Chirstin Michelsdotter",
", Chirstin Olsdotter",
", Chirstin P\u00e5hlsdotter",
", Christina",
", Christina Johansdotter",
", Clara J\u00f6ransdotter",
", Clara Mattsdotter",
", Daniel Abrahami",
", Didrik Persson",
", Dorde",
", Dorde Erichsdotter",
", Dorothea Marcusdotter",
", Dorothea Mattsdotter",
", Dorothea Olofsdotter",
", Elin",
", Elin",
", Elin",
", Elin",
", Elin Filpusdotter",
", Elin Hendricsdotter",
", Elin J\u00f6ransdotter",
", Elin Larsdotter",
", Elin Larsdotter",
", Elin Mattsdotter",
", Elin Pavelsdotter",
", Elin P\u00e5lsdotter",
", Elina Juhantyt\u00e4r",
", Elisabet Jacobsdotter",
", Elisabeth",
", Elisabeth Hindricksdotter",
", Elisabeth Jacobsdotter",
", Elisabeth Mattsdotter",
", Eric Abj\u00f6rnsson",
", Erich Johansson",
", Filpus Ivarsson",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud",
", Gertrud Andersdotter",
", Gertrud Brusiusdotter",
", Gertrud Eskelsdotter",
", Gertrud Hendersdotter",
", Gertrud J\u00f6ransdotter",
", Gertrud J\u00f6ransdotter",
", Gertrud Mattsdotter",
", Gertrud Pedersdotter",
", Hebla",
", Hedvig Simonsdotter",
", Hedvig Kristiina Erkintyt\u00e4r",
", Heikki",
", Helena",
", Helga Larsdotter",
", Helga Mattsdotter",
", Helga Peersdotter",
", Helga Thomasdotter",
", Henrich Pedersson",
", Henrich Sigfredsson",
", Inge Ingesson",
", Ingebog Simonsdotter",
", Ingeborg",
", Ingeborg",
", Ingeborg",
", Ingrid Ingesdotter",
", Johan Johansson",
", Johan Larsson",
", Johanna",
", Johanna",
", Johanna Johansdotter",
", Johanna Simonsdotter",
", Judith Ericsdotter",
", J\u00f6ns",
", J\u00f6ns Bengtsson",
", J\u00f6ran",
", J\u00f6ran Hansson",
", J\u00f6ran Jacobsson",
", J\u00f6ran Lukasson",
", J\u00f6ran Sigfridsson",
", Kaisa",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin",
", Karin Hinrichsdotter",
", Karin J\u00f6ransdotter",
", Karin Larsdotter",
", Karin Markusdotter",
", Katarina",
", Katarina",
", Katarina Petrusdotter",
", Kirstin",
", Kirstin",
", Kirstin",
", Kirstin",
", Kirstin Andersdotter",
", Kirstin Jacobsdotter",
", Kristin Michelsdotter",
", Kristina Henriksdotter",
", Kristina Ingesdotter",
", Lars Hindrichsson",
", Leena",
", Lisa",
", Lisa",
", Lisa",
", Lisa",
", Lisa Andersdotter",
", Lisa Ersdotter",
", Lisa Johansdotter",
", Lisa Johansdotter",
", Lisa Johansdotter",
", Lisa Larsdotter",
", Lydeke",
", Maija Stiina Heikintyt\u00e4r",
", Maisa",
", Maisa",
", Maisa Eskellsdotter",
", Maisa Eskelsdotter",
", Maisa Marcusdotter",
", Malin",
", Malin Erichsdotter",
", Malin Eriksdotter",
", Marcus Marcusson",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta Ericsdotter",
", Margareta Henriksdotter",
", Margareta Hindrichsdotter",
", Margareta J\u00f6nsdotter",
", Margareta J\u00f6ransdotter",
", Margareta Larsdotter",
", Margareta Nilsdotter",
", Margareta Sunesdotter",
", Margaretha",
", Margaretha",
", Margeta",
", Margeta Hendersdotter",
", Margeta Nilsdotter",
", Margetha Marcusdotter",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria Andersdotter",
", Maria Clemensdotter",
", Maria Ericsdotter",
", Maria Eskelsdotter",
", Maria Hindricsdotter",
", Maria Hinricsdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria J\u00f6ransdotter",
", Maria J\u00f6ransdotter",
", Maria Larsdotter",
", Maria Marcusdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria M\u00e5rtensdotter",
", Maria P\u00e5hlsdotter",
", Maria Sigfridsdotter",
", Maria Simonsdotter",
", Maria Simonsdotter",
", Maria Thomasdotter",
", Markus Jacobsson",
", Matti Matinpoika",
", Matts",
", Matts Larsson",
", Matts Mattsson",
", Matts Mattsson",
", Matts Mattsson",
", Matts Olofsson",
", Mauno",
", Michel Hinckasson",
", Michel J\u00f6ransson",
", M\u00e5rten",
", M\u00e4rta",
", N Henriksdotter",
", Niina",
", Per Mattson",
", Peter Matsson",
", Pia",
", P\u00e5l P\u00e5lsson",
", Ragnell",
", Sara Henricsdotter",
", Scolastica Henriksdotter",
", Sigfridus Martini",
", Simon Ambrosiusson",
", Sofia Jacobsdotter",
", Sofia Johansdotter",
", Sofia Juhontyt\u00e4r",
", Sofia J\u00f6ransdotter",
", Sophia",
", Sophia",
", Sophia",
", Sophia Henrichsdotter",
", Sophia Johansdotter",
", Sophia Larsdotter",
", Sophia Larsdotter",
", Sophia Mathsdotter",
", Sophia Olofsdotter",
", Sophia Pehrsdotter",
", Sophia Sigfredsdotter",
", Sten Henriksson",
", Stephanus Johansson",
", Stina Johansdotter",
", Susanna Thomasdotter",
", Terttu",
", Thomas",
", Thomas Thomasson",
", Tomas Bertilsson",
", Tuve M\u00e5nsson",
", Valborg Eskelsdotter",
", Valborg Hendersdotter",
", Valborg Mattsdotter",
", Valborg M\u00e5rtensdotter",
", Veijo",
", Vilhelmiina Kallentyt\u00e4r",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg Andersdotter",
", Walborg Bertilsdotter",
", Walborg Erichsdotter",
", Walborg Ericsdotter",
", Walborg Henricsdotter",
", Walborg Henriksdotter",
", Walborg Johansdotter",
", Walborg Larsdotter",
", Walborg Mattsdotter",
", Walborg Petersdotter",
", Walborg P\u00e5hlsdotter",
"Acka, Anders",
"Acka, Lucas",
"Akkanen, Anders Andersson",
"Akkanen, Anders Andersson",
"Akkanen, Anna Bertilsdotter",
"Akkanen, Anna Johansdotter",
"Akkanen, Bertill Larsson",
"Akkanen, Brita Lucasdotter",
"Akkanen, Carin Larsdotter",
"Akkanen, Catharina Bertsdotter",
"Akkanen, Helena Simonsdotter",
"Akkanen, Johan Johansson",
"Akkanen, Johan Johansson",
"Akkanen, Johan Lucasson",
"Akkanen, Lars Bertilsson",
"Akkanen, Lukas Andersson",
"Akkanen, Maria Lucasdotter",
"Akkanen, Peter Andersson",
"Akkanen, Riitta Heikintyt\u00e4r",
"Akkanen, Simon Andersson",
"Akkanen, Walborg",
"Akkanen, Walborg Petersdotter",
"Ala-Hinkkala, Hedvig Simontyt\u00e4r",
"Alakangas, Anna Maria Akselintyt\u00e4r",
"Amnelin, Anna",
"Ancherus, Erik Arvidsson",
"Ancherus, Johanna Ericsdotter",
"Anttila, Anna Jacobsdotter",
"Anttila, Lisa Jacobsdotter",
"Anttonen, Anna Pettersdotter",
"Anttonen, Maria Mattsdotter",
"Anttonen, Maria Ristontyt\u00e4r",
"Anttonen, Peter",
"Apiala, J\u00f6ran Mattsson",
"Apiala, Kirstin J\u00f6ransdotter",
"Apiala, Margareta J\u00f6ransdotter",
"Arvaja, Olof Hansson",
"Balk, M\u00e5ns Nilsson",
"Barck, Maria Samuelsdotter",
"Barck, Samuel Eriksson",
"Barkare, Jacob",
"Bergman, Margaretha",
"Birkman, Elias Henrici",
"Birkman, Gustaf Eliae",
"Birkman, Henrik Henriksson",
"Birkman, Henrik Jacobsson",
"Bj\u00f6rnram till Isn\u00e4s, Anna Engelbrektintyt\u00e4r",
"Bj\u00f6rnram till Isn\u00e4s, Engelbrekt Larsson",
"Bl\u00e5field, Anna Gustavsdotter",
"Bl\u00e5field, Bengt J\u00f6nsson",
"Bl\u00e5field, Gustaf Ivarsson",
"Bl\u00e5field, Gustaf Nilsson",
"Bl\u00e5field, Ivar Gustafsson",
"Bl\u00e5field, Mickel Bengtsson",
"Bl\u00e5field, Nils Michelsson",
"Broke, Ingeborg Larsdotter",
"Broke, Lars Pedersson",
"B\u00e4ck, Hedvig",
"Calle, D\u00f6nhoff",
"Cavall, Otto Gustafsson",
"Crawford (Williams), Elsie Ellen",
"Dj\u00e4kn, Bj\u00f6rn Pedersson",
"Dj\u00e4kn, Erengisle Bj\u00f6rnsson",
"Dj\u00e4kn, Klaus Lydekesson",
"Dj\u00e4kn, M\u00e4rta Erengilsdotter",
"Dj\u00e4kn, M\u00e4rta Klasdotter",
"Dufva till N\u00e4set, Jacob Bengtsson",
"D\u00f6nsby i Karis, Dynius Magnusson",
"D\u00f6nsby i Karis, Henrik Dyniusson",
"D\u00f6nsby i Karis, Magnus Dyniusson",
"D\u00f6nsby i Karis, Marietta Henriksdotter",
"Edesniemi, Anders Johansson",
"Edesniemi, Antti Antinpoika",
"Edesniemi, Maija Liisa Antintyt\u00e4r",
"Eeva, Abraham",
"Eeva, Abraham Andersson",
"Eeva, Anders Abrahamsson",
"Eeva, Anna Mattsdotter",
"Eeva, Aune Paavontyt\u00e4r",
"Eeva, Lars Abrahamsson",
"Eeva, Matts Larsson",
"Eeva, Paul Tobiasson",
"Eeva, Tobias Abrahamsson",
"Ekbom, Johanna",
"Ekel\u00f6f, Margareta Eriksdotter",
"Ekel\u00f6f i G\u00e4sterby, Erik Larsson",
"Ekkil\u00e4, Leena Eliaantyt\u00e4r",
"Elfvenberg, Susanna Elisabet",
"Elg, Anna Carlsdotter",
"Eskola, Maria Mattsdotter",
"Fincke, Elin G\u00f6dekesdotter",
"Fincke, G\u00f6deke",
"Fincke, G\u00f6deke den gamble",
"Fincke, Henrik",
"Fincke, Metta G\u00f6dekesdotter",
"Finnil\u00e4, Kirstin Philipsdotter",
"Finnil\u00e4, Philip Jacobsson",
"Fleming, Brita Persdotter",
"Fleming, Erik Hermansson",
"Fleming, Henrik Klasson",
"Fleming, Johan Henriksson",
"Fleming, Klaus Pedersson",
"Fleming, Magnus Klasson",
"Fleming, Peder",
"Fleming af Torlax, Brita Johansdotter",
"Fleming till Vijais i Rimito, Per Eriksson",
"Fleming till Villn\u00e4s, Herman Magnusson",
"Forssk\u00e5hl, Anna Charlotta Jacobsdotter",
"Forssk\u00e5hl, Jakob Johansson",
"Forssk\u00e5hl, Jakob Simonsson",
"Forssk\u00e5hl, Johan Jacobsson",
"Forssk\u00e5hl, Simon Sigfridi",
"Friis, Christina Henriksdotter",
"Friis, Henrich",
"Garp, Anders",
"Garp, J\u00f6ns Andersson",
"Garp, Kristina J\u00f6nsdotter",
"Greek, Brita Jacobsdotter",
"Greek, Brita Simonsdotter",
"Greek i Helsingfors, Jakob",
"Grip, Eric Michelsson",
"Grip, Johanna Sofia Erkintyt\u00e4r",
"Gr\u00f6nfelt, Bertil Mattsson",
"Gr\u00f6nfelt, Brita Bertilsdotter",
"Guthrie (Williams), Mayme Mildred",
"Haatainen, Anna Adamsdotter",
"Hahkalainen, Per",
"Haikonen, Anna Juhontyt\u00e4r",
"Haikonen, Bertil J\u00f6ransson",
"Haikonen, J\u00f6ran Bertilsson",
"Haikonen, J\u00f6ran Thomasson",
"Haikonen, Katri Simontyt\u00e4r",
"Haikonen, Simo Yrj\u00f6npoika",
"Hakolahti, Per Sigfridsson",
"Haljala, Anders Simonsson",
"Haljala, Christina Andersdotter",
"Haljala, Simon Thomasson",
"Halonen, Benjam Benjamsson",
"Halonen, Benjamin Johansson",
"Halonen, Catharina Benjaminsdotter",
"Hampaala, Clemet Mikelsson",
"Hampaala, Henrik Marcusson",
"Hampaala, Johan J\u00f6ransson",
"Hampaala, J\u00f6ran Mattsson",
"Hampaala, Marcus Thomasson",
"Hampaala, Matts Hendersson",
"Hampaala, Thomas Clemetson",
"Hannin, Pehr",
"Hannin, Pehr Pehrsson",
"Hannukainen, Anna",
"Harvonen, Walborg Hindrichsdotter",
"Hassi, Ambrosius Thomasson",
"Hassi, J\u00f6ran Thomasson",
"Hassi, Maria Simonsdotter",
"Hassi, Matts Brusiusson",
"Hassi, Simon J\u00f6ransson",
"Hassi, Thomas Mattsson",
"Hassi, Thomas Olsson",
"Hatakka, Carin Paulsdotter",
"Hatakka, Catharina Christersdotter",
"Hatakka, Christer Christersson",
"Hatakka, Christer Henricsson",
"Hatakka, Hindrich",
"Hatakka, Maria Michelsdotter",
"Hatakka, Michel Christersson",
"Hauhalainen, Claes Jacobsson",
"Heikkil\u00e4, Grels Henriksson",
"Heikkil\u00e4, Henrik J\u00f6nsson",
"Heikkil\u00e4, Henrik Nilsson",
"Heikkil\u00e4, Hindrich Sigfredsson",
"Heikkil\u00e4, J\u00f6ns",
"Heikkil\u00e4, Maria Grelsdotter",
"Heikkil\u00e4, Maria Hindrichsdotter",
"Heikkil\u00e4, Maria Michelsdotter",
"Heikkil\u00e4, Michel Eskilsson",
"Heikkil\u00e4, Nils Henriksson",
"Heikkonen, Anna",
"Heikkonen, Brita Hansdotter",
"Heikkonen, Catharina Henricsdotter",
"Heikkonen, Elin Sigfredsdotter",
"Heikkonen, Hans",
"Heikkonen, Johan",
"Heikkonen, Sigfred Johansson",
"Heikkonen, Sophia Mattsdotter",
"Heikniemi, Edla Lydia Kallentyt\u00e4r",
"Heikniemi, Kalle Aataminpoika",
"Heiskanen, Elisabeth Johansdotter",
"Heiskanen, Johan J\u00f6ransson",
"Hentonen, Anders J\u00f6ransson",
"Hentonen, Anna",
"Hentonen, Clemet",
"Hentonen, Helena Lisa Petersdotter",
"Hentonen, J\u00f6ran",
"Hentonen, Peter Andersson",
"Hentonen, Walborg Clemetsdotter",
"Herkepaeus, Laurentius Andreasson",
"Herra, Gertrud Simonsdotter",
"Hiiri, Catharina Olofsdotter",
"Hiiri, Elma Elina",
"Hiiri, Georg Henricsson",
"Hiiri, Henric J\u00f6ransson",
"Hiiri, Johan J\u00f6ransson",
"Hiiri, Juho Juhonpoika",
"Hiiri, Juho Juhonpoika",
"Hiiri, Juho Juhonpoika",
"Hiiri, J\u00f6ran Thomasson",
"Hiiri, Katri Juhontyt\u00e4r",
"Hiiri, Laina Kaarin",
"Hiiri, Olof Thomasson",
"Hiiri, Thomas",
"Hiiri, Tuomas Simonpoika",
"Hiiri, Tuomas Tuomaanpoika",
"Hiiri, Tuomas Tuomaanpoika",
"Hinkka, Erik Sigfridsson",
"Hinkka, Michel Michelsson",
"Hinkka, Sigfrid Michelsson",
"Hinkkala, Maria J\u00f6ransdotter",
"Hinkkala, Valborg Eriksdotter",
"Hirvel\u00e4, Eeva Margareta Matintyt\u00e4r",
"Hoffman, Margareta",
"Hohtari, Carl Martinsson",
"Hohtari, Carl Petersson",
"Hohtari, Johan Petersson",
"Hohtari, Juhana Riitanpoika",
"Hohtari, Liisa Juhontyt\u00e4r",
"Hohtari, Maria Riitantyt\u00e4r",
"Hohtari, Matti Kaarlonpoika",
"Hohtari, Matts Petersson",
"Hohtari, M\u00e5rten Carlsson",
"Hohtari, Peter",
"Hohtari, Peter Matthsson",
"Hohtari, Riitta Matintyt\u00e4r",
"Hoikka, Saara",
"Hokka, Ambrosius Persson",
"Hokka, Jacob Knutsson",
"Hokka, Knut Jacobsson",
"Hokka, Knut Mattsson",
"Hokka, Maria Margaretha M\u00e5rtensdotter",
"Hokka, Matts Brusiusson",
"Hokka, M\u00e5rten Knutsson",
"Hokka, Oloff Persson",
"Hokka, Peder Olsson",
"Hokkanen, Carin Nilsdotter",
"Hokkanen, Johan Cnuthsson",
"Hokkanen, Lars",
"Hokkanen, Lars Nilsson",
"Hokkanen, Matts Johansson",
"Hokkanen, Nils Larsson",
"Hokkanen, Nils Larsson",
"Hokkanen, Sofia Mattsdotter",
"Hopia, Anders Andersson",
"Hopia, Anders Christersson",
"Hopia, Christer",
"Hopia, Elisabeth",
"Hopia, Maria Matintyt\u00e4r",
"Hopia, Matts Andersson",
"Horn af Kanckas till Toijala i Halikko, Cecilia Jacobsdotter",
"Horn af \u00c5minne, Olof Mattsson",
"Horn till Toijala i Halikko, Jakob Olofsson",
"Hosikainen, Walborg",
"Hoskari, Jacob Mattsson",
"Hoskari, Jacob Mattsson",
"Hoskari, Matts Jacobsson",
"Hoskari, Matts Michelsson",
"Hoskari, Walborg Jacobsdotter",
"Hotokka, Madlena Christoffersdotter",
"Hujala, Eeva Juhontyt\u00e4r",
"Hujala, Johan Mattsson",
"Hujala, Matts M\u00e5rtensson",
"Hujala, M\u00e5rten Thomasson",
"Hujala, Thomas Clemetsson",
"Hukki, Lars Larsson",
"Hulipas, Henrik Johansson",
"Hulipas, Simo Heikinpoika",
"Humalainen, Katarina Johansdotter",
"Huntila, Matts S\u00f6fringsson",
"Huovila, Carl Jacobsson",
"Huovila, Jacob Thomasson",
"Huovila, Maria Carlsdotter",
"Huovila, Olof Olofsson",
"Huovila, Thomas Olofsson",
"Huovinen, Gertrud Hansdotter",
"Huppunen, Bertil Eskelsson",
"Huppunen, Brigitta",
"Huppunen, Eskell",
"Huppunen, Helena Bertilsdotter",
"Huppunen, Walborg Bertilsdotter",
"Huuhka, Anders J\u00f6ransson",
"Huuhka, Anna Cnutsdotter",
"Huuhka, Ingeborg Mattsdotter",
"Huuhka, Matts",
"Huuhka, Sophia",
"Huuska, Brita Henricsdotter",
"Hynninen, Johanna",
"Hyrynen, Maria",
"Hyyti\u00e4inen, Agnetha",
"H\u00e4kkinen, Anders Cristiansson",
"H\u00e4kkinen, Cnunuth Michelsson",
"H\u00e4kkinen, Elin Erichsdotter",
"H\u00e4kkinen, Elin Simonsdotter",
"H\u00e4kkinen, Maria Andersdotter",
"H\u00e4kkinen, Michel Michelsson",
"H\u00e4kkinen, Michel P\u00e5hlsson",
"H\u00e4kkinen, P\u00e5hl",
"H\u00e4kli, Brita",
"H\u00e4kli, Stephan Bertilsson",
"H\u00e4m\u00e4l\u00e4inen, Helena Simonsdotter",
"H\u00e4m\u00e4l\u00e4inen, Jacob Simonsson",
"H\u00e4m\u00e4l\u00e4inen, Simon",
"H\u00e4m\u00e4l\u00e4inen, Simon Jacobsson",
"H\u00e4nnik\u00e4inen, Beatha Petersdotter",
"H\u00e4nnik\u00e4inen, Liisa Mikontyt\u00e4r",
"H\u00e4nnik\u00e4inen, Petter",
"H\u00e4nninen, Andreas Petersson",
"H\u00e4nninen, Antti Juhonpoika",
"H\u00e4nninen, Eeva Antintyt\u00e4r",
"H\u00e4nninen, Johan Andersson",
"H\u00e4nninen, Peter Petersson",
"H\u00e4nninen, Peter Petersson",
"H\u00e4t\u00f6nen, Maria",
"H\u00e4t\u00f6nen, Maria Mattsdotter",
"H\u00e4t\u00f6nen, Matts",
"i Fr\u00f6jdb\u00f6le, M\u00e5rten J\u00f6nsson",
"i G\u00e4sterby, Lasse",
"i H\u00e4rton\u00e4s, Margareta",
"i Strand i \u00c4lg\u00e5, N Salomonsdotter",
"i Strand i \u00c4lg\u00e5, Salomon",
"Ihalainen, Adam Mattsson",
"Ihalainen, Anna Martintyt\u00e4r",
"Ihalainen, Christer",
"Ihalainen, Maria Christersdotter",
"Ihalainen, Maria Reinholdsdotter",
"Ihalainen, Martin Adamsson",
"Ihalainen, Matts",
"Ihalainen, Matts Reinholdsson",
"Ihalainen, Reinhold Mattsson",
"Iili\u00e4inen, Brita",
"Ij\u00e4s, Anna Danielsdotter",
"Ij\u00e4s, Daniel",
"Ij\u00e4s, Daniel Gabrielsson",
"Ij\u00e4s, Daniel Gabrielsson",
"Ij\u00e4s, Eeva",
"Ij\u00e4s, Gabriel Danielsson",
"Ij\u00e4s, Gabriel Danielsson",
"Ikonen, Anna Wendela",
"Ikonen, V\u00e4in\u00f6",
"Immonen, Carin Henrichsdotter",
"Immonen, Henrick Michelsson",
"Immonen, Michel",
"Inkinen, Aina Aliina",
"Inkinen, Anders Christersson",
"Inkinen, Anna Andersdotter",
"Inkinen, Anna Eskellsdotter",
"Inkinen, Anna Heinrichsdotter",
"Inkinen, Aune Paavontyt\u00e4r",
"Inkinen, Brita Mattsdotter",
"Inkinen, Christer Jacobsson",
"Inkinen, Heinrich Heinrichsson",
"Inkinen, Heinrich Johansson",
"Inkinen, Helena Andersdotter",
"Inkinen, Henric Henricsson",
"Inkinen, Henric Lucasson",
"Inkinen, Henric Mattsson",
"Inkinen, Henrich",
"Inkinen, Jacob",
"Inkinen, Jacob Christersson",
"Inkinen, Jacob Mattsson",
"Inkinen, Johan Henricsson",
"Inkinen, Lena Petersdotter",
"Inkinen, Lucas",
"Inkinen, Maria",
"Inkinen, Maria Henricsdotter",
"Inkinen, Maria Mattsdotter",
"Inkinen, Matti Juhonpoika",
"Inkinen, Matts",
"Inkinen, Matts Jacobsson",
"Inkinen, Matts Lucasson",
"Inkinen, Paavo Yrj\u00f6npoika",
"Inkinen, Peter Henricsson",
"Iso-Attila, Clas Marcusson",
"Iso-Attila, Ivar Mattsson",
"Iso-Attila, Sunniva Sigfridstotter",
"Iso-Attila, Walborg Ivarsdotter",
"Iso-Attila, Walborg Thomasdotter",
"Isotalo, David J\u00f6ransson",
"Isotalo, Hedvig Elisabet Kallentyt\u00e4r",
"Isotalo, J\u00f6ran Davidsson",
"Isotalo, Kalle Taavetinpoika",
"Ivala, Christina Johansdotter",
"Ivala, Jacob Thomasson",
"Ivala, Johan Jacobsson",
"Ivala, Johan Johansson",
"Ivala, Joonas Matinpoika",
"Ivala, Matts Clemetsson",
"Ivala, Thomas Mattsson",
"Jaakkola, Juho Jaakonpoika",
"Javanainen, Amalia M\u00e5rtensdotter",
"Javanainen, Gertrud J\u00f6ransdotter",
"Javanainen, M\u00e5rten",
"Javanainen, Walborg M\u00e5rtensdotter",
"Jermolajeff, Anna Iivanantyt\u00e4r",
"Jokela, Juho Joonaanpoika",
"Jokela, Maija-Liisa Juhontyt\u00e4r",
"Jortikka, Anna Johansdotter",
"Jortikka, Carin Johansdotter",
"Jortikka, Carin Stephensdotter",
"Jortikka, Johan",
"Jortikka, Stephan Christersson",
"Jussila, Erik Eriksson",
"Jussila, Erik Mikilsson",
"Jussila, J\u00f6ran Thomasson",
"Jussila, Margaretha J\u00f6ransdotter",
"Jussila, Simon Eriksson",
"Jussila, Thomas Simonsson",
"J\u00e4ppinen, Aina",
"J\u00e4ppinen, Anders Andersson",
"J\u00e4ppinen, Anders Grelsson",
"J\u00e4ppinen, Antti Antinpoika",
"J\u00e4ppinen, Brita Grelsdotter",
"J\u00e4ppinen, Eija Inkeri",
"J\u00e4ppinen, Grels",
"J\u00e4ppinen, Grels Grelsson",
"J\u00e4ppinen, Grels Michelsson",
"J\u00e4ppinen, Heikki Antinpoika",
"J\u00e4ppinen, Heimo Einari",
"J\u00e4ppinen, Helena",
"J\u00e4ppinen, Henrik Anselm",
"J\u00e4ppinen, Hilma Maria",
"J\u00e4ppinen, Johan Johansson",
"J\u00e4ppinen, Johan Mattsson",
"J\u00e4ppinen, Maria Mikontyt\u00e4r",
"J\u00e4ppinen, Matti Mikonpoika",
"J\u00e4ppinen, Matti Mikonpoika",
"J\u00e4ppinen, Matts Grelsson",
"J\u00e4ppinen, Michel Grelsson",
"J\u00e4ppinen, Michel Johansson",
"J\u00e4ppinen, Mikko Matinpoika",
"J\u00e4ppinen, Varpu Matintyt\u00e4r",
"J\u00e4ppinen, Varpu Mikontyt\u00e4r",
"J\u00e4ppinen, William",
"J\u00e4rvenp\u00e4\u00e4, Vilhelmina Juhontyt\u00e4r",
"J\u00e4rvensivu, Eric Johan Johansson",
"J\u00e4rvensivu, Johan Mattsson",
"J\u00e4rvensivu, Juho Kustaa Erkinpoika",
"J\u00e4rvensivu, Kalle Fredrik Kallenpoika",
"J\u00e4rvensivu, Kalle Kustaa Juhonpoika",
"J\u00e4rvensivu, Matts Johansson",
"J\u00e4rvinen, Anian Juhonpoika",
"J\u00e4\u00e4skel\u00e4inen, Helena",
"J\u00e4\u00e4skel\u00e4inen, Maria Hindricsdotter",
"Kaasalainen, Anders Johansson",
"Kaasalainen, Anna Johansdotter",
"Kaasalainen, Anna Pehrsdotter",
"Kaasalainen, Anna Stephansdotter",
"Kaasalainen, Brita",
"Kaasalainen, Brita Johansdotter",
"Kaasalainen, Carin J\u00f6ransdotter",
"Kaasalainen, Catharina J\u00f6ransdotter",
"Kaasalainen, Catharina Mattsdotter",
"Kaasalainen, Elisabeth",
"Kaasalainen, Elisabetha",
"Kaasalainen, Gustaf",
"Kaasalainen, Helena J\u00f6ransdotter",
"Kaasalainen, Hindrich",
"Kaasalainen, Johan",
"Kaasalainen, Johan Mattsson",
"Kaasalainen, J\u00f6ran",
"Kaasalainen, J\u00f6ran J\u00f6ransson",
"Kaasalainen, J\u00f6ran Mattson",
"Kaasalainen, J\u00f6ran Michelsson",
"Kaasalainen, Maria",
"Kaasalainen, Maria",
"Kaasalainen, Maria Mattsdotter",
"Kaasalainen, Maria Michelsdotter",
"Kaasalainen, Maria Mikontyt\u00e4r",
"Kaasalainen, Maria Petersdotter",
"Kaasalainen, Martin",
"Kaasalainen, Matthias Cnutsson",
"Kaasalainen, Matts",
"Kaasalainen, Matts Johansson",
"Kaasalainen, Michel",
"Kaasalainen, Michel J\u00f6ransson",
"Kaasalainen, Pehr",
"Kaasalainen, Stephan Hinrdichson",
"Kaasalainen, Stephan Stephansson",
"Kaasalainen, Walborg Johansdotter",
"Kaasalainen, Walborg Martinsdotter",
"Kahonen, Maria Pettersdotter",
"Kaipom\u00e4ki, Axel Johansson",
"Kaipom\u00e4ki, Chirstin Axelsdotter",
"Kaipom\u00e4ki, Johan Larsson",
"Kaipom\u00e4ki, J\u00f6ns Larsson",
"Kaipom\u00e4ki, Lars Johansson",
"Kaitiainen, Maria Petersdotter",
"Kallio, Liisa Matintyt\u00e4r",
"Kallio, Samuli Samulinpoika",
"Kalliom\u00e4ki, Samuli Yrj\u00f6npoika",
"Kalliom\u00e4ki, Vilhelmiina Samulintyt\u00e4r",
"Kallonen, Yrj\u00f6 Juhonpoika",
"Kanninen, Anna Bertilsdotter",
"Kanninen, Bertil Andersson",
"Kanninen, Magdalena Bertilsdotter",
"Karikko, Erich Grelsson",
"Karikko, Erik Johansson",
"Karikko, Grels Eriksson",
"Karikko, J\u00f6ns Nilsson",
"Karikko, Rosina Samuelsdotter",
"Karikko, Samuel Eriksson",
"Karilainen, Anders",
"Karilainen, Anna",
"Karilainen, Anna Michelsdotter",
"Karilainen, Catharina",
"Karilainen, Elisabeth",
"Karilainen, Elisabeth",
"Karilainen, Elisabeth J\u00f6ransdotter",
"Karilainen, Matts",
"Karilainen, Michel Andersson",
"Karjalainen, J\u00f6ran",
"Karjula, Thomas Simonsson",
"Karonen, Helena Pehrsdotter",
"Karpinen, Anna Varpu Heikintyt\u00e4r",
"Karpinen, Henrik Matinpoika",
"Karvanen, Walborg Mickelsdotter",
"Karvia, Anders Andersson",
"Karvia, Anders Clemetsson",
"Karvia, Anders J\u00f6ransson",
"Karvia, Anna Stina Antintyt\u00e4r",
"Karvia, Cirstin Andersdotter",
"Karvia, Clemet Ersson",
"Karvia, Erik Grelsson",
"Karvia, Erik Nilsson",
"Karvia, Grels Erichsson",
"Karvia, Nils Olsson",
"Karvinen, Helena",
"Karvinen, Helena",
"Karvinen, Johan",
"Karvinen, Matts Johansson",
"Karvinen, Matts Mattsson",
"Kasoin, Cnuth",
"Kaukinen, Anna",
"Kaukinen, Maria Matintyt\u00e4r",
"Kaukinen, Simon",
"Kaukinen, Staffan Simonsson",
"Kaukinen, Walborg Staffansdotter",
"Kaura, Johanna Michelsdotter",
"Keikkala, Clemet Mattsson",
"Keikkala, Matts Thomasson",
"Keikkala, Thomas Olsson",
"Keikkala, Thomas Thomasson",
"Kekki, Anna Matintyt\u00e4r",
"Kekki, Carin M\u00e5rtensdotter",
"Kemppi, Catharina Petersdotter",
"Kemppi, Pehr J\u00f6ransson",
"Keppil\u00e4, Kirsti Matintyt\u00e4r",
"Kerppola, Sofia Jacobsdotter",
"Kerppola, Thomas Johansson",
"Kettunen, Anders Henricsson",
"Kettunen, Maria Andersdotter",
"Kierros, Bertil Mattsson",
"Kierros, Henrich Mattsson",
"Kierros, Margareta Bertilsdotter",
"Kierros, Matts Hindersson",
"Kiiski, Brita",
"Kiiski, Maria Mattsdotter",
"Kiiski, Paul Johansson",
"Kiiski, Thomas",
"Kiiski, Walborg Thomasdotter",
"Kiiveri, Johan",
"Kilpel\u00e4inen, Ingeborg Petersdotter",
"Kilpel\u00e4inen, Lars",
"Kilpel\u00e4inen, Peter Larsson",
"Kinkkunen, Elisabeth",
"Kinnari, Brigitta Hindricksdotter",
"Kinnari, Maria",
"Kinnari, Maria Stephansdotter",
"Kitunen, Anna M\u00e5rtensdotter",
"Kitunen, Walborg Olofsdotter",
"Kivioja, Jonas Adamsson",
"Knepp, Simon Andersson",
"Knuutila, Henrich Henrichsson",
"Knuutila, Henrik M\u00e5nsson",
"Knuutila, M\u00e5ns Matsson",
"Knuutila, Samuel Henrichsson",
"Koiranen, Brita",
"Kokko, Knut Nilsson",
"Kokko, Nils Bertilsson",
"Kolehma, Anna Eliasdotter",
"Kolehma, Elias J\u00f6ransson",
"Kolienp\u00e4\u00e4, Oleff Laurisson",
"Kolkka, Carin Michelsdotter",
"Kolkkanen, Helena Georgsdotter",
"Kopok, Maria",
"Koppanen, Anna Maria Juhontyt\u00e4r",
"Koppanen, Juho Matinpoika",
"Koppanen, Matti Tuomaanpoika",
"Koppanen, Matti Tuomaanpoika",
"Koppanen, Paul Andersson",
"Koppanen, Thomas Paulsson",
"Koppanen, Tuomas Matinpoika",
"Koppeloj\u00e4rvi, Kustaava Manuntyt\u00e4r",
"Kopra, Maria",
"Korkka, Agnetha Petersdotter",
"Korpelainen, Kaarina Matintyt\u00e4r",
"Korppila, Lisa Michelsdotter",
"Koski, Bertil Thomasson",
"Koski, Gertrud Bertilsdotter",
"Koski, J\u00f6ran M\u00e5rtensson",
"Koski, Walborg J\u00f6ransdotter",
"Kotonen, Carin Simonsdotter",
"Kotonen, Johan J\u00f6ransson",
"Kotonen, J\u00f6ran",
"Kotonen, Simon Johansson",
"Kotti, Anna Antintyt\u00e4r",
"Kottila, Johan P\u00e5hlsson",
"Kottila, Maria Johansdotter",
"Kuggb\u00f6le, Brita Sigfridsdotter",
"Kuggb\u00f6le, Sigfrid",
"Kuisma, Agneta",
"Kuisma, Paavo",
"Kukko, Abram",
"Kukko, Agnetha J\u00f6ransdotter",
"Kukko, Anna Abramsdotter",
"Kukko, Anna Bertelsdotter",
"Kukko, Anna Johansdotter",
"Kukko, Bertel",
"Kukko, Bertel",
"Kukko, Brita Abramsdotter",
"Kukko, Christer Johansson",
"Kukko, Christer J\u00f6ransson",
"Kukko, Georg Christersson",
"Kukko, Georg Johansson",
"Kukko, Johan Christersson",
"Kukko, Maria",
"Kukko, Maria",
"Kukko, Maria Christersdotter",
"Kukko, Maria J\u00f6ransdotter",
"Kukko, Philip",
"Kukko, Walborg Bertelsdotter",
"Kukkonen, Margaretha",
"Kukkonen, Matts",
"Kukkonen, Matts Mattsson",
"Kukkula, Justinus Justinuksenpoika",
"Kulkas, Johan Michelsson",
"Kulkas, J\u00f6ran Johansson",
"Kulkas, J\u00f6ran J\u00f6ransson",
"Kulkas, J\u00f6ran Mattsson",
"Kulkas, Matts J\u00f6ransson",
"Kulkas, Michel Simonsson",
"Kulkas, Olof",
"Kulkas, Simon Olsson",
"Kulkas, Walborg J\u00f6ransdotter",
"Kultanen, Helena Mattsdotter",
"Kultanen, Mathias J\u00f6ransson",
"Kupo, Elisabeth Henricsdotter",
"Kupo, Henric Jacobsson",
"Kupo, Jacob",
"Kurikka, Anders Christersson",
"Kurikka, Christer Matsson",
"Kurikka, Maria Matthiasdotter",
"Kurikka, Mathias Andersson",
"Kuronen, Anders Henricsson",
"Kuronen, Anna",
"Kuronen, Elisabeth Andersdotter",
"Kuronen, Henric",
"Kurrinen, Maria Samuelsdotter",
"Kurrinen, Samuel Petersson",
"Kutinlahti, Henrich Michelsson",
"Kutinlahti, J\u00f6ran Henrichsson",
"Kuuppo, Brita Jacobsdotter",
"Kyll\u00f6nen, Maria Michelsdotter",
"Kyll\u00f6nen, Walborg",
"Kylm\u00e4, Walborg",
"Kym\u00e4l\u00e4inen, Carin",
"Kyyr\u00f6, Anna Eskontyt\u00e4r",
"Kyyr\u00f6, Eskil Johansson",
"Kyyr\u00f6, Hindrich Mattsson",
"Kyyr\u00f6, Johan",
"Kyyr\u00f6, Matts Hendricsson",
"K\u00e4h\u00f6nen, Walborg Ericsdotter",
"K\u00e4nk\u00e4nen, Agnetha Mattsdotter",
"K\u00e4nk\u00e4nen, Mathias Petersson",
"K\u00e4nk\u00e4nen, Peter Simonsson",
"K\u00e4nk\u00e4nen, Simon",
"K\u00e4ppi, Anders Mattsson",
"K\u00e4ppi, Anna Henricsdotter",
"K\u00e4ppi, Maria Andersdotter",
"K\u00e4ppi, Matts",
"K\u00f6lhi, Margareta",
"K\u00f6mi, Eskel Larsson",
"K\u00f6mi, Eskell P\u00e5fwelsson",
"K\u00f6mi, Hendrich Eskilsson",
"K\u00f6mi, Johan Larsson",
"K\u00f6mi, Lars",
"K\u00f6mi, Lars Eskelsson",
"K\u00f6mi, Lars Larsson",
"K\u00f6mi, Matts Henrichsson",
"K\u00f6mi, P\u00e5hl Larsson",
"K\u00f6mi, Walborg Henrichsdotter",
"K\u00f6ntter, Sigfrid",
"K\u00f6ntt\u00e4ri, J\u00f6ran Larsson",
"K\u00f6ntt\u00e4ri, Kirstin J\u00f6ransdotter",
"K\u00f6ntt\u00e4ri, Lars Sigfridsson",
"Laaksi, Akseli Erkki",
"Laaksi, Emanuel Johansson",
"Laaksi, Johan Johansson",
"Laaksi, Johan Thomasson",
"Laaksi, J\u00f6ren Ohlsson",
"Laaksi, J\u00f6ren P\u00e5fwelsson",
"Laaksi, Matts P\u00e5hlsson",
"Laaksi, Olof P\u00e5hlsson",
"Laaksi, P\u00e5fwel J\u00f6ransson",
"Laaksi, P\u00e5hl Bertilsson",
"Laaksi, Thomas J\u00f6ransson",
"Laalahti, Henrik Michelsson",
"Laalahti, Michel Henriksson",
"Laalahti, Valborg Henriksdotter",
"Lankinen, Carin Mattsdotter",
"Lapakko, Margaretha B\u00e4rtilsdotter",
"Lappalainen, Anna Simonsdotter",
"Lappalainen, Carin Johansdotter",
"Lappalainen, Elisabeth",
"Lappalainen, Helena Henrichsdotter",
"Lappalainen, Henrich",
"Lappalainen, Johan",
"Lappalainen, Johan Larsson",
"Lappalainen, Lars",
"Lappalainen, Maria",
"Lappalainen, Maria Tuomaantyt\u00e4r",
"Lappalainen, Simon Johansson",
"Lappi, Carin Mattsdotter",
"Lappi, Matts Pedhersson",
"Laurikainen, Maria",
"Leini\u00e4inen, Bertil Olofsson",
"Leini\u00e4inen, Maria Bertilsdotter",
"Leini\u00e4inen, Olof",
"Lepp\u00e4j\u00e4rvi, Stina Liisa Kustaantyt\u00e4r",
"Lepp\u00e4nen, Anders",
"Lepp\u00e4nen, Brita Larsdotter",
"Lepp\u00e4nen, Carin Thomasdotter",
"Lepp\u00e4nen, Lars Andersson",
"Lepp\u00e4nen, Pekka Tuomaanpoika",
"Liimatta, Hanna",
"Lilius, Maria Elisabeth",
"Lintu, Lars P\u00e5hlsson",
"Lintula, Bengt Larsson",
"Lintula, Bertil Bengtsson",
"Lintula, Jacob Simonsson",
"Lintula, Lisa Simonsdotter",
"Lintula, Lisa Thuresdotter",
"Lintula, Simon Bertilsson",
"Lintula, Simon Thuresson",
"Lintunen, Carin Adamsdotter",
"Lipponen, Brita Mattsdotter",
"Lipponen, Matts",
"Lipponen, Matts Mattsson",
"Lius, Anders",
"Lius, Maria Andersdotter",
"Lius, Matts Andersson",
"Liuttula, Margareta Thomasdotter",
"Loimusalo, Veikko Aulis",
"Loponen, Carin Thomasdotter",
"Loponen, Henric",
"Loponen, Maria",
"Loponen, Thomas Henricsson",
"Lukkari, Anna Carlsdotter",
"Lukkari, Carl J\u00f6ransson",
"Lukkari, Hendrich Thomasson",
"Lukkari, J\u00f6ren Larsson",
"Lukkari, Lars Hindersson",
"Lukkari, Tomas Nilsson",
"Luostarinen, Walborg",
"Luukkanen, Anna Cnutsdotter",
"Luukkanen, Anna Mattsdotter",
"Luukkanen, Bertill",
"Luukkanen, Brita",
"Luukkanen, Elisabeth Eskilsdotter",
"Luukkanen, Eskil J\u00f6ransson",
"Luukkanen, Helga Helena",
"Luukkanen, Maria Stephansdotter",
"Luukkanen, Mats Bertilsson",
"Luukkanen, Simon Bertilsson",
"Luukkanen, Stephan Simosson",
"Luukkanen, Stephan Stephansson",
"L\u00e5ng, Matts Hansson",
"L\u00e4tti, Brita",
"L\u00e4tti, Helena Eskelsdotter",
"L\u00e4ttil\u00e4, Anna Maria J\u00f6ransdotter",
"L\u00e4ttil\u00e4, J\u00f6ran Mattsson",
"L\u00e4ttil\u00e4, J\u00f6ran Thomasson",
"L\u00e4ttil\u00e4, Lasse Eriksson",
"L\u00e4ttil\u00e4, Matts J\u00f6ransson",
"L\u00e4ttil\u00e4, Simon Larsson",
"L\u00e4ttil\u00e4, Thomas Simonsson",
"L\u00e4\u00e4veri, Brigita Mathiae",
"L\u00e4\u00e4veri, Mathias Staffansson",
"L\u00f6yt\u00e4n\u00e4, Anna Stephansdotter",
"L\u00f6yt\u00e4n\u00e4, Carin Jacobsdotter",
"L\u00f6yt\u00e4n\u00e4, Hindrich Staffansson",
"L\u00f6yt\u00e4n\u00e4, Staffan Henrichsson",
"Maijala, Anna Liisa Juhontyt\u00e4r",
"Maijala, Jacob Thomasson",
"Maijala, Juho Yrj\u00f6npoika",
"Maijala, Maria Jacobsdotter",
"Maijala, Thomas Nilsson",
"Maijala, Yrj\u00f6 Juhonpoika",
"Makkara, Eeva Matintyt\u00e4r",
"Makkonen, Catharina Pettersdotter",
"Mannikainen, Maija-Liisa",
"Mannikainen, Maila",
"Mannikainen, P\u00e5hl Hindricsson",
"Mannikainen, Simo",
"Marttila, Cnuth Brusiusson",
"Marttila, Elin Mattsdotter",
"Marttila, Erich Knutsson",
"Marttila, Matts Erichsson",
"Marttinen, Henrik",
"Marttinen, Henrik Henriksson",
"Marttinen, Lars Hendersson",
"Matikainen, Walborg",
"Mattila, Hedvig Kallentyt\u00e4r",
"Mattila, Ida Juhontyt\u00e4r",
"Mattila, Juho Yrj\u00f6npoika",
"Mattila, Juho Kustaa Juhonpoika",
"Mattila, Juho Oskar Juhonpoika",
"Mattila, Kalle Kustaanpoika",
"Mattila, Matts Henrici",
"Maunula, Eskill M\u00e5nsson",
"Maunula, Magnus Mattsson",
"Maunula, Matts Eskelsson",
"Melin, Maria",
"Meltonen, Maria Mattsdotter",
"Meltonen, Matts",
"Mentu, Andreas Larsson",
"Mentu, Maria Andersdotter",
"Meskanen, Anna",
"Meskanen, Anna Johansdotter",
"Meskanen, Carin J\u00f6ransdotter",
"Meskanen, Carin Simonsdotter",
"Meskanen, Johan",
"Meskanen, J\u00f6ran Simonsson",
"Meskanen, Simon Matsson",
"Mexberg, Gabriel Henricsson",
"Mexberg, Hedvig Kaapontyt\u00e4r",
"Mexberg, Hendrich",
"Mikkola, Walborg Marcusdotter",
"Minkkinen, Hindrich Larsson",
"Minkkinen, J\u00f6ran Mattsson",
"Minkkinen, J\u00f6ran Mattsson",
"Minkkinen, Matts Hendersson",
"Minkkinen, Matts J\u00f6ransson",
"Moisio, Aino",
"Moisio, Juho Vilhelm Kustaanpoika",
"Moksu, Anna Elia'dotter",
"Moksu, Elias Nilsson",
"Mong\u00e5, Johan Johansson",
"Mononen, Brita Johansdotter",
"Mononen, Clemet Mattsson",
"Mononen, Henrich Mattsson",
"Mononen, Johan Henrichsson",
"Mononen, Matts",
"Mononen, Matts Clemetsson",
"Montonen, Catharina",
"Mosalainen, Anders Henricsson",
"Muikonen, Maria Christersdotter",
"Muli, Brita Petersdotter",
"Muli, Johan Johansson",
"Muli, Johan Lucasson",
"Muli, Johan Lucasson",
"Muli, Lucas Johansson",
"Muli, Lukas",
"Muli, Maria Petersdotter",
"Muli, Peter",
"Muli, Walborg Johansdotter",
"Muli, Walborg Lukasdotter",
"Mulkola, Maria Claesdotter",
"Multia, Kirstin Thomasdotter",
"Murtom\u00e4ki, Eskil Johansson",
"Murtom\u00e4ki, Fredrika Tuomaantyt\u00e4r",
"Murtom\u00e4ki, Thomas Eskilsson",
"Murtom\u00e4ki, Tuomas Tuomaanpoika",
"Musakka, Brigita Mattsdotter",
"Musakka, Catharina",
"Musakka, Elisabeth P\u00e5hlsdotter",
"Musakka, Maria Petersdotter",
"Musakka, Matts",
"Musakka, Matts",
"Musakka, Matts Mattsson",
"Musakka, Peter Mattsson",
"Musakka, P\u00e5hl",
"Musakka, Walborg",
"Musakka, Walborg Andersdotter",
"Mustonen, Anna",
"Mustonen, Carin Johansdotter",
"Mustonen, Catharina J\u00f6ransdotter",
"Mustonen, Henric Larsson",
"Mustonen, Henric Larsson",
"Mustonen, Johan",
"Mustonen, J\u00f6ran",
"Mustonen, J\u00f6ran",
"Mustonen, Kaisa Matintyt\u00e4r",
"Mustonen, Lars Henricsson",
"Mustonen, Matti Heikinpoika",
"Mustonen, Matts",
"Mustonen, Walborg J\u00f6ransdotter",
"Mustonen, Walborg Mattsdotter",
"Mutkari, Elisabeth Michelsdotter",
"Mutkari, Michel",
"Muuransuo, Kalle Aataminpoika",
"Muuriainen, Maria",
"Muurla i \u00c5bo, Margareta Nilsdotter",
"M\u00e4kel\u00e4, Kaarle Henrik Samulinpoika",
"M\u00e4kel\u00e4, Samuli Tuomaanpoika",
"M\u00e4kel\u00e4, Tuomas Manunpoika",
"M\u00e4kel\u00e4inen, Helga Helena Frantzdotter",
"M\u00e4ki, Henrich Sigfridsson",
"M\u00e4ki, Maria Henrichsdotter",
"M\u00e4ki, Sigfred Henrichsson",
"M\u00e4ki-Siukola, Kustaa Adolf Joonaanpoika",
"M\u00e4mmi, J\u00f6ran Thomasson",
"M\u00e4mmi, Lars Larsson",
"M\u00e4mmi, Thomas J\u00f6ransson",
"M\u00e4mmi, Thomas Larsson",
"M\u00e4nts\u00e4, Nils Larsson",
"M\u00e4nts\u00e4, Thomas Nilsson",
"M\u00e4ntt\u00e4, Helena Markuksentyt\u00e4r",
"M\u00e4ntt\u00e4, Heta Kristiina Juhontyt\u00e4r",
"M\u00e4ntt\u00e4, Johan Marcusson",
"M\u00e4ntt\u00e4, Juho Markuksenpoika",
"M\u00e4ntt\u00e4, Marcus Mattsson",
"M\u00e4ntt\u00e4, Marcus Thomasson",
"M\u00e4ntt\u00e4, Matts Johansson",
"M\u00e4ntt\u00e4, Thomas Thomasson",
"M\u00e4ntt\u00e4, Thomas Thomasson",
"M\u00e4\u00e4tt\u00e4nen, Adam Larsson",
"M\u00e4\u00e4tt\u00e4nen, Cnut Michelsson",
"M\u00e4\u00e4tt\u00e4nen, Henric Adamsson",
"M\u00e4\u00e4tt\u00e4nen, J\u00f6ran Paulsson",
"M\u00e4\u00e4tt\u00e4nen, Lars Larsson",
"M\u00e4\u00e4tt\u00e4nen, Sara Cnutsdotter",
"M\u00e4\u00e4tt\u00e4nen, Walborg Henricsdotter",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N",
"N, N Knutsdotter",
"Naskali, Elias Thomasson",
"Naskali, Staffan",
"Naskali, Thomas Staffansson",
"Naskali, Walborg Eliasdotter",
"Natt och Dag, Margareta Tuvesdotter",
"Nenonen, Erich",
"Nenonen, Maria Ericsdotter",
"Neo, Walborg",
"Niemi, Henrich Mattsson",
"Niemi, Matts Henrichsson",
"Nihti, Maria Bertilsdotter",
"Nihtil\u00e4, Henric Larsson",
"Nihtil\u00e4, J\u00f6ran Henriksson",
"Niinim\u00e4ki, Eric Jacobsson",
"Nikin-Eskola, Kalle Matinpoika",
"Nikkil\u00e4, Christina Urbanusdotter",
"Nikkil\u00e4, Matts Nilsson",
"Nikkil\u00e4, Nils Knutsson",
"Nikkil\u00e4, Urbanus Mattsson",
"Niukkanen, Nils",
"Niukkanen, Walborg Nilsdotter",
"Niuta, Brita Petersdotter",
"Niuta, Peter",
"Nokelainen, Carin Pettersdotter",
"Nokelainen, Catharina Johansdotter",
"Nokelainen, Elisabeth Henricsdotter",
"Nokelainen, Helena Olofsdotter",
"Nokelainen, Henric",
"Nokelainen, Johan",
"Nokelainen, Johan Johansson",
"Nokelainen, Maria J\u00f6ransdotter",
"Nokelainen, Maria Olovsdotter",
"Nokelainen, Matts",
"Nokelainen, Olov Mattsson",
"Nokelainen, Olov Petersson",
"Nokelainen, Peter",
"Nokelainen, Petter Henricsson",
"Nokre, Anna Mattsdotter",
"Nokre, Anna Tuomaantyt\u00e4r",
"Nokre, Hindric",
"Nokre, Johan Mattsson",
"Nokre, J\u00f6ran Hindricsson",
"Nokre, Maria Tahvontyt\u00e4r",
"Nokre, Matts J\u00f6ransson",
"Nokre, Stephan Mattsson",
"Nokre, Tuomas Juhonpoika",
"Nolo, Hendric",
"Nolo, Juho Juhonpoika",
"Nolo, J\u00f6ran Hendricsson",
"Nolo, Katri Juhontyt\u00e4r",
"Nolo, Maria J\u00f6ransdotter",
"Nuora, Anna",
"Nurkka, Maria",
"Nyman, Antti Kustaa Antinpoika",
"Nyyss\u00f6nen, Maria Larsdotter",
"N\u00e4nnim\u00e4inen, Anna Mattsdotter",
"N\u00e4nnim\u00e4inen, Carin J\u00f6ransdotter",
"N\u00e4nnim\u00e4inen, J\u00f6ran",
"N\u00e4nnim\u00e4inen, Maria J\u00f6ransdotter",
"N\u00e4ppil\u00e4, Anders Simonsson",
"N\u00e4ppil\u00e4, J\u00f6ran Andersson",
"N\u00e4ri\u00e4inen, Heinrich Petersson",
"N\u00e4ri\u00e4inen, Peter Cnutsson",
"N\u00e4ri\u00e4inen, Peter Petersson",
"N\u00e4ri\u00e4inen, Simon Heinrichsson",
"N\u00e4ri\u00e4inen, Varpu Yrj\u00f6ntyt\u00e4r",
"N\u00e4ri\u00e4inen, Yrj\u00f6 Simonpoika",
"N\u00e4rv\u00e4, Elias Jacobsson",
"Olkinuora, Agnetha Simonsdotter",
"Olkinuora, Simon",
"Ollikainen, Anna Henricsdotter",
"Oranen, Anders Johansson",
"Oranen, Anna Andersdotter",
"Oranen, Johan",
"Ouni, Bertill Mattsson",
"Ouni, Johan Sigfridsson",
"Ouni, Sigfrid Thomasson",
"Ouni, Thomas Bertilsson",
"Paajanen, Anna Mattsdotter",
"Paajanen, Brigitta M\u00e5rtensdotter",
"Paajanen, Gregorius Mattsson",
"Paajanen, Henric Johansson",
"Paajanen, Johan Johansson",
"Paajanen, Johan Sigfredsson",
"Paajanen, Korius",
"Paajanen, Lisa Henriksdotter",
"Paajanen, Maria Gregoriusdotter",
"Paajanen, Maria J\u00f6ransdotter",
"Paajanen, Matts Gregoriusson",
"Paajanen, M\u00e5rten",
"Paajanen, Sigfred Gregoriusson",
"Paajanen, Walborg",
"Paakkanen, Anna Stephansdotter",
"Paakkanen, Joseph",
"Paakkanen, Stephan Josephsson",
"Paakkari, Jacob Thomasson",
"Paakkari, Michel Jacobsson",
"Paakkari, P\u00e5hl Michelson",
"Paakkari, Walborg Michelssotter",
"Paavilainen, Anna",
"Paavilainen, Maria Walborg Hindricsdotter",
"Pajari, Catharina Adamsdotter",
"Pakarinen, Anders J\u00f6ransson",
"Pakarinen, Anna Andersdotter",
"Pakarinen, Elisabeth",
"Pakarinen, Ingeborg",
"Pakarinen, J\u00f6ran Pettersson",
"Pakom\u00e4ki, Adam Staphansson",
"Palander, Abraham Axelio",
"Palander, Lisa Pehrsdotter",
"Palander, Petrus",
"Palander, Petter Pettersson",
"Pamppanen, Walborg",
"Pappinen, Simon Bertilsson",
"Papunen, Maria Larsdotter",
"Parkkali, Catharina Zachariasdotter",
"Parkkali, Zacharias Jacobsson",
"Partanen, Hindrich",
"Partanen, Stephan Hindrichsson",
"Partanen, Walborg Staffansdotter",
"Paso, Anna Sigfredsdotter",
"Pauhari, Eric Olofsson",
"Pauhari, Grels Thomasson",
"Pauhari, Henrich M\u00e5rtensson",
"Pauhari, Johan Olofsson",
"Pauhari, M\u00e5rten Ericsson",
"Pauhari, Olof",
"Pauhari, Olof Johansson",
"Pauhari, Thomas Henrichsson",
"Paukku, Anna Petersdotter",
"Paukku, Peter Henricsson",
"Paussu, Aatami Juhonpoika",
"Paussu, Johan Petersson",
"Paussu, Katri Aatamintyt\u00e4r",
"Paussu, Peter",
"Paussu, Peter P\u00e5hlsson",
"Paussu, P\u00e5hl Petersson",
"Pekkala, Abraham Juhonpoika",
"Pekkala, Aino Anna-Liisa",
"Pekkala, Axel Eriksson",
"Pekkala, Einar Arvid",
"Pekkala, Erik Axselsson",
"Pekkala, Juho Akselinpoika",
"Pellikainen, Erick",
"Pellikainen, Magdalena Helena Ericsdotter",
"Peltonen, Maria Pekantyt\u00e4r",
"Peltonen, Pekka",
"Pennanen, Carin Mattsdotter",
"Pennanen, Johan",
"Pennanen, Lars",
"Pennanen, Matts Larsson",
"Penttil\u00e4, Matts J\u00f6ransson",
"Penttinen, Catharina Mattsdotter",
"Penttinen, Matts",
"Perttula, Maria Andersdotter",
"Pihlajalahti, Frans Jacobsson",
"Pihlajalahti, Johan J\u00f6ransson",
"Pihlajalahti, Kirstin Johansdotter",
"Pihlajalahti, Peer Fransson",
"Pihlajalahti, Yrj\u00f6 Pekanpoika",
"Piiparinen, Anna Andersdotter",
"Piippu, Catharina Johansdotter",
"Pirttisarka, Emanuel Matinpoika",
"Pitk\u00e4nen, Helena Juhontyt\u00e4r",
"Pitk\u00e4nen, Juho Simonpoika",
"Pitk\u00e4nen, J\u00f6ran Andersson",
"Pitk\u00e4nen, Maria Gabrielsdotter",
"Pitk\u00e4nen, Maria Pettersdotter",
"Pitk\u00e4nen, Petter",
"Pitk\u00e4nen, Simon J\u00f6ransson",
"Pitk\u00e4nen, Simon Simonsson",
"Pohjalainen, Anna Petersdotter",
"Pohjalainen, Johan J\u00f6ransson",
"Pohjalainen, Johan Michelsson",
"Pohjalainen, J\u00f6ran Jonasson",
"Pohjalainen, Maria Michelsdotter",
"Pohjalainen, Michel",
"Pohjalainen, Michel Johansson",
"Pohjalainen, Simon",
"Pohjalainen, Varpu Juhontyt\u00e4r",
"Pokkinen, Elisabeth",
"Posti, Elin Isacsdotter",
"Posti, Isach Mattsson",
"Posti, Matts Peersson",
"Posti, Sigfrid Isacsson",
"Puikkonen, Agnetha Christersdotter",
"Puikkonen, Christer Henricsson",
"Puikkonen, Henric Mattsson",
"Puikkonen, Lisa Mattsdotter",
"Puikkonen, Matts",
"Pulakka, Maria Andersdotter",
"Pulkki, Brita Nilsdotter",
"Pulkkinen, Lempi Maria Viljamintyt\u00e4r",
"Pullinen, Catarina Matsdotter",
"Puolakainen, Anders Michelsson",
"Puolakainen, Anna Andersdotter",
"Puolakainen, Michel Michelsson",
"Puolakainen, Michel Oloffsson",
"Puolakainen, Oloff Brusiusson",
"Puputti, Catharina Samuelsdotter",
"Puputti, Lena Pehrsdotter",
"Pusa, Aapro Heikinpoika",
"Pusa, Agnetha J\u00f6ransdotter",
"Pusa, Anna",
"Pusa, Anna J\u00f6ransdotter",
"Pusa, Anna Mattsdotter",
"Pusa, Anna M\u00e5rtensdotter",
"Pusa, Elisabeth Johansdotter",
"Pusa, Elisabeth Simonsdotter",
"Pusa, Georg Simonsson",
"Pusa, Ilmari",
"Pusa, Johan M\u00e5rtensson",
"Pusa, J\u00f6ran Simonsson",
"Pusa, Lisa J\u00f6ransdotter",
"Pusa, Maria",
"Pusa, Maria M\u00e5rtensdotter",
"Pusa, Matts M\u00e5rtensson",
"Pusa, M\u00e5rten Thomasson",
"Pusa, Simon",
"Pusa, Simon Simonsson",
"Pusa, Simon Simonsson",
"Pusa, Walborg",
"Puukka, Catharina",
"Pyk\u00e4list\u00f6, Heta Liisa Juhontyt\u00e4r",
"Pylkki, Benjamin Antinpoika",
"Pylkki, Johan Erik Andersson",
"Pyykk\u00f6, Walborg Michelsdotter",
"P\u00e4rri, Johanna Kustaava Simontyt\u00e4r",
"P\u00e4rri, Maria Heikintyt\u00e4r",
"P\u00e4rssinen, Adam Andersson",
"P\u00e4rssinen, Anders Johansson",
"P\u00e4rssinen, Anders Mattsson",
"P\u00e4rssinen, Anna",
"P\u00e4rssinen, Anna Matthsdotter",
"P\u00e4rssinen, Anna Michelsdotter",
"P\u00e4rssinen, Brita Mattsdotter",
"P\u00e4rssinen, Elisabeth",
"P\u00e4rssinen, Irja Ester",
"P\u00e4rssinen, Johan Adamsson",
"P\u00e4rssinen, Johan Michelsson",
"P\u00e4rssinen, Johan Petersson",
"P\u00e4rssinen, Juho",
"P\u00e4rssinen, Juho Juhonpoika",
"P\u00e4rssinen, Juho Mikonpoika",
"P\u00e4rssinen, Lisa Hendricsdotter",
"P\u00e4rssinen, Maria Johansdotter",
"P\u00e4rssinen, Maria J\u00f6ransdotter",
"P\u00e4rssinen, Matths Johansson",
"P\u00e4rssinen, Matts",
"P\u00e4rssinen, Matts Adamsson",
"P\u00e4rssinen, Matts Stephansson",
"P\u00e4rssinen, Michel",
"P\u00e4rssinen, Michel Johansson",
"P\u00e4rssinen, Mikko Juhonpoika",
"P\u00e4rssinen, Paul Mattsson",
"P\u00e4rssinen, Riitta Paulintyt\u00e4r",
"P\u00e4rssinen, Stephan Johansson",
"P\u00e4rssinen, Toivo",
"P\u00e4rssinen, Varpu Antintyt\u00e4r",
"P\u00e4rssinen, Walborg Simonsdotter",
"P\u00f6h\u00f6, Johan Larsson",
"P\u00f6h\u00f6, J\u00f6ran Petersson",
"P\u00f6h\u00f6, Lars J\u00f6ransson",
"P\u00f6h\u00f6, Walborg Larsdotter",
"P\u00f6ll\u00e4kk\u00e4, J\u00f6ran Andersson",
"P\u00f6yh\u00f6nen, Maria",
"P\u00f6ysti, Anna",
"Raami, Johan",
"Raami, Johan Mattsson",
"Raami, J\u00f6ran",
"Raami, Katri Juhontyt\u00e4r",
"Raami, Maria Matthsdotter",
"Raami, Matths Mattsson",
"Raami, Matts Johansson",
"Raami, Matts Sigfredsson",
"Raami, Sigfred J\u00f6ransson",
"Rahm i Strand i \u00c4lg\u00e5, Salomon Torstensson",
"Rainio, Hans J\u00f6nsson",
"Rainio, Johan Hansson",
"Rainio, Lisbetha Johansdotter",
"Raiskinm\u00e4ki, Juho Yrj\u00f6npoika",
"Raiskinm\u00e4ki, Liisa Juhontyt\u00e4r",
"Rakkolainen, Walborg",
"Ram, Margareta Torstensdotter",
"Ram, Torsten Ingelsson",
"Ram, Torsten Salomonsson",
"Rampa, Anders",
"Rampa, Bertil Larsson",
"Rampa, Cnut",
"Rampa, Lars",
"Rampa, Matts Cnutsson",
"Rampa, Matts Mattsson",
"Rampa, Walborg Bertilsdotter",
"Rampa, Walborg Mattsdotter",
"Rantalainen, Johan",
"Rantalainen, Maria Johansdotter",
"Rasi, Eric Mattsson",
"Rasi, Maria Mattsdotter",
"Rasi, Matts Henricsson",
"Rasi, Matts Mattsson",
"Rasi, Valpuri Erkintyt\u00e4r",
"Rassi, Kirstin Simonsdotter",
"Raukola, Lisa Thuronis",
"Raukola, Matts Henriksson",
"Raumannus, Jacobus Pauli",
"Rautia, Mikil Nilsson",
"Rautiainen, Anna Maununtyt\u00e4r",
"Rautiainen, Bertil Andersson",
"Rautiainen, Brita Thomasdotter",
"Rautiainen, Henric",
"Rautiainen, Johan Johansson",
"Rautiainen, Johan Magnusson",
"Rautiainen, J\u00f6ran J\u00f6ransson",
"Rautiainen, Loviisa Matintyt\u00e4r",
"Rautiainen, Magnus",
"Rautiainen, Magnus Johansson",
"Rautiainen, Magnus Simonsson",
"Rautiainen, Maria Henricstotter",
"Rautiainen, Maria Yrj\u00f6ntyt\u00e4r",
"Rautiainen, Simon Magnusson",
"Rautiainen, Thomas Henricsson",
"Rautiainen, Walborg Thomasdotter",
"Reinikka, Chirstin Mattsdotter",
"Reinikka, Johan J\u00f6ransson",
"Reinikka, Kristiina Juhontyt\u00e4r",
"Rekola, Grels Sigfridsson",
"Rekola, Jacob Mattsson",
"Rekola, J\u00f6ren Grelsson",
"Rekola, Margeta Thomasdotter",
"Rekola, Maria M\u00e5rtensdotter",
"Rekola, Matts Thomasson",
"Rekola, Matts Thomasson",
"Rekola, M\u00e5rten Thomasson",
"Rekola, Sigfrid Knutsson",
"Rekola, Thomas Grelsson",
"Rekola, Thomas J\u00f6ransson",
"Riiko, Elin J\u00f6ransdotter",
"Riiko, J\u00f6ran Olofsson",
"Ripainen, Carin Christersdotter",
"Ristsepp\u00e4, Anna Mattsdotter",
"Ristsepp\u00e4, Mathias Simonsson",
"Ristsepp\u00e4, Simon Eskelsson",
"Roini, Olaus",
"Roini, Walborg Petersdotter",
"Romu, Mikko Villenpoika",
"Romu, Sirkka Maria",
"Romu, Sylvi Hedvig",
"Roponen, Alexander Thomasson",
"Roponen, Elisabeth Thomasdotter",
"Roponen, Thomas",
"Roponen, Thomas Thomasson",
"Rosted (Williams), Bertha Lempi Eugenia",
"Rouhiainen, Maria",
"Ruolahti, Ingeborg Johansdotter",
"Ruuna, Helga",
"Ruuna, Peter",
"Ruuna, Walborg Petersdotter",
"Ruuska, Aatami Aataminpoika",
"Ruuska, Maria",
"R\u00e4hm\u00f6nen, Brita Johansdotter",
"R\u00e4hm\u00f6nen, Daniel",
"R\u00e4hm\u00f6nen, Johan Danielsson",
"R\u00e4m\u00f6, Abraham Mattsson",
"R\u00e4m\u00f6, Abraham Stephansson",
"R\u00e4m\u00f6, Anders J\u00f6ransson",
"R\u00e4m\u00f6, Hetti Vilpuntyt\u00e4r",
"R\u00e4m\u00f6, Juho Tuomaanpoika",
"R\u00e4m\u00f6, J\u00f6ran J\u00f6ransson",
"R\u00e4m\u00f6, J\u00f6ran Mattsson",
"R\u00e4m\u00f6, Maria Abrahamsdotter",
"R\u00e4m\u00f6, Marianna Tuomaantyt\u00e4r",
"R\u00e4m\u00f6, Mathias J\u00f6ransson",
"R\u00e4m\u00f6, Matts",
"R\u00e4m\u00f6, Matts Hendriksson",
"R\u00e4m\u00f6, Michel Abrahamsson",
"R\u00e4m\u00f6, Stephan Andersson",
"R\u00e4m\u00f6, Tuomas Mikonpoika",
"R\u00e4m\u00f6, Tuomas Tuomaanpoika",
"R\u00e4nn\u00e4li, Adam Petersson",
"R\u00e4nn\u00e4li, Agnetha Adamsdotter",
"R\u00e4nn\u00e4li, Matts",
"R\u00e4nn\u00e4li, Peter Matsson",
"R\u00e4tt\u00f6, Carin P\u00e5hlsdotter",
"R\u00e4tt\u00f6, Elina",
"R\u00f6ring, Henrik Johansson",
"R\u00f6ring, Johan Mattsson",
"R\u00f6ring, Maria Henriksdotter",
"Saikkonen, Elina",
"Saira, Erik Simonsson",
"Saira, Eskil Ericsson",
"Saira, Hedvig Michelsdotter",
"Saira, Michel Eskilsson",
"Salen, Johanna Thomasdotter",
"Salen, Thomas Grelsson",
"Sallinen, Lars",
"Sallinen, Lars Larsson",
"Sallinen, Walborg Larsdotter",
"Salvenius, Anders Johan",
"Salvenius, Christina Elisabeth Andersdotter",
"Salvenius, Erik Mattson",
"Sandb\u00e4ck, Matts Mattsson",
"Sandb\u00e4ck, Yrj\u00f6 Matinpoika",
"Savolainen, Anna J\u00f6ransdotter",
"Savolainen, Antti Luukkaanpoika",
"Savolainen, Bertil",
"Savolainen, Carin",
"Savolainen, Elsa Elli Juhontyt\u00e4r",
"Savolainen, Eric",
"Savolainen, Helena Hindrichsdotter",
"Savolainen, Helena P\u00e4rsdotter",
"Savolainen, Hindrich Hindrichsson",
"Savolainen, Hindrich P\u00e5hlsson",
"Savolainen, Johan",
"Savolainen, Johan Bertilsson",
"Savolainen, Johan Johansson",
"Savolainen, Johan Johasson",
"Savolainen, Johan Johasson",
"Savolainen, Johan Lucasson",
"Savolainen, Liisa Antintyt\u00e4r",
"Savolainen, Lucas Johansson",
"Savolainen, Lucas Johansson",
"Savolainen, Maria",
"Savolainen, Maria Heikintyt\u00e4r",
"Savolainen, Maria Johansdotter",
"Savolainen, Maria Johansdotter",
"Savolainen, Pehr",
"Savolainen, Walborg Augustsdotter",
"Savolainen, Walborg Ericsdotter",
"Savolainen, Walborg Henricsdotter",
"Saxberg, Maria Heikintyt\u00e4r",
"Sepp\u00e4, Eskel Thomasson",
"Sepp\u00e4, Thomas",
"Sepp\u00e4nen, Anna Hindricksdotter",
"Sepp\u00e4nen, Hindrick M\u00e5rtensson",
"Sepp\u00e4nen, Maria",
"Sepp\u00e4nen, Maria Gabrielsdotter",
"Seurasalmi, Anders J\u00f6ransson",
"Seurasalmi, Eva Andersdotter",
"Sillanp\u00e4\u00e4, Akseli",
"Simolin, Henric",
"Simolin, Ulrika Henricsdotter",
"Sipil\u00e4inen, Katarina Tuomaantyt\u00e4r",
"Sipil\u00e4inen, Margaretha Mattsdotter",
"Sirkkala, Eskil Michelsson",
"Sirkkala, Eskill J\u00f6ransson",
"Sirkkala, J\u00f6ran Eskilsson",
"Sirkkala, Maria Samuelsdotter",
"Sirkkala, Maria Sigfredsdotter",
"Sirkkala, Sigfred Eskilsson",
"Siurola, Clemet Thuresson",
"Siurola, Henrich Thomasson",
"Siurola, Olof Tordsson",
"Siurola, Sigfrid Olofsson",
"Siurola, Thomas Clemetsson",
"Siurola, Thomas Henriksson",
"Siurola, Thure Clemetsson",
"Siurola, Thure Thomasson",
"Siurola, Tord Sigfridsson",
"Sjundby, Brita Bertilsdotter",
"Skalm, Claes Andersson",
"Skugge, Anna",
"Skytt\u00e4l\u00e4, Matts Bertilsson",
"Smedh, Sigfred",
"Somppi, Brita Pehrsdotter",
"Somppi, Henrich Mattsson",
"Somppi, Matts Erichsson",
"Somppi, Peder Pedersson",
"Somppi, Per Persson",
"Sontikka, Maria",
"Sorola, Valborg Clasdotter",
"Sotku, Anders Andersson",
"Sotku, Jacob",
"Sotku, Lisa Matthsdotter",
"Sotku, Matths Jacobsson",
"Sparf, Benjamin Mattsson",
"Sparf, Hedvig Benjaminsdotter",
"Speitz, Christina J\u00f6ransdotter",
"Speitz, Henrik Jacobsson",
"Speitz, J\u00f6ran Henriksson",
"Stierna, Elin M\u00e5rtensdotter",
"Stierna, M\u00e5rten Ericsson",
"Stiernkors i Fr\u00f6jdb\u00f6le, Erik M\u00e5rtensson",
"Stjernkors, Ivar Axelsson",
"Stolpe, Johannes Adamsson",
"Strandman, Andreas",
"Strandman, Andreas Andre\u00e6",
"Suikkanen, Anna",
"Suluslahti, Lisa Henrichsdotter",
"Sundstr\u00f6m, Henrik Mattsson",
"Sundstr\u00f6m, Maria Elisabeth Henricsdotter",
"Suolaxius, Axelius Theodorici",
"Suomatka, Michel J\u00f6nsson",
"Susi, Maria Nicolaisdotter",
"Suutari, Anders",
"Suutari, Britha Andersdotter",
"Suutari, Catharina Petersdotter",
"Suutari, J\u00f6ran Andersson",
"Suutari, Maria J\u00f6ransdotter",
"Suutari, Peter Olofsson",
"S\u00e4rkinen, Maria",
"Taavettila, Elisabeth Johansdotter",
"Taavettila, Johan Michelsson",
"Taavettila, Michel Michelsson",
"Taavettila, Walborg Michelsdotter",
"Taipale, Herman Aapronpoika",
"Talikainen, Brita Sigfredsdotter",
"Talikainen, Sigfred",
"Talonpoika, Elisabeth J\u00f6ransdotter",
"Talonpoika, Jacob Staffansson",
"Talonpoika, J\u00f6ran Jacobsson",
"Talonpoika, Maria",
"Tanninen, Kaarina Tuomaantyt\u00e4r",
"Tasainen, Henrik Persson",
"Tasainen, Valborg Henriksdotter",
"Tavela, Axel Hansson",
"Tavela, Carin Axelsdotter",
"Tavela, Hans Bengtsson",
"Tavela, Sofia Axelsdotter",
"Tawast, J\u00f6ns Olofsson",
"Tawast, Katarina Nilsdotter",
"Tawast, Margit J\u00f6nsdotter",
"Tawast, Nils Olofsson",
"Tawast, Olof J\u00f6nsson",
"Tawast, Valborg J\u00f6nsdotter",
"Techtonia, Elisabeth Jacobsdotter",
"Tehi, Maria Simonsdotter",
"Tehi, Simon Andersson",
"Teit, Gregorius Martini",
"Tepponen, Anders Ericsson",
"Tepponen, Anna Andersdotter",
"Tepponen, Eric",
"Tervanen, Eric",
"Tervanen, Johan Ericsson",
"Tervanen, Walborg Johansdotter",
"Tihver\u00e4inen, Anders",
"Tihver\u00e4inen, Anna Heikintyt\u00e4r",
"Tihver\u00e4inen, Catharina Johansdotter",
"Tihver\u00e4inen, Heikki Matinpoika",
"Tihver\u00e4inen, Henric",
"Tihver\u00e4inen, Henric Henricsson",
"Tihver\u00e4inen, Johan Johansson",
"Tihver\u00e4inen, Johan Johansson",
"Tihver\u00e4inen, Johan Simonsson",
"Tihver\u00e4inen, Juho Heikinpoika",
"Tihver\u00e4inen, Kaarina Maununtyt\u00e4r",
"Tihver\u00e4inen, Magnus Stephansson",
"Tihver\u00e4inen, Matti Heikinpoika",
"Tihver\u00e4inen, Simon Johansson",
"Tihver\u00e4inen, Stephan Johansson",
"Tiira, Walborg Petersdotter",
"Tikka, Brita Mattsdotter",
"Tikka, Matts",
"till Aln\u00e4s, Christofer Bertilsson",
"till Aln\u00e4s, Elin Helena Kristoffersdotter",
"till Moisio, J\u00f6ns Mickelsson",
"till Viurila, Elseby M\u00e5nsdotter",
"Tirkkonen, Olga Maria Kaarlontyt\u00e4r",
"Toikka, Catharina Mattsdotter",
"Toikka, Matts",
"Toiviainen, Elisabeth Syringsdotter",
"Toiviainen, Syring",
"Tomperi, Aarne",
"Tomperi, Aili",
"Tomperi, Anders Johansson",
"Tomperi, Anna Liisa",
"Tomperi, Ilmi Ilona",
"Tomperi, Johan",
"Tomperi, Johan Mattsson",
"Tomperi, Juho Yrj\u00f6npoika",
"Tomperi, Juho Yrj\u00f6npoika",
"Tomperi, J\u00f6ran Johansson",
"Tomperi, Matts Andersson",
"Tomperi, Raija Leena",
"Tomperi, Toini Sivi\u00e4",
"Tomperi, Vilho",
"Tomperi, Yrj\u00f6 Juhonpoika",
"Tontti, Elisabeta",
"Torkkeli, J\u00f6ran",
"Torkkeli, Maria",
"Torkkeli, Walborg J\u00f6ransdotter",
"Tuna, Maria",
"Tunkelo, Johan Johansson",
"Tuokko, Anna Tahvontyt\u00e4r",
"Tuokko, Pauli Heikinpoika",
"Tuomela, Erkki Ensio",
"Tuomela, Lea Annikki",
"Tuominen, Aili Sisko",
"Tuottinen, Knut",
"Turkki, Maria P\u00e5hlsdotter",
"Turkkinen, Thomas Abrahamsson",
"Turve, Helena",
"T\u00f6rnqvist, Johan",
"T\u00f6rnqvist, Johan Johansson",
"T\u00f6rnqvist, Johanna Johansdotter",
"T\u00f6yr\u00e4niemi, Anna Mattsdotter",
"Udd, Matts Mattsson",
"Ulkolainen, Anna J\u00f6ransdotter",
"Ulkolainen, J\u00f6ran",
"Ursin, Catharina",
"Uuranniemi, Lena Thomasdotter",
"Vaitti, Helena Mattsdotter",
"Vaitti, Johan Mattsson",
"Vaitti, Matthias Johansson",
"Vaitti, Matts Andersson",
"Vaitti, Matts Mattsson",
"Vanhanen, Anders Johansson",
"Vanhanen, Brita Petersdotter",
"Vanhanen, Catharina",
"Vanhanen, Catharina Mattsdotter",
"Vanhanen, Grels",
"Vanhanen, Johan",
"Vanhanen, Maria Grelsdotter",
"Vanhanen, Peter Andersson",
"Vanhanen, Simon P\u00e5hlsson",
"Vaskelainen",
"Vaskelainen, J\u00f6ran",
"Vaskelainen, Walborg J\u00f6ransdotter",
"Vehkoo, Lisa Eliasdotter",
"Veitikka, Walborg Staffansdotter",
"Ventonen, Maria Jacobsdotter",
"Vessari, Anders Mattsson",
"Vessari, Brita Andreasdotter",
"Vessari, Hedvig Henricsdotter",
"Vessari, Henrik Andersson",
"Vessari, Lars Peersson",
"Vessari, Margeta Peersdotter",
"Vessari, Matts Peersson",
"Vessari, Olof Larsson",
"Vessari, Peer Olsson",
"Vessari, Per",
"Viiala, Erika Joonaantyt\u00e4r",
"Viiala, Johan Ersson",
"Vilkki, Beatha Bertilsdotter",
"Vilkki, Bertill",
"Vilkkil\u00e4, Johan Svensson",
"Vilkkil\u00e4, J\u00f6ran M\u00e5rtensson",
"Vilkkil\u00e4, M\u00e5rten Johansson",
"Vilkkil\u00e4, M\u00e5rten J\u00f6ransson",
"Virkki, Walborg",
"Virolainen, Anna Tuomaantyt\u00e4r",
"Virolainen, Brita Jacobsdotter",
"Virolainen, Carin",
"Virolainen, Carin P\u00e5hlsdotter",
"Virolainen, Jacob",
"Virolainen, Maria Mattsdotter",
"Virolainen, Matts",
"Virolainen, P\u00e5hl Mattsson",
"Virtanen, Ida Otteliana",
"Virtanen, Kalle Kustaa Kallenpoika",
"Viskari, Elin Mattsdotter",
"Viskari, Erich",
"Viskari, Jacob Ericsson",
"Viskari, Matts Thomasson",
"Viskari, Thomas Jacobsson",
"Vuohelainen, Bertyl Jacobsson",
"Vuohelainen, Bertyl J\u00f6ransson",
"Vuohelainen, Elisabeth J\u00f6ransdotter",
"Vuohelainen, Georg Bertylsson",
"Vuohelainen, Helena Jacobsdotter",
"Vuohelainen, Jacob Henricsson",
"Vuohelainen, J\u00f6ran",
"Vuohelainen, Lisa Bertylsdotter",
"Vuohelainen, Maria",
"Vuohelainen, Maria J\u00f6ransdotter",
"V\u00e4likara, Maria Henriksdotter",
"V\u00e4lkki, N Persdotter",
"V\u00e4lkki, Olof Nilsson",
"V\u00e4lkky, Maria Henrichsdotter",
"Welling, Catharina Olofsdotter",
"Wikar, Hans Hansson",
"Wikar, Magdalena Hansdotter",
"Williams, Arthur Oliver",
"Williams, John Ellis",
"Williams, Otto Albert",
"Williams, Rudolf Toivo",
"Williams, Wells Eldon",
"Wilsten, Carl",
"Wilsten, Carl",
"Wilsten, Susanna Carlsdotter",
"Wolffelt, Ebba Juliana",
"Ylinen, Maria Samuelsdotter",
"Ylinen, Samuel Mattsson",
"Ylti\u00e4, Leena Tuomaantyt\u00e4r",
"Ylti\u00e4, Thomas Sigfredsson",
"Yl\u00e4-H\u00e4kkinen, Erich Mattsson",
"Yl\u00e4-H\u00e4kkinen, Gabriel J\u00f6ransson",
"Yl\u00e4-H\u00e4kkinen, J\u00f6ran Eriksson",
"Yl\u00e4-H\u00e4kkinen, Lisa Gabrielsdotter",
"Yl\u00e4-Nikkil\u00e4, Johanna Heikintyt\u00e4r",
"Yrj\u00f6l\u00e4, Amanda Mathilda Erkintyt\u00e4r",
"Yrj\u00f6l\u00e4, Anna J\u00f6ransdotter",
"Yrj\u00f6l\u00e4, Carl Henrik Yrj\u00f6npoika",
"Yrj\u00f6l\u00e4, J\u00f6ran J\u00f6ransson",
"Yrj\u00f6l\u00e4, J\u00f6ran M\u00e5rtensson",
"\u00c4hrlig, Anna",
"\u00c4ij\u00f6, Anna",
"\u00c4ij\u00f6, Anna Christersdotter",
"\u00c4ij\u00f6, Christer",
"\u00c4ij\u00f6, Helena Johansdotter",
"\u00c4ij\u00f6, J\u00f6ran Christersson",
"\u00c4ij\u00f6, Maria",
"\u00c4ij\u00f6, Maria J\u00f6ransdotter",
"\u00c4ij\u00f6, Maria Thomasdotter",
"\u00c4ij\u00f6, Simon J\u00f6ransson",
"\u00c4ij\u00f6, Walborg Simonsdotter",
"\u00c4nkk\u00e4, Maria Ericsdotter"
]
Dwr.ScriptLoaded('dwr_db_I_short_name_0.js');
