// This file is generated

P_name_0 = [
"115 East Nelson Street, Cadillac, Wexford County, Michigan, USA",
"Aakkola, Orivesi, Suomi",
"Aitolahti, Tampere, Suomi",
"Akaa, Suomi",
"Ala-Hinkkalan ratsutila, Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"Ala-Jaarila, H\u00f6ytee, Juupajoki, Suomi",
"Ala-Kerkkolan ratsutila, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Ala-Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ala-Mella, Patala, J\u00e4ms\u00e4, Suomi",
"Ala-Mononen, Monoskyl\u00e4, Virrat, Suomi",
"Ala-Rekola, Vierel\u00e4, Tervala, J\u00e4ms\u00e4, Suomi",
"Ala-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alakangas, Pihlaisto, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Alakyl\u00e4n ryhm\u00e4kyl\u00e4, Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alanen, Porvola, Juupajoki, Suomi",
"Alanen, Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alankomaat",
"Alapuusti, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Alasjoen kartano, Tavastila, Mietoinen, Myn\u00e4m\u00e4ki, Suomi",
"Alavus, Suomi",
"Alhaisten rustholli, Porras, Hauho, H\u00e4meenlinna, Suomi",
"Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Alhon ratsutila, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Ali-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Aln\u00e4s, Ritvala, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Ammattienedist\u00e4mislaitos, Helsinki, Suomi",
"Ampiala, Keuruu, Suomi",
"Annila, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Antrea, Luovutettu Karjala",
"Anttila, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Anttila, Hoivala, H\u00f6ytee, Juupajoki, Suomi",
"Anttila, Korvenkyl\u00e4, J\u00e4ms\u00e4, Suomi",
"Anttila, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"Anttula, Kuhmoinen, Suomi",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"Apilakoski, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Arkansas, USA",
"Arvaja, J\u00e4ms\u00e4, Suomi",
"Arvassalo, Kalanti, Uusikaupunki, Suomi",
"Aseme, Honkala, J\u00e4ms\u00e4, Suomi",
"Askainen, Masku, Suomi",
"Asunta, Keuruu, Suomi",
"Attila, Orivesi, Suomi",
"Autio, Rajalahti, Ruovesi, Suomi",
"Auttoinen, Padasjoki, Suomi",
"Auvila, J\u00e4ms\u00e4, Suomi",
"Avondale, Evart, Osceola County, Michigan, USA",
"Berrien County, Michigan, USA",
"Borgby, Sipoo, Suomi",
"Boston, Suffolk County, Massachusetts, USA",
"Br\u00f6dtorp, Pohja, Raasepori, Suomi",
"B\u00f6le, Kemi\u00f6, Kemi\u00f6nsaari, Suomi",
"Cadillac High School, Cadillac, Wexford County, Michigan, USA",
"Cadillac, Wexford County, Michigan, USA",
"Cherry Valley Cemetery, Hartwick Township, Osceola County, Michigan, USA",
"Coady Cemetery, Maple Valley Township, Montcalm County, Michigan, USA",
"Das askanische Herzogtum Sachsen, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"D\u00f6nsby, Karjaa, Raasepori, Suomi",
"East Lansing, Ingham County, Michigan, USA",
"Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"Edessalo, Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"Eerola, Keij\u00e4rvi, Yl\u00f6j\u00e4rvi, Suomi",
"Eerola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Eerola, Uuhiniemi, Orivesi, Suomi",
"Ehikki, Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Ekonen, J\u00e4ms\u00e4, Suomi",
"Elkins, Washington County, Arkansas, USA",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkuan kansakoulu, Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Er\u00e4slahti, Orivesi, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Hauhon kirkonkyl\u00e4, Hauho, H\u00e4meenlinna, Suomi",
"Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Eskola, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Eskola, Vehkalahti, Orivesi, Suomi",
"Espoo, Suomi",
"Eura, Suomi",
"European Theater of Operations, United States Army, Sotilasorganisaatiot",
"Evart, Osceola County, Michigan, USA",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Finnil\u00e4, Maakeski, Padasjoki, Suomi",
"Forsby, Uudenkaarlepyyn maalaiskunta, Uusikaarlepyy, Suomi",
"Foutila, Sauvo, Suomi",
"G.A. Serlachius Oy, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Gamla konungsg\u00e5rden, Porvoo, Suomi",
"Gammelby, Pernaja, Loviisa, Suomi",
"Gesterby, Sipoo, Suomi",
"Grand Rapids, Kent County, Michigan, USA",
"G\u00f6teborg, Ruotsi",
"Haapajoki, Moiskala, J\u00e4ms\u00e4, Suomi",
"Haapam\u00e4ki, Keuruu, Suomi",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haavisto, Orivesi, Suomi",
"Hahkala, J\u00e4ms\u00e4, Suomi",
"Haitermaa, Sakkola, Luovutettu Karjala",
"Hakola, Ruhala, Ruovesi, Suomi",
"Hakolahti, Urjala, Suomi",
"Halikko, Salo, Suomi",
"Haljala, Puukkoinen, Kuhmoinen, Suomi",
"Halli, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Hallin varuskunta, Halli, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Hallinpenkki, Halli, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Halolanm\u00e4en kansakoulu, Halolanm\u00e4ki, Suonenjoki, Suomi",
"Halolanm\u00e4ki, Suonenjoki, Suomi",
"Hamina, Suomi",
"Hampaala, Pakkala, Sahalahti, Kangasala, Suomi",
"Hanho, Ruovesi, Suomi",
"Hankala, Hy\u00f6m\u00e4ki, Hauho, H\u00e4meenlinna, Suomi",
"Hankavesi, \u00c4ht\u00e4ri, Suomi",
"Hankom\u00e4ki, Hankavesi, \u00c4ht\u00e4ri, Suomi",
"Hannila, Antrea, Luovutettu Karjala",
"Hanninen, Hannila, Antrea, Luovutettu Karjala",
"Hannola, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Hannukkala, Hiitola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Hardus, Moiskala, J\u00e4ms\u00e4, Suomi",
"Harjumaa, Viro",
"Harola, Talviainen, Orivesi, Suomi",
"Hartwick Township, Osceola County, Michigan, USA",
"Hassi, Hassi, J\u00e4ms\u00e4, Suomi",
"Hassi, J\u00e4ms\u00e4, Suomi",
"Hatakkala, Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Hattula, Muolaa, Luovutettu Karjala",
"Hattula, Suomi",
"Hatula, Antrea, Luovutettu Karjala",
"Hauhala, Sorola, Kangasala, Suomi",
"Hauho, H\u00e4meenlinna, Suomi",
"Hauhon kirkonkyl\u00e4, Hauho, H\u00e4meenlinna, Suomi",
"Hauhon seurakunta, Suomen ev.lut. kirkko",
"Haukila, Valkeakoski, Suomi",
"Haukkavaara, Hiitola, Luovutettu Karjala",
"Hauta alttarin alla, Pirkkalan kirkko, Pirkkala, Suomi",
"Hauta kirkkomaan ensimm\u00e4isess\u00e4 osassa, L\u00e4ngelm\u00e4en kirkko, Orivesi, Suomi",
"Hauta kirkon alla, J\u00e4ms\u00e4n kirkko, J\u00e4ms\u00e4, Suomi",
"Hauta kirkon alla, Kangasalan kirkko, Kangasala, Suomi",
"Hauta kirkon alla, Keuruun kirkko, Keuruu, Suomi",
"Hauta kirkon alla, Kuhmalahden kirkko, Kuhmalahti, Kangasala, Suomi",
"Hauta kirkon alla, Kuhmoisten kirkko, Kuhmoinen, Suomi",
"Hauta kirkon alla, Kuoreven kirkko, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Hauta kirkon alla, L\u00e4ngelm\u00e4en kirkko, Orivesi, Suomi",
"Hauta kirkon alla, Messukyl\u00e4n kirkko, Messukyl\u00e4, Tampere, Suomi",
"Hauta kirkon alla, Muolaan kirkko, Muolaa, Luovutettu Karjala",
"Hauta kirkon alla, Oriveden kirkko, Oriveden kyl\u00e4, Orivesi, Suomi",
"Hauta kirkon alla, Padasjoen kirkko, Padasjoki, Suomi",
"Hauta kirkon alla, Pet\u00e4j\u00e4veden kirkko, Pet\u00e4j\u00e4vesi, Suomi",
"Hauta kirkon alla, Pirkkalan kirkko, Pirkkala, Suomi",
"Hauta kirkon alla, P\u00e4lk\u00e4neen vanha kirkko, P\u00e4lk\u00e4ne, Suomi",
"Hauta kirkon alla, Ruoveden kirkko, Ritoniemi, Ruovesi, Suomi",
"Hauta kirkon alla, Saarij\u00e4rven kirkko, Saarij\u00e4rvi, Suomi",
"Hauta kirkon alla, Sahalahden kirkko, Sahalahti, Kangasala, Suomi",
"Hauta kirkon alla, Urjalan kirkko, Urjala, Suomi",
"Hauta kirkon eteisess\u00e4, Messukyl\u00e4n kirkko, Messukyl\u00e4, Tampere, Suomi",
"Hauta kirkon eteisess\u00e4, Sakkolan kirkko, Sakkola, Luovutettu Karjala",
"Hauta kirkossa, J\u00e4ms\u00e4n kirkko, J\u00e4ms\u00e4, Suomi",
"Hauta kirkossa, Keuruun kirkko, Keuruu, Suomi",
"Hauta kirkossa, Kuhmalahden kirkko, Kuhmalahti, Kangasala, Suomi",
"Hauta kirkossa, Kuhmoisten kirkko, Kuhmoinen, Suomi",
"Hauta kirkossa, Messukyl\u00e4n kirkko, Messukyl\u00e4, Tampere, Suomi",
"Hauta kirkossa, Padasjoen kirkko, Padasjoki, Suomi",
"Hauta kirkossa, Paraisten kirkko, Parainen, Suomi",
"Hauta kirkossa, P\u00e4lk\u00e4neen vanha kirkko, P\u00e4lk\u00e4ne, Suomi",
"Hauta kirkossa, Sakkolan kirkko, Sakkola, Luovutettu Karjala",
"Hauta kirkossa, Sauvon kirkko, Sauvo, Suomi",
"Hauta kirkossa, Sipoon kirkko, Sipoo, Suomi",
"Hauta kirkossa, Urjalan kirkko, Urjala, Suomi",
"Hauta kirkossa, Vetelin kirkko, Veteli, Suomi",
"Hautam\u00e4ki, Salokunta, Juupajoki, Suomi",
"Hautaniemi, Putula, Alavus, Suomi",
"Heikkil\u00e4, Aakkola, Orivesi, Suomi",
"Heikkil\u00e4, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Heikkil\u00e4, J\u00e4hdyspohja, Virrat, Suomi",
"Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Heikkil\u00e4, Naappila, Orivesi, Suomi",
"Heikkil\u00e4, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Heikkil\u00e4, Seppola, J\u00e4ms\u00e4, Suomi",
"Heikkil\u00e4n rustholli, Huhti, Urjala, Suomi",
"Heikkil\u00e4n rustholli, Tuittula, Hauho, H\u00e4meenlinna, Suomi",
"Heikkil\u00e4n tila, Heikkil\u00e4, Seppola, J\u00e4ms\u00e4, Suomi",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"Heikurila, Heinjoki, Luovutettu Karjala",
"Heinjoen tilattomat, Heinjoki, Heinjoki, Luovutettu Karjala",
"Heinjoki, Heinjoki, Luovutettu Karjala",
"Heinjoki, Luovutettu Karjala",
"Heinsaari, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Hein\u00e4vehmas torp., Luomaj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Helg\u00e5 kungsg\u00e5rd, Perni\u00f6, Salo, Suomi",
"Helsingin yliopisto, Helsinki, Suomi",
"Helsinki, Suomi",
"Henkikomppania, Pohjanmaan jalkav\u00e4kirykmentti, Sotilasorganisaatiot",
"Heponiemi, Kangasala, Suomi",
"Hiirsalakka, Penttil\u00e4, J\u00e4\u00e4ski, Luovutettu Karjala",
"Hiitola, Luovutettu Karjala",
"Hinkkala, Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"Hinthaara, Porvoo, Suomi",
"Hirsivalkama, Kalhola, Kaukola, Kuhmoinen, Suomi",
"Hirvel\u00e4, Valkealuomi, J\u00e4ms\u00e4, Suomi",
"Hirvij\u00e4rvi, Juupajoki, Suomi",
"Hiukkaa, J\u00e4ms\u00e4, Suomi",
"Hoivala, H\u00f6ytee, Juupajoki, Suomi",
"Hoivala, Orivesi, Suomi",
"Hoivala, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Hokka, Auttoinen, Padasjoki, Suomi",
"Hokkanen, Asunta, Keuruu, Suomi",
"Hollolan kihlakunta, Suomi",
"Holma, Orivesi, Suomi",
"Holma, Ulvila, Suomi",
"Holmala, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Holman kartano, Holma, Orivesi, Suomi",
"Honkala, J\u00e4ms\u00e4, Suomi",
"Honkala, Seppola, J\u00e4ms\u00e4, Suomi",
"Honkola, Urjala, Suomi",
"Honkolan s\u00e4teriratsutila, Honkola, Urjala, Suomi",
"Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Hoskari, Pohjoislahti, Keuruu, Suomi",
"Hovila, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Huhti, Rautu, Luovutettu Karjala",
"Huhti, Urjala, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huittinen, Suomi",
"Huittula, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"Hulipas, Juupajoki, Suomi",
"Humppila, Suomi",
"Huntila, P\u00e4lk\u00e4ne, Suomi",
"Huntilan rustholli, Huntila, P\u00e4lk\u00e4ne, Suomi",
"Huovila, V\u00e4lkkil\u00e4, Urjala, Suomi",
"Hurttala, Hattula, Suomi",
"Huurretie 5, Julkuj\u00e4rvi, Yl\u00f6j\u00e4rvi, Suomi",
"Hyhky, Tampere, Suomi",
"Hypp\u00f6l\u00e4, Nurmij\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Hyrkk\u00f6l\u00e4, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Hyrkk\u00f6l\u00e4, Valkiala, Kuhmoinen, Suomi",
"Hyvink\u00e4\u00e4, Suomi",
"Hyv\u00f6l\u00e4, Ouluvesi, \u00c4ht\u00e4ri, Suomi",
"Hyyryl\u00e4, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Hy\u00f6m\u00e4ki, Hauho, H\u00e4meenlinna, Suomi",
"H\u00e4kkinen, Suolahti, Keuruu, Suomi",
"H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"H\u00e4meen historiallinen maakunta, Suomi",
"H\u00e4meen l\u00e4\u00e4nin jalkav\u00e4kirykmentti, Sotilasorganisaatiot",
"H\u00e4meenkyr\u00f6, Suomi",
"H\u00e4meenlinna, Suomi",
"H\u00e4meenlinnan triviaalikoulu, H\u00e4meenlinna, Suomi",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"H\u00e4nn\u00e4ri, Hyhky, Tampere, Suomi",
"H\u00e4yskynvaara, Ruskeala, Luovutettu Karjala",
"H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"H\u00f6ytee, Juupajoki, Suomi",
"Ihantala, Viipurin maalaiskunta, Luovutettu Karjala",
"Iitin seurakunta, Suomen ev.lut. kirkko",
"Iitti, Suomi",
"Ikaala, Urjala, Suomi",
"Ikaalan rustholli, Ikaala, Urjala, Suomi",
"Ikaalinen, Suomi",
"Ilmajoen komppania, Pohjanmaan jalkav\u00e4kirykmentti, Sotilasorganisaatiot",
"Ilola torp., Kerkkola, J\u00e4ms\u00e4, Suomi",
"Ilola, Muolaa, Luovutettu Karjala",
"Ilola, Sahalahti, Kangasala, Suomi",
"Ingham County, Michigan, USA",
"Inkeri, Ven\u00e4j\u00e4",
"Innil\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Isn\u00e4s, Pernaja, Loviisa, Suomi",
"Iso Alho Norola, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Iso-Attila, Attila, Orivesi, Suomi",
"Iso-Heikkil\u00e4, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Iso-K\u00f6lli, Kopsamo, Juupajoki, Suomi",
"Isoj\u00e4rvi, Multia, Suomi",
"Isokyr\u00f6, Suomi",
"Isoniemi, Kokkila, Juupajoki, Suomi",
"Isotalo, H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"Isotalo, Laitila, Suomi",
"Itko, Saarioispuoli, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Ivaskansaari, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaakkola, Naappila, Orivesi, Suomi",
"Jaakkola, Pohja, Kuhmalahti, Kangasala, Suomi",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaarila, H\u00f6ytee, Juupajoki, Suomi",
"Jaarlan rustholli, Jaarila, H\u00f6ytee, Juupajoki, Suomi",
"Jaatila, J\u00e4ms\u00e4, Suomi",
"Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Jakari, Porvoo, Suomi",
"Jennings, Lake Township, Missaukee County, Michigan, USA",
"Joensuu, Joensuu, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Joensuu, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Joensuun kartano, Halikko, Salo, Suomi",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"Jokela, Partala torp., Jokioinen, J\u00e4ms\u00e4, Suomi",
"Jokihaara, Kopsamo, Juupajoki, Suomi",
"Jokioinen, J\u00e4ms\u00e4, Suomi",
"Julkuj\u00e4rvi, Yl\u00f6j\u00e4rvi, Suomi",
"Juokslahti, J\u00e4ms\u00e4, Suomi",
"Jussila, Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Jussila, Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Jussila, Rautio, Sahalahti, Kangasala, Suomi",
"Jussila, Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Jutikkala, Jutikkala, Saarioispuoli, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Jutikkala, Saarioispuoli, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Juupajoki, Suomi",
"Jyv\u00e4skyl\u00e4, Suomi",
"Jyv\u00e4skyl\u00e4n lyseo, Jyv\u00e4skyl\u00e4, Suomi",
"Jyv\u00e4skyl\u00e4n maalaiskunta, Jyv\u00e4skyl\u00e4, Suomi",
"J\u00e4hdyspohja, Virrat, Suomi",
"J\u00e4ms\u00e4, Suomi",
"J\u00e4ms\u00e4n kirkko, J\u00e4ms\u00e4, Suomi",
"J\u00e4ms\u00e4n seurakunta, Suomen ev.lut. kirkko",
"J\u00e4ms\u00e4nkoski, J\u00e4ms\u00e4, Suomi",
"J\u00e4rvenp\u00e4\u00e4, Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"J\u00e4rvenp\u00e4\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"J\u00e4rvensivu, Tampere, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"J\u00e4\u00e4k\u00e4ritykist\u00f6rykmentti, Sotilasorganisaatiot",
"J\u00e4\u00e4sken kirkkomaa, J\u00e4\u00e4ski, Luovutettu Karjala",
"J\u00e4\u00e4ski, Luovutettu Karjala",
"Kaarina, Suomi",
"Kaarlahti, Kaukola, Luovutettu Karjala",
"Kaarlela, Kokkola, Suomi",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kaipola, J\u00e4ms\u00e4, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kajaanin sissipataljoona, Sotilasorganisaatiot",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kalanti, Uusikaupunki, Suomi",
"Kalhola, Kaukola, Kuhmoinen, Suomi",
"Kallio, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Kallioj\u00e4rvi torp., Rauhalahti, Kuhmoinen, Suomi",
"Kalliolampi, Myllym\u00e4ki, \u00c4ht\u00e4ri, Suomi",
"Kalliom\u00e4ki, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kangasala, Suomi",
"Kangasalan kirkko, Kangasala, Suomi",
"Kangasalan seurakunta, Suomen ev.lut. kirkko",
"Kangasalan vanha hautausmaa, Kangasala, Suomi",
"Kangasniemi, Suomi",
"Kankaisten kartano, Masku, Suomi",
"Kantala, Ruhala, Ruovesi, Suomi",
"Karhola, Sakkola, Luovutettu Karjala",
"Karikko, Pet\u00e4j\u00e4vesi, Suomi",
"Karjaa, Raasepori, Suomi",
"Karjalohja, Lohja, Suomi",
"Karjula, Kuru, Yl\u00f6j\u00e4rvi, Suomi",
"Karkeala, Valkj\u00e4rvi",
"Karkku, Vammala, Sastamala, Suomi",
"Karonen, R\u00e4ih\u00e4ranta, Vuoksela, Luovutettu Karjala",
"Karppilan rustholli, Kokko, Urjala, Suomi",
"Karttiala, Tursola, Kangasala, Suomi",
"Karuna, Sauvo, Suomi",
"Karvia, Kyl\u00e4noja, Orivesi, Suomi",
"Karvia, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Kaskaala, Rautu, Luovutettu Karjala",
"Kaskinen, Mietoinen, Myn\u00e4m\u00e4ki, Suomi",
"Kastelholman linna, Sund, Suomi",
"Katila, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Katinala, Hattula, Suomi",
"Kattelus, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Kauhkiala, J\u00e4ms\u00e4, Suomi",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Kaukola, Kuhmoinen, Suomi",
"Kaukola, Luovutettu Karjala",
"Kaukola, Niemola, J\u00e4ms\u00e4, Suomi",
"Kaukolan Hukki-Nihtil\u00e4, Kaukola, Kuhmoinen, Suomi",
"Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Kaustala, Katinala, Hattula, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kavantsaari, Antrea, Luovutettu Karjala",
"Kawandsari samtaliga torpare, Kavantsaari, Antrea, Luovutettu Karjala",
"Keij\u00e4rvi, Yl\u00f6j\u00e4rvi, Suomi",
"Keikkala, Tapiala, Kuhmoinen, Suomi",
"Keitelepohja, Viitasaari, Suomi",
"Kekkonen, Ruovesi, Suomi",
"Kelh\u00e4n pappila, Seppola, J\u00e4ms\u00e4, Suomi",
"Kelja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kelja, Sakkola, Luovutettu Karjala",
"Kellari, Kopsamo, Juupajoki, Suomi",
"Kemi\u00f6, Kemi\u00f6nsaari, Suomi",
"Kemi\u00f6nsaari, Suomi",
"Kemppil\u00e4, Antrea, Luovutettu Karjala",
"Kemppinen, Kontu, J\u00e4\u00e4ski, Luovutettu Karjala",
"Kent County, Michigan, USA",
"Keppil\u00e4n rustholli, Laukeela, Urjala, Suomi",
"Kerkkola-Koski -ratsutila, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Kerkkola, J\u00e4ms\u00e4, Suomi",
"Kerppola, Kangasala, Suomi",
"Kerppolan sukuhauta, Kangasalan vanha hautausmaa, Kangasala, Suomi",
"Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kerttula, Raisio, Suomi",
"Keskinen, Honkala, Seppola, J\u00e4ms\u00e4, Suomi",
"Keskinen, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Ketarsalmi, Taivassalo, Suomi",
"Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Keuruu, Suomi",
"Keuruun kirkko, Keuruu, Suomi",
"Keuruun seurakunta, Suomen ev.lut. kirkko",
"Kienala, Niemola, J\u00e4ms\u00e4, Suomi",
"Kierros, Vehkoo, Multia, Suomi",
"Kihlala, Juupajoki, Suomi",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiiskil\u00e4, Hassi, J\u00e4ms\u00e4, Suomi",
"Kiiverinnotko, Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kilpola, Hiitola, Luovutettu Karjala",
"Kinnil\u00e4, Rouhiala, J\u00e4\u00e4ski, Luovutettu Karjala",
"Kirkkoj\u00e4rvi, Uusikirkko Vpl, Luovutettu Karjala",
"Kirkniemi, Lohja, Suomi",
"Kirkonkyl\u00e4n koulu, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kirkonm\u00e4ki, Keuruu, Suomi",
"Kirsta, Ritoniemi, Ruovesi, Suomi",
"Kirvu, Luovutettu Karjala",
"Kiukoila, Lopotti, J\u00e4ms\u00e4, Suomi",
"Kiurula, J\u00e4\u00e4ski, Luovutettu Karjala",
"Kivel\u00e4, Partala torp., Jokioinen, J\u00e4ms\u00e4, Suomi",
"Kivij\u00e4rvi, Suolahti, Keuruu, Suomi",
"Kiviniemi, Sakkola, Luovutettu Karjala",
"Kivioja, Hassi, J\u00e4ms\u00e4, Suomi",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Knapsby, Karjaa, Raasepori, Suomi",
"Knuutila, Er\u00e4slahti, Orivesi, Suomi",
"Koivisto, Humppila, Suomi",
"Koivisto, Sukkila, Juupajoki, Suomi",
"Koivuniemi, Orivesi, Suomi",
"Kokkila, Juupajoki, Suomi",
"Kokko, Urjala, Suomi",
"Kokkola, Suomi",
"Kokkolan Kappatehdas, Kokkola, Suomi",
"Kolehma, Simsi\u00f6, Pihlajavesi, Keuruu, Suomi",
"Kolehmam\u00e4ki, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"Kolhi, Kolhi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kolhi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kolhi, Savo, Orivesi, Suomi",
"Kolho, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Koljonen, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Koljonkanta eli Solala, Orivesi, Suomi",
"Konkari, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kontiolahti, Ruskeala, Luovutettu Karjala",
"Kontti, Oriveden kyl\u00e4, Orivesi, Suomi",
"Kontu, Antrea, Luovutettu Karjala",
"Kontu, J\u00e4\u00e4ski, Luovutettu Karjala",
"Kopola, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Koprala, Heinjoki, Luovutettu Karjala",
"Kopsala, Hiitola, Luovutettu Karjala",
"Kopsamo, Juupajoki, Suomi",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korpi, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Korpilahti, Jyv\u00e4skyl\u00e4, Suomi",
"Korppila, \u00c4k\u00e4m\u00e4ki, Kuhmoinen, Suomi",
"Korpula, Korpula, Ruovesi, Suomi",
"Korpula, Ruovesi, Suomi",
"Kortesuo, Kokkila, Juupajoki, Suomi",
"Korvenkyl\u00e4, J\u00e4ms\u00e4, Suomi",
"Kosela, Mets\u00e4pirtti, Luovutettu Karjala",
"Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Koski, Kaarina, Suomi",
"Koski, Karjula, Kuru, Yl\u00f6j\u00e4rvi, Suomi",
"Koski, Karkku, Vammala, Sastamala, Suomi",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kotaj\u00e4rvi, Kuhmoinen, Suomi",
"Kottila, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Kottila, Kiviniemi, Sakkola, Luovutettu Karjala",
"Koukunniemi, Mets\u00e4pirtti, Luovutettu Karjala",
"Kourum\u00e4ki, Multia, Suomi",
"Kruunupyy, Suomi",
"Kuhmalahden kirkko, Kuhmalahti, Kangasala, Suomi",
"Kuhmalahti, Kangasala, Suomi",
"Kuhmoinen, Suomi",
"Kuhmoisten kirkko, Kuhmoinen, Suomi",
"Kuhmoisten seurakunta, Suomen ev.lut. kirkko",
"Kuikka, S\u00e4yryl\u00e4, J\u00e4ms\u00e4, Suomi",
"Kuitia, Parainen, Suomi",
"Kuitula, Kuitulanper\u00e4, Pet\u00e4j\u00e4vesi, Suomi",
"Kuitulanper\u00e4, Pet\u00e4j\u00e4vesi, Suomi",
"Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kukkula, Nikkil\u00e4, Haavisto, Orivesi, Suomi",
"Kulho, Turku, Suomi",
"Kulkas, Sorila, Aitolahti, Tampere, Suomi",
"Kultanen, Hattula, Muolaa, Luovutettu Karjala",
"Kumalax, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kuninkaanristi, Vuoksela, Luovutettu Karjala",
"Kuninkaanselk\u00e4, Rautu, Luovutettu Karjala",
"Kunnianiemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kuokkala, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Kuoksj\u00e4rvi, Hiitola, Luovutettu Karjala",
"Kuoreniemi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuoreveden kunta, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuoreveden seurakunta, Suomen ev.lut. kirkko",
"Kuoreven kirkko, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kurikka, Kavantsaari, Antrea, Luovutettu Karjala",
"Kurkela, Ikaalinen, Suomi",
"Kurkela, Nurmii, Muolaa, Luovutettu Karjala",
"Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Kurra, Pitk\u00e4nen, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuru, Yl\u00f6j\u00e4rvi, Suomi",
"Kurvila, Heinjoki, Luovutettu Karjala",
"Kutinlahti, Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"Kuukkaj\u00e4rvi, Uurainen, Suomi",
"Kuunjoen V\u00e4\u00e4r\u00e4koski, Kirvu, Luovutettu Karjala",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Kuusj\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuusj\u00e4rvi, Kuusj\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuuttila, Savilahti - Pohjankyl\u00e4, Antrea, Luovutettu Karjala",
"Kylm\u00e4melli, Melli, Juupajoki, Suomi",
"Kyl\u00e4noja, Orivesi, Suomi",
"Kyrkstad, Lohja, Suomi",
"Kytt\u00e4l\u00e4, Tampere, Suomi",
"K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"K\u00e4kisalmen maaseurakunta, Suomen ev.lut. kirkko",
"K\u00e4kisalmi, Luovutettu Karjala",
"K\u00e4rjenniemi, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"K\u00e4rkniemi, Karuna, Sauvo, Suomi",
"K\u00e4\u00e4ntym\u00e4, Heinjoki, Luovutettu Karjala",
"K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"K\u00f6nkk\u00f6l\u00e4, Seppola, J\u00e4ms\u00e4, Suomi",
"K\u00f6ntt\u00e4ri, Suolahti, Keuruu, Suomi",
"K\u00f6yk\u00e4np\u00e4\u00e4, Holma, Orivesi, Suomi",
"K\u00f6yr\u00e4, Kangasala, Suomi",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Laalahti, Aitolahti, Tampere, Suomi",
"Laalahti, Laalahti, Aitolahti, Tampere, Suomi",
"Laasola, Orivesi, Suomi",
"Lahnajoki, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Lahti, Suomi",
"Laitila, Suomi",
"Lake City, Missaukee County, Michigan, USA",
"Lake Township, Missaukee County, Michigan, USA",
"Lamberg, Kiviniemi, Sakkola, Luovutettu Karjala",
"Lammi, H\u00e4meenlinna, Suomi",
"Lankinen, Rauralaniemi, Hiitola, Luovutettu Karjala",
"Lankkua, Suolahti, Keuruu, Suomi",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"Lappi, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Larjava, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Lassila, Pajuskyl\u00e4, Ruovesi, Suomi",
"Laukeela, Urjala, Suomi",
"Laurila, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Lavia, Pori, Suomi",
"Lempaala, Inkeri, Ven\u00e4j\u00e4",
"Lemp\u00e4\u00e4l\u00e4, Suomi",
"Lemp\u00e4\u00e4l\u00e4n seurakunta, Suomen ev.lut. kirkko",
"Lemu, Masku, Suomi",
"Lepist\u00f6, Myn\u00e4m\u00e4ki, Suomi",
"Lepp\u00e4j\u00e4rvi, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"Liesniemi, Sauvo, Suomi",
"Liettu, Niemenkyl\u00e4, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Lihasula, Kangasala, Suomi",
"Liivinmaa, Ven\u00e4j\u00e4",
"Lillby, Sauvo, Suomi",
"Linkka, Kirkkoj\u00e4rvi, Uusikirkko Vpl, Luovutettu Karjala",
"Lintulan rustholli, Paalila, Kangasala, Suomi",
"Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Lippainmaa, Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Litslena socken, Uppland, Ruotsi",
"Liuksiala, Kangasala, Suomi",
"Liuksialan kartano, Liuksiala, Kangasala, Suomi",
"Liuttula, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Liuttulan ratsutila, Liuttula, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Lohijoki, Sakkola, Luovutettu Karjala",
"Lohja, Suomi",
"Loila, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Loimaa, Suomi",
"Loimaan kotiteollisuuskoulu, Loimaa, Suomi",
"Loponen, Lapinlahti, Sakkola, Luovutettu Karjala",
"Lopotti, J\u00e4ms\u00e4, Suomi",
"Lotta Sv\u00e4rd maanpuolustusty\u00f6n tukij\u00e4rjest\u00f6, Suomi",
"Lottola, Antrea, Luovutettu Karjala",
"Loviisa, Suomi",
"Lukkari, Tapiala, Kuhmoinen, Suomi",
"Luomaj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Luotsanlahti, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Luovutettu Karjala",
"Lupra, Sakkola, Luovutettu Karjala",
"Lvov, Ukraina",
"Lylyj\u00e4rvi, Juupajoki, Suomi",
"Lyykyl\u00e4nj\u00e4rvi, Viipurin maalaiskunta, Luovutettu Karjala",
"Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"Ly\u00f6ttil\u00e4, Iitti, Suomi",
"L\u00e5ngbergs\u00f6da, Saltvik, Suomi",
"L\u00e5ngila, R\u00e4yrinki, Veteli, Suomi",
"L\u00e4hteenoja, Eura, Suomi",
"L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"L\u00e4ngelm\u00e4en kirkko, Orivesi, Suomi",
"L\u00e4ngelm\u00e4en seurakunta, Suomen ev.lut. kirkko",
"L\u00e4ngelm\u00e4ki, Suomi",
"L\u00e4stil\u00e4, Kuhmoinen, Suomi",
"L\u00e4tin ratsutila, Myllykyl\u00e4, Sammatti, Lohja, Suomi",
"L\u00e4ttil\u00e4, Tapiala, Kuhmoinen, Suomi",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"L\u00f6yt\u00e4n\u00e4, Teisko, Tampere, Suomi",
"Maakeski, Padasjoki, Suomi",
"Maarian seurakunta, Suomen ev.lut. kirkko",
"Maastricht, Alankomaat",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Makkola, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Mannila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Manninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Manniskyl\u00e4, Pohjoislahti, Keuruu, Suomi",
"Manskivi, Luomaj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Maple Hill Cemetery, Cadillac, Wexford County, Michigan, USA",
"Maple Valley Township, Montcalm County, Michigan, USA",
"Markkula, Loila, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Markkula, Ruoranen, Isoj\u00e4rvi, Multia, Suomi",
"Martb\u00f6le, Sauvo, Suomi",
"Marttila, Anttula, Kuhmoinen, Suomi",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Marttinen, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Marttinen, Virrat, Suomi",
"Masku, Suomi",
"Maskun kihlakunta, Suomi",
"Massachusetts, USA",
"Massby, Sipoo, Suomi",
"Matiskala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Mattila, Hallinpenkki, Halli, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Mattila, Tursola, Kangasala, Suomi",
"Maunukkala torp., Holma, Orivesi, Suomi",
"Maunula, Kopsamo, Juupajoki, Suomi",
"Maunula, Pehula, Orivesi, Suomi",
"McKinley Elementary school, Michigan, USA",
"Mella, Patala, J\u00e4ms\u00e4, Suomi",
"Melli, Juupajoki, Suomi",
"Melli, Melli, Juupajoki, Suomi",
"Merola, Muolaa, Luovutettu Karjala",
"Messukyl\u00e4, Tampere, Suomi",
"Messukyl\u00e4n kirkko, Messukyl\u00e4, Tampere, Suomi",
"Messukyl\u00e4n seurakunta, Suomen ev.lut. kirkko",
"Mestauspaikka, Oriveden kyl\u00e4, Orivesi, Suomi",
"Mets\u00e4pirtti, Luovutettu Karjala",
"Michigan State College of Agriculture and Applied Science, Michigan, USA",
"Michigan State University, East Lansing, Ingham County, Michigan, USA",
"Michigan, USA",
"Miemola, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Mierola, Hattula, Suomi",
"Mietoinen, Myn\u00e4m\u00e4ki, Suomi",
"Miinajoki, Kaukola, Luovutettu Karjala",
"Miisua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Mikkola, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Mikkola, M\u00e4yr\u00e4, Kangasala, Suomi",
"Mikkola, Pohjoislahti, Keuruu, Suomi",
"Minkkil\u00e4, Kuukkaj\u00e4rvi, Uurainen, Suomi",
"Missaukee County, Michigan, USA",
"Moijanen, Keuruu, Suomi",
"Moiniemi, Muolaa, Luovutettu Karjala",
"Moisio, Lohja, Suomi",
"Moisio, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Moiskala, J\u00e4ms\u00e4, Suomi",
"Moksu, \u00c4ht\u00e4ri, Suomi",
"Mononen, Monoskyl\u00e4, Virrat, Suomi",
"Monoskyl\u00e4, Virrat, Suomi",
"Montcalm County, Michigan, USA",
"Mulkoila, Orivesi, Suomi",
"Mulli, Laasola, Orivesi, Suomi",
"Mullikka, Viiala, J\u00e4ms\u00e4, Suomi",
"Multia, Suomi",
"Multianniemi, Multia, Suomi",
"Muolaa, Luovutettu Karjala",
"Muolaan hovi, Muolaan kirkonkyl\u00e4, Muolaa, Luovutettu Karjala",
"Muolaan kirkko, Muolaa, Luovutettu Karjala",
"Muolaan kirkonkyl\u00e4, Muolaa, Luovutettu Karjala",
"Muolaanj\u00e4rvi, Muolaa, Luovutettu Karjala",
"Muorila, Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"Murtom\u00e4ki, Haapam\u00e4ki, Keuruu, Suomi",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Mustaj\u00e4rvi, Ruovesi, Suomi",
"Mustasuu, Orivesi, Suomi",
"Mustio, Karjaa, Raasepori, Suomi",
"Mustosenmaa, Heikurila, Heinjoki, Luovutettu Karjala",
"Muurame, Suomi",
"Muuransuo torp., Ruotsula, J\u00e4ms\u00e4, Suomi",
"Myllykyl\u00e4, Sammatti, Lohja, Suomi",
"Myllym\u00e4ki, \u00c4ht\u00e4ri, Suomi",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Myn\u00e4m\u00e4ki, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4kel\u00e4, Valkealuomi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ki-Savo, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ki-Sipi, Per\u00e4nne, \u00c4ht\u00e4ri, Suomi",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4kil\u00e4, Sahalahti, Kangasala, Suomi",
"M\u00e4lk\u00f6l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"M\u00e4nts\u00e4, Uskela, Valkeakoski, Suomi",
"M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4yr\u00e4, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"Naantali, Suomi",
"Naappila, Orivesi, Suomi",
"Narva, Viro",
"Natukka, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Nenonen, Pihlajalahti, Ruovesi, Suomi",
"Nenonen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Neuvostoliiton miehitysvy\u00f6hyke",
"Niemel\u00e4, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Niemel\u00e4, Jokioinen, J\u00e4ms\u00e4, Suomi",
"Niemel\u00e4, Tevaj\u00e4rvi, Kuhmoinen, Suomi",
"Niemen rustholli, T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"Niemenkyl\u00e4, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Niemi, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Niemi, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Nieminen, Juokslahti, J\u00e4ms\u00e4, Suomi",
"Niemisvesi, Hankavesi, \u00c4ht\u00e4ri, Suomi",
"Niemola, J\u00e4ms\u00e4, Suomi",
"Nihtil\u00e4, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Niikkula, Koivuniemi, Orivesi, Suomi",
"Niinim\u00e4ki, Patala, J\u00e4ms\u00e4, Suomi",
"Niittykatu 3, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4, Haavisto, Orivesi, Suomi",
"Nikkil\u00e4, Hiukkaa, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4n rustholli, Kokko, Urjala, Suomi",
"Niles, Berrien County, Michigan, USA",
"Nisula, Seppola, J\u00e4ms\u00e4, Suomi",
"Noisniemi, Vuoksela, Luovutettu Karjala",
"Noitermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Nokia, Suomi",
"Norola, Hassi, J\u00e4ms\u00e4, Suomi",
"Norsjoki, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Noskua, Antrea, Luovutettu Karjala",
"Nousiainen, Suomi",
"Nuottiniemi, Mustaj\u00e4rvi, Ruovesi, Suomi",
"Nurmii, Muolaa, Luovutettu Karjala",
"Nurmij\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Nurminmaa, Hatula, Antrea, Luovutettu Karjala",
"Nyyn\u00e4inen, Lemu, Masku, Suomi",
"Nyyn\u00e4isten kartano, Nyyn\u00e4inen, Lemu, Masku, Suomi",
"Nyyss\u00f6l\u00e4, \u00c4ht\u00e4ri, Suomi",
"N\u00e4ppil\u00e4, Vehkaj\u00e4rvi, Kuhmalahti, Kangasala, Suomi",
"N\u00e4rv\u00e4, Kuhmoinen, Suomi",
"N\u00e4se, Porvoo, Suomi",
"N\u00e4ttil\u00e4, Patala, J\u00e4ms\u00e4, Suomi",
"Oak Grove Cemetery, Jennings, Lake Township, Missaukee County, Michigan, USA",
"Ohtola, Kangasala, Suomi",
"Oinala, Muolaa, Luovutettu Karjala",
"Ojaniemi, Sakkola, Luovutettu Karjala",
"Ojantakanen m\u00e4kitupa, Yl\u00e4-Rekola, Vierel\u00e4, Tervala, J\u00e4ms\u00e4, Suomi",
"Okemos, Ingham County, Michigan, USA",
"Oksj\u00e4rvi, Yl\u00e4-Partala, Jokioinen, J\u00e4ms\u00e4, Suomi",
"Olkkola, Nurmij\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"Onnistaipale, Orivesi, Suomi",
"Oriveden kirkko, Oriveden kyl\u00e4, Orivesi, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"Oriveden seurakunta, Suomen ev.lut. kirkko",
"Orivesi, Suomi",
"Orjansaari, Rautu, Luovutettu Karjala",
"Orola, Muolaa, Luovutettu Karjala",
"Orola, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Osceola County, Michigan, USA",
"Osmalahti, Sauvo, Suomi",
"Ostamo, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Ottola, Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ouluvesi, \u00c4ht\u00e4ri, Suomi",
"Ouni, Ouninpohja, J\u00e4ms\u00e4, Suomi",
"Ouninpohja, J\u00e4ms\u00e4, Suomi",
"Paakkarila, Antrea, Luovutettu Karjala",
"Paalila, Kangasala, Suomi",
"Paattila, Seppola, J\u00e4ms\u00e4, Suomi",
"Paavola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Paavola, Ponsa, Kangasala, Suomi",
"Padasjoen kirkko, Padasjoki, Suomi",
"Padasjoki, Suomi",
"Padustaipale, Orivesi, Suomi",
"Pahuj\u00e4rvi torp., Alhon ratsutila, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Pajuskyl\u00e4, Ruovesi, Suomi",
"Pakkala, Sahalahti, Kangasala, Suomi",
"Pakom\u00e4ki, Yl\u00e4-Partala, Jokioinen, J\u00e4ms\u00e4, Suomi",
"Palkeala, Rautu, Luovutettu Karjala",
"Palo, Lihasula, Kangasala, Suomi",
"Palttila, Laitila, Suomi",
"Pappila, Hiukkaa, J\u00e4ms\u00e4, Suomi",
"Pappila, J\u00e4ms\u00e4, Suomi",
"Pappila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Pappila, Pirkkala, Suomi",
"Pappila, S\u00e4rkilahti, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Pappilan torpparit, Sakkola, Luovutettu Karjala",
"Pappilankulma, Ruovesi, Suomi",
"Pappinen, Lapinlahti, Sakkola, Luovutettu Karjala",
"Parainen, Suomi",
"Paraisten kirkko, Parainen, Suomi",
"Parpola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Parrinmaa, Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Partala torp., Jokioinen, J\u00e4ms\u00e4, Suomi",
"Pastoraatti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Patala ent. kapteenin virkatalo, Patala, J\u00e4ms\u00e4, Suomi",
"Patala, J\u00e4ms\u00e4, Suomi",
"Pattoinen, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pauhari, Urjalankyl\u00e4, Urjala, Suomi",
"Pehula, Orivesi, Suomi",
"Peikola, Muolaa, Luovutettu Karjala",
"Pekkala, Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Pelli, Kontu, Antrea, Luovutettu Karjala",
"Pellonper\u00e4, Kurvila, Heinjoki, Luovutettu Karjala",
"Peltola, Kaipola, J\u00e4ms\u00e4, Suomi",
"Peltola, Mustaj\u00e4rvi, Ruovesi, Suomi",
"Penttil\u00e4, Hurttala, Hattula, Suomi",
"Penttil\u00e4, J\u00e4\u00e4ski, Luovutettu Karjala",
"Perkj\u00e4rvi, Muolaa, Luovutettu Karjala",
"Pernaja, Loviisa, Suomi",
"Perni\u00f6, Salo, Suomi",
"Perttula, Kopsamo, Juupajoki, Suomi",
"Perttula, Siitama, Orivesi, Suomi",
"Perttula, Urjalankyl\u00e4, Urjala, Suomi",
"Per\u00e4nne, \u00c4ht\u00e4ri, Suomi",
"Peska, Mustaj\u00e4rvi, Ruovesi, Suomi",
"Pessi, Kaarlahti, Kaukola, Luovutettu Karjala",
"Pet\u00e4j\u00e4rvi, Sakkola, Luovutettu Karjala",
"Pet\u00e4j\u00e4veden kirkko, Pet\u00e4j\u00e4vesi, Suomi",
"Pet\u00e4j\u00e4vesi, Suomi",
"Peuraus, Miemola, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Pietil\u00e4, J\u00e4ms\u00e4, Suomi",
"Pihkala, Heinjoki, Luovutettu Karjala",
"Pihlaisto, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Pihlajalahti, Kuhmoinen, Suomi",
"Pihlajalahti, Ruovesi, Suomi",
"Pihlajaveden seurakunta, Suomen ev.lut. kirkko",
"Pihlajavesi, Keuruu, Suomi",
"Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"Piikki\u00f6, Kaarina, Suomi",
"Piikki\u00f6n seurakunta, Suomen ev.lut. kirkko",
"Pirkkala, Suomi",
"Pirkkalan kirkko, Pirkkala, Suomi",
"Pirkkalan seurakunta, Suomen ev.lut. kirkko",
"Pirttisarka rustholli, Jaarila, H\u00f6ytee, Juupajoki, Suomi",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Pitk\u00e4l\u00e4, Pihlajalahti, Ruovesi, Suomi",
"Pitk\u00e4nen, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Pohja, Kuhmalahti, Kangasala, Suomi",
"Pohja, Raasepori, Suomi",
"Pohjanmaan historiallinen maakunta, Suomi",
"Pohjanmaan jalkav\u00e4kirykmentti, Sotilasorganisaatiot",
"Pohjaslahti, Suomi",
"Pohjaslahti, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Pohjois-Suomen laamannikunta, Suomi",
"Pohjoislahti, Keuruu, Suomi",
"Poikko, Rym\u00e4ttyl\u00e4, Naantali, Suomi",
"Ponsa, Kangasala, Suomi",
"Pori, Suomi",
"Porin l\u00e4\u00e4nin jalkav\u00e4kirykmentti, Sotilasorganisaatiot",
"Porkkala, Lammi, H\u00e4meenlinna, Suomi",
"Porras, Hauho, H\u00e4meenlinna, Suomi",
"Porvola, Juupajoki, Suomi",
"Porvoo, Suomi",
"Porvoon hiippakunnan tuomiokapituli, Porvoon hiippakunta, Suomen ev.lut. kirkko",
"Porvoon hiippakunta, Suomen ev.lut. kirkko",
"Posti, Loila, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Preussin kuningaskunta, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Puharila, Orivesi, Suomi",
"Puikkoinen, Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pulkkinen, Veteli, Suomi",
"Pullinen, Valkj\u00e4rvi, Sakkola, Luovutettu Karjala",
"Punnus, Muolaa, Luovutettu Karjala",
"Puolustuslaitos, Suomi",
"Puotunen, Nousiainen, Suomi",
"Purpua, Haparainen, Sakkola, Luovutettu Karjala",
"Puttola, Honkala, Seppola, J\u00e4ms\u00e4, Suomi",
"Putula, Alavus, Suomi",
"Puukkoinen, Kuhmoinen, Suomi",
"Puusti, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Pyht\u00e4\u00e4, Suomi",
"Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Pyh\u00e4j\u00e4rven (Vpl) seurakunta, Suomen ev.lut. kirkko",
"Pyh\u00e4j\u00e4rven kirkkomaa, Pyh\u00e4j\u00e4rven kirkonkyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rven kirkonkyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyk\u00e4list\u00f6, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkki, Juupajoki, Suomi",
"Pyynikkil\u00e4n pappila, Pappilankulma, Ruovesi, Suomi",
"P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"P\u00e4iv\u00e4rinta m\u00e4kitupa, Yl\u00e4-Piispalan ratsutila, Jaatila, J\u00e4ms\u00e4, Suomi",
"P\u00e4k\u00e4ri, Keuruu, Suomi",
"P\u00e4lk\u00e4ne, Suomi",
"P\u00e4lk\u00e4neen seurakunta, Suomen ev.lut. kirkko",
"P\u00e4lk\u00e4neen vanha kirkko, P\u00e4lk\u00e4ne, Suomi",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"P\u00e4nk\u00e4l\u00e4, Toivila, J\u00e4ms\u00e4, Suomi",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"P\u00e4\u00e4skyl\u00e4, Orivesi, Suomi",
"P\u00f6h\u00f6, Rahikkala, Antrea, Luovutettu Karjala",
"P\u00f6lh\u00f6l\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"P\u00f6ll\u00f6, Kurkela, Ikaalinen, Suomi",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"P\u00f6yty\u00e4, Suomi",
"Raaju, Mets\u00e4pirtti, Luovutettu Karjala",
"Raasepori, Suomi",
"Rahikkala, Antrea, Luovutettu Karjala",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Raikku, Kangasala, Suomi",
"Rainio, Karkku, Vammala, Sastamala, Suomi",
"Raisio, Suomi",
"Raiskinm\u00e4ki, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Raivattala, Hiitola, Luovutettu Karjala",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"Rajalahti, Ruovesi, Suomi",
"Rakkolanjoki, Vahviala, Luovutettu Karjala",
"Rantala, Ilola, Sahalahti, Kangasala, Suomi",
"Rantala, Kaipola, J\u00e4ms\u00e4, Suomi",
"Rasi, Pohja, Kuhmalahti, Kangasala, Suomi",
"Raudun seurakunta, Suomen ev.lut. kirkko",
"Rauhalahti, Kuhmoinen, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"Rauma, Suomi",
"Rauralaniemi, Hiitola, Luovutettu Karjala",
"Rautalammin vanha hallintopit\u00e4j\u00e4, Suomi",
"Rautia, Kuokkala, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Rautiala, Toivila, J\u00e4ms\u00e4, Suomi",
"Rautio, Sahalahti, Kangasala, Suomi",
"Rautu, Luovutettu Karjala",
"Reinikka, Pihlajavesi, Keuruu, Suomi",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Rekola, Ilola, Sahalahti, Kangasala, Suomi",
"Rekola, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"Rekolan rustholli, Heponiemi, Kangasala, Suomi",
"Retukyl\u00e4, Muolaa, Luovutettu Karjala",
"Revonlahti, Ojaniemi, Sakkola, Luovutettu Karjala",
"Riddarholmskyrkan, Tukholma, Ruotsi",
"Riekkola, Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Riekkola, Riekkolanper\u00e4, Ruovesi, Suomi",
"Riekkolanper\u00e4, Ruovesi, Suomi",
"Rieskala, Huittinen, Suomi",
"Riihihuhti torp., Moiskala, J\u00e4ms\u00e4, Suomi",
"Riipil\u00e4, Puharila, Orivesi, Suomi",
"Riiska, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"Riku, Kangasala, Suomi",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"Ritoniemi, Ritoniemi, Ruovesi, Suomi",
"Ritoniemi, Ruovesi, Suomi",
"Ritvala, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rouhiala, J\u00e4\u00e4ski, Luovutettu Karjala",
"Ruhala, Ruovesi, Suomi",
"Runko, Piikki\u00f6, Kaarina, Suomi",
"Ruokonen, Orivesi, Suomi",
"Ruoranen, Isoj\u00e4rvi, Multia, Suomi",
"Ruotsi",
"Ruotsula, J\u00e4ms\u00e4, Suomi",
"Ruoveden kirkko, Ritoniemi, Ruovesi, Suomi",
"Ruoveden komppania, Porin l\u00e4\u00e4nin jalkav\u00e4kirykmentti, Sotilasorganisaatiot",
"Ruoveden seurakunta, Suomen ev.lut. kirkko",
"Ruovesi, Suomi",
"Ruskeala, Luovutettu Karjala",
"Ruskealan seurakunta, Suomen ev.lut. kirkko",
"Ruudala, Huittula, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Ruuska, Kaarlahti, Kaukola, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rym\u00e4ttyl\u00e4, Naantali, Suomi",
"Ryttm\u00e4stare Fecklenbourgs kompani, V\u00e4stg\u00f6ta tre och femm\u00e4nningsregemente kavalleri, Sotilasorganisaatiot",
"Ryttm\u00e4stare Kr\u00fcdeners kompani, V\u00e4stg\u00f6ta tre och femm\u00e4nningsregemente kavalleri, Sotilasorganisaatiot",
"R\u00e4ih\u00e4 Kangas, Keitelepohja, Viitasaari, Suomi",
"R\u00e4ih\u00e4, Pet\u00e4j\u00e4vesi, Suomi",
"R\u00e4ih\u00e4ranta, Vuoksela, Luovutettu Karjala",
"R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"R\u00e4tt\u00f6, Akaa, Suomi",
"R\u00e4tt\u00f6l\u00e4, Heinjoki, Luovutettu Karjala",
"R\u00e4yrinki, Veteli, Suomi",
"R\u00e4\u00e4veli, Viro",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Sakkola, Luovutettu Karjala",
"Saarij\u00e4rven kirkko, Saarij\u00e4rvi, Suomi",
"Saarij\u00e4rvi, Suomi",
"Saarikko, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Saarioinen, Sahalahti, Kangasala, Suomi",
"Saarioispuoli, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Saaris Kakaristo, Saaris, J\u00e4ms\u00e4, Suomi",
"Saaris, J\u00e4ms\u00e4, Suomi",
"Saaroinen, Mets\u00e4pirtti, Luovutettu Karjala",
"Sahalahden kirkko, Sahalahti, Kangasala, Suomi",
"Sahalahden seurakunta, Suomen ev.lut. kirkko",
"Sahalahti, Kangasala, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Sakari, Kiukoila, Lopotti, J\u00e4ms\u00e4, Suomi",
"Sakkola, Luovutettu Karjala",
"Sakkolan kirkko, Sakkola, Luovutettu Karjala",
"Sakkolan kirkkomaa, Sakkola, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Sakkolan pappila, Sakkola, Luovutettu Karjala",
"Sakkolan seurakunta, Suomen ev.lut. kirkko",
"Saksa",
"Saksalainen ritarikunta, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Saksan demokraattinen tasavalta",
"Saksan valtakunta",
"Saksi-Wittenbergin herttuakunta, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Saksin kuningaskunta, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Saksin vaaliruhtinaskunta, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Salhoja torp., Takahuhti, Messukyl\u00e4, Tampere, Suomi",
"Salitsanrannan kansakoulu, Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salkinoja, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Salmenkyl\u00e4, Pihlajavesi, Keuruu, Suomi",
"Salmij\u00e4rvi, Viiala, J\u00e4ms\u00e4, Suomi",
"Salo, Suomi",
"Salokunta, Juupajoki, Suomi",
"Salontaka, Halikko, Salo, Suomi",
"Saltvik, Suomi",
"Sammalisto, Jokioinen, J\u00e4ms\u00e4, Suomi",
"Sammatti, Lohja, Suomi",
"Sanaslahti torp., Tyry, J\u00e4ms\u00e4, Suomi",
"Sann\u00e4s, Karjaa, Raasepori, Suomi",
"Sarapihan vanhainkoti, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Sarvisalo, Marttila, Anttula, Kuhmoinen, Suomi",
"Sastamala, Suomi",
"Sattulanniemi, L\u00e4stil\u00e4, Kuhmoinen, Suomi",
"Saustila, Sauvo, Suomi",
"Saustilan kartano, Saustila, Sauvo, Suomi",
"Sauvo, Suomi",
"Sauvola, Piikki\u00f6, Kaarina, Suomi",
"Sauvon kirkko, Sauvo, Suomi",
"Sauvon seurakunta, Suomen ev.lut. kirkko",
"Savilahti - Pohjankyl\u00e4, Antrea, Luovutettu Karjala",
"Savilahti, Antrea, Luovutettu Karjala",
"Savitaipale, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Savo, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Savo, Orivesi, Suomi",
"Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Savo, Teisko, Tampere, Suomi",
"Savon historiallinen maakunta, Suomi",
"Sein\u00e4joki, Suomi",
"Seppola, J\u00e4ms\u00e4, Suomi",
"Sepp\u00e4l\u00e4, Aakkola, Orivesi, Suomi",
"Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Sepp\u00e4l\u00e4, Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Sepp\u00e4l\u00e4, Laasola, Orivesi, Suomi",
"Seurasalmi, Rauhalahti, Kuhmoinen, Suomi",
"Siikala, Laasola, Orivesi, Suomi",
"Siitama, Orivesi, Suomi",
"Sikanen, Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"Sillanp\u00e4\u00e4, Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Simola, Toivila, J\u00e4ms\u00e4, Suomi",
"Simsi\u00f6, Pihlajavesi, Keuruu, Suomi",
"Simsi\u00f6, Simsi\u00f6, Pihlajavesi, Keuruu, Suomi",
"Simuna, H\u00e4meenkyr\u00f6, Suomi",
"Sipoo, Suomi",
"Sipoon kirkko, Sipoo, Suomi",
"Sirki\u00e4nsaari, Rautu, Luovutettu Karjala",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Siukola, Oriveden kyl\u00e4, Orivesi, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siuntio, Suomi",
"Siuro, Oriveden kyl\u00e4, Orivesi, Suomi",
"Siurola, Raikku, Kangasala, Suomi",
"Skaffari, Kontu, Antrea, Luovutettu Karjala",
"Sm\u00e5land, Ruotsi",
"Soini, Suomi",
"Somerniemen seurakunta, Suomen ev.lut. kirkko",
"Someron seurakunta, Suomen ev.lut. kirkko",
"Somppi, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"Sorila, Aitolahti, Tampere, Suomi",
"Sorkkala, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Sorola, Kangasala, Suomi",
"Sortanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Sorvola, Huittinen, Suomi",
"Sotainvalidien Veljesliiton Kuoreveden osasto, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Sotilasorganisaatiot",
"St. Ann\u2019s Catholic Parish, U.S. Catholic Church",
"Storg\u00e5rd, Kyl\u00e4noja, Orivesi, Suomi",
"Storg\u00e5rd, Parainen, Suomi",
"Storminiemi, Ruovesi, Suomi",
"Strand, \u00c4lg\u00e5, V\u00e4rmland, Ruotsi",
"Suffolk County, Massachusetts, USA",
"Suhonkyl\u00e4, Suonenjoki, Suomi",
"Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Sukkila, Juupajoki, Suomi",
"Suluslahti, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Sund, Suomi",
"Suoj\u00e4rvi, Keuruu, Suomi",
"Suolahti, Keuruu, Suomi",
"Suomasema, Orivesi, Suomi",
"Suomaseman rustholli, Suomasema, Orivesi, Suomi",
"Suomen ev.lut. kirkko",
"Suomen ortodoksinen kirkko",
"Suomen Sukututkimusseura ry, Suomi",
"Suomi",
"Suonenjoki, Suomi",
"Sysm\u00e4, Suomi",
"S\u00e4llinlahti, Pihlajavesi, Keuruu, Suomi",
"S\u00e4rkikanta, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"S\u00e4rkilahti, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"S\u00e4yn\u00e4tj\u00e4rvi, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"S\u00e4yryl\u00e4, J\u00e4ms\u00e4, Suomi",
"S\u00e4\u00e4ksm\u00e4en kihlakunta, Suomi",
"S\u00e4\u00e4ksm\u00e4en tuomiokunta, Turun hovioikeuspiiri, Suomi",
"S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Taavettila, Asunta, Keuruu, Suomi",
"Taipale, Mets\u00e4pirtti, Luovutettu Karjala",
"Taipale, Padustaipale, Orivesi, Suomi",
"Taipale, Suoj\u00e4rvi, Keuruu, Suomi",
"Taivassalo, Suomi",
"Takahuhti, Messukyl\u00e4, Tampere, Suomi",
"Talikkala, Antrea, Luovutettu Karjala",
"Talviainen, Orivesi, Suomi",
"Tamminiemi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Tampere, Suomi",
"Tanska",
"Tapanila, Tehi, Kuhmoinen, Suomi",
"Tapiala, Kuhmoinen, Suomi",
"Tarhap\u00e4\u00e4, Multia, Suomi",
"Tarhia, Keuruu, Suomi",
"Tarkkala, Kokkila, Juupajoki, Suomi",
"Tasala, Kerttula, Raisio, Suomi",
"Taubila, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tauriala, Seppola, J\u00e4ms\u00e4, Suomi",
"Tavastila, Mietoinen, Myn\u00e4m\u00e4ki, Suomi",
"Tavela, Tursola, Kangasala, Suomi",
"Teboil Julkuj\u00e4rvi, Huurretie 5, Julkuj\u00e4rvi, Yl\u00f6j\u00e4rvi, Suomi",
"Teerijoki, Oriveden kyl\u00e4, Orivesi, Suomi",
"Tehi, Kuhmoinen, Suomi",
"Teisko, Tampere, Suomi",
"Terenttil\u00e4, Mets\u00e4pirtti, Luovutettu Karjala",
"Tervala, J\u00e4ms\u00e4, Suomi",
"Tevaj\u00e4rvi, Kuhmoinen, Suomi",
"The Pennsylvania Railroad Company, USA",
"Tiirikka, Kurkela, Ikaalinen, Suomi",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tilattomat, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tiurulan ortodoksinen seurakunta, Suomen ortodoksinen kirkko",
"Tiusala, Valkealahti, Keuruu, Suomi",
"Tjusterby, Pernaja, Loviisa, Suomi",
"Tjusterbyn kartano, Tjusterby, Pernaja, Loviisa, Suomi",
"Tohloppi, Tampere, Suomi",
"Toijala, Halikko, Salo, Suomi",
"Toijala, Suomi",
"Toivila, J\u00e4ms\u00e4, Suomi",
"Tolsterniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tonteri, Ihantala, Viipurin maalaiskunta, Luovutettu Karjala",
"Toppola, Hauhon kirkonkyl\u00e4, Hauho, H\u00e4meenlinna, Suomi",
"Torlahden kartano, Torlahti, Kalanti, Uusikaupunki, Suomi",
"Torlahti, Kalanti, Uusikaupunki, Suomi",
"Tryyk\u00e4rinmaa, Huittinen, Suomi",
"Tuittula, Hauho, H\u00e4meenlinna, Suomi",
"Tukholma, Ruotsi",
"Tunkelo, Orivesi, Suomi",
"Tunkelon rustholli, Tunkelo, Orivesi, Suomi",
"Tuomaala, Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Tuomaala, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Tuomarla, K\u00e4rjenniemi, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Tuomola, Uuhiniemi, Orivesi, Suomi",
"Turku, Suomi",
"Tursola, Kangasala, Suomi",
"Turun akatemia, Turku, Suomi",
"Turun arkkihiippakunta, Suomen ev.lut. kirkko",
"Turun hovioikeuspiiri, Suomi",
"Turun katedraalikoulu, Turku, Suomi",
"Turun linna, Turku, Suomi",
"Turun ruotsalainen ja suomalainen seurakunta, Suomen ev.lut. kirkko",
"Tuuri, Kurkela, Ikaalinen, Suomi",
"Tyrv\u00e4nt\u00f6, Hattula, Suomi",
"Tyrv\u00e4\u00e4n rovastikunta, Turun arkkihiippakunta, Suomen ev.lut. kirkko",
"Tyry, J\u00e4ms\u00e4, Suomi",
"Ty\u00f6r\u00f6, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"T\u00e4rkkil\u00e4, Tervala, J\u00e4ms\u00e4, Suomi",
"T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"U.S. Catholic Church",
"Uitamo, Multia, Suomi",
"Ukonpelto, Suhonkyl\u00e4, Suonenjoki, Suomi",
"Ukraina",
"Ulvila, Suomi",
"United States Army, Sotilasorganisaatiot",
"Unkila, Padustaipale, Orivesi, Suomi",
"Untamala, Suomi",
"Uotila, Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Uotila, Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"Uppland, Ruotsi",
"Urjala, Suomi",
"Urjalan kirkko, Urjala, Suomi",
"Urjalankyl\u00e4, Urjala, Suomi",
"USA",
"Uskela, Valkeakoski, Suomi",
"Uudenkaarlepyyn maalaiskunta, Uusikaarlepyy, Suomi",
"Uudenmaan historiallinen maakunta, Suomi",
"Uudenmaan ja H\u00e4meen l\u00e4\u00e4nin ratsuv\u00e4kirykmentti, Sotilasorganisaatiot",
"Uudenmaan maaseutuopisto, Hyvink\u00e4\u00e4, Suomi",
"Uuhiniemi, Orivesi, Suomi",
"Uura, Multia, Suomi",
"Uurainen, Suomi",
"Uusi-Juhola, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Uusikaarlepyy, Suomi",
"Uusikaupunki, Suomi",
"Uusikirkko Vpl, Luovutettu Karjala",
"Uusitalo, Mustasuu, Orivesi, Suomi",
"Vaakkola, Tohloppi, Tampere, Suomi",
"Vaatturiliike Kolkkava, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Vaatturiliike U. M\u00e4kinen, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Vagabundi - Sakkolan tilattomia, Sakkola, Luovutettu Karjala",
"Vahviala, Luovutettu Karjala",
"Vainio-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Valkeajoki, Kokkila, Juupajoki, Suomi",
"Valkeakoski, Suomi",
"Valkealahti, Keuruu, Suomi",
"Valkealuomi, J\u00e4ms\u00e4, Suomi",
"Valkeam\u00e4ki, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Valkeaniemi, Keuruu, Suomi",
"Valkiala, Kuhmoinen, Suomi",
"Valkj\u00e4rvi",
"Valkj\u00e4rvi, Sakkola, Luovutettu Karjala",
"Valma Lepola Ky, Yl\u00f6j\u00e4rvi, Suomi",
"Valmet Lentokoneteollisuus, Halli, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vammala, Sastamala, Suomi",
"Vanaja, Suomi",
"Vanha-Pappila, Suolahti, Keuruu, Suomi",
"Vanhainkoti, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vanhajaama, Mets\u00e4pirtti, Luovutettu Karjala",
"Vanhakartano, Arvassalo, Kalanti, Uusikaupunki, Suomi",
"Varala, Kangasala, Suomi",
"Varsinais-Suomen historiallinen maakunta, Suomi",
"Vehkaj\u00e4rvi, Kuhmalahti, Kangasala, Suomi",
"Vehkalahti, Hamina, Suomi",
"Vehkalahti, Orivesi, Suomi",
"Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"Vehkoo, Multia, Suomi",
"Vehmaa, Suomi",
"Vehmais, Rautu, Luovutettu Karjala",
"Vehoniemi, Kangasala, Suomi",
"Vekkaila, Valkiala, Kuhmoinen, Suomi",
"Ven\u00e4j\u00e4",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vesikkala, Muolaa, Luovutettu Karjala",
"Vesilahti, Suomi",
"Vesiniitty, Huittinen, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vesti, Sauvo, Suomi",
"Veteli, Suomi",
"Vetelin kirkko, Veteli, Suomi",
"Vierel\u00e4, Tervala, J\u00e4ms\u00e4, Suomi",
"Vihti, Suomi",
"Vihtinen, Ohtola, Kangasala, Suomi",
"Viiainen, Taivassalo, Suomi",
"Viiala, J\u00e4ms\u00e4, Suomi",
"Viialan puustelli, Kaipola, J\u00e4ms\u00e4, Suomi",
"Viias, Viiainen, Taivassalo, Suomi",
"Viiksanlahti, Sakkola, Luovutettu Karjala",
"Viipuri, Luovutettu Karjala",
"Viipurin hiippakunta, Suomen ev.lut. kirkko",
"Viipurin linna, Viipuri, Luovutettu Karjala",
"Viipurin maalaiskunta, Luovutettu Karjala",
"Viipurin rykmentti, Sotilasorganisaatiot",
"Viisas, Turku, Suomi",
"Viisjoki, Mets\u00e4pirtti, Luovutettu Karjala",
"Viitaniemi, Savo, Teisko, Tampere, Suomi",
"Viitasaari, Suomi",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilhula, Multia, Suomi",
"Viljainen, Rym\u00e4ttyl\u00e4, Naantali, Suomi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Vilppulan maamieskoulu, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Vinni, Hahkala, J\u00e4ms\u00e4, Suomi",
"Virkaj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Viro",
"Virrat, Suomi",
"Viskari, Haparainen, Sakkola, Luovutettu Karjala",
"Visuvesi, Ruovesi, Suomi",
"Vittajoki, Kuoreniemi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Volossula, Sakkola, Luovutettu Karjala",
"Vuohela, Kaipola, J\u00e4ms\u00e4, Suomi",
"Vuohensalo, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Vuoksela, Luovutettu Karjala",
"Vuole, Inkeri, Ven\u00e4j\u00e4",
"Vuorenalainen, Jokioinen, J\u00e4ms\u00e4, Suomi",
"Vuorenp\u00e4\u00e4 torp., L\u00e4stil\u00e4, Kuhmoinen, Suomi",
"Vuosalmi, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"V\u00e4h\u00e4-K\u00e4tt\u00f6, Koivisto, Humppila, Suomi",
"V\u00e4h\u00e4-K\u00f6mi, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"V\u00e4h\u00e4talo, H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"V\u00e4likara, Salmenkyl\u00e4, Pihlajavesi, Keuruu, Suomi",
"V\u00e4lkkil\u00e4, Urjala, Suomi",
"V\u00e4lkky, Keuruu, Suomi",
"V\u00e4rmland, Ruotsi",
"V\u00e4sterbottenin jalkav\u00e4kirykmentti, Sotilasorganisaatiot",
"V\u00e4sterby, Siuntio, Suomi",
"V\u00e4stg\u00f6ta tre och femm\u00e4nningsregemente kavalleri, Sotilasorganisaatiot",
"V\u00e4stil\u00e4, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"V\u00e4\u00e4k\u00e4s, R\u00e4tt\u00f6, Akaa, Suomi",
"V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Washington County, Arkansas, USA",
"Watikkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Weimarin tasavalta",
"Wernitsan hovi, Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Wexford County, Michigan, USA",
"Williamston, Ingham County, Michigan, USA",
"Wittenberg Universit\u00e4t, Wittenberg, Saksa",
"Wittenberg, Saksa",
"Wiurilan kartano, Halikko, Salo, Suomi",
"Yij\u00e4l\u00e4, J\u00e4ms\u00e4, Suomi",
"Yij\u00e4l\u00e4n ratsutila, Yij\u00e4l\u00e4, J\u00e4ms\u00e4, Suomi",
"Ylinen, Kytt\u00e4l\u00e4, Tampere, Suomi",
"Ylinen, Porvola, Juupajoki, Suomi",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ylinen, Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ylistalo, Visuvesi, Ruovesi, Suomi",
"Ylti\u00e4, Pihlajavesi, Keuruu, Suomi",
"Yl\u00e4-H\u00e4kkinen, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Yl\u00e4-Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Nikki, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Partala, Jokioinen, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Piispalan ratsutila, Jaatila, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Rekola, Vierel\u00e4, Tervala, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Satakunnan historiallinen maakunta, Suomi",
"Yl\u00e4joki nyb., Rauhalahti, Kuhmoinen, Suomi",
"Yl\u00e4j\u00e4rven kansakoulu, Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4kokkola, Hiitola, Luovutettu Karjala",
"Yl\u00e4ne, P\u00f6yty\u00e4, Suomi",
"Yl\u00e4neen kartano, Yl\u00e4ne, P\u00f6yty\u00e4, Suomi",
"Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4puusti, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Yl\u00f6j\u00e4rvi, Suomi",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yrjas, Forsby, Uudenkaarlepyyn maalaiskunta, Uusikaarlepyy, Suomi",
"Yrj\u00f6l\u00e4, Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yrj\u00f6l\u00e4, Naappila, Orivesi, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Yrj\u00f6l\u00e4, Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Yskj\u00e4rvi, Muolaa, Luovutettu Karjala",
"\u00c4ht\u00e4ri, Suomi",
"\u00c4k\u00e4m\u00e4ki, Kuhmoinen, Suomi",
"\u00c4lg\u00e5, V\u00e4rmland, Ruotsi",
"\u00c4nkk\u00e4 torp., Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"\u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala"
]
Dwr.ScriptLoaded('dwr_db_P_name_0.js');
