// This file is generated

I_birth_place_0 = [
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Pappila, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Peltola, Mustaj\u00e4rvi, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Rainio, Karkku, Vammala, Sastamala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Kavantsaari, Antrea, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kruunupyy, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Retukyl\u00e4, Muolaa, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"Maunukkala torp., Holma, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Iso-K\u00f6lli, Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"\u00c4ht\u00e4ri, Suomi",
"",
"",
"",
"",
"",
"",
"Gammelby, Pernaja, Loviisa, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Veteli, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Gammelby, Pernaja, Loviisa, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"",
"",
"Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Sakari, Kiukoila, Lopotti, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Rautiala, Toivila, J\u00e4ms\u00e4, Suomi",
"",
"",
"Ouni, Ouninpohja, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Keuruu, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Paattila, Seppola, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Ruotsi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Aakkola, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Pyh\u00e4j\u00e4rven kirkonkyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rven kirkonkyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ala-Hinkkalan ratsutila, Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"Alakangas, Pihlaisto, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Porvola, Juupajoki, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Vehmaa, Suomi",
"Iitti, Suomi",
"",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"L\u00e4ngelm\u00e4ki, Suomi",
"",
"",
"",
"Anttila, Hoivala, H\u00f6ytee, Juupajoki, Suomi",
"",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"Apiala, Seppola, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Litslena socken, Uppland, Ruotsi",
"",
"",
"Tavela, Tursola, Kangasala, Suomi",
"Tavela, Tursola, Kangasala, Suomi",
"",
"Kangasala, Suomi",
"",
"",
"",
"",
"",
"Sauvo, Suomi",
"",
"",
"Liesniemi, Sauvo, Suomi",
"",
"",
"Nenonen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"Uusikirkko Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"Keuruu, Suomi",
"Michigan, USA",
"",
"",
"",
"Salokunta, Juupajoki, Suomi",
"",
"",
"",
"",
"Nyyn\u00e4inen, Lemu, Masku, Suomi",
"",
"",
"",
"",
"D\u00f6nsby, Karjaa, Raasepori, Suomi",
"",
"Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"Edesniemi, Arvaja, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Kosela, Mets\u00e4pirtti, Luovutettu Karjala",
"Vanhajaama, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"",
"Gesterby, Sipoo, Suomi",
"",
"",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"Eskola, Lylyj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"",
"Eskola, Lylyj\u00e4rvi, Juupajoki, Suomi",
"",
"Eskola, Vehkalahti, Orivesi, Suomi",
"Eskola, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Eskola, Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Suomi",
"",
"",
"",
"Finnil\u00e4, Maakeski, Padasjoki, Suomi",
"Maakeski, Padasjoki, Suomi",
"",
"Askainen, Masku, Suomi",
"",
"Vanhakartano, Arvassalo, Kalanti, Uusikaupunki, Suomi",
"",
"Askainen, Masku, Suomi",
"",
"",
"",
"",
"Pirkkala, Suomi",
"Sauvo, Suomi",
"",
"",
"",
"Porras, Hauho, H\u00e4meenlinna, Suomi",
"",
"",
"",
"",
"",
"",
"Maastricht, Alankomaat",
"",
"Riipil\u00e4, Puharila, Orivesi, Suomi",
"",
"",
"Cadillac, Wexford County, Michigan, USA",
"",
"",
"Kelja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"",
"",
"",
"",
"Kuhmoinen, Suomi",
"Kuhmoinen, Suomi",
"Punnus, Muolaa, Luovutettu Karjala",
"",
"Punnus, Muolaa, Luovutettu Karjala",
"",
"",
"Hampaala, Pakkala, Sahalahti, Kangasala, Suomi",
"Hampaala, Pakkala, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Hassi, Hassi, J\u00e4ms\u00e4, Suomi",
"",
"Hassi, Hassi, J\u00e4ms\u00e4, Suomi",
"J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Sakkola, Luovutettu Karjala",
"",
"Heikkil\u00e4n rustholli, Huhti, Urjala, Suomi",
"Heikkil\u00e4n rustholli, Huhti, Urjala, Suomi",
"Huhti, Urjala, Suomi",
"",
"",
"",
"Heikkil\u00e4n rustholli, Huhti, Urjala, Suomi",
"",
"J\u00e4ms\u00e4, Suomi",
"",
"",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Heikkil\u00e4n rustholli, Huhti, Urjala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"J\u00e4ms\u00e4, Suomi",
"Seurasalmi, Rauhalahti, Kuhmoinen, Suomi",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Miisua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Miisua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Hinkkala, Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"",
"",
"Hinkkala, Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"Hinkkala, Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"",
"Suomaseman rustholli, Suomasema, Orivesi, Suomi",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kopsala, Hiitola, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kopsala, Hiitola, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"",
"",
"Hokka, Auttoinen, Padasjoki, Suomi",
"",
"Hokka, Auttoinen, Padasjoki, Suomi",
"",
"",
"",
"",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Asunta, Keuruu, Suomi",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Asunta, Keuruu, Suomi",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Halikko, Salo, Suomi",
"",
"Halikko, Salo, Suomi",
"",
"",
"",
"",
"",
"Keuruu, Suomi",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Huikuri, Huikuri, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"",
"Hujala, Puukkoinen, Kuhmoinen, Suomi",
"",
"",
"",
"",
"",
"",
"Hulipas, Juupajoki, Suomi",
"",
"",
"",
"",
"Hulipas, Juupajoki, Suomi",
"",
"Hulipas, Juupajoki, Suomi",
"",
"",
"Huntilan rustholli, Huntila, P\u00e4lk\u00e4ne, Suomi",
"Huovila, V\u00e4lkkil\u00e4, Urjala, Suomi",
"V\u00e4lkkil\u00e4, Urjala, Suomi",
"Huovila, V\u00e4lkkil\u00e4, Urjala, Suomi",
"V\u00e4lkkil\u00e4, Urjala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4kokkola, Hiitola, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Keuruu, Suomi",
"",
"",
"",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kilpola, Hiitola, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Nurminmaa, Hatula, Antrea, Luovutettu Karjala",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"",
"Savilahti, Antrea, Luovutettu Karjala",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"H\u00e4nninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"R\u00e4tt\u00f6l\u00e4, Heinjoki, Luovutettu Karjala",
"Muolaan hovi, Muolaan kirkonkyl\u00e4, Muolaa, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Strand, \u00c4lg\u00e5, V\u00e4rmland, Ruotsi",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kopsala, Hiitola, Luovutettu Karjala",
"",
"",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"L\u00e4ngelm\u00e4ki, Suomi",
"Iso-Attila, Attila, Orivesi, Suomi",
"",
"L\u00e4ngelm\u00e4ki, Suomi",
"",
"Ikaalan rustholli, Ikaala, Urjala, Suomi",
"Ikaalan rustholli, Ikaala, Urjala, Suomi",
"",
"",
"Ikaalan rustholli, Ikaala, Urjala, Suomi",
"Isotalo, H\u00f6rts\u00e4n\u00e4, Onnistaipale, Orivesi, Suomi",
"",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Kuhmoinen, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"Ivala, Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"",
"",
"",
"Naappila, Orivesi, Suomi",
"Jaakkola, Pohja, Kuhmalahti, Kangasala, Suomi",
"Naappila, Orivesi, Suomi",
"Naappila, Orivesi, Suomi",
"Naappila, Orivesi, Suomi",
"",
"",
"",
"",
"",
"Joensuu, Joensuu, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Jokela, Partala torp., Jokioinen, J\u00e4ms\u00e4, Suomi",
"V\u00e4stil\u00e4, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Jussila, Rautio, Sahalahti, Kangasala, Suomi",
"",
"Rautio, Sahalahti, Kangasala, Suomi",
"",
"Jussila, Rautio, Sahalahti, Kangasala, Suomi",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Sorvola, Huittinen, Suomi",
"",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Sakkola, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Eskola, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"J\u00e4rvenp\u00e4\u00e4, Alanen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"J\u00e4rvensivun rustholli, J\u00e4rvensivu, Tampere, Suomi",
"",
"J\u00e4rvenp\u00e4\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Korpi, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Korpi, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Korpi, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Korpi, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Pet\u00e4j\u00e4rvi, Sakkola, Luovutettu Karjala",
"",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kunnianiemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"",
"Kalliom\u00e4ki, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Kallio, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Kutinlahti, Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"Kalliom\u00e4ki, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Kantala, Ruhala, Ruovesi, Suomi",
"Pet\u00e4j\u00e4vesi, Suomi",
"Pet\u00e4j\u00e4vesi, Suomi",
"Pet\u00e4j\u00e4vesi, Suomi",
"",
"",
"Karikko, Pet\u00e4j\u00e4vesi, Suomi",
"Karikko, Pet\u00e4j\u00e4vesi, Suomi",
"",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Karvia, Kyl\u00e4noja, Orivesi, Suomi",
"",
"",
"Kyl\u00e4noja, Orivesi, Suomi",
"Karvia, Kyl\u00e4noja, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Kaukola, Niemola, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"Pajuskyl\u00e4, Ruovesi, Suomi",
"Kemppil\u00e4, Antrea, Luovutettu Karjala",
"",
"Keppil\u00e4n rustholli, Laukeela, Urjala, Suomi",
"Kerppola, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"Kienala, Niemola, J\u00e4ms\u00e4, Suomi",
"",
"Multia, Suomi",
"",
"",
"",
"",
"Kihlala, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"Norola, Hassi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Knuutila, Er\u00e4slahti, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"Orivesi, Suomi",
"Kolhi, Savo, Orivesi, Suomi",
"",
"Kolhi, Kolhi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"",
"",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Koppeloj\u00e4rvi, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Kopsamo, Juupajoki, Suomi",
"",
"",
"Raaju, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Korppila, \u00c4k\u00e4m\u00e4ki, Kuhmoinen, Suomi",
"Korpula, Korpula, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Koski, Karjula, Kuru, Yl\u00f6j\u00e4rvi, Suomi",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Watikkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kottila, Heikkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Rahkaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Riiska, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Orivesi, Suomi",
"",
"",
"",
"",
"Kulkas, Sorila, Aitolahti, Tampere, Suomi",
"",
"",
"",
"Kulkas, Sorila, Aitolahti, Tampere, Suomi",
"Hattula, Muolaa, Luovutettu Karjala",
"",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Kavantsaari, Antrea, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kurra, Pitk\u00e4nen, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kurra, Pitk\u00e4nen, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Taipale, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"",
"Kutinlahti, Liesj\u00e4rvi, Pihlajavesi, Keuruu, Suomi",
"",
"",
"",
"",
"",
"",
"Kylm\u00e4melli, Melli, Juupajoki, Suomi",
"Melli, Juupajoki, Suomi",
"",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"",
"",
"",
"",
"P\u00e4llil\u00e4, Muolaa, Luovutettu Karjala",
"Merola, Muolaa, Luovutettu Karjala",
"",
"",
"",
"",
"Kottila, Kiviniemi, Sakkola, Luovutettu Karjala",
"",
"",
"V\u00e4h\u00e4-K\u00f6mi, K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"Pihlajavesi, Keuruu, Suomi",
"",
"",
"",
"",
"K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"K\u00f6mi, Pihlajavesi, Keuruu, Suomi",
"",
"Keuruu, Suomi",
"K\u00f6ntt\u00e4ri, Suolahti, Keuruu, Suomi",
"",
"K\u00f6yk\u00e4np\u00e4\u00e4, Holma, Orivesi, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Tuomaala, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Tuomaala, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Laalahti, Laalahti, Aitolahti, Tampere, Suomi",
"",
"Lahnajoki, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Lahnajoki, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"Lahnajoki, Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"",
"",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Lahnavalkama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kuusaa, Muolaa, Luovutettu Karjala",
"",
"",
"",
"",
"Laurila, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"",
"",
"Keuruu, Suomi",
"",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Riku, Kangasala, Suomi",
"",
"",
"",
"Lintulan rustholli, Paalila, Kangasala, Suomi",
"Lintulan rustholli, Paalila, Kangasala, Suomi",
"",
"",
"",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Liuttulan ratsutila, Liuttula, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"",
"Lapinlahti, Sakkola, Luovutettu Karjala",
"Ojaniemi, Sakkola, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"L\u00e4ttil\u00e4, Tapiala, Kuhmoinen, Suomi",
"L\u00e4ttil\u00e4, Tapiala, Kuhmoinen, Suomi",
"",
"",
"L\u00e4ttil\u00e4, Tapiala, Kuhmoinen, Suomi",
"",
"",
"",
"",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"L\u00f6yt\u00e4n\u00e4, Teisko, Tampere, Suomi",
"",
"L\u00f6yt\u00e4n\u00e4, Kurkij\u00e4rvi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Pohja, Kuhmalahti, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Maijala, Pohja, Kuhmalahti, Kangasala, Suomi",
"Volossula, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Manninen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Savon historiallinen maakunta, Suomi",
"",
"",
"",
"",
"",
"",
"Ukonpelto, Suhonkyl\u00e4, Suonenjoki, Suomi",
"",
"",
"Mattila, Tursola, Kangasala, Suomi",
"Mattila, Hallinpenkki, Halli, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"Mattila, Tursola, Kangasala, Suomi",
"Mattila, Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"",
"",
"",
"Hirvij\u00e4rvi, Juupajoki, Suomi",
"Pehula, Orivesi, Suomi",
"",
"Maunula, Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"",
"Pehula, Orivesi, Suomi",
"Maunula, Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"",
"Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"Melli, Juupajoki, Suomi",
"",
"Melli, Melli, Juupajoki, Suomi",
"",
"",
"Melli, Melli, Juupajoki, Suomi",
"Vehmais, Rautu, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Kuokkala, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Urjala, Suomi",
"",
"",
"Patala, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Juokslahti, J\u00e4ms\u00e4, Suomi",
"",
"",
"Minkkil\u00e4, Kuukkaj\u00e4rvi, Uurainen, Suomi",
"Minkkil\u00e4, Kuukkaj\u00e4rvi, Uurainen, Suomi",
"",
"Minkkil\u00e4, Kuukkaj\u00e4rvi, Uurainen, Suomi",
"Moisio, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Monoskyl\u00e4, Virrat, Suomi",
"Monoskyl\u00e4, Virrat, Suomi",
"Monoskyl\u00e4, Virrat, Suomi",
"Monoskyl\u00e4, Virrat, Suomi",
"",
"Monoskyl\u00e4, Virrat, Suomi",
"",
"",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Mulkoila, Orivesi, Suomi",
"Laasola, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Keuruu, Suomi",
"Keuruu, Suomi",
"Tiusala, Valkealahti, Keuruu, Suomi",
"Murtom\u00e4ki, Haapam\u00e4ki, Keuruu, Suomi",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Heikurila, Heinjoki, Luovutettu Karjala",
"",
"",
"",
"",
"Heikurila, Heinjoki, Luovutettu Karjala",
"Heikurila, Heinjoki, Luovutettu Karjala",
"Heikurila, Heinjoki, Luovutettu Karjala",
"",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Muuransuo torp., Ruotsula, J\u00e4ms\u00e4, Suomi",
"",
"",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4kel\u00e4, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"\u00c4ht\u00e4ri, Suomi",
"",
"M\u00e4ki-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Multia, Suomi",
"",
"Multianniemi, Multia, Suomi",
"",
"",
"M\u00e4nts\u00e4, Uskela, Valkeakoski, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Laaksi, Kuoreveden Ev\u00e4j\u00e4rvi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00e4ntt\u00e4, Keuruskoski, M\u00e4ntt\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"",
"",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Ilola, Muolaa, Luovutettu Karjala",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Tolsterniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Nenonen, V\u00e4\u00e4rinmaja, Ruovesi, Suomi",
"",
"Tiusala, Valkealahti, Keuruu, Suomi",
"",
"",
"",
"",
"Niemen rustholli, T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"Nihtil\u00e4, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"",
"",
"",
"",
"Niikkula, Koivuniemi, Orivesi, Suomi",
"",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikin-Eskola, Savo, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4n rustholli, Kokko, Urjala, Suomi",
"",
"",
"",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4n rustholli, Kokko, Urjala, Suomi",
"",
"",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4n rustholli, Kokko, Urjala, Suomi",
"",
"",
"",
"",
"",
"Noitermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Konnitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Nuottiniemi, Mustaj\u00e4rvi, Ruovesi, Suomi",
"Peska, Mustaj\u00e4rvi, Ruovesi, Suomi",
"Pitk\u00e4l\u00e4, Pihlajalahti, Ruovesi, Suomi",
"",
"Hautam\u00e4ki, Salokunta, Juupajoki, Suomi",
"",
"Valkeam\u00e4ki, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"N\u00e4ppil\u00e4, Vehkaj\u00e4rvi, Kuhmalahti, Kangasala, Suomi",
"N\u00e4ppil\u00e4, Vehkaj\u00e4rvi, Kuhmalahti, Kangasala, Suomi",
"Alakyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Puusti, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"Revonlahti, Ojaniemi, Sakkola, Luovutettu Karjala",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Ouni, Ouninpohja, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Paakkarila, Antrea, Luovutettu Karjala",
"",
"",
"",
"Paavola, Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"Katila, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Peltola, Kaipola, J\u00e4ms\u00e4, Suomi",
"Liuksiala, Kangasala, Suomi",
"Suolahti, Keuruu, Suomi",
"K\u00f6ntt\u00e4ri, Suolahti, Keuruu, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Haukkavaara, Hiitola, Luovutettu Karjala",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pauhari, Urjalankyl\u00e4, Urjala, Suomi",
"Urjala, Suomi",
"Pauhari, Urjalankyl\u00e4, Urjala, Suomi",
"Pauhari, Urjalankyl\u00e4, Urjala, Suomi",
"Pauhari, Urjalankyl\u00e4, Urjala, Suomi",
"Urjala, Suomi",
"Pauhari, Urjalankyl\u00e4, Urjala, Suomi",
"Pauhari, Urjalankyl\u00e4, Urjala, Suomi",
"",
"",
"Riiska, Sakkola, Luovutettu Karjala",
"Sirki\u00e4nsaari, Rautu, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"Palkeala, Rautu, Luovutettu Karjala",
"",
"",
"",
"",
"Pekkala, Suolahti, Keuruu, Suomi",
"Ehikki, Jaatila, Koskenp\u00e4\u00e4, J\u00e4ms\u00e4, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"Taipale, Suoj\u00e4rvi, Keuruu, Suomi",
"Kaipom\u00e4ki, Kuivasm\u00e4ki, Pet\u00e4j\u00e4vesi, Suomi",
"Pekkala, Suolahti, Keuruu, Suomi",
"",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"",
"Jaama, Mets\u00e4pirtti, Luovutettu Karjala",
"Pyh\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Hattula, Suomi",
"",
"",
"Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"",
"Perttula, Siitama, Orivesi, Suomi",
"Perttula, Kopsamo, Juupajoki, Suomi",
"Perttula, Kopsamo, Juupajoki, Suomi",
"",
"",
"",
"Pihlajalahti, Kuhmoinen, Suomi",
"Pihlajalahti, Kuhmoinen, Suomi",
"Pihlajalahti, Kuhmoinen, Suomi",
"",
"Hulipas, Juupajoki, Suomi",
"",
"",
"Pirttisarka rustholli, Jaarila, H\u00f6ytee, Juupajoki, Suomi",
"Sortanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"",
"Myllypelto, R\u00e4is\u00e4l\u00e4, Luovutettu Karjala",
"",
"P\u00f6rtsykk\u00e4, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Pohjaslahti, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"",
"Posti, Loila, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Posti, Loila, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Joentaka, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Ojaniemi, Sakkola, Luovutettu Karjala",
"",
"Pulkkinen, Veteli, Suomi",
"",
"Palkeala, Rautu, Luovutettu Karjala",
"Korhola, Mets\u00e4pirtti, Luovutettu Karjala",
"Kuninkaanselk\u00e4, Rautu, Luovutettu Karjala",
"",
"",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Alapuusti, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ivaskansaari, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Rotjanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ivaskansaari, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Ivaskansaari, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ivaskansaari, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Pyk\u00e4list\u00f6, Alhoj\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Ylinen, Porvola, Juupajoki, Suomi",
"Ylinen, Porvola, Juupajoki, Suomi",
"",
"",
"",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"",
"P\u00e4rrinautio, H\u00f6ytee, Juupajoki, Suomi",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Norsjoki, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"Kelja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Kiimaj\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Kelja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Rahikkala, Antrea, Luovutettu Karjala",
"",
"P\u00f6h\u00f6, Rahikkala, Antrea, Luovutettu Karjala",
"Hiirsalakka, Penttil\u00e4, J\u00e4\u00e4ski, Luovutettu Karjala",
"",
"",
"",
"",
"Saapru, Sakkola, Luovutettu Karjala",
"",
"Saapru, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"",
"",
"Strand, \u00c4lg\u00e5, V\u00e4rmland, Ruotsi",
"",
"Karkku, Vammala, Sastamala, Suomi",
"Rainio, Karkku, Vammala, Sastamala, Suomi",
"Raiskinm\u00e4ki, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Raiskinm\u00e4ki, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"Rajalahti, Rajalahti, Ruovesi, Suomi",
"",
"Suomi",
"V\u00e4rmland, Ruotsi",
"Strand, \u00c4lg\u00e5, V\u00e4rmland, Ruotsi",
"",
"",
"",
"",
"",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Rasi, Pohja, Kuhmalahti, Kangasala, Suomi",
"",
"Kuhmalahti, Kangasala, Suomi",
"Rasi, Pohja, Kuhmalahti, Kangasala, Suomi",
"Rasi, Pohja, Kuhmalahti, Kangasala, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"Rauma, Suomi",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vesikkala, Muolaa, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Pihlajavesi, Keuruu, Suomi",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"Reinikka, Reinikka, Pihlajavesi, Keuruu, Suomi",
"",
"Rekolan rustholli, Heponiemi, Kangasala, Suomi",
"",
"",
"Rekola, Pihlajavesi, Pihlajavesi, Keuruu, Suomi",
"",
"",
"",
"",
"",
"",
"Riekkola, Riekkolanper\u00e4, Ruovesi, Suomi",
"",
"",
"",
"",
"",
"",
"Riekkola, Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Ristsepp\u00e4l\u00e4, Heinjoki, Luovutettu Karjala",
"",
"",
"",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Michigan, USA",
"",
"",
"",
"",
"",
"Kaarlahti, Kaukola, Luovutettu Karjala",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Moiniemi, Muolaa, Luovutettu Karjala",
"Moiniemi, Muolaa, Luovutettu Karjala",
"Muolaa, Luovutettu Karjala",
"Parrinmaa, Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"",
"",
"Moiniemi, Muolaa, Luovutettu Karjala",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Moiniemi, Muolaa, Luovutettu Karjala",
"Muolaa, Luovutettu Karjala",
"Kuusaa, Muolaa, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Moiniemi, Muolaa, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Ala-Kuusaa, Muolaa, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"Riiska, Sakkola, Luovutettu Karjala",
"",
"",
"",
"",
"R\u00e4yrinki, Veteli, Suomi",
"L\u00e5ngila, R\u00e4yrinki, Veteli, Suomi",
"Kokkola, Suomi",
"",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"",
"",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Kaukila, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"",
"Karppilan rustholli, Kokko, Urjala, Suomi",
"Heikkil\u00e4n rustholli, Huhti, Urjala, Suomi",
"",
"",
"Saaroinen, Mets\u00e4pirtti, Luovutettu Karjala",
"Jussila, Rautio, Sahalahti, Kangasala, Suomi",
"L\u00e4ngelm\u00e4ki, Suomi",
"",
"Hautaniemi, Putula, Alavus, Suomi",
"Pohjanmaan historiallinen maakunta, Suomi",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Kahvenitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Saapru, Sakkola, Luovutettu Karjala",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Keuruu, Suomi",
"",
"",
"",
"",
"Hirvij\u00e4rvi, Juupajoki, Suomi",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"Nihtil\u00e4, P\u00e4ij\u00e4l\u00e4, Kuhmoinen, Suomi",
"Ivalanniemi, Tapiala, Kuhmoinen, Suomi",
"",
"",
"Laasola, Orivesi, Suomi",
"Laasola, Orivesi, Suomi",
"Laasola, Orivesi, Suomi",
"",
"",
"",
"Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"",
"",
"",
"",
"Simola, Toivila, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Sakkolan kyl\u00e4, Sakkola, Luovutettu Karjala",
"",
"",
"",
"L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"",
"L\u00e4ngelm\u00e4ki, Suomi",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"Sirkkala, L\u00e4ngelm\u00e4en Ev\u00e4j\u00e4rvi, J\u00e4ms\u00e4, Suomi",
"",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuoreniemi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"",
"Siurola, Raikku, Kangasala, Suomi",
"",
"",
"",
"",
"",
"Siurola, Raikku, Kangasala, Suomi",
"Siurola, Raikku, Kangasala, Suomi",
"Siurola, Raikku, Kangasala, Suomi",
"",
"",
"Vihti, Suomi",
"",
"",
"",
"",
"Pihlajavesi, Keuruu, Suomi",
"",
"",
"",
"",
"Sorola, Kangasala, Suomi",
"Musakanlahti, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"K\u00f6nkk\u00f6l\u00e4, Seppola, J\u00e4ms\u00e4, Suomi",
"Niemi, Juokslahti, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Suomi",
"Kemi\u00f6, Kemi\u00f6nsaari, Suomi",
"",
"Kauhkiala, J\u00e4ms\u00e4, Suomi",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Huntilan rustholli, Huntila, P\u00e4lk\u00e4ne, Suomi",
"Suomaseman rustholli, Suomasema, Orivesi, Suomi",
"",
"",
"",
"",
"",
"Kalamaja, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Vilakkala, Sakkola, Luovutettu Karjala",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"",
"",
"Asunta, Keuruu, Suomi",
"Asunta, Keuruu, Suomi",
"",
"Asunta, Keuruu, Suomi",
"",
"",
"",
"Matiskala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Hannola, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Tiitua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Kangasala, Suomi",
"",
"",
"Myn\u00e4m\u00e4ki, Suomi",
"",
"",
"",
"",
"",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"Teerijoki, Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"Pernaja, Loviisa, Suomi",
"",
"Vernitsa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Markkula, Ruoranen, Isoj\u00e4rvi, Multia, Suomi",
"Ampiala, Keuruu, Suomi",
"",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Taubila, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Ryhm\u00e4kyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Korkkala, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Filikyl\u00e4, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4puusti, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Kiviniemi, Sakkola, Luovutettu Karjala",
"",
"",
"Aln\u00e4s, Ritvala, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"",
"",
"Kontiolahti, Ruskeala, Luovutettu Karjala",
"",
"",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Jaama, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Multia, Suomi",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Kivipaarina, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"Tunkelon rustholli, Tunkelo, Orivesi, Suomi",
"Koukunniemi, Mets\u00e4pirtti, Luovutettu Karjala",
"Koukunniemi, Mets\u00e4pirtti, Luovutettu Karjala",
"",
"Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"\u00c4ht\u00e4ri, Suomi",
"",
"Kuoreniemi, Vilppula, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"",
"",
"Pappilan torpparit, Sakkola, Luovutettu Karjala",
"Kilpola, Hiitola, Luovutettu Karjala",
"",
"",
"",
"Sahalahti, Kangasala, Suomi",
"Sahalahti, Kangasala, Suomi",
"Niemen rustholli, T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"",
"",
"",
"Uotila, Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"",
"",
"Uura, Multia, Suomi",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"Vaitti, Myll\u00f6l\u00e4, Antrea, Luovutettu Karjala",
"",
"",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Yl\u00e4j\u00e4rvi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Enkkua, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Vessari, V\u00e4h\u00e4salmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Viialan puustelli, Kaipola, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Ruotsi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"",
"Kostermaa, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"",
"",
"Heikniemi, Hassi, J\u00e4ms\u00e4, Suomi",
"Ilola torp., Kerkkola, J\u00e4ms\u00e4, Suomi",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"",
"Haparainen, Sakkola, Luovutettu Karjala",
"",
"",
"",
"",
"Vuohensalo, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"",
"Salitsanranta, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"",
"Vuohensalo, K\u00e4kisalmen maalaiskunta, Luovutettu Karjala",
"V\u00e4likara, Salmenkyl\u00e4, Pihlajavesi, Keuruu, Suomi",
"Hakolahti, Urjala, Suomi",
"",
"Moksu, \u00c4ht\u00e4ri, Suomi",
"",
"Kruunupyy, Suomi",
"",
"Cadillac, Wexford County, Michigan, USA",
"Jennings, Lake Township, Missaukee County, Michigan, USA",
"Cadillac, Wexford County, Michigan, USA",
"Cadillac, Wexford County, Michigan, USA",
"Cadillac, Wexford County, Michigan, USA",
"",
"",
"",
"Turku, Suomi",
"",
"",
"Ylinen, Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"",
"",
"Ylinen, Yl\u00e4nen, Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00f6vesi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kytt\u00e4l\u00e4, Tampere, Suomi",
"Kavala, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Messukyl\u00e4, Tampere, Suomi",
"",
"",
"",
"",
"Ylti\u00e4, Pihlajavesi, Keuruu, Suomi",
"",
"",
"Kaltila, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-H\u00e4kkinen, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-H\u00e4kkinen, H\u00e4kkiskyl\u00e4, Keuruu, Suomi",
"Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Nikkil\u00e4, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Yrj\u00f6l\u00e4, Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"Vilkkil\u00e4, J\u00e4ms\u00e4, Suomi",
"",
"V\u00e4sterby, Siuntio, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Haapaniemi, Pyh\u00e4j\u00e4rvi Vpl, Luovutettu Karjala",
"Karikko, Pet\u00e4j\u00e4vesi, Suomi",
"\u00c4nkk\u00e4 torp., Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi",
"\u00c4nkk\u00e4 torp., Hopsu, Kerkkola, J\u00e4ms\u00e4, Suomi"
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
