// This file is generated

P_type_0 = [
"Organisaatio",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Tila tai talo",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Rakennus tai torppa",
"Rakennus tai torppa",
"Rakennus tai torppa",
"Kyl\u00e4",
"Rakennus tai torppa",
"Rakennus tai torppa",
"Organisaatio",
"Rakennus tai torppa",
"Kyl\u00e4",
"Oppilaitos",
"Hautausmaa",
"Hautausmaa",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Katuosoite",
"Kaupunginosa",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Kaupunginosa",
"Kyl\u00e4",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Organisaatio",
"Sota",
"Oppilaitos",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Hautausmaa",
"Paikkakunta",
"Kirkko",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kaupunginosa",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kaupunginosa",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Sota",
"Tila tai talo",
"Katuosoite",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Rakennus tai torppa",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Laitos",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Rakennus tai torppa",
"Rakennus tai torppa",
"Kyl\u00e4",
"Rakennus tai torppa",
"Rakennus tai torppa",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kaupunginosa",
"Kyl\u00e4",
"Kirkko",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Rakennus tai torppa",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Katuosoite",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Laitos",
"Kaupunginosa",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kaupunginosa",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kaupunginosa",
"Tila tai talo",
"Kyl\u00e4",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Katuosoite",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Hautausmaa",
"Kirkko",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Organisaatio",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Organisaatio",
"Sota",
"Kaupunginosa",
"Valtio tai liittovaltio",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Sota",
"Tila tai talo",
"Kaupunginosa",
"Katuosoite",
"Organisaatio",
"Paikkakunta",
"Organisaatio",
"Taistelu",
"Organisaatio",
"Kyl\u00e4",
"Organisaatio",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Sota",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Valtio tai liittovaltio",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Rakennus tai torppa",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4"
]
Dwr.ScriptLoaded('dwr_db_P_type_0.js');
