// This file is generated

P_type_0 = [
"Tila tai talo",
"Paikkakunta",
"Linna",
"Linna",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Maakunta",
"Tila tai talo",
"Organisaatio",
"Paikkakunta",
"Kirkko",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Laitos",
"Rakennus tai torppa",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Laitos",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Organisaatio",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Alue",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Seurakunta",
"Tila tai talo",
"Paikkakunta",
"Linna",
"Linna",
"Kyl\u00e4",
"Alue",
"Paikkakunta",
"Kyl\u00e4",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Rakennus tai torppa",
"Paikkakunta",
"Paikkakunta",
"Linna",
"Paikkakunta",
"Maakunta",
"Organisaatio",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Alue",
"Linna",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Oppilaitos",
"Paikkakunta",
"Rakennus tai torppa",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Linna",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Rakennus tai torppa",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"L\u00e4\u00e4ni tai osavaltio",
"Maakunta",
"Kirkko",
"Paikkakunta",
"Organisaatio",
"Paikkakunta",
"Tila tai talo",
"Rakennus tai torppa",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Valtio tai liittovaltio",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Rakennus tai torppa",
"Organisaatio",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Laitos",
"Paikkakunta",
"Tila tai talo",
"Alue",
"Tila tai talo",
"Kyl\u00e4",
"Laitos",
"Tila tai talo",
"Paikkakunta",
"Alue",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Organisaatio",
"Paikkakunta",
"Tila tai talo",
"Alue",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Kirkko",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Tila tai talo",
"Rakennus tai torppa",
"Linna",
"Paikkakunta",
"Paikkakunta",
"Laitos",
"Rakennus tai torppa",
"Alue",
"Organisaatio",
"Laitos",
"Linna",
"Kyl\u00e4",
"Alue",
"Tila tai talo",
"Organisaatio",
"Alue",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Organisaatio",
"Kyl\u00e4",
"Rakennus tai torppa",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Maakunta",
"Kyl\u00e4",
"Rakennus tai torppa",
"Paikkakunta",
"Tila tai talo",
"Organisaatio",
"Alue",
"Rakennus tai torppa",
"Organisaatio",
"Maakunta",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Kyl\u00e4",
"Oppilaitos",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Kyl\u00e4",
"Organisaatio",
"Kyl\u00e4",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Hautausmaa",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tuntematon",
"Laitos",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Katuosoite",
"Kaupunginosa",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Alue",
"Organisaatio",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Organisaatio",
"Maakunta",
"Maakunta",
"Linna",
"Organisaatio",
"Paikkakunta",
"Tila tai talo",
"Kaupunginosa",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Linna",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"L\u00e4\u00e4ni tai osavaltio",
"Paikkakunta",
"Tila tai talo",
"Alue",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Sota",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Oppilaitos",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Laitos",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Hautausmaa",
"Linna",
"Alue",
"Paikkakunta",
"Organisaatio",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Paikkakunta",
"Kirkko",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kirkko",
"Organisaatio",
"Kyl\u00e4",
"Paikkakunta",
"Linna",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"L\u00e4\u00e4ni tai osavaltio",
"Tila tai talo",
"Kaupunginosa",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Alue",
"Rakennus tai torppa",
"Kaupunginosa",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Kirkko",
"Kyl\u00e4",
"Tila tai talo",
"Alue",
"Organisaatio",
"Tila tai talo",
"Organisaatio",
"Organisaatio",
"Kirkko",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Sota",
"Rakennus tai torppa",
"Paikkakunta",
"Kyl\u00e4",
"L\u00e4\u00e4ni tai osavaltio",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kirkko",
"L\u00e4\u00e4ni tai osavaltio",
"Laitos",
"Tila tai talo",
"Kirkko",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Organisaatio",
"Tila tai talo",
"Alue",
"Paikkakunta",
"Kirkko",
"Seurakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Sota",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Katuosoite",
"Paikkakunta",
"Tila tai talo",
"Alue",
"Tila tai talo",
"Organisaatio",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Linna",
"Paikkakunta",
"Katu",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Organisaatio",
"Rakennus tai torppa",
"Paikkakunta",
"Seurakunta",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Linna",
"Taistelu",
"Alue",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Maakunta",
"Kirkko",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Kirkko",
"Kyl\u00e4",
"Kyl\u00e4",
"Alue",
"Kyl\u00e4",
"Tila tai talo",
"Laitos",
"Tila tai talo",
"Alue",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"L\u00e4\u00e4ni tai osavaltio",
"Paikkakunta",
"Organisaatio",
"Kyl\u00e4",
"Kyl\u00e4",
"Laitos",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Alue",
"Linna",
"Tila tai talo",
"Kirkko",
"Paikkakunta",
"Kirkko",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Kirkko",
"Linna",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Maakunta",
"Kyl\u00e4",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Kirkko",
"Tila tai talo",
"Paikkakunta",
"Alue",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Vesist\u00f6nosa",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Kirkko",
"Seurakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Paikkakunta",
"Sota",
"Alue",
"Valtio tai liittovaltio",
"Paikkakunta",
"Organisaatio",
"Paikkakunta",
"Maakunta",
"Katu",
"Paikkakunta",
"Alue",
"Organisaatio",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Paikkakunta",
"Linna",
"Linna",
"Kyl\u00e4",
"Tila tai talo",
"Maakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Rakennus tai torppa",
"Kyl\u00e4",
"Rakennus tai torppa",
"Rakennus tai torppa",
"Rakennus tai torppa",
"Kyl\u00e4",
"Tila tai talo",
"Organisaatio",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kaupunginosa",
"Kyl\u00e4",
"Alue",
"Linna",
"Kirkko",
"Kyl\u00e4",
"Seurakunta",
"Paikkakunta",
"Alue",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Rakennus tai torppa",
"Paikkakunta",
"Kaupunki",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Organisaatio",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Linna",
"Katuosoite",
"Paikkakunta",
"Seurakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Maakunta",
"Organisaatio",
"Alue",
"Paikkakunta",
"Organisaatio",
"Oppilaitos",
"Organisaatio",
"Tila tai talo",
"Valtio tai liittovaltio",
"Paikkakunta",
"Alue",
"Kyl\u00e4",
"Valtio tai liittovaltio",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Valtio tai liittovaltio",
"Sota",
"Laitos",
"Kaupunginosa",
"Paikkakunta",
"Valtio tai liittovaltio",
"Paikkakunta",
"Seurakunta",
"Kirkko",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kaupunginosa",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Seurakunta",
"Maakunta",
"Kyl\u00e4",
"Organisaatio",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Linna",
"L\u00e4\u00e4ni tai osavaltio",
"Kyl\u00e4",
"Paikkakunta",
"Valtio tai liittovaltio",
"Kyl\u00e4",
"Kyl\u00e4",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Oppilaitos",
"Seurakunta",
"Kyl\u00e4",
"Organisaatio",
"Tila tai talo",
"Laitos",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kirkko",
"Kaupunki",
"Linna",
"Kirkko",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Alue",
"Kirkko",
"Paikkakunta",
"Paikkakunta",
"Rakennus tai torppa",
"Tila tai talo",
"Alue",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Alue",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Alue",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Valtio tai liittovaltio",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Organisaatio",
"Alue",
"Tila tai talo",
"Kirkko",
"Seurakunta",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Linna",
"Kyl\u00e4",
"Kirkko",
"Paikkakunta",
"Laitos",
"Katuosoite",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Organisaatio",
"Maakunta",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Kyl\u00e4",
"Rakennus tai torppa",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Alue",
"Alue",
"Tila tai talo",
"Alue",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Rakennus tai torppa",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Laitos",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Organisaatio",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Hautausmaa",
"Kirkko",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Alue",
"Paikkakunta",
"Kirkko",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Laitos",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Valtio tai liittovaltio",
"Tila tai talo",
"Maakunta",
"Organisaatio",
"Laitos",
"Laitos",
"Paikkakunta",
"Organisaatio",
"Taistelu",
"Taistelu",
"Taistelu",
"Taistelu",
"Kyl\u00e4",
"Rakennus tai torppa",
"Tila tai talo",
"Maakunta",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Kirkko",
"Paikkakunta",
"Kyl\u00e4",
"Organisaatio",
"Paikkakunta",
"Linna",
"Linna",
"Linna",
"Alue",
"Linna",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kirkko",
"Taistelu",
"Katuosoite",
"Rakennus tai torppa",
"Linna",
"Alue",
"Paikkakunta",
"Tuntematon",
"L\u00e4\u00e4ni tai osavaltio",
"Kyl\u00e4",
"Kyl\u00e4",
"Organisaatio",
"Organisaatio",
"Tila tai talo",
"Kyl\u00e4",
"Organisaatio",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Organisaatio",
"Organisaatio",
"Sota",
"Kaupunginosa",
"Valtio tai liittovaltio",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Laitos",
"Linna",
"Kyl\u00e4",
"Laitos",
"Alue",
"Alue",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Paikkakunta",
"Maakunta",
"Paikkakunta",
"Kaupunki",
"Kirkko",
"Paikkakunta",
"Alue",
"Paikkakunta",
"Paikkakunta",
"Kirkko",
"Kyl\u00e4",
"Kaupunki",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Sota",
"Tila tai talo",
"Paikkakunta",
"Kaupunginosa",
"Katuosoite",
"Paikkakunta",
"Organisaatio",
"Paikkakunta",
"Organisaatio",
"Taistelu",
"Organisaatio",
"Valtio tai liittovaltio",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Laitos",
"Paikkakunta",
"Linna",
"Alue",
"Paikkakunta",
"Tila tai talo",
"Kirkko",
"Valtio tai liittovaltio",
"Organisaatio",
"Organisaatio",
"Kyl\u00e4",
"Tila tai talo",
"Alue",
"Alue",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Sota",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Kirkko",
"Paikkakunta",
"Organisaatio",
"Alue",
"Tila tai talo",
"Kaupunki",
"Tuntematon",
"Paikkakunta",
"Linna",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Oppilaitos",
"Organisaatio",
"L\u00e4\u00e4ni tai osavaltio",
"Linna",
"Organisaatio",
"Kirkko",
"Tila tai talo",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Linna",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Seurakunta",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Maakunta",
"Organisaatio",
"Kirkko",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"L\u00e4\u00e4ni tai osavaltio",
"Organisaatio",
"Paikkakunta",
"Tila tai talo",
"Paikkakunta",
"Laitos",
"Paikkakunta",
"Kyl\u00e4",
"Rakennus tai torppa",
"Alue",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Linna",
"Maakunta",
"Paikkakunta",
"Organisaatio",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Kyl\u00e4",
"Valtio tai liittovaltio",
"Sota",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Kyl\u00e4",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Tila tai talo",
"Kyl\u00e4",
"Paikkakunta",
"Linna",
"Alue",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Valtio tai liittovaltio",
"Tila tai talo",
"Alue",
"Organisaatio",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Paikkakunta",
"Linna",
"Paikkakunta",
"Laitos",
"Kyl\u00e4",
"Rakennus tai torppa",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Kyl\u00e4",
"Kyl\u00e4",
"Alue",
"Organisaatio",
"Alue",
"Maakunta",
"Organisaatio",
"Paikkakunta",
"L\u00e4\u00e4ni tai osavaltio",
"Tila tai talo",
"Maakunta",
"Paikkakunta",
"Kirkko",
"Paikkakunta",
"Kirkko",
"Linna",
"Paikkakunta",
"Maakunta",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Kyl\u00e4",
"Kyl\u00e4",
"Alue",
"Organisaatio",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Organisaatio",
"Alue",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Tila tai talo",
"Paikkakunta",
"Tila tai talo",
"Tila tai talo",
"Organisaatio",
"Organisaatio",
"Organisaatio",
"Linna",
"Tila tai talo",
"Tila tai talo",
"Maakunta",
"Organisaatio",
"Tila tai talo",
"Paikkakunta",
"Linna",
"Tila tai talo",
"Paikkakunta",
"Maakunta",
"Alue",
"Tila tai talo",
"Paikkakunta",
"Linna",
"Linna",
"Organisaatio",
"Maakunta",
"Organisaatio",
"Kyl\u00e4",
"Kyl\u00e4",
"Paikkakunta",
"Alue",
"Organisaatio",
"Paikkakunta",
"Organisaatio",
"Paikkakunta",
"Paikkakunta",
"Paikkakunta",
"Tila tai talo"
]
Dwr.ScriptLoaded('dwr_db_P_type_0.js');
