// This file is generated

P_name_0 = [
"Aagaard, Kettrup Sogn, Jutland, Tanska",
"Aalborg, Nordjylland, Tanska",
"Aalborghus, Nordjylland, Tanska",
"Aalborgshus, Aalborg, Nordjylland, Tanska",
"Aaltosen Kenk\u00e4tehdas Oy, Kyllikinkatu 13-15, Tammela, Tampere, Suomi",
"Aarhus, Tanska",
"Adel\u00f6vs socken, Sm\u00e5land, Ruotsi",
"Ahvenanmaa, Suomi",
"Ahvenkosken kartano, Pyht\u00e4\u00e4, Suomi",
"Airam Oy Ab, Helsinki, Suomi",
"Akaa, Suomi",
"Akaan kirkko, Toijala, Akaa, Suomi",
"Ala-Marttila, Jokioinen, Kangasala, Suomi",
"Ala-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ala-Tanhuanp\u00e4\u00e4, Riku, Kangasala, Suomi",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"Alanen, Kautiala, Kangasala, Suomi",
"Alanen, Tarpila, Kangasala, Suomi",
"Alasjoen kartano, Tavastila, Mietoinen, Myn\u00e4m\u00e4ki, Suomi",
"Alatalo, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Albergan kartano, Stora Hoplax, Espoo, Suomi",
"Alkkula, Viiala, Akaa, Suomi",
"Altuna socken, Simtuna h\u00e4rad, Uppland, Ruotsi",
"Alunda socken, Uppland, Ruotsi",
"Alvastra kloster, V\u00e4stra Tollstads socken, \u00d6sterg\u00f6tland, Ruotsi",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"Angel, Schleswig, S\u00f8nderjylland, Tanska",
"Ania, Pirkkala, Suomi",
"Annisse, Tanska",
"Antskog, Raasepori, Suomi",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Anttila, P\u00e4ilahti, Orivesi, Suomi",
"Anttila, Raronsalo, Kangasala, Suomi",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"Apajapohja, Kangasala, Suomi",
"Arboga kloster, Arboga socken, V\u00e4stmanland, Ruotsi",
"Arboga socken, V\u00e4stmanland, Ruotsi",
"Arra, Moltsia, Sahalahti, Kangasala, Suomi",
"Arran rustoholi, Moltsia, Sahalahti, Kangasala, Suomi",
"Aska h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Askers h\u00e4rad, N\u00e4rke, Svealand, Ruotsi",
"Askers socken, Askers h\u00e4rad, N\u00e4rke, Svealand, Ruotsi",
"Askersunds socken, Sundbo h\u00e4rad, N\u00e4rke, Svealand, Ruotsi",
"Askeryds socken, Sm\u00e5land, Ruotsi",
"Ask\u00f8y, Norja",
"Aspen\u00e4s, Malexanders socken, Ydre h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Aspinge, Hurva socken, Sk\u00e5ne, Ruotsi",
"Aspn\u00e4s, \u00d6sterv\u00e5la socken, V\u00e5la h\u00e4rad, Uppland, Ruotsi",
"Asp\u00f6 socken i S\u00f6dermanland, Selebo h\u00e4rad, S\u00f6dermanland, Ruotsi",
"Aura, Suomi",
"Auran seurakunta, Suomen ev.lut. kirkko",
"Autionmaa, Hulipas, Juupajoki, Suomi",
"Avignon, Ranska",
"Axevalla hus, V\u00e4sterg\u00f6tland, Ruotsi",
"Axevalla slott, V\u00e4sterg\u00f6tland, Ruotsi",
"Backa by, Inkoo, Suomi",
"Baden-W\u00fcrttemberg, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Balingsta socken, Hagunda h\u00e4rad, Uppland, Ruotsi",
"Ballenstedt, Harz, Sachsen, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Bankekinds h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Barkar\u00f6 socken, V\u00e4stmanland, Ruotsi",
"Bavelse Sogn, Tanska",
"Bavelse, Bavelse Sogn, Tanska",
"Benhamra, Vada socken, Uppland, Ruotsi",
"Berga socken, Sunnerbo h\u00e4rad, Sm\u00e5land, Ruotsi",
"Bergen, Norja",
"Bergunda socken, Kinnevalds h\u00e4rad, Sm\u00e5land, Ruotsi",
"Bergunda, Bergunda socken, Kinnevalds h\u00e4rad, Sm\u00e5land, Ruotsi",
"Bernburg, Sachsen, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Bertuli torp, Setola, Karnainen, Lohja, Suomi",
"Bettna socken, S\u00f6dermanland, Ruotsi",
"Bjurums socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Bj\u00e4rkaholm, \u00d6sterg\u00f6tland, Ruotsi",
"Bj\u00f6rs\u00e4ters socken, \u00d6sterg\u00f6tland, Ruotsi",
"Blekinge, G\u00f6taland, Ruotsi",
"Bobergs h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Bogesund, V\u00e4sterg\u00f6tland, Ruotsi",
"Bollstad s\u00e4teri, Bollstad, Inkoo, Suomi",
"Bollstad, Inkoo, Suomi",
"Bordsj\u00f6, Askeryds socken, Sm\u00e5land, Ruotsi",
"Borg, Brede, T\u00f8nder, Syddanmark, Tanska",
"Borgby, Sipoo, Suomi",
"Borgesyssel, Norja",
"Borgholm, \u00d6land, Ruotsi",
"Borreg\u00e5rd, Tune, \u00d8stfold, Norja",
"Bosg\u00e5rden, M\u00f6lneby, \u00d6stra Fr\u00f6lunda socken, Kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Brandenburg, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Brandenburgische Universit\u00e4t Frankfurt, Frankfurt an der Oder, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Brede, T\u00f8nder, Syddanmark, Tanska",
"Bredvik torp, Bredvik, Karjaa, Raasepori, Suomi",
"Bredvik, Karjaa, Raasepori, Suomi",
"Bregnholm, Jylland, Tanska",
"Bro h\u00e4rad, Uppland, Ruotsi",
"Bro\u00e4nda, Perni\u00f6, Salo, Suomi",
"Brunsberg, Yttersel\u00f6 socken, S\u00f6dermanland, Ruotsi",
"Br\u00f6msehus, Blekinge, G\u00f6taland, Ruotsi",
"Bystad, Askers socken, Askers h\u00e4rad, N\u00e4rke, Svealand, Ruotsi",
"B\u00e5laby \u00d6verg\u00e5rd, B\u00e5laby, Karjaa, Raasepori, Suomi",
"B\u00e5laby, Karjaa, Raasepori, Suomi",
"B\u00e4cks torparen, Myrans, Siuntio, Suomi",
"B\u00e4linge socken i S\u00f6dermanland, R\u00f6n\u00f6 h\u00e4rad, S\u00f6dermanland, Ruotsi",
"B\u00f6ne socken, Redv\u00e4gs h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Clausholm, Voldum Sogn, Midtjylland, Tanska",
"Dalarna, Ruotsi",
"Dalsland, G\u00f6taland, Ruotsi",
"Dalums kyrka, Dalums socken, Redv\u00e4gs h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Dalums socken, Redv\u00e4gs h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Danderyd h\u00e4rad, Uppland, Ruotsi",
"Danzig, Preussi",
"Demstrup, R\u00e5by Sogn, Jutland, Tanska",
"Dragon torp, Laakspohja, Lohja, Suomi",
"Edebo socken, Uppland, Ruotsi",
"Eerola, Vehkalahti, Orivesi, Suomi",
"Eerolan rustholli, Rautio, Sahalahti, Kangasala, Suomi",
"Ejby Sogn, Tanska",
"Ekeberg herrg\u00e5rd, Lillkyrka socken i N\u00e4rke, N\u00e4rke, Svealand, Ruotsi",
"Ekholmen, Veckholms socken, Tr\u00f6gds h\u00e4rad, Uppland, Ruotsi",
"Ekhult, Bj\u00f6rs\u00e4ters socken, \u00d6sterg\u00f6tland, Ruotsi",
"Ekornarp, Berga socken, Sunnerbo h\u00e4rad, Sm\u00e5land, Ruotsi",
"Ellinge, V\u00e4stra Sallerups socken, Harjagers h\u00e4rad, Sk\u00e5ne, Ruotsi",
"Englanti",
"Enk\u00f6ping, Uppland, Ruotsi",
"Epaala, P\u00e4lk\u00e4ne, Suomi",
"Epil\u00e4, Raikku, Kangasala, Suomi",
"Erikstad, Vittaryds sochen, Sunnerbo h\u00e4rad, Sm\u00e5land, Ruotsi",
"Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Erkkil\u00e4n rustholli, Kaltsila, Vesilahti, Suomi",
"Ervalla herrg\u00e5rd, Ervalla socken, V\u00e4stmanland, Ruotsi",
"Ervalla socken, V\u00e4stmanland, Ruotsi",
"Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Er\u00e4slahti, Orivesi, Suomi",
"Eskola, Haapasaari, Kuhmalahti, Kangasala, Suomi",
"Eskola, Vehkalahti, Orivesi, Suomi",
"Espoo, Suomi",
"Estb\u00f6le, \u00c5minne s\u00e4teri, Pohja, Raasepori, Suomi",
"Etel\u00e4-Suomen laamannikunta, Suomi",
"Ettaks kungsg\u00e5rd, Vartofta h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Eura, Suomi",
"Fagervik, Inkoo, Suomi",
"Fagervikin ruukki, Fagervik, Inkoo, Suomi",
"Falk\u00f6ping, V\u00e4sterg\u00f6tland, Ruotsi",
"Fareb\u00e6ksholm, Ejby Sogn, Tanska",
"Finnveden, Sm\u00e5land, Ruotsi",
"Finsta g\u00e5rd, Skederids socken, Uppland, Ruotsi",
"Fiskars, Raasepori, Suomi",
"Fiskarsin ruukki, Fiskars, Raasepori, Suomi",
"Fituna, Sorunda socken, S\u00f6dermanland, Ruotsi",
"Fjenneslev, Sj\u00e6lland, Tanska",
"Flandern",
"Florv\u00e5g, Ask\u00f8y, Norja",
"Folkenborg, Borgesyssel, Norja",
"Folln\u00e4s, Sorunda socken, S\u00f6dermanland, Ruotsi",
"Frankfurt an der Oder, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Frederikssund, Sj\u00e6lland, Tanska",
"Fredrikstad, Norja",
"Frinnaryds socken, Sm\u00e5land, Ruotsi",
"Fr\u00f6kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Fr\u00f6sthults socken, Uppland, Ruotsi",
"Fr\u00f6svik, \u00d6stra Ryds socken i Uppland, Danderyd h\u00e4rad, Uppland, Ruotsi",
"Fr\u00f6tuna skeppslag, Roslagen, Uppland, Ruotsi",
"F\u00e5gelvik, Tryserums socken, Sm\u00e5land, Ruotsi",
"F\u00e5n\u00f6, L\u00f6ts socken, Uppland, Ruotsi",
"F\u00e4rsaaret",
"Gainsborough, Lincolnshire, Englanti",
"Gamla Vinstorp, B\u00f6ne socken, Redv\u00e4gs h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Gammalkils socken, Valkebo h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Gammelby kyrka, Sm\u00e5land, Ruotsi",
"Glads rakuunatorppa, Veijola, Lohja, Suomi",
"Glaskulla, V\u00e5rkumla socken, Fr\u00f6kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Glottra, Runtuna socken, S\u00f6dermanland, Ruotsi",
"Gotland, Ruotsi",
"Grabbacka, Karjaa, Raasepori, Suomi",
"Grams, Mutikko, Kangasala, Suomi",
"Gripsholm, S\u00f6dermanland, Ruotsi",
"Grolanda socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Grue, Norja",
"Gr\u00e5br\u00f6draklostret i Stockholm, Tukholma, Ruotsi",
"Gr\u00f6nkulla torp, Utan\u00e5ker, Inkoo, Suomi",
"Gr\u00f6nlanti",
"Gudhems h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Gudhems kloster, Falk\u00f6ping, V\u00e4sterg\u00f6tland, Ruotsi",
"G\u00e4ddeholm, S\u00f6dermanland, Ruotsi",
"G\u00e4stre, Fr\u00f6sthults socken, Uppland, Ruotsi",
"G\u00e4strikland, Norrland, Ruotsi",
"G\u00f6ksholm, Stora Mell\u00f6sa socken, Askers h\u00e4rad, N\u00e4rke, Svealand, Ruotsi",
"G\u00f6strings h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"G\u00f6taland, Ruotsi",
"G\u00f6tene g\u00e5rd, G\u00f6tene socken, Kinne h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"G\u00f6tene socken, Kinne h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Haapaniemi, Kangasala, Suomi",
"Haapaniemi, Kisko, Salo, Suomi",
"Haapasaari, Kuhmalahti, Kangasala, Suomi",
"Hagunda h\u00e4rad, Uppland, Ruotsi",
"Haihunkoski, Viiala, Akaa, Suomi",
"Haittola torp, Veijola, Lohja, Suomi",
"Hakim\u00e4en rustholli, Hakkila, Vesilahti, Suomi",
"Hakkila, Urjala, Suomi",
"Hakkila, Vesilahti, Suomi",
"Halikko, Salo, Suomi",
"Halikon kihlakunta, Suomi",
"Halland, Ruotsi",
"Hallila, Messukyl\u00e4, Tampere, Suomi",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Hamina, Suomi",
"Hampaalan rustholli, Pakkala, Sahalahti, Kangasala, Suomi",
"Hankkija Oy, Tampere, Suomi",
"Haraldsted skog, Ringsted, Sj\u00e6lland, Tanska",
"Harapakka, Veijola, Lohja, Suomi",
"Harjagers h\u00e4rad, Sk\u00e5ne, Ruotsi",
"Harjumaa, Viro",
"Harkki, Haihunkoski, Viiala, Akaa, Suomi",
"Harola, Talviainen, Orivesi, Suomi",
"Harz, Sachsen, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Hatanp\u00e4\u00e4, Tampere, Suomi",
"Hatanp\u00e4\u00e4n koulu, H\u00e4rm\u00e4l\u00e4, Tampere, Suomi",
"Hattelmala, Vanaja, Suomi",
"Hattula, Suomi",
"Hattulan kihlakunta, Suomi",
"Haudanniemi, Toijala, Akaa, Suomi",
"Hauhon kihlakunta, Suomi",
"Haurala, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Hauta kirkon alla, Akaan kirkko, Toijala, Akaa, Suomi",
"Hauta kirkon alla, Kalvolan kirkko, Kalvola, H\u00e4meenlinna, Suomi",
"Hauta kirkon alla, Kangasalan kirkko, Kangasala, Suomi",
"Hauta kirkon alla, Keuruun kirkko, Keuruu, Suomi",
"Hauta kirkon alla, Kuhmalahden kirkko, Kuhmalahti, Kangasala, Suomi",
"Hauta kirkon alla, Kuoreveden kirkko, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Hauta kirkon alla, L\u00e4ngelm\u00e4en kirkko, Orivesi, Suomi",
"Hauta kirkon alla, Messukyl\u00e4n kirkko, Messukyl\u00e4, Tampere, Suomi",
"Hauta kirkon alla, Oriveden kirkko, Oriveden kyl\u00e4, Orivesi, Suomi",
"Hauta kirkon alla, P\u00e4lk\u00e4neen Pyh\u00e4n Mikaelin kirkko, P\u00e4lk\u00e4ne, Suomi",
"Hauta kirkon alla, Sahalahden kirkko, Sahalahti, Kangasala, Suomi",
"Hauta kirkossa, Karjaan kirkko, Karjaa, Raasepori, Suomi",
"Hauta kirkossa, Messukyl\u00e4n kirkko, Messukyl\u00e4, Tampere, Suomi",
"Hauta kirkossa, P\u00e4lk\u00e4neen Pyh\u00e4n Mikaelin kirkko, P\u00e4lk\u00e4ne, Suomi",
"Hauta kirkossa, Taivassalon kirkko, Taivassalo, Suomi",
"Haviseva, Kangasala, Suomi",
"Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"Heikkil\u00e4, Hakkila, Urjala, Suomi",
"Heikkil\u00e4, Hyk\u00f6nsalo, Kangasala, Suomi",
"Heikkil\u00e4, Neulaniemi, Kangasala, Suomi",
"Heikkil\u00e4, Rautio, Sahalahti, Kangasala, Suomi",
"Heikkil\u00e4, Sarkkila, Viiala, Akaa, Suomi",
"Heikkil\u00e4n rustholli, Ania, Pirkkala, Suomi",
"Hein\u00e4s, V\u00e4h\u00e4-Teutari, Lohja, Suomi",
"Helga Lekamens kor, Turun tuomiokirkko, Turku, Suomi",
"Helgeseter kloster, Trondheim, Norja",
"Helsingborg, Sk\u00e5ne, Ruotsi",
"Helsinki, Suomi",
"Hemil\u00e4, K\u00e4rv\u00e4nt\u00e4l\u00e4, P\u00e4lk\u00e4ne, Suomi",
"Heponiemi, Kangasala, Suomi",
"Herdedal, Inkoo, Suomi",
"Herrs\u00e4ter, V\u00e4rna socken, \u00d6sterg\u00f6tland, Ruotsi",
"Hervannantie 33, Viinikka, Tampere, Suomi",
"Hervanta, Tampere, Suomi",
"Hettusen rustholli, Tursola, Sahalahti, Kangasala, Suomi",
"Hiiren rustholli, Miemola, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Hindsgavl, Middelfart, Syddanmark, Tanska",
"Hinkka, Hypp\u00e4ril\u00e4, Kangasala, Suomi",
"Hinkkala, Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"Hinkkalan rustholli, Vedentaka, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Hinsala, Vesilahti, Suomi",
"Hirtolahti, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Hirvij\u00e4rvi, Juupajoki, Suomi",
"Hjalmaryd, Ljungby socken i Sunnerbo h\u00e4rad, Kronobergs l\u00e4n, Sm\u00e5land, Ruotsi",
"Hofs slottsl\u00e4n, \u00d6sterg\u00f6tland, Ruotsi",
"Hollolan kihlakunta, Suomi",
"Hov, Hovs socken i \u00d6sterg\u00f6tland, G\u00f6strings h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Hovs socken i \u00d6sterg\u00f6tland, G\u00f6strings h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Hukia, Hinsala, Vesilahti, Suomi",
"Hulipas, Juupajoki, Suomi",
"Hultti, Toijala, Akaa, Suomi",
"Hurva socken, Sk\u00e5ne, Ruotsi",
"Husaby strand, S\u00f6derk\u00f6ping, \u00d6sterg\u00f6tland, Ruotsi",
"Huseby, Ons\u00f8y, Fredrikstad, Norja",
"Huti, Sauvala, Kalvola, H\u00e4meenlinna, Suomi",
"Huunan rustholli, Haapasaari, Kuhmalahti, Kangasala, Suomi",
"Hyk\u00f6nsalo, Kangasala, Suomi",
"Hypp\u00e4ril\u00e4, Kangasala, Suomi",
"H\u00e5bo h\u00e4rad, Uppland, Ruotsi",
"H\u00e4lsingland, Ruotsi",
"H\u00e4meen historiallinen maakunta, Suomi",
"H\u00e4meen linna, H\u00e4meenlinna, Suomi",
"H\u00e4meen tiepiiri, Tie- ja vesirakennushallitus TVH, Suomi",
"H\u00e4meenlinna, Suomi",
"H\u00e4rl\u00f6v, Norra \u00c5sums socken, Sk\u00e5ne, Ruotsi",
"H\u00e4rm\u00e4l\u00e4, Tampere, Suomi",
"H\u00e4steryd, Frinnaryds socken, Sm\u00e5land, Ruotsi",
"H\u00e4sthalla, Skallmeja socken, Sk\u00e5nings h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"H\u00e4til\u00e4, H\u00e4meenlinna, Suomi",
"H\u00f6lebo h\u00e4rad, S\u00f6dermanland, Ruotsi",
"H\u00f6lli, T\u00f6yk\u00e4n\u00e4, Sahalahti, Kangasala, Suomi",
"H\u00f6llil\u00e4, V\u00e4nnil\u00e4, Vesilahti, Suomi",
"H\u00f6llin rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"H\u00f6rningsholms slott, M\u00f6rk\u00f6 socken, S\u00f6dermanland, Ruotsi",
"Ihari, Kangasala, Suomi",
"Iharinkoski, Ihari, Kangasala, Suomi",
"Ilkko, Kangasala, Suomi",
"Illans, Backa by, Inkoo, Suomi",
"Ilola, Sahalahti, Kangasala, Suomi",
"Ilom\u00e4ki, Koppala, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Immula, Lohja, Suomi",
"Inkerinmaa, Ven\u00e4j\u00e4",
"Inkoo, Suomi",
"Irjalan rustholli, Takahuhti, Messukyl\u00e4, Tampere, Suomi",
"Islanti",
"Iso-Arran rustholli, Moltsia, Sahalahti, Kangasala, Suomi",
"Iso-Jussila, Jokioinen, Kangasala, Suomi",
"Iso-Kaulo, Kaulo, Toijala, Akaa, Suomi",
"Isolahti, Sahalahti, Kangasala, Suomi",
"Isotalo, Laitila, Suomi",
"Isotalo, Suomela, Kangasala, Suomi",
"Itil\u00e4, Junnila, Vesilahti, Suomi",
"It\u00e4-Jerusalem",
"Ivangorods f\u00e4stning, Ven\u00e4j\u00e4",
"J. W. Enqvist Oy, Tampere, Suomi",
"Jaakkola, Kuru, Kangasala, Suomi",
"Jaakkola, Nihattula, Hattula, Suomi",
"jatkosota, toinen maailmansota",
"Jerusalem",
"Joenpohja, Tottij\u00e4rvi, Nokia, Suomi",
"Joensuun kartano, Halikko, Salo, Suomi",
"Johanneksen koulu, Keskusta, Tampere, Suomi",
"Jokela, Rassa, Kaakila, Vesilahti, Suomi",
"Jokioinen, Kangasala, Suomi",
"Joppi, Hinsala, Vesilahti, Suomi",
"Joutsiniemi, Kangasala, Suomi",
"Julita kloster, Julita socken, S\u00f6dermanland, Ruotsi",
"Julita socken, S\u00f6dermanland, Ruotsi",
"Junnila, Vesilahti, Suomi",
"Jussila, Mierola, Hattula, Suomi",
"Jussilan rustholli, Rautio, Sahalahti, Kangasala, Suomi",
"Jutland, Tanska",
"Juupajoki, Suomi",
"Juusela, Ilola, Sahalahti, Kangasala, Suomi",
"Juva, Hallila, Messukyl\u00e4, Tampere, Suomi",
"Jylland, Tanska",
"J\u00e4ms\u00e4, Suomi",
"J\u00e4rvenper\u00e4, Kopsamo, Juupajoki, Suomi",
"J\u00e4rvenp\u00e4\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"J\u00e4rvenp\u00e4\u00e4, Laurila, Haapaniemi, Kangasala, Suomi",
"J\u00e4rvenranta, Vesilahti, Suomi",
"J\u00f6nsb\u00f6le, Lohja, Suomi",
"Kaakila, Vesilahti, Suomi",
"Kaarina, Suomi",
"Kalevankankaan hautausmaa, Tampere, Suomi",
"Kalmar slott, Kalmar, Sm\u00e5land, Ruotsi",
"Kalmar slottsl\u00e4n, Sm\u00e5land, Ruotsi",
"Kalmar, Sm\u00e5land, Ruotsi",
"Kalmarin unioni",
"Kaltsila, Vesilahti, Suomi",
"Kalvola, H\u00e4meenlinna, Suomi",
"Kalvolan kirkko, Kalvola, H\u00e4meenlinna, Suomi",
"Kangasala, Suomi",
"Kangasalan kirkko, Kangasala, Suomi",
"Kaninkola, Halikko, Salo, Suomi",
"Kankaisten kartano, Masku, Suomi",
"Karjaa, Raasepori, Suomi",
"Karjaan kirkko, Karjaa, Raasepori, Suomi",
"Karjalan laamannikunta, Suomi",
"Karjaskyl\u00e4, Uskela, Salo, Suomi",
"Karlsborg, V\u00e4sterg\u00f6tland, Ruotsi",
"Karlsborgs f\u00e4stning, Karlsborg, V\u00e4sterg\u00f6tland, Ruotsi",
"Karlstorps socken, Njudungs historiska sm\u00e5 landen, Sm\u00e5land, Ruotsi",
"Karnainen, Lohja, Suomi",
"Karo, Haudanniemi, Toijala, Akaa, Suomi",
"Karppi, S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Karttiala, Tursola, Kangasala, Suomi",
"Karuna, Sauvo, Suomi",
"Kasila, Vedentaka, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Kastelholms l\u00e4n, Ahvenanmaa, Suomi",
"Kataja, Haudanniemi, Toijala, Akaa, Suomi",
"Katajaluoto, Helsinki, Suomi",
"Kaukanen, Kuivanen, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Kauko, Ojoinen, Vesilahti, Suomi",
"Kaulo, Toijala, Akaa, Suomi",
"Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Kauppila, Pakkala, Sahalahti, Kangasala, Suomi",
"Kautiala, Kangasala, Suomi",
"Kedjen\u00e4s, \u00c4lghults socken, V\u00e4rend, Sm\u00e5land, Ruotsi",
"Keljo, Ihari, Kangasala, Suomi",
"Keljo, Sahalahti, Kangasala, Suomi",
"Kemi\u00f6nsaari, Suomi",
"Kerppola, Kangasala, Suomi",
"Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Keski-Eurooppa",
"Keskinen, Liuksiala, Kangasala, Suomi",
"Keskusta, Tampere, Suomi",
"Keso, Kangasala, Suomi",
"Ketarsalmi, Taivassalo, Suomi",
"Kettrup Sogn, Jutland, Tanska",
"Keuruu, Suomi",
"Keuruun kirkko, Keuruu, Suomi",
"Keuruunkyl\u00e4, Keuruu, Suomi",
"Kiesil\u00e4, Niemenkyl\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Kiev",
"Kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Kinnari, Hinsala, Vesilahti, Suomi",
"Kinne h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Kinnevalds h\u00e4rad, Sm\u00e5land, Ruotsi",
"Kirche des Stiftes Ballenstedt, Ballenstedt, Harz, Sachsen, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Kirkniemen kartano, Kirkniemi, Lohja, Suomi",
"Kirkniemi, Lohja, Suomi",
"Kirkwall, Orkneysaaret, Skotlanti",
"Kirvel\u00e4, Nummi, Nousiainen, Suomi",
"Kisko, Salo, Suomi",
"Kittfall, Lohja, Suomi",
"Klemola, Hattelmala, Vanaja, Suomi",
"Klemola, Ohtola, Kangasala, Suomi",
"Koivisto, Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Koivisto, Kangasala, Suomi",
"Koivisto, Koivisto, Kangasala, Suomi",
"Koivisto, Sukkila, Juupajoki, Suomi",
"Kokkila, Juupajoki, Suomi",
"Kolmikymmenvuotinen sota (1618-1648)",
"Kongehallen, Bergen, Norja",
"Konstanz, Baden-W\u00fcrttemberg, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Koppala, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Kopparbergs l\u00e4n, Dalarna, Ruotsi",
"Koppeloj\u00e4rvi, Juupajoki, Suomi",
"Kopsamo, Juupajoki, Suomi",
"Korpiniemi, Sahalahti, Kangasala, Suomi",
"Korppoo, Voitila, Orivesi, Suomi",
"Korpraalin puustelli eli virkatalo, Kataja, Haudanniemi, Toijala, Akaa, Suomi",
"Kottila, Paatiala, Sahalahti, Kangasala, Suomi",
"Kourlan kartano, Olkkala, Vihti, Suomi",
"Kristkirken, Bergen, Norja",
"Kronobergs l\u00e4n, Sm\u00e5land, Ruotsi",
"Kronob\u00e4cks johanniterkloster, M\u00f6nster\u00e5s socken, Sm\u00e5land, Ruotsi",
"Kr\u00e5kerum, M\u00f6nster\u00e5s socken, Sm\u00e5land, Ruotsi",
"Kuhmalahden kirkko, Kuhmalahti, Kangasala, Suomi",
"Kuhmalahti, Kangasala, Suomi",
"Kuivanen, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Kuivanen, Kuivanen, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Kullings h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Kungs Norrby, Motala, \u00d6sterg\u00f6tland, Ruotsi",
"Kungskullen, Levene socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Kungslena socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Kuoreveden kirkko, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuoreveden seurakunta, Suomen ev.lut. kirkko",
"Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kuru, Kangasala, Suomi",
"Kurvola, Toijala, Akaa, Suomi",
"Kustaa III:n sota",
"Kuuliala, P\u00e4lk\u00e4ne, Suomi",
"Kvie, Vang, Valdres, Norja",
"Kylkilahti, Suomasema, Orivesi, Suomi",
"Kyllikinkatu 13-15, Tammela, Tampere, Suomi",
"Kylm\u00e4koski, Akaa, Suomi",
"Kyl\u00e4-K\u00e4rki rustholli, Hinsala, Vesilahti, Suomi",
"Kypros",
"Ky\u00f6stil\u00e4, Savo, Kangasala, Suomi",
"K\u00e5llands h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"K\u00e4kisalmi, Luovutettu Karjala",
"K\u00e4rkniemi, Karuna, Sauvo, Suomi",
"K\u00e4rv\u00e4nt\u00e4l\u00e4, P\u00e4lk\u00e4ne, Suomi",
"K\u00e4r\u00e4v\u00e4, Vuoltee, Kylm\u00e4koski, Akaa, Suomi",
"K\u00f8benhavns Slot, K\u00f6penhamn, Tanska",
"K\u00f6penhamn, Tanska",
"K\u00f6pmangatan, Tukholma, Ruotsi",
"K\u00f6ssi, Oriveden kyl\u00e4, Orivesi, Suomi",
"K\u00f6ssil\u00e4, T\u00f6yk\u00e4n\u00e4, Sahalahti, Kangasala, Suomi",
"K\u00f6yli\u00f6, S\u00e4kyl\u00e4, Suomi",
"K\u00f6yr\u00e4, Kangasala, Suomi",
"Laakspohja, Lohja, Suomi",
"Laakspohjan kartano, Laakspohja, Lohja, Suomi",
"Laatu, Saviniemi, Kylm\u00e4koski, Akaa, Suomi",
"Lagn\u00f6, Asp\u00f6 socken i S\u00f6dermanland, Selebo h\u00e4rad, S\u00f6dermanland, Ruotsi",
"Lagunda h\u00e4rad, Uppland, Ruotsi",
"Lahdenpohja, \u00c4rr\u00e4l\u00e4, Voitila, Orivesi, Suomi",
"Laitila, Suomi",
"Laitilan seurakunta, Suomen ev.lut. kirkko",
"Lammi, H\u00e4meenlinna, Suomi",
"Langi, J\u00f6nsb\u00f6le, Lohja, Suomi",
"Lassa, Kittfall, Lohja, Suomi",
"Laukko, Vesilahti, Suomi",
"Laukon kartano, Laukko, Vesilahti, Suomi",
"Laurila, Alkkula, Viiala, Akaa, Suomi",
"Laurila, Haapaniemi, Kangasala, Suomi",
"Laurila, Lohnattila, Vesilahti, Suomi",
"Laurila, M\u00e4lki\u00e4inen, Valkeakoski, Suomi",
"Laurilan rustholli, Korpiniemi, Sahalahti, Kangasala, Suomi",
"Laurilan rustholli, Taustiala, Sahalahti, Kangasala, Suomi",
"Lejre Municipality, Tanska",
"Lemp\u00e4\u00e4l\u00e4, Suomi",
"Lemu, Masku, Suomi",
"Lepist\u00f6, Myn\u00e4m\u00e4ki, Suomi",
"Leuku, Pirkkalankyl\u00e4, Pirkkala, Suomi",
"Levene socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Lidk\u00f6ping, V\u00e4sterg\u00f6tland, Ruotsi",
"Lihulan linna, P\u00e4rnumaa, Viro",
"Lihulan taistelu, Lihulan linna, P\u00e4rnumaa, Viro",
"Liivinmaa",
"Liljevik, Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Lillkyrka socken i N\u00e4rke, N\u00e4rke, Svealand, Ruotsi",
"Lillungs, \u00d6stersolberg, Inkoo, Suomi",
"Lincolnshire, Englanti",
"Lindk\u00f6pings domkyrka, Link\u00f6ping, \u00d6sterg\u00f6tland, Ruotsi",
"Link\u00f6ping, \u00d6sterg\u00f6tland, Ruotsi",
"Lintulan rustholli, Paalila, Kangasala, Suomi",
"Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Liukon rustholli, J\u00e4rvenranta, Vesilahti, Suomi",
"Liuksiala, Kangasala, Suomi",
"Liuksialan kartano, Liuksiala, Kangasala, Suomi",
"Ljungby socken i Sunnerbo h\u00e4rad, Kronobergs l\u00e4n, Sm\u00e5land, Ruotsi",
"Lo slott, L\u00e5ngareds socken, Kullings h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Lohja, Suomi",
"Lohjan Pyh\u00e4n Laurin kirkko, Lohja, Suomi",
"Lohnattila, Vesilahti, Suomi",
"Lojobacken, Lohja, Suomi",
"Lolland, Sj\u00e6lland, Tanska",
"Luikala, P\u00e4lk\u00e4ne, Suomi",
"Luikko, Kaltsila, Vesilahti, Suomi",
"Lummelunds bruk, Gotland, Ruotsi",
"Lund\u00e5s, Edebo socken, Uppland, Ruotsi",
"Luovutettu Karjala",
"Luukkaala, Kangasala, Suomi",
"Luukkaala, P\u00f6yh\u00f6l\u00e4, Vesilahti, Suomi",
"Luutnantin virkatalo, Keljo, Ihari, Kangasala, Suomi",
"Lycka l\u00e4n, Blekinge, G\u00f6taland, Ruotsi",
"Lyck\u00e5, Blekinge, G\u00f6taland, Ruotsi",
"Lyhundra h\u00e4rad, Uppland, Ruotsi",
"Lyly, Juupajoki, Suomi",
"Lylyj\u00e4rvi, Juupajoki, Suomi",
"Lylyn viestivarikko, Lyly, Juupajoki, Suomi",
"Lyypekki, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"L\u00e5ngareds socken, Kullings h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"L\u00e4ck\u00f6 l\u00e4n, V\u00e4sterg\u00f6tland, Ruotsi",
"L\u00e4ck\u00f6 slott, L\u00e4ck\u00f6 l\u00e4n, V\u00e4sterg\u00f6tland, Ruotsi",
"L\u00e4hteenoja, Eura, Suomi",
"L\u00e4ngelm\u00e4en kirkko, Orivesi, Suomi",
"L\u00e4ngelm\u00e4ki, Suomi",
"L\u00e4nna kyrka i S\u00f6dermanland, Merl\u00e4nna, S\u00f6dermanland, Ruotsi",
"L\u00e4nna socken i Uppland, Uppland, Ruotsi",
"L\u00f6ts socken, Uppland, Ruotsi",
"Malexanders socken, Ydre h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Malm\u00f6, Sk\u00e5ne, Ruotsi",
"Mangs, J\u00f6nsb\u00f6le, Lohja, Suomi",
"Mariakirken, Oslo, Norja",
"Marieborg slott, Enk\u00f6ping, Uppland, Ruotsi",
"Marttila, Kuru, Kangasala, Suomi",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Masku, Suomi",
"Maskun kihlakunta, Suomi",
"Mattila, Ihari, Kangasala, Suomi",
"Mattila, Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Mattila, Ohtola, Kangasala, Suomi",
"Mattila, Paatiala, Sahalahti, Kangasala, Suomi",
"Mattila, P\u00e4tsiniemi, Toijala, Akaa, Suomi",
"Mattila, Suomasema, Orivesi, Suomi",
"Mattilan rustholli, Per\u00e4l\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Maunu, Luukkaala, Kangasala, Suomi",
"Maunula, Kopsamo, Juupajoki, Suomi",
"Mecklenburg",
"Medelpad, Ruotsi",
"Meisala, Halikko, Salo, Suomi",
"Memmings h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Merl\u00e4nna, S\u00f6dermanland, Ruotsi",
"Messukyl\u00e4, Tampere, Suomi",
"Messukyl\u00e4n kirkko, Messukyl\u00e4, Tampere, Suomi",
"Mets\u00e4-Heikkil\u00e4, Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"Middelfart, Syddanmark, Tanska",
"Midtjylland, Tanska",
"Miemola, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Mierola, Hattula, Suomi",
"Mietoinen, Myn\u00e4m\u00e4ki, Suomi",
"Mikkola, Haapaniemi, Kangasala, Suomi",
"Mikkola, Monikkala, Kangasala, Suomi",
"Mikkola, M\u00e4lki\u00e4inen, Valkeakoski, Suomi",
"Mikkola, Sionkyl\u00e4, Pirkkala, Suomi",
"Minsk",
"Moltsia, Sahalahti, Kangasala, Suomi",
"Momma, Pauni, Lohja, Suomi",
"Monikkala, Kangasala, Suomi",
"Monnila, Pikku-Parola, H\u00e4meenlinna, Suomi",
"Morkarla socken, Uppland, Ruotsi",
"Motala, \u00d6sterg\u00f6tland, Ruotsi",
"Muhuj\u00e4rvi, Kokkila, Juupajoki, Suomi",
"Mukkulan rustholli, Pajukanta, Orivesi, Suomi",
"Mullin rustholli, Mustinen, Vesilahti, Suomi",
"Muolaa, Luovutettu Karjala",
"Mustialan kartano, Tammela, Suomi",
"Mustinen, Vesilahti, Suomi",
"Mutikko, Kangasala, Suomi",
"Mutonen, Riiti\u00e4l\u00e4, Viiala, Akaa, Suomi",
"Myn\u00e4m\u00e4ki, Suomi",
"Myrans, Siuntio, Suomi",
"M\u00e4ki-K\u00e4rki, Hinsala, Vesilahti, Suomi",
"M\u00e4kip\u00e4\u00e4, Kopsamo, Juupajoki, Suomi",
"M\u00e4laren, S\u00f6dermanland, Ruotsi",
"M\u00e4lkil\u00e4, P\u00e4lk\u00e4ne, Suomi",
"M\u00e4lki\u00e4inen, Valkeakoski, Suomi",
"M\u00e4llinoja, M\u00e4lkil\u00e4, P\u00e4lk\u00e4ne, Suomi",
"M\u00e4ntt\u00e4-Vilppula, Suomi",
"M\u00f6hk\u00f6l\u00e4, Taustiala, Sahalahti, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"M\u00f6lneby, \u00d6stra Fr\u00f6lunda socken, Kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"M\u00f6nster\u00e5s socken, Sm\u00e5land, Ruotsi",
"M\u00f6rk\u00f6 socken, S\u00f6dermanland, Ruotsi",
"Naantali, Suomi",
"Naantalin kirkko, Naantali, Suomi",
"Naantalin seurakunta, Suomen ev.lut. kirkko",
"Narva, Vesilahti, Suomi",
"Nekala, Tampere, Suomi",
"Neulaniemi, Kangasala, Suomi",
"Niemenkyl\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Nihattula, Hattula, Suomi",
"Niittum\u00e4ki, Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Nikkil\u00e4, K\u00f6yr\u00e4, Kangasala, Suomi",
"Nikula, Tiihala, Kangasala, Suomi",
"Njudungs historiska sm\u00e5 landen, Sm\u00e5land, Ruotsi",
"Nokia, Suomi",
"nordiska sju\u00e5rskriget",
"Nordjylland, Tanska",
"Norja",
"Norra H\u00e4rene socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Norra Vedbo h\u00e4rad, Sm\u00e5land, Ruotsi",
"Norra \u00c5sums socken, Sk\u00e5ne, Ruotsi",
"Norrbotten, Ruotsi",
"Norrbro, Tukholma, Ruotsi",
"Norrk\u00f6ping, \u00d6sterg\u00f6tland, Ruotsi",
"Norrland, Ruotsi",
"Norunda h\u00e4rad, Uppland, Ruotsi",
"Nousiainen, Suomi",
"Nummi, Nousiainen, Suomi",
"Nurmis g\u00e5rd, Viipuri, Luovutettu Karjala",
"Nya Vinstorp, Dalums socken, Redv\u00e4gs h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Nybacka torp, Laakspohja, Lohja, Suomi",
"Nyk\u00f6ping, S\u00f6dermanland, Ruotsi",
"Nyk\u00f6pingshus, Nyk\u00f6ping, S\u00f6dermanland, Ruotsi",
"Nyn\u00e4s, B\u00e4linge socken i S\u00f6dermanland, R\u00f6n\u00f6 h\u00e4rad, S\u00f6dermanland, Ruotsi",
"Nyyn\u00e4inen, Lemu, Masku, Suomi",
"Nyyn\u00e4isten kartano, Nyyn\u00e4inen, Lemu, Masku, Suomi",
"N\u00e4rke, Svealand, Ruotsi",
"N\u00e6s, Karlstorps socken, Njudungs historiska sm\u00e5 landen, Sm\u00e5land, Ruotsi",
"N\u00e4s, Torpa socken i \u00d6sterg\u00f6tland, Ydre h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Odense, Syddanmark, Tanska",
"Ohralahti, S\u00e4ij\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Ohtola, Kangasala, Suomi",
"Ojala, Liuksiala, Kangasala, Suomi",
"Ojala, Peltolammi, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Ojalan torppa, Hinkka, Hypp\u00e4ril\u00e4, Kangasala, Suomi",
"Ojoinen, Vesilahti, Suomi",
"Ojonen, Kauppila, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Olands h\u00e4rad, Uppland, Ruotsi",
"Olkkala, Vihti, Suomi",
"Olkkalan kartano, Olkkala, Vihti, Suomi",
"Onkem\u00e4ki, Vesilahti, Suomi",
"Onkiniemi, Tampere, Suomi",
"Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"Ons\u00f8y, Fredrikstad, Norja",
"Oppenstens slott, S\u00f6dra \u00c5sarps socken, Kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Oriveden kirkko, Oriveden kyl\u00e4, Orivesi, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"Oriveden seurakunta, Suomen ev.lut. kirkko",
"Orivesi, Suomi",
"Orkneysaaret, Skotlanti",
"Oslo, Norja",
"Outinen, Ania, Pirkkala, Suomi",
"Paalila, Kangasala, Suomi",
"Paatiala, Sahalahti, Kangasala, Suomi",
"Paavola, Haviseva, Kangasala, Suomi",
"Padasjoki, Suomi",
"P\u00e1fos, Kypros",
"Pajukanta, Orivesi, Suomi",
"Pajunen, Raikku, Kangasala, Suomi",
"Pakkala, Sahalahti, Kangasala, Suomi",
"Paloniemi, Yl\u00e4ne, P\u00f6yty\u00e4, Suomi",
"Palttila, Laitila, Suomi",
"Papinkontu, Tyr\u00f6, Inkerinmaa, Ven\u00e4j\u00e4",
"Pappila, Vesilahti, Suomi",
"Paradis torp, Veijola, Lohja, Suomi",
"Parainen, Suomi",
"Pariisi, Ranska",
"Paukkala, Ohtola, Kangasala, Suomi",
"Pauni, Lohja, Suomi",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Peltolammi, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Penningby g\u00e5rd, L\u00e4nna socken i Uppland, Uppland, Ruotsi",
"Penttil\u00e4, Luikala, P\u00e4lk\u00e4ne, Suomi",
"Perni\u00f6, Salo, Suomi",
"Perttula, Siitama, Orivesi, Suomi",
"Per\u00e4l\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Pietil\u00e4, Vahderp\u00e4\u00e4, Kangasala, Suomi",
"Pietola, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Piikki\u00f6, Kaarina, Suomi",
"Piikki\u00f6n kihlakunta, Turun ja Porin l\u00e4\u00e4ni, Suomi",
"Piittala, Orivesi, Suomi",
"Pikkola, Kangasala, Suomi",
"Pikku-Parola, H\u00e4meenlinna, Suomi",
"Piksborg, Sm\u00e5land, Ruotsi",
"Pinninkatu 2, Tammela, Tampere, Suomi",
"Pirkkala, Suomi",
"Pirkkalan seurakunta, Suomen ev.lut. kirkko",
"Pirkkalankyl\u00e4, Pirkkala, Suomi",
"Pispala, Kangasala, Suomi",
"Pitk\u00e4j\u00e4rvi, Orivesi, Suomi",
"Pohja, Raasepori, Suomi",
"Pohjanmaa, Suomi",
"Pohjois-Suomen laamannikunta, Suomi",
"Pommeri",
"Pori, Suomi",
"Porin l\u00e4\u00e4nin jalkav\u00e4kirykmentti, Sotilasorganisaatiot",
"Porin pedagogio, Pori, Suomi",
"Porin rovastikunta, Suomen ev.lut. kirkko",
"Porkkala, Lammi, H\u00e4meenlinna, Suomi",
"Portugali",
"Porvoo, Suomi",
"Porvoon linnal\u00e4\u00e4ni, Suomi",
"Poutala, Kylm\u00e4koski, Akaa, Suomi",
"Preussi",
"Prinssi, Jokioinen, Kangasala, Suomi",
"Pukali, Immula, Lohja, Suomi",
"Punala, Pikku-Parola, H\u00e4meenlinna, Suomi",
"Puola",
"Puolan sota (1611-1632)",
"Puolustuslaitos, Suomi",
"Puotinharju, Helsinki, Suomi",
"Pyht\u00e4\u00e4, Suomi",
"Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Pyh\u00e4maa, Uusikaupunki, Suomi",
"Pyh\u00e4maan seurakunta, Suomen ev.lut. kirkko",
"Pyh\u00e4n Ristin kirkko, Rauma, Suomi",
"Pylkinautio, Pylkki, Juupajoki, Suomi",
"Pylkki, Juupajoki, Suomi",
"Pynn\u00f6l\u00e4, Riku, Kangasala, Suomi",
"Pyynikki, Tampere, Suomi",
"P\u00e4ilahti, Orivesi, Suomi",
"P\u00e4lk\u00e4ne, Suomi",
"P\u00e4lk\u00e4neen Pyh\u00e4n Mikaelin kirkko, P\u00e4lk\u00e4ne, Suomi",
"P\u00e4lk\u00e4neen seurakunta, Suomen ev.lut. kirkko",
"P\u00e4rnumaa, Viro",
"P\u00e4tsiniemi, Toijala, Akaa, Suomi",
"p\u00e4\u00e4lippue, Sotilasorganisaatiot",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"P\u00f6yh\u00f6l\u00e4, Vesilahti, Suomi",
"P\u00f6yty\u00e4, Suomi",
"Raasepori, Suomi",
"Raaseporin linna, Raasepori, Suomi",
"Raaseporin linnal\u00e4\u00e4ni, Suomi",
"Raikku, Kangasala, Suomi",
"Ramkvilla socken, Sm\u00e5land, Ruotsi",
"Ranska",
"Rantaperki\u00f6, Tampere, Suomi",
"Raronsalo, Kangasala, Suomi",
"Rasbo h\u00e4rad, Uppland, Ruotsi",
"Rasila, Haihunkoski, Viiala, Akaa, Suomi",
"Rassa, Kaakila, Vesilahti, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"Rauma, Suomi",
"Rauman pedagogio, Rauma, Suomi",
"Rauman seurakunta, Suomen ev.lut. kirkko",
"Rautio, Sahalahti, Kangasala, Suomi",
"Redv\u00e4gs h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Rein, Rissa, Tr\u00f8ndelag, Norja",
"Reins kloster, Rissa, Tr\u00f8ndelag, Norja",
"Reippi, Pirkkalankyl\u00e4, Pirkkala, Suomi",
"Restrup, S\u00f8nderholm Sogn, Jutland, Tanska",
"Revelsta, Altuna socken, Simtuna h\u00e4rad, Uppland, Ruotsi",
"Ribe Cathedral, Ribe, Syddanmark, Tanska",
"Ribe, Syddanmark, Tanska",
"Riberhus, Ribe, Syddanmark, Tanska",
"Riddarholmskyrkan, Tukholma, Ruotsi",
"Rid\u00f6, Barkar\u00f6 socken, V\u00e4stmanland, Ruotsi",
"Riippa, Vuoltee, Kylm\u00e4koski, Akaa, Suomi",
"Riiti\u00e4l\u00e4, Viiala, Akaa, Suomi",
"Riku, Kangasala, Suomi",
"Ringshult g\u00e5rd, Torpa socken i \u00d6sterg\u00f6tland, Ydre h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Ringstadaholms slottsl\u00e4n, \u00d6sterg\u00f6tland, Ruotsi",
"Ringsted Kirke, Ringsted, Sj\u00e6lland, Tanska",
"Ringsted, Sj\u00e6lland, Tanska",
"Rissa, Tr\u00f8ndelag, Norja",
"Risstens torp, Kirkniemi, Lohja, Suomi",
"Ristniemi, Sauvo, Suomi",
"Romerike, Norja",
"Rongonaho, Hulipas, Juupajoki, Suomi",
"Rongonpelto, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Rooseli, Lohnattila, Vesilahti, Suomi",
"Roseli, Monikkala, Kangasala, Suomi",
"Roskilde, Sj\u00e6lland, Tanska",
"Roslagen, Uppland, Ruotsi",
"Rossi, Epaala, P\u00e4lk\u00e4ne, Suomi",
"Rottala, Ryti\u00e4l\u00e4, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Rugnola, Kemi\u00f6nsaari, Suomi",
"Rumlaborgs slottsl\u00e4n, Sm\u00e5land, Ruotsi",
"Runko, Piikki\u00f6, Kaarina, Suomi",
"Runtoft, Angel, Schleswig, S\u00f8nderjylland, Tanska",
"Runtuna socken, S\u00f6dermanland, Ruotsi",
"Ruokolahti, Suomi",
"Ruotsi",
"Ruotsilan puustelli eli sotilasvirkatalo, Hakkila, Vesilahti, Suomi",
"Ruovesi, Suomi",
"Ryti\u00e4l\u00e4, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"R\u00e5by Sogn, Jutland, Tanska",
"R\u00e5da socken, V\u00e4sterg\u00f6tland, Ruotsi",
"R\u00e4fsteting i S\u00f6t\u00e5sa, Adel\u00f6vs socken, Sm\u00e5land, Ruotsi",
"R\u00e4ih\u00e4l\u00e4, Pakkala, Sahalahti, Kangasala, Suomi",
"R\u00f6n\u00f6 h\u00e4rad, S\u00f6dermanland, Ruotsi",
"Sachsen, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Sagersta, Askersunds socken, Sundbo h\u00e4rad, N\u00e4rke, Svealand, Ruotsi",
"Sahalahden kirkko, Sahalahti, Kangasala, Suomi",
"Sahalahden seurakunta, Suomen ev.lut. kirkko",
"Sahalahti, Kangasala, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"Salo, Suomi",
"Salsta, Uppsala, Uppland, Ruotsi",
"Sammalisto, Kangasala, Suomi",
"Sankt Bendts Kirke, Ringsted, Sj\u00e6lland, Tanska",
"Sankt J\u00f8rgensbjerg, Roskilde, Sj\u00e6lland, Tanska",
"Sankta Klara kloster, Tukholma, Ruotsi",
"Santalahdentie 9, Pyynikki, Tampere, Suomi",
"Sarkkila, Viiala, Akaa, Suomi",
"Sarvanta, Vehmainen, Messukyl\u00e4, Tampere, Suomi",
"Sarvela, Voitila, Orivesi, Suomi",
"Satakunnan-Pohjanmaan laamannikunta, Suomi",
"Satakunta, Suomi",
"Sauvala, Kalvola, H\u00e4meenlinna, Suomi",
"Sauvo, Immula, Lohja, Suomi",
"Sauvo, Suomi",
"Sauvola, Piikki\u00f6, Kaarina, Suomi",
"Saviniemi torp, Orivesi, Suomi",
"Saviniemi, Kylm\u00e4koski, Akaa, Suomi",
"Savo, Kangasala, Suomi",
"Savola, Kuru, Kangasala, Suomi",
"Savolan rustholli, Pakkala, Sahalahti, Kangasala, Suomi",
"Savoy, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Schlei, Schleswig, S\u00f8nderjylland, Tanska",
"Schleswig, S\u00f8nderjylland, Tanska",
"Seiv\u00e4s, Onkem\u00e4ki, Vesilahti, Suomi",
"Sela\u00f6n, Yttersel\u00f6 socken, S\u00f6dermanland, Ruotsi",
"Selebo h\u00e4rad, S\u00f6dermanland, Ruotsi",
"Sepp\u00e4l\u00e4, Er\u00e4slahti, Orivesi, Suomi",
"Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Sepp\u00e4l\u00e4, Immula, Lohja, Suomi",
"Sepp\u00e4l\u00e4, Keljo, Ihari, Kangasala, Suomi",
"Sepp\u00e4l\u00e4, Keljo, Sahalahti, Kangasala, Suomi",
"Sepp\u00e4l\u00e4, Myrans, Siuntio, Suomi",
"Sepp\u00e4l\u00e4, Pakkala, Sahalahti, Kangasala, Suomi",
"Sepp\u00e4l\u00e4, Pirkkalankyl\u00e4, Pirkkala, Suomi",
"Sepp\u00e4l\u00e4, Pispala, Kangasala, Suomi",
"Sepp\u00e4l\u00e4n rustholli, M\u00e4lki\u00e4inen, Valkeakoski, Suomi",
"Setola, Karnainen, Lohja, Suomi",
"Sigtuna dominikankloster, Sigtuna, Uppland, Ruotsi",
"Sigtuna, Uppland, Ruotsi",
"Siitama, Orivesi, Suomi",
"Sikkinen, Haurala, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Simonstorp, Grolanda socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Simtuna h\u00e4rad, Uppland, Ruotsi",
"Sionkyl\u00e4, Pirkkala, Suomi",
"Sipil\u00e4, Lyytikk\u00e4l\u00e4, Orivesi, Suomi",
"Sipil\u00e4n rustoholli, Vehoniemi, Kangasala, Suomi",
"Sipoo, Suomi",
"Siuntio, Suomi",
"Siuntion kirkon hautausmaa, Siuntion Pyh\u00e4n Pietarin kirkko, Siuntio, Suomi",
"Siuntion Pyh\u00e4n Pietarin kirkko, Siuntio, Suomi",
"Siuro, Oriveden kyl\u00e4, Orivesi, Suomi",
"Siurola, Raikku, Kangasala, Suomi",
"Sjundbyn kartano, Siuntio, Suomi",
"Sj\u00e6lland, Tanska",
"Skallmeja socken, Sk\u00e5nings h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Skara domkyrka, Skara, Kinne h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Skara, Kinne h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Skea, S\u00f8rum, Romerike, Norja",
"Skederids socken, Uppland, Ruotsi",
"Skepptuna, Uppland, Ruotsi",
"Sko kloster, Skoklosters socken, H\u00e5bo h\u00e4rad, Uppland, Ruotsi",
"Skofteby s\u00e4teri, Norra H\u00e4rene socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Skogshyddan, Pohja, Raasepori, Suomi",
"Skoklosters socken, H\u00e5bo h\u00e4rad, Uppland, Ruotsi",
"Skotlanti",
"Skullerupholm, Lejre Municipality, Tanska",
"Sk\u00e5ne, Ruotsi",
"Sk\u00e5nings h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Sk\u00e4nninge dominikankloster, Sk\u00e4nninge, \u00d6sterg\u00f6tland, Ruotsi",
"Sk\u00e4nninge nunnekloster, Sk\u00e4nninge, \u00d6sterg\u00f6tland, Ruotsi",
"Sk\u00e4nninge, \u00d6sterg\u00f6tland, Ruotsi",
"Sk\u00e4rkinds h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Slaget ved Viborg, Jylland, Tanska",
"slaget vid Brunkeberg, Tukholma, Ruotsi",
"Slaget vid Gestilren, G\u00e4stre, Fr\u00f6sthults socken, Uppland, Ruotsi",
"slaget vid Lena, Kungslena socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Slangerup, Frederikssund, Sj\u00e6lland, Tanska",
"Smeds torpet, Liuksiala, Kangasala, Suomi",
"Smeds, V\u00e4h\u00e4-Teutari, Lohja, Suomi",
"Sm\u00e5land, Ruotsi",
"Somero, Suomi",
"Sonasund, Inkoo, Suomi",
"Sorknes, Grue, Norja",
"Sorola, Kangasala, Suomi",
"Sorri, Hinsala, Vesilahti, Suomi",
"Sorri, Ukaa, Teisko, Tampere, Suomi",
"Sorunda socken, S\u00f6dermanland, Ruotsi",
"Sor\u00f8 Klosterkirke, Sor\u00f8, Sj\u00e6lland, Tanska",
"Sor\u00f8, Sj\u00e6lland, Tanska",
"Sotavalta, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Sotilasorganisaatiot",
"Stege, Sj\u00e6lland, Tanska",
"Stegeborgs slott, S\u00f6derk\u00f6ping, \u00d6sterg\u00f6tland, Ruotsi",
"Stegeborgs slott, \u00d6sterg\u00f6tland, Ruotsi",
"Stegeholm, V\u00e4stervik, Sm\u00e5land, Ruotsi",
"Stegeholms slottsl\u00e4n, Sm\u00e5land, Ruotsi",
"Stockholms slott, Tukholma, Ruotsi",
"Stora Bjurum, Bjurums socken, V\u00e4sterg\u00f6tland, Ruotsi",
"Stora Hoplax, Espoo, Suomi",
"Stora Mell\u00f6sa socken, Askers h\u00e4rad, N\u00e4rke, Svealand, Ruotsi",
"Storkyrkan i Stockholm, Tukholma, Ruotsi",
"stormningen av Ronneby, nordiska sju\u00e5rskriget",
"Stortorget, Tukholma, Ruotsi",
"Str\u00f6mb\u00e4ck, Laukko, Vesilahti, Suomi",
"Styresholm, Styrn\u00e4s socken, \u00c5ngermanland, Ruotsi",
"Styresholms slottsl\u00e4n, \u00c5ngermanland, Ruotsi",
"Styrn\u00e4s socken, \u00c5ngermanland, Ruotsi",
"St\u00e5lhandskegravkoret, Turun tuomiokirkko, Turku, Suomi",
"St\u00e4keholms slottsl\u00e4n, \u00d6sterg\u00f6tland, Ruotsi",
"Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Sukkila, Juupajoki, Suomi",
"Sundals h\u00e4rad, Dalsland, G\u00f6taland, Ruotsi",
"Sundbo h\u00e4rad, N\u00e4rke, Svealand, Ruotsi",
"Sundboholm, B\u00e4linge socken i S\u00f6dermanland, R\u00f6n\u00f6 h\u00e4rad, S\u00f6dermanland, Ruotsi",
"Sunnan\u00e5, Torpa socken i \u00d6sterg\u00f6tland, Ydre h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Sunnerbo h\u00e4rad, Sm\u00e5land, Ruotsi",
"Suomasema, Orivesi, Suomi",
"Suomaseman rustholli, Suomasema, Orivesi, Suomi",
"Suomela, Kangasala, Suomi",
"Suomen ev.lut. kirkko",
"Suomen Sahanter\u00e4tehdas Oy, Onkiniemi, Tampere, Suomi",
"Suomen sis\u00e4llissota, Suomi",
"Suomenlinna, Helsinki, Suomi",
"Suomi",
"Suonp\u00e4\u00e4, Vihtij\u00e4rvi, Vihti, Suomi",
"Suontaka, Vihti, Suomi",
"Suorama, Kangasala, Suomi",
"Svartbr\u00f6draklostret i Stockholm, Tukholma, Ruotsi",
"Svartsj\u00f6 slott, Uppland, Ruotsi",
"Svart\u00e5, Raasepori, Suomi",
"Svart\u00f6 bruk, Svart\u00e5, Raasepori, Suomi",
"Svealand, Ruotsi",
"Syddanmark, Tanska",
"S\u00e4ij\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"S\u00e4kyl\u00e4, Suomi",
"S\u00e4llin rustholli, Sotavalta, Lemp\u00e4\u00e4l\u00e4, Suomi",
"S\u00e4rkilahti, Taivassalo, Suomi",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"S\u00f6derk\u00f6ping, \u00d6sterg\u00f6tland, Ruotsi",
"S\u00f6dermanland, Ruotsi",
"S\u00f6dra \u00c5sarps socken, Kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"S\u00f8nderborg, Syddanmark, Tanska",
"S\u00f8nderholm Kirke, S\u00f8nderholm Sogn, Jutland, Tanska",
"S\u00f8nderholm Sogn, Jutland, Tanska",
"S\u00f8nderjylland, Tanska",
"S\u00f8rum, Romerike, Norja",
"Taivassalo, Suomi",
"Taivassalon kirkko, Taivassalo, Suomi",
"Takahuhti, Messukyl\u00e4, Tampere, Suomi",
"Tallinna, Harjumaa, Viro",
"Talola, K\u00e4rv\u00e4nt\u00e4l\u00e4, P\u00e4lk\u00e4ne, Suomi",
"Talvia, Tiihala, Kangasala, Suomi",
"Talviainen, Orivesi, Suomi",
"talvisota, toinen maailmansota",
"Tammela, Suomasema, Orivesi, Suomi",
"Tammela, Suomi",
"Tammela, Tampere, Suomi",
"Tammelankatu 12, Tammela, Tampere, Suomi",
"Tammisaari, Raasepori, Suomi",
"Tampella Oy Ab, Tampere, Suomi",
"Tampere, Suomi",
"Tampereen kaupunki, Tampere, Suomi",
"Tampereen taistelu, Suomen sis\u00e4llissota, Suomi",
"Tampereen Verkatehdas Oy, Tampere, Suomi",
"Tanska",
"Tarpila, Kangasala, Suomi",
"Tauranen, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"Taustiala, Sahalahti, Kangasala, Suomi",
"Tavastila, Mietoinen, Myn\u00e4m\u00e4ki, Suomi",
"Teijo, Perni\u00f6, Salo, Suomi",
"Teijon kartano, Teijo, Perni\u00f6, Salo, Suomi",
"Teijon ruukki, Teijo, Perni\u00f6, Salo, Suomi",
"Teisko, Tampere, Suomi",
"Telge hus, S\u00f6dermanland, Ruotsi",
"Telgehus slottsl\u00e4n, S\u00f6dermanland, Ruotsi",
"Tenhola, Raasepori, Suomi",
"Tenholan kartano, Lemu, Masku, Suomi",
"Tenstads kyrka, Uppland, Ruotsi",
"Th\u00fcringen, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Tie- ja vesirakennushallitus TVH, Suomi",
"Tiesenhausenin rakuunarykmentti, Sotilasorganisaatiot",
"Tiihala, Kangasala, Suomi",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Tiundaland, Ruotsi",
"Tjust, Sm\u00e5land, Ruotsi",
"Tohka, Joenpohja, Tottij\u00e4rvi, Nokia, Suomi",
"Toijala, Akaa, Suomi",
"Toikka, Vatiala, Kangasala, Suomi",
"Toikkola, Kangasala, Suomi",
"toinen maailmansota",
"Toosi, Vatiala, Kangasala, Suomi",
"Toosila, Kangasala, Suomi",
"Torittu, Orivesi, Suomi",
"Torpa socken i \u00d6sterg\u00f6tland, Ydre h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Tottij\u00e4rven kartano, Tottij\u00e4rvi, Nokia, Suomi",
"Tottij\u00e4rvi, Nokia, Suomi",
"Trondheim, Norja",
"Trosa landskyrka, S\u00f6dermanland, Ruotsi",
"Tryserums socken, Sm\u00e5land, Ruotsi",
"Tr\u00f6gds h\u00e4rad, Uppland, Ruotsi",
"Tr\u00f8ndelag, Norja",
"Tuhola, Apajapohja, Kangasala, Suomi",
"Tukholma, Ruotsi",
"Tukholman veril\u00f6yly, Stortorget, Tukholma, Ruotsi",
"Tune, \u00d8stfold, Norja",
"Tunsberghus, T\u00f8nsberg, Norja",
"Turku, Suomi",
"Tursola, Kangasala, Suomi",
"Tursola, Sahalahti, Kangasala, Suomi",
"Turun akatemia, Turku, Suomi",
"Turun hovioikeus, Turku, Suomi",
"Turun ja Porin l\u00e4\u00e4ni, Suomi",
"Turun linna, Turku, Suomi",
"Turun l\u00e4\u00e4nin ratsuv\u00e4kirykmentti, Sotilasorganisaatiot",
"Turun tuomiokirkko, Turku, Suomi",
"Turva, Kuuliala, P\u00e4lk\u00e4ne, Suomi",
"Tyrv\u00e4nt\u00f6, Hattula, Suomi",
"Tyr\u00f6, Inkerinmaa, Ven\u00e4j\u00e4",
"T\u00e5dene socken, K\u00e5llands h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"T\u00f8nder Slot, T\u00f8nder, Syddanmark, Tanska",
"T\u00f8nder, Syddanmark, Tanska",
"T\u00f8nsberg, Norja",
"T\u00f6yk\u00e4n\u00e4, Sahalahti, Kangasala, Suomi",
"T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"Ukaa, Teisko, Tampere, Suomi",
"Ulvila, Suomi",
"Ulvilan ja Porin seurakunta, Suomen ev.lut. kirkko",
"Untamala, Suomi",
"Uotila, Luikala, P\u00e4lk\u00e4ne, Suomi",
"Uotila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Uotila, Varala, Kangasala, Suomi",
"Uppland, Ruotsi",
"Upplands lagsaga, Uppland, Ruotsi",
"Uppsala domkyrka, Uppsala, Uppland, Ruotsi",
"Uppsala, Uppland, Ruotsi",
"Urjala, Suomi",
"Uskela, Salo, Suomi",
"Utan\u00e5ker, Inkoo, Suomi",
"Uudenmaan ja H\u00e4meen l\u00e4\u00e4ni, Suomi",
"Uudenmaan ja H\u00e4meen ratsuv\u00e4kirykmentti, Sotilasorganisaatiot",
"Uusikaupunki, Suomi",
"Uusitalo, Hirtolahti, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Vada socken, Uppland, Ruotsi",
"Vadstena kloster, Vadstena, \u00d6sterg\u00f6tland, Ruotsi",
"Vadstena, \u00d6sterg\u00f6tland, Ruotsi",
"Vahderp\u00e4\u00e4, Kangasala, Suomi",
"Vainionp\u00e4\u00e4, Lylyj\u00e4rvi, Juupajoki, Suomi",
"Valdres, Norja",
"Valkeakoski, Suomi",
"Valkebo h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Valla, Sela\u00f6n, Yttersel\u00f6 socken, S\u00f6dermanland, Ruotsi",
"Valle h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Vanaja, Suomi",
"Vang, Valdres, Norja",
"Varala, Kangasala, Suomi",
"Varberg, Halland, Ruotsi",
"Varbergs f\u00e4stning, Varberg, Halland, Ruotsi",
"Varsinais-Suomen historiallinen maakunta, Suomi",
"Varteig, Norja",
"Vartofta h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Vasa g\u00e5rd, Skepptuna, Uppland, Ruotsi",
"Vatiala, Kangasala, Suomi",
"Veckholms socken, Tr\u00f6gds h\u00e4rad, Uppland, Ruotsi",
"Vedentaka, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Vehkalahti, Hamina, Suomi",
"Vehkalahti, Orivesi, Suomi",
"Vehkapuntari, Kuhmalahti, Kangasala, Suomi",
"Vehmainen, Messukyl\u00e4, Tampere, Suomi",
"Vehoniemi, Kangasala, Suomi",
"Veijola, Lohja, Suomi",
"Ven\u00e4j\u00e4",
"Ven\u00e4j\u00e4n sota (1609-1617)",
"Vesilahti, Suomi",
"Vesto, Narva, Vesilahti, Suomi",
"Vetterkulla, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Viby, \u00d6stra Ryds socken i \u00d6sterg\u00f6tland, Sk\u00e4rkinds h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Vihasj\u00e4rvi, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Vihti, Suomi",
"Vihtij\u00e4rvi, Vihti, Suomi",
"Vihtinen, Kangasala, Suomi",
"Viiainen, Taivassalo, Suomi",
"Viiala, Akaa, Suomi",
"Viias, Viiainen, Taivassalo, Suomi",
"Viinikka, Tampere, Suomi",
"Viipuri, Luovutettu Karjala",
"Viipurin linna, Viipuri, Luovutettu Karjala",
"Viipurin linnal\u00e4\u00e4ni",
"Viipurin l\u00e4\u00e4nin jalkav\u00e4kirykmentti, Sotilasorganisaatiot",
"Vik, Balingsta socken, Hagunda h\u00e4rad, Uppland, Ruotsi",
"Vilppulan rustholli, Poutala, Kylm\u00e4koski, Akaa, Suomi",
"Vilske h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Vilske-Kleva socken, Vilske h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Vilske, Vartofta h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Vin\u00e4s s\u00e4teri, V\u00e4stra Eds socken, Sm\u00e5land, Ruotsi",
"Vin\u00e4s, Gammalkils socken, Valkebo h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Viro",
"Virola, Tiihala, Kangasala, Suomi",
"Visings\u00f6, Sm\u00e5land, Ruotsi",
"Viste h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"Vittaryds sochen, Sunnerbo h\u00e4rad, Sm\u00e5land, Ruotsi",
"Vohloinen, Lohja, Suomi",
"Voitila, Orivesi, Suomi",
"Voittola, Kopsamo, Juupajoki, Suomi",
"Voldum Sogn, Midtjylland, Tanska",
"Vordingborg slot, Vordingborg, Sj\u00e6lland, Tanska",
"Vordingborg, Sj\u00e6lland, Tanska",
"Vreta kloster, \u00d6sterg\u00f6tland, Ruotsi",
"Vuoltee, Kylm\u00e4koski, Akaa, Suomi",
"Vuorenp\u00e4\u00e4, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"V\u00e5la h\u00e4rad, Uppland, Ruotsi",
"V\u00e5nga socken i \u00d6sterg\u00f6tland, \u00d6sterg\u00f6tland, Ruotsi",
"V\u00e5rkumla socken, Fr\u00f6kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"V\u00e4h\u00e4-K\u00f6lli, Kopsamo, Juupajoki, Suomi",
"V\u00e4h\u00e4-Saarikko, K\u00f6yr\u00e4, Kangasala, Suomi",
"V\u00e4h\u00e4-Teutari, Lohja, Suomi",
"V\u00e4h\u00e4kyl\u00e4, Vihti, Suomi",
"V\u00e4h\u00e4kyl\u00e4n puustelli eli sotilasvirkatalo, V\u00e4h\u00e4kyl\u00e4, Vihti, Suomi",
"V\u00e4lli, V\u00e4h\u00e4-Teutari, Lohja, Suomi",
"V\u00e4nni, V\u00e4nninsalo, Kangasala, Suomi",
"V\u00e4nnil\u00e4, Vesilahti, Suomi",
"V\u00e4nninsalo, Kangasala, Suomi",
"V\u00e4rend, Sm\u00e5land, Ruotsi",
"V\u00e4rends lagsaga, Sm\u00e5land, Ruotsi",
"V\u00e4rmd\u00f6 skeppslag, Uppland, Ruotsi",
"V\u00e4rmland, Ruotsi",
"V\u00e4rmlands lagsaga, V\u00e4rmland, Ruotsi",
"V\u00e4rna socken, \u00d6sterg\u00f6tland, Ruotsi",
"V\u00e4sterbottens l\u00e4n, Ruotsi",
"V\u00e4sterg\u00e5rd, Bollstad s\u00e4teri, Bollstad, Inkoo, Suomi",
"V\u00e4sterg\u00f6tland, Ruotsi",
"V\u00e4stervik, Sm\u00e5land, Ruotsi",
"V\u00e4ster\u00e5kers kyrka, V\u00e4ster\u00e5kers socken, Hagunda h\u00e4rad, Uppland, Ruotsi",
"V\u00e4ster\u00e5kers socken, Hagunda h\u00e4rad, Uppland, Ruotsi",
"V\u00e4ster\u00e5s domkyrka, V\u00e4ster\u00e5s, V\u00e4stmanland, Ruotsi",
"V\u00e4ster\u00e5s slott, V\u00e4ster\u00e5s, V\u00e4stmanland, Ruotsi",
"V\u00e4ster\u00e5s, V\u00e4stmanland, Ruotsi",
"V\u00e4stmanland, Ruotsi",
"V\u00e4stra Eds socken, Sm\u00e5land, Ruotsi",
"V\u00e4stra Ryds socken i Uppland, Bro h\u00e4rad, Uppland, Ruotsi",
"V\u00e4stra Sallerups socken, Harjagers h\u00e4rad, Sk\u00e5ne, Ruotsi",
"V\u00e4stra Tollstads socken, \u00d6sterg\u00f6tland, Ruotsi",
"V\u00e4\u00e4kil\u00e4, Vihti, Suomi",
"V\u00e4\u00e4ksy, Kangasala, Suomi",
"Windel Porten, Lyypekki, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"Ydre h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"Yli-Tanhuanp\u00e4\u00e4, Riku, Kangasala, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"Ylistaro, Sauvo, Suomi",
"Yl\u00e4-Marttila, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yl\u00e4-Satakunnan kihlakunta, Suomi",
"Yl\u00e4-Satalkunta, Suomi",
"Yl\u00e4ne, P\u00f6yty\u00e4, Suomi",
"Yl\u00e4neen kartano, Yl\u00e4ne, P\u00f6yty\u00e4, Suomi",
"Yrj\u00f6l\u00e4, Keljo, Ihari, Kangasala, Suomi",
"Yrj\u00f6l\u00e4, Kerte, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Yrj\u00f6l\u00e4, Korpiniemi, Sahalahti, Kangasala, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Yrj\u00f6l\u00e4, Vihasj\u00e4rvi, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Yttersel\u00f6 socken, S\u00f6dermanland, Ruotsi",
"\u00c5by pr\u00e4stg\u00e5rd, Norrk\u00f6ping, \u00d6sterg\u00f6tland, Ruotsi",
"\u00c5g\u00e5rdens s\u00e4teri, R\u00e5da socken, V\u00e4sterg\u00f6tland, Ruotsi",
"\u00c5kerbo h\u00e4rad i V\u00e4stmanland, V\u00e4stmanland, Ruotsi",
"\u00c5kerbo h\u00e4rad i \u00d6sterg\u00f6tland, \u00d6sterg\u00f6tland, Ruotsi",
"\u00c5kers h\u00e4rad, S\u00f6dermanland, Ruotsi",
"\u00c5ker\u00f6 slott, Bettna socken, S\u00f6dermanland, Ruotsi",
"\u00c5l, V\u00e5nga socken i \u00d6sterg\u00f6tland, \u00d6sterg\u00f6tland, Ruotsi",
"\u00c5minne s\u00e4teri, Pohja, Raasepori, Suomi",
"\u00c5ngermanland, Ruotsi",
"\u00c5s h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"\u00c4ij\u00e4nen, Torittu, Orivesi, Suomi",
"\u00c4lghults socken, V\u00e4rend, Sm\u00e5land, Ruotsi",
"\u00c4lvsborgs slott, V\u00e4sterg\u00f6tland, Ruotsi",
"\u00c4rr\u00e4l\u00e4, Voitila, Orivesi, Suomi",
"\u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"\u00d6land, Ruotsi",
"\u00d6ljym\u00e4ki, It\u00e4-Jerusalem",
"\u00d6rb\u00e4ck, Ruotsi",
"\u00d6rebro, N\u00e4rke, Svealand, Ruotsi",
"\u00d6rebron linna, \u00d6rebro, N\u00e4rke, Svealand, Ruotsi",
"\u00d6restens f\u00e4stning, V\u00e4sterg\u00f6tland, Ruotsi",
"\u00d6stbo h\u00e4rad, Sm\u00e5land, Ruotsi",
"\u00d6sterg\u00f6tland, Ruotsi",
"\u00d6sterrekarne h\u00e4rad, S\u00f6dermanland, Ruotsi",
"\u00d6sterr\u00f6ra by, V\u00e4stra Ryds socken i Uppland, Bro h\u00e4rad, Uppland, Ruotsi",
"\u00d6stersolberg, Inkoo, Suomi",
"\u00d6sterv\u00e5la socken, V\u00e5la h\u00e4rad, Uppland, Ruotsi",
"\u00d8stfold, Norja",
"\u00d6stkinds h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"\u00d6stra Fr\u00f6lunda socken, Kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"\u00d6stra h\u00e4rad i Sm\u00e5land, Sm\u00e5land, Ruotsi",
"\u00d6stra Ryds socken i Uppland, Danderyd h\u00e4rad, Uppland, Ruotsi",
"\u00d6stra Ryds socken i \u00d6sterg\u00f6tland, Sk\u00e4rkinds h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"\u00d6versel\u00f6 socken, S\u00f6dermanland, Ruotsi",
"\u00d6yr\u00e4, Onkem\u00e4ki, Vesilahti, Suomi"
]
Dwr.ScriptLoaded('dwr_db_P_name_0.js');
