// This file is generated

S_text_0 = [
"<p>\n<b>\nJulkaisutiedot: \n</b>\nSvenska heraldiska f\u00f6reningen\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nSt\u00e5lberg, Wilhelmina, Berg, P. G.\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nStockholm 1864-1866\n</p>",
"",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nSvenska litteraturs\u00e4llskapet i Finland\n</p>",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nFinska Kyrkohistoriska Samfundets handringar - Suomen Kirkkohistoriallisen Seuran toimituksia II, Borg\u00e5 1899\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nBricka, Carl Frederik\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nKj\u00f8benhavn 1887-1905\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nElgenstierna, Gustaf\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nStockholm 1925-1936\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nF\u00f6reningen \u00c4nglag\u00e5rdsbilen\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nMunch, Peter Andreas\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nOslo 1941-1943\n</p>",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nKansalliskirjaston julkaisuarkisto\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nJensen-Eriksen, Patrik\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nHelsingin yliopisto, Maisterintutkielma, Historian maisteriohjelma, Humanistinen tiedekunta, Huhtikuu 2023\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nHuld\u00e9n, Lars\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nSvenska litteraturs\u00e4llskapet i Finland r.f.\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nOikeusministeri\u00f6n Internet-palvelu\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nRamsay, Jully\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nHelsingfors 1909-1916\n</p>",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nSuomen Sukututkimusseura\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nvon M\u00f6ller, Peter\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\n1871\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nKotimaisten kielten keskus\n</p>",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nHildebrand., E 1881-1905, H\u00f6jer, Torvald 1906-1920\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nSvenska Historiska F\u00f6reningen 1881-1920\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nKepsu, Saulo\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nKotimaisten kielten keskuksen verkkojulkaisuja 71. Helsinki 2022\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nV\u00e4h\u00e4kangas, Tapio\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nVuorela, Juha\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nStudia Biographica 4. Helsinki, Suomalaisen Kirjallisuuden Seura, 1997\u2013\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nKarisalmi, Esko\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nURL www.karisalmi.fi\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nTrap, Jens Peter\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\n1856-1906\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nKotimaisten kielten keskus\n</p>",
"",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nMuseovirasto\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nStrokirk, Oscar Fredrik\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\n1915-1920\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nSuomalaisen Kirjallisuuden Seura, Helsinki 1881\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nRapo, Seppo\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nJ\u00e4ppinen, Veijo\n</p><p>\n<b>\nLyhennys: \n</b>\nMusta Rudolf\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nVerkkojulkaisu 2007, URL https://veijoja.github.io/keskinen/ .\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nKotimaisten kielten keskus\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1904 - 1926\n</p>",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nPunkari, Yrj\u00f6\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\n1997-2024\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nTampereen seudun sukututkimusseura ry:n j\u00e4senlehti\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nDigi- ja v\u00e4est\u00f6tietovirasto\n</p><p>\n<b>\nLyhennys: \n</b>\nOsoitepalvelu\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nPuhelinpalvelu\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nPaunasalo, Kari\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nF. U. Wrangel (1898-1903), Holger Rosman (1904-1906)\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nSvenska Autografs\u00e4llskapet (1898-1905), Personhistoriska samfundet (1906-), Kungl. Boktryckeriet. P. A. Norstedt & s\u00f6ner, Stockholm 1899-1908\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nRuotsin valtionarkiston verkkopalvelu\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nConradi Mattsson, Agneta\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\n\u00d6rebro l\u00e4ns museum 1998, 605 sidor, ISBN 9789185642243\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nHaapanen, Markku\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nSuomen historian Pro gradu-tutkielma, Jyv\u00e4skyl\u00e4n yliopisto 2006\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nSinivaara, Juha\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nToropainen, Veli-Pekka\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nWilskman, Atle\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nSkrifter utgivna av Svenska Litteraturs\u00e4llskapet i Finland CVII: 2, Helsingfors 1914\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nBrenner, Alf\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nSkrifter utgivna av Svenska Litteraturs\u00e4llskapet i Finland CCLXXXVI: 2, Helsingfors 1947\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nLappalainen, Jussi T\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nSuomen Sotahistoriallinen Seura ry 2014\n</p>",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nSuomen Sukututkimusseura\n</p>",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nAnrep, Gabriel\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nStockholm 1858-1864\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nStrinnholm, Anders Magnus\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\n1834-1854\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nAlbert Bonniers f\u00f6rlag, Stockholm 1942-1948\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nRuotsin valtionarkiston verkkopalvelu, riksarkivet.se\n</p>",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nIso-Iivari, Lasse\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.1.1904, julkaisija tuntematon\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.1.1905\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.9.1908\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.12.1912\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.11.1914\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.12.1919\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.5.1922\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.1.1923\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.3.1926\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.9.1929\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.1.1933\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.12.1935\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\n1.9.1939\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nSuomen Sukututkimusseura\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nTietosanakirja-Osakeyhti\u00f6, Helsinki 1909-1922\n</p>",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nV\u00e4\u00e4n\u00e4nen, Ky\u00f6sti\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nStudia Biographica 9. Helsinki, Suomalaisen Kirjallisuuden Seura, 2011\u2013\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nKepsu, Saulo\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nKotimaisten kielten keskuksen verkkojulkaisuja 80, Helsinki 2024\n</p>",
"",
"",
"",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nMuseovirasto\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nMuseovirasto\n</p>",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nLehtonen, Antti\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nJalmari Finnen S\u00e4\u00e4ti\u00f6, Tampereen Historiallinen Seura ry\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nHeikki Rantatupa historialliset kartat portaali\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nSuvanto, Seppo\n</p>",
"<p>\n<b>\nJulkaisutiedot: \n</b>\nKutilainen, Mikko\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nKepsu, Saulo\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nKotimaisten kielten keskuksen verkkojulkaisuja 68, Helsinki 2021\n</p>",
"<p>\n<b>\nTekij\u00e4: \n</b>\nPuro, Ritva\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nTampere 2000, ISBN 952-91-1679-9\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nPunkari, Yrj\u00f6\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\n2002-2008\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nWichmann, Ossian\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nBorg\u00e5 1901\n</p>",
"",
"<p>\n<b>\nTekij\u00e4: \n</b>\nKotivuori, Yrj\u00f6\n</p><p>\n<b>\nJulkaisutiedot: \n</b>\nHelsingin yliopisto, verkkojulkaisu 2005\n</p>",
"",
""
]
Dwr.ScriptLoaded('dwr_db_S_text_0.js');
