// This file is generated

I_name_0 = [
", Aage",
", Abj\u00f6rn",
", Abraham Abrahamsson",
", Abraham Johan Abrahahamsson",
", Abram Mortensson",
", Afonso I",
", Agnes",
", Agnes",
", Agnes Augustinusdotter",
", Agnes H\u00e5konsdatter",
", Agnes Mattsdotter",
", Agnes Olofsdotter",
", Agneta",
", Agneta",
", Agneta J\u00f6ransdotter",
", Agneta Mattsdotter",
", Agneta Thomasdotter",
", Agnis Hendricsdotter",
", Aldon\u00e7a",
", Algot Brynolfsson",
", Anders",
", Anders Marcusson",
", Anders Michelsson",
", Anders Thomasson",
", Anders Tomasson",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna",
", Anna Andersdotter",
", Anna Andersdotter",
", Anna Bertilsdotter",
", Anna Cnudsdotter",
", Anna Cnudsdotter",
", Anna Erichsdotter",
", Anna Hansdotter",
", Anna Henrichsdotter",
", Anna Henricsdotter",
", Anna Henriksdotter",
", Anna Henriksdotter",
", Anna Johansdotter",
", Anna Johansdotter",
", Anna Larsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna M\u00e5rtensdotter",
", Anna Sigfridsdotter",
", Anna Thomasdotter",
", Anna Thomasdotter",
", Anna Stina Catharinasdotter",
", Beata",
", Beata Bertilsdotter",
", Beata Hansdotter",
", Beata Jacobsdotter",
", Benedicta Sunesdotter",
", Bengt snivil Folkesson",
", Bengta",
", Bernhard",
", Birger brosa",
", Birger Karlsson",
", Birgitta Haraldsdotter",
", Birgitta Jonsdotter",
", Birgitta Knutsdotter",
", Birgitta Knutsdotter",
", Birgitta Nilsdotter",
", Birith",
", Bo",
", Bodil Thrugotsdatter",
", Bothild Bengtsdotter",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita",
", Brita Eskilsdotter",
", Brita Jakobsdotter",
", Brita J\u00f6ransdotter",
", Brita J\u00f6ransdotter",
", Brita J\u00f6ransdotter",
", Brita Klemetsdotter",
", Brita Larsdotter",
", Brita Mattsdotter",
", Brita Mattsdotter",
", Brita Olofsdotter",
", Brita Peersdotter",
", Brita Sigfridsdotter",
", Brita Simonsdotter",
", Brita Thomasdotter",
", Brita Thomasdotter",
", Britha J\u00f6ransdotter",
", B\u00e5rd Guttormsson",
", Caisa",
", Caisa Hendricsdotter",
", Caisa Johansdotter",
", Caisa Johansdotter",
", Caisa Michelsdotter",
", Caisa Peersdotter",
", Caisa Simonsdotter",
", Carin",
", Carin",
", Carin Hansdotter",
", Carin Johansdotter",
", Carin Mattsdotter",
", Carin Olofsdotter",
", Carin Sigfridsdotter",
", Catharina Andersdotter",
", Cecilia",
", Cecilia",
", Cecilia Knutsdotter",
", Cecilia Nilsdotter",
", Cecilia Nilsdotter",
", Chirstin Hansdotter",
", Christina",
", Christina Jacobsdotter",
", Christina Jonsdotter",
", Cristina Sigmundsdtr",
", Dorde J\u00f6ransdotter",
", Dorothea Larsdotter",
", Elin",
", Elin",
", Elin H\u00e5kansdotter",
", Elin Jacobsdotter",
", Elin J\u00f6nsdotter",
", Elin Magnusdotter",
", Elin Mattsdotter",
", Eric I Ejegod",
", Eric Sigfridsson",
", Erling",
", Estrid Svensdatter",
", Euphemia",
", Euphemia",
", Filip",
", Folke Algotsson",
", Folke den tjocke",
", Folke jarl",
", Gertrud Andersdotter",
", Gertrud Eskilsdotter",
", Gertrud Gertsdotter",
", Gertrud Jakobsdotter",
", Gertrud J\u00f6nsdotter",
", Gertrud J\u00f6ransdotter",
", Gertrud Larsdotter",
", Gertrud Larsdotter",
", Gertrud Pehrsdotter",
", Gertrud P\u00e5hlsdotter",
", Gertrud Sigfridsdotter",
", Gertrud Thomasdotter",
", Gertrudh Erichsdotter",
", Greta Johansdotter",
", Gunhild",
", Gunhild Matsdotter",
", Guttorm",
", Guttorm \u00c5solvsson",
", Hans Sigfridsson",
", Harald H\u00e5kansson",
", Hedvig Serafia Henriksdotter",
", Helena",
", Helena Andersdotter",
", Helena Guttormsdotter",
", Helena Hermansdotter",
", Helena Jacobsdotter",
", Helena Mattsdotter",
", Helena Sverkersdotter",
", Helga J\u00f6nsdotter",
", Helga J\u00f6nsdotter",
", Helga Thomasdotter",
", Hendrich Andersson",
", Henric",
", Henric Ericsson",
", Henric Henricsson",
", Henrik",
", Henrik Mattsson",
", Henrik Mattsson",
", Herman Ericsson",
", Hindrich",
", Hindrich Hindrichsson",
", H\u00e5kan Magnusson",
", H\u00e5kon Finnsson",
", H\u00e5kon III Sverresson",
", H\u00e5kon V Magnusson den eldre",
", Ide Lagesdatter",
", Iliana \u00c5kesdotter",
", Inga",
", Inge I den \u00e4ldre",
", Inge II den yngre",
", Ingeborg",
", Ingeborg",
", Ingeborg Barnamsdotter",
", Ingeborg Bengtsdotter",
", Ingeborg Johansdotter",
", Ingeborg Karlsdotter",
", Ingeborg Knutsdotter",
", Ingeborg Mattsdotter",
", Ingeborg Svantepolksdotter",
", Ingerid Knudsdatter",
", Ingevald Estridsson",
", Ingrid",
", Ingrid",
", Ingrid Abj\u00f6rnsdotter",
", Ingrid Karlsdotter",
", Ingrid Svantepolksdotter",
", Israel",
", Jacob Jacobsson",
", Jacob Johansson",
", Jacob Thomasson",
", Johan Andersson",
", Johan Ericsson",
", Johan Filipsson",
", Johan Jacobsson",
", Johan Mathia",
", Johan Mattsson",
", Johan Nilsson",
", Johan Henrik Johansson",
", Johanna Sigfridsdotter",
", Judith",
", Juho Vihtori Tuomaanpoika",
", Juliana Bertilsdotter",
", J\u00f6ns Nilsson",
", J\u00f6ran",
", J\u00f6ran Jacobsson",
", J\u00f6ran J\u00f6nsson",
", J\u00f6ran J\u00f6ransson",
", J\u00f6ran M\u00e5rtensson",
", J\u00f6ran M\u00e5rtensson",
", Karin",
", Karin",
", Karin Bj\u00f6rnsdotter",
", Karin Henrichsdotter",
", Karin Larsdotter",
", Karl Birgersson",
", Karl den d\u00f6ve",
", Karl Sunesson",
", Karl VII Sverkersson den yngre",
", Katarina",
", Katarina",
", Katarina Lagesdotter",
", Katarina Magnusdotter",
", Katarina V\u00e4stensdotter",
", Kirstin",
", Kirstin",
", Kirstin",
", Kirstin Henricsdotter",
", Kirstin Henricsdotter",
", Kirstin J\u00f6ransdotter",
", Knud IV den Hellige",
", Knut Abj\u00f6rnsson",
", Knut Folkesson",
", Knut jarl",
", Knut Magnusson",
", Kristina",
", Kristina Ingesdotter",
", Kristina Magnusdotter",
", Kristina Petersdotter",
", Kristina Toresdotter",
", Lage Gustavsson",
", Lastika Nilsdotter",
", Laurent",
", Lidinvard Haraldsson",
", Lisa",
", Lisa",
", Lisa",
", Lisa",
", Lisa Georgii",
", Lisa Henricsdotter",
", Lisa M\u00e5rtensdotter",
", Lisa Samuelsdotter",
", Lisa Simonsdotter",
", Lisa Simonsdotter",
", Lydeke",
", Mafalda",
", Magdalena J\u00f6ransdotter",
", Magnus H\u00e5kansson",
", Magnus II Henriksson",
", Magnus Ingevaldsson",
", Magnus Marinasson",
", Magnus minnesk\u00f6ld Bengtsson",
", Magnus Nilsson",
", Maisa",
", Maisa",
", Maisa Ericsdotter",
", Malin",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta",
", Margareta Bengtsdotter",
", Margareta Ericsdotter",
", Margareta Ericsdotter",
", Margareta Grelsdotter",
", Margareta Johansdotter",
", Margareta Knudsdatter",
", Margareta Larsdotter",
", Margareta Larsdotter",
", Margareta Lidinvardsdotter",
", Margareta Marcusdotter",
", Margareta Mattsdotter",
", Margareta M\u00e5rtensdotter",
", Margareta Pedersdotter",
", Margareta Pehrsdotter",
", Margareta Petersdotter",
", Margareta Sigfridsdotter",
", Margareta Skulesdotter",
", Margareta Torgilsdotter",
", Margareta Ulfsdotter",
", Margaretha Matthiae",
", Margeta",
", Margeta",
", Margeta",
", Margeta Lukasdotter",
", Margeta Mattsdotter",
", Margetha",
", Margetha Berendsdotter",
", Margetha Nisiusdotter",
", Maria",
", Maria",
", Maria",
", Maria",
", Maria Andersdotter",
", Maria Danielsdotter",
", Maria Eliasdotter",
", Maria Eriksdotter",
", Maria Hendrichsdotter",
", Maria Hindrichsdotter",
", Maria Jacobsdotter",
", Maria Johannis",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria Johansdotter",
", Maria J\u00f6ransdotter",
", Maria J\u00f6ransdotter",
", Maria J\u00f6ransdotter",
", Maria Markusdotter",
", Maria Matthiae",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Michelsdotter",
", Maria M\u00e5rtensdotter",
", Maria Sigfridsdotter",
", Maria Simonsdotter",
", Maria Thomasdotter",
", Maria Elisabeth Lovisa Gabrielsdotter",
", Mats Oddsson",
", Matts\u200e",
", Matts",
", Matts J\u00f6nsson",
", Matts Marci",
", Michel Cnutsson",
", Michel Grelsson",
", Michel Mattsson",
", Mstislav I",
", M\u00e5rten Henricsson",
", M\u00e5rten J\u00f6ransson",
", M\u00e5rten J\u00f6ransson",
", M\u00e4rta",
", M\u00e4rta Siggesdotter",
", N",
", N",
", N",
", N",
", N",
", N Jonsdotter",
", N Knutsdotter",
", N Magnusdotter",
", N Svantopolksdotter",
", Nils",
", Nils",
", Nils Magnusson",
", Olof",
", Olof Abelsson",
", Peer Hendersson",
", Peter Ragnvaldsson",
", Petter J\u00f6ransson",
", Ragnfrid Erlingsdatter",
", Ragnhild",
", Ragnhild",
", Ragnhild",
", Ragnhild Eriksdotter",
", Ramborg Magnusdotter",
", Ramfrid Gustavsdotter",
", Sancho I",
", Sara Bertilsdotter",
", Sigmund Keldorsson",
", Sigrid",
", Sigrid Torkjellsdotter",
", Sigrid Uddormsdotter",
", Simon Mattsson",
", Sixten",
", Skule B\u00e5rdsson",
", Sofia",
", Sofia J\u00f6ransdotter",
", Sofia Mattsdotter",
", Sofia Thomasdotter",
", Sophia",
", Sophia",
", Sophia Eskilsdotter",
", Sophia Josephsdotter",
", Sophia M\u00e5rtensdotter",
", Sophia Sigfridsdotter",
", Sophia Thomasdotter",
", Sophie",
", Stenkil",
", Sune Folkesson",
", Sunniva Larsdotter",
", Sunniva Sigfridsdotter",
", Sunniva Thomasdotter",
", Susanna J\u00f6ransdotter",
", Svantepolk Knudsen",
", Svantopolk",
", Sven Jonsson",
", Svend II Estridsen",
", Sverker I den \u00e4ldre",
", Sverker II den yngre",
", Sverre",
", Thomas Jacobsson",
", Thomas Johansson",
", Thomas Michelsson",
", Torgil Knutsson",
", Uddorm Petersson",
", Ulf Torgilsen",
", Ulrika Vilhelmina Abrahamsdotter",
", Ulvhild Haakonsdatter",
", Ursula Mattsdotter",
", Valborg",
", Valborg Olofsdotter",
", Valborg Sigfridsdotter",
", Valdemar II sejr",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg",
", Walborg Clemetsdotter",
", Walborg Hendersdotter",
", Walborg Johansdotter",
", Walborg Johansdotter",
", Walborg Knutsdotter",
", Walborg Larsdotter",
", Walborg Mattsdotter",
", Walborg Mattsdotter",
", Walborg Michelsdotter",
", Walborg M\u00e5rtensdotter",
", Walborg Philipsdotter",
", Walborg Sigfridsdotter",
", Walborg Simonsdotter",
", Walborg Thomasdotter",
"af Aagaard, Christina",
"af Flandern, Edel",
"af Portugal, Bereng\u00e1ria",
"af Sachsen, Albrecht I",
"Ahokas, Taimi Sivi\u00e4",
"Alanen, Anna Petri",
"Alanen, Gustav Petersson",
"Alanen, Peter Thomasson",
"Alanen, Petter Gustafsson",
"Alanen, Thomas Petersson",
"Altena, Ermegaard Eggartsdotter",
"And, Anders",
"And, Israel Andersson",
"And, Ramborg Israelsdotter",
"Anttila, Elisabeth Jacobsdotter",
"Anttila, Eric Johansson",
"Anttila, Henrich Johansson",
"Anttila, Johan Ericsson",
"Anttila, Johan Henrichsson",
"Anttila, Johan Johansson",
"Anttila, Lisa Pauli",
"Anttila, Maria Henricsdotter",
"Anttila, P\u00e5hl Thomasson",
"Anttila, Thomas Johansson",
"Arctopolitana, Kristina Gregoriusdotter",
"Arctopolitanus, Gregorius Thomae",
"Arra, Eric Larsson",
"Arra, Henric J\u00f6ransson",
"Arra, Johan J\u00f6ransson",
"Arra, Joseph Johansson",
"Arra, J\u00f6ran Josephsson",
"Arra, Lars M\u00e5rtensson",
"Arra, Margeta Ericsdotter",
"Arra, Walborg Henricsdotter",
"Aspen\u00e4s, Cecilia Knutsdotter",
"Aspen\u00e4s, Knut Jonsson",
"av Danmark, Ingeborg Eriksdatter",
"av Kiev, Ingeborg",
"av Minsk, Volodar",
"av Polen, Rikissa",
"av Reval, Knud",
"Balk, Margareta R\u00f6riksdotter",
"Balk, R\u00f6rik Birgersson",
"Ban\u00e9r, Eskil Isaksson",
"Ban\u00e9r, Isak Bj\u00f6rnsson",
"Ban\u00e9r, Isak Isaksson",
"Ban\u00e9r, Sigrid Eskilsdotter",
"Barun, Estrid Knutsdotter",
"Barun, Knut Erengislesson",
"Berg, Abel Olofsson",
"Berg, Erik Johan Abelsson",
"Berg, Erik Johan Eriksson",
"Berg, Eva Stina",
"Bergman, Anna Sofia",
"Bese, Gunhild Johansdotter",
"Bese, Johan Stensson",
"Bese, J\u00f6nis Stensson",
"Bese, Sten",
"Bese, Sten J\u00f6nsson",
"Beurr\u00e6us, Arvid Claesson",
"Bielke, Bengt Thuresson",
"Bielke, Birgitta Turesdotter",
"Bielke, Catharina Turesdotter",
"Bielke, Erik Turesson",
"Bielke, Karin Eriksdotter",
"Bielke, Katarina Stensdotter",
"Bielke, K\u00e4ttil",
"Bielke, Peder Turesson",
"Bielke, Sten Bengtsson",
"Bielke, Sten Turesson",
"Bielke, Thure K\u00e4ttilsson",
"Bielke, Thure Thuresson",
"Bielke, Ture Bengtsson",
"Bielke, Ture Pedersson",
"Bielke, Ture Stensson",
"Birkman, Elisabeth Joachimsdotter",
"Birkman, Joachimus Sigfridi",
"Birkman, Sigfridus Olai",
"Bj\u00e4lbo, Bengt Magnusson",
"Bj\u00e4lbo, Bengt Magnusson",
"Bj\u00e4lbo, Ingeborg Bengtsdotter",
"Bj\u00e4lbo, Katarina Bengtsdotter",
"Bj\u00e4lbo, Magnus Bengtsson",
"Blomberg, Olof",
"Bl\u00e5tann, Harald",
"Boll, Eva Andersdotter",
"Bonde, Birgitta Karlsdotter",
"Bonde, Erengisle Petersson",
"Bonde, Karl Tordsson",
"Bonde, Karl VIII Knutson",
"Bonde, Knut Tordsson",
"Bonde, Kristina Karlsdotter",
"Bonde, M\u00e4rta Tordsdotter",
"Bonde, Peter Erengislesson",
"Bonde, R\u00f6rik Tordsson",
"Bonde, Tord Petersson",
"Bonde, Tord Petersson",
"Bonde, Tord R\u00f6riksson",
"Borgare, Henrik",
"Borgare, Michel Henricsson",
"Bosson, Bengt",
"Bosson, Magnus Bengtsson",
"Bosson, Margareta Bengtsdotter",
"Brock, Eske Jensen",
"Brock, Lave Eskelsen",
"Brock, Margareta Lagesdotter",
"Brun, Anders Andersson",
"Brun, Anna Andersdotter",
"Brun, Sigge",
"Bydelsbach, Albrecht",
"Bydelsbach, Beate Albrechtsdatter",
"Bydelsbach, Hebbla Albrechtsdatter",
"B\u00fclow, Ermeg\u00e5rd Fickesdotter",
"B\u00fclow, Ficke",
"B\u00fclow, Johan",
"B\u00e4k, Sven",
"den Fagra, Sigrid",
"den Gamle, Gorm",
"den Gamle, H\u00e5kon IV H\u00e5konsson",
"den store, Valdemar I",
"der B\u00e4r, Albrecht",
"Dickman, Catharina Jobstsdotter",
"Dickman, Jobst Jobstsson",
"Dickman, Jobst Johansson",
"Dickman, Johan Jobstsson",
"Dj\u00e4ken, Cecilie J\u00f6nissadottir",
"Dj\u00e4ken, J\u00f6nis",
"Dj\u00e4kn, Abraham",
"Dj\u00e4kn, Karin Klasdotter",
"Dj\u00e4kn, Klaus Lydekesson",
"Dj\u00e4kn, M\u00e5rten Abrahamsson",
"Dj\u00e4kn, M\u00e4rta Klasdotter",
"Dj\u00e4kn, N Klasdotter",
"Dj\u00e4kn, N M\u00e5rtensdotter",
"Dyre, Bo Tygesen",
"Dyre, Cecilia Bosdotter",
"Eerola, Anna Henrichsdotter",
"Eerola, Beata Henricsdotter",
"Eerola, Henric Henricsson",
"Eerola, Henric Thomasson",
"Eerola, Thomas Henricsson",
"Eskola, Brita Ericsdotter",
"Eskola, Erich J\u00f6ransson",
"Eskola, Erik Eskilsson",
"Eskola, Eskil Eskilsson",
"Eskola, J\u00f6ran Thomasson",
"Eskola, Lars Ericsson",
"Eskola, Thomas Larsson",
"Feirich, Catharina M\u00e5rtensdotter",
"Feirich, M\u00e5rten",
"Finsta, Birger Persson",
"Finsta, Katerina Birgersdotter",
"Finsta, N Israelsdotter",
"Finsta, Peter Israelsson",
"Frestadius, Lena Pehrsdotter",
"Frestadius, Olof Pettersson",
"Frestadius, Petrus Olofsson",
"Frestadius, Petter Petri",
"Frille, Christer H\u00e5kansson",
"Frille, Christiern Frellavsen",
"Frille, Frellav Hakonsen",
"Frille, Hakon Frellavsen",
"Frille, H\u00e5kan Christersen",
"Frille, Kristina Christersdotter",
"Frisern af Flandern, Robert",
"Fr\u00f6svik, Birgitta Finvidsdotter",
"Fr\u00f6svik, Finvid Nilsson",
"F\u00e5ck, Walborg Georgii",
"F\u00e4lt, Alexander Viktor",
"Garp, Anders",
"Garp, Jakob J\u00f6nsson",
"Garp, J\u00f6ns Andersson",
"Garp, Karin Olofsdotter",
"Garp, Kristina Jacobsdotter",
"Garp, Kristina J\u00f6nsdotter",
"Gille, Harald IV",
"Glad, Carl",
"Glad, Ester Sofia",
"Glad, Jacob Jacobsson",
"Glad, Johannes Joel",
"Gottleben, Gabriel",
"Gottleben, Margareta Gabrielsdotter",
"Gottleben, Valentin",
"Gren, Cecilia Haraldsdotter",
"Gren, Ernils Kettilbj\u00f6rnsson",
"Gren, Harald Ernilsson",
"Gren, Harald Stensson",
"Gren, Kettilbj\u00f6rn Knutsson",
"Gren, Sten Haraldsson",
"Grubbe, Juliane Pedersdatter",
"Grubbe, Peder Jensen",
"Gylden\u00e4r, Conrad",
"Gylden\u00e4r, Ingeborg Johansdotter",
"Gylden\u00e4r, Johan Conradsson",
"Gyllenstierna, Christina Nilsdotter",
"Gyllenstierna, Erik Eriksson den \u00e4ldre",
"Gyllenstierna, Kerstin Eriksdotter",
"Gyllenstierna, Nils Eriksson",
"Gyllenstierna af Svaneholm, Erik Nielsen",
"Gyllenstierna af Svaneholm, Erik Nilsen",
"Gyllenstierna af Svaneholm, Niels Eriksen",
"Gyllenstierna af Svaneholm, Niels Eriksen den h\u00f6ge",
"G\u00e4dda, Erengisle Karlsson",
"G\u00e4dda, Iliana Erengislesdotter",
"G\u00e4dda, Johan Nilsson",
"G\u00e4dda, Jon",
"G\u00e4dda, Karl Nilsson",
"G\u00e4dda, Katarina Johansdotter",
"G\u00e4dda, Nils Jonsson",
"Haapaniemi, M\u00e5rten Henricsson",
"Hakim\u00e4ki, Maria Henricsdotter",
"Halvonoja, Hedvig Albertina Henricsdotter",
"Halvonoja, Henric J\u00f6ransson",
"Hammersta, Kristina Magnusdotter",
"Hampaala, Caisa",
"Hampaala, Jacob J\u00f6ransson",
"Hampaala, J\u00f6ran Jacobsson",
"Hampaala, Lisa M\u00e5rtensdotter",
"Hampaala, Maria J\u00f6ransdotter",
"Hampaala, Sofia Jacobsdotter",
"Harkki, Jacob Pettersson",
"Harkki, Maria Jacobi",
"Harola, Jacob J\u00f6ransson",
"Harola, J\u00f6ran Eskelsson",
"Harola, Maria Jacobsdotter",
"Hatt, Anund",
"Hatt, Kristina Anundsdotter",
"Heikkil\u00e4, Anders Christersson",
"Heikkil\u00e4, Anders Henricsson",
"Heikkil\u00e4, Anna Andersdotter",
"Heikkil\u00e4, Brusius Mattsson",
"Heikkil\u00e4, Carl Pehrsson",
"Heikkil\u00e4, Christer Sigfridsson",
"Heikkil\u00e4, Cnud Ericsson",
"Heikkil\u00e4, Gabriel Michelsson",
"Heikkil\u00e4, Hendrich Hendersson",
"Heikkil\u00e4, Henric Mathiae",
"Heikkil\u00e4, Henric M\u00e5rtensson",
"Heikkil\u00e4, Henric Thomasson",
"Heikkil\u00e4, Henric Thomasson",
"Heikkil\u00e4, Henrik Olofsson",
"Heikkil\u00e4, Ingeborg Carlsdotter",
"Heikkil\u00e4, Marcus Henricsson",
"Heikkil\u00e4, Margareta Cnudsdotter",
"Heikkil\u00e4, Maria Marcusdotter",
"Heikkil\u00e4, Maria Michelsdotter",
"Heikkil\u00e4, Matts Mattsson",
"Heikkil\u00e4, Matts M\u00e5rtensson",
"Heikkil\u00e4, Michel Gabrielsson",
"Heikkil\u00e4, Michel Mattsson",
"Heikkil\u00e4, M\u00e5rten Henricsson",
"Heikkil\u00e4, Olof Henriksson",
"Heikkil\u00e4, Simon Simonis",
"Heikkil\u00e4, Sophia Henricsdotter",
"Heikkil\u00e4, Thomas Brusiusson",
"Heikkil\u00e4, Thomas Henricsson",
"Herckman, Gustaf Henricsson",
"Herckman, Hans Gustafsson",
"Herckman, Hebla Henricsdotter",
"Herckman, Maria Henricsdotter",
"Herckman, Sara Hansdotter",
"Hettunen, Beata Ericsdotter",
"Hettunen, Eric Henricsson",
"Hettunen, Eric Larsson",
"Hettunen, Henric Ericsson",
"Hettunen, Lars Olsson",
"Hettunen, Margeta Thomasdotter",
"Hettunen, Olef Staffansson",
"Hettunen, Thomas Cnutsson",
"Hiiri, Bertil Nilsson",
"Hiiri, Matts Bertilsson",
"Hiiri, Nils Larsson",
"Hinkka, Maria Hendrichsdotter",
"Hinkka, Nils H\u00e5kansson",
"Hinkka, Olof Nilsson",
"Hinkka, Walborg Olofsdotter",
"Hinkkala, Maria J\u00f6ransdotter",
"Hirvenoja, Johan Gustaf Thomasson",
"Hirvenoja, Susanna Juhontyt\u00e4r",
"Hjorthuvud, Gudmar Magnusson",
"Hogenskild, Anna Clemetsdotter",
"Hogenskild, Clemet Bengtsson",
"Horn af Kanckas, Arvid Henriksson",
"Horn af Kanckas, Elin Arvidsdotter",
"Horn af Kanckas, Ingeborg Arvidsdotter",
"Horn af \u00c5minne, Arvid Mauritzson",
"Horn af \u00c5minne, Christina Arvidsdotter",
"Horn af \u00c5minne, Henrik Olofsson",
"Horn af \u00c5minne, Klas Henriksson",
"Horn af \u00c5minne, Klas Kristersson",
"Horn af \u00c5minne, Krister Klasson",
"Horn af \u00c5minne, Krister Klasson",
"Horn af \u00c5minne, Mauritz Kristersson",
"Horn af \u00c5minne, Olof Mattsson",
"Horn till Kanckas, Henrik Klasson",
"Hultti, Gertrud Ollsdotter",
"Hultti, Olof Sigfridsson",
"Hultti, Sigfred Simonsson",
"Huti, Lars Sigfridsson",
"Huti, Lisa Thomasdotter",
"Huti, Sigfrid Michelsson",
"Huti, Thomas Larsson",
"Huuna, Elin Hendrichsdotter",
"Huuna, Henric Thomasson",
"Huuna, Henrich J\u00f6ransson",
"Huuna, J\u00f6ran Ericsson",
"Huuna, Thomas Henrichsson",
"Hvide, Benedicta Ebbesdotter",
"Hvide, Christine Stigsdatter",
"Hvide, Ebbe Skjalmsen",
"Hvide, Ebbe Sunesen",
"Hvide, Skjalm",
"Hvide, Stig",
"Hvide, Sune Ebbesen",
"H\u00e4rtsi\u00e4, Marcus",
"H\u00e4rtsi\u00e4, Morthen Marcusson",
"H\u00f6gberg, Eric Henricsson",
"H\u00f6lli, Brita Sigfridsdotter",
"H\u00f6lli, Clemet Mattsson",
"H\u00f6lli, Henrik Henriksson",
"H\u00f6lli, J\u00f6ran J\u00f6ransson",
"H\u00f6lli, J\u00f6ran J\u00f6ransson",
"H\u00f6lli, J\u00f6ran Mattsson",
"H\u00f6lli, Lars Henriksson",
"H\u00f6lli, Maria Mathiae",
"H\u00f6lli, Matts J\u00f6ransson",
"H\u00f6lli, Matts Larsson",
"H\u00f6lli, Matts Mattsson",
"H\u00f6lli, Sigfrid Clemetsson",
"Illander, Maria Nilsdotter",
"Illander, Nicolaus Nielsson",
"Illander, Nils",
"Illman, Anders",
"Illman, Eva Andersdotter",
"Irjala, Johan Thomasson",
"Irjala, Johan Thomasson",
"Irjala, Karin Johansdotter",
"Irjala, Kirstin Johansdotter",
"Irjala, Maria J\u00f6ransdotter",
"Irjala, Thomas J\u00f6ransson",
"Irjala, Thomas Pehrsson",
"Iso-Kaulo, Marcus Nilsson",
"Iso-Kaulo, P\u00e5hl Marcusson",
"Iso-Kaulo, Simon P\u00e5hlsson",
"Jaakkola, Michael Michaelis",
"Jokela, Edvard Lauri",
"Jokela, Juha Kustaa Kustaanpoika",
"Jokela, Leo Ensio",
"Jokela, Rauha Signe",
"Joppi, Johan Henricsson",
"Jussila, Eric Simonsson",
"Jussila, Henric J\u00f6ransson",
"Jussila, J\u00f6ran Thomasson",
"Jussila, Simon Mattsson",
"Jussila, Sofia Henricsdotter",
"Juusela, Eric Thomasson",
"Juusela, Maria Ericsdotter",
"Juva, Erich Eskillsson",
"Juva, Eskill",
"Juva, Peer Staffansson",
"Juva, Staffan Ericsson",
"Karo, J\u00f6ran Nilsson",
"Karo, Nisius Larsson",
"Karo, Peer J\u00f6ransson",
"Karppi, Eskell P\u00e5fwellsson",
"Karppi, Henric Larsson",
"Karppi, Lars Henricsson",
"Karppi, Maria Mattsdotter",
"Karppi, Marja Mattsdotter",
"Karppi, Matts Eskelsson",
"Karppi, Matts Mattsson",
"Karppi, Matts Michelsson",
"Karppi, P\u00e5fwell Larsson tai Jacobsson",
"Kauko, Anders Marcusson",
"Kauko, Bertil Marcusson",
"Kauko, Eric Mattsson",
"Kauko, Marcus Bertilssson",
"Kauko, Marcus Ericsson",
"Kauko, Matts Pehrsson",
"Kauko, Walborg Andersdotter",
"Kaulo, Nils J\u00f6nsson",
"Kauppila, Jacob Olsson",
"Kauppila, Lasse Larsson",
"Kauppila, Lasse Persson",
"Kauppila, Matts Simonsson",
"Kauppila, Olof Larsson",
"Kauppila, Simon Jacobsson",
"Kauppila, Walborg Mattsdotter",
"Keskinen, Heikki Juhonpoika",
"Keskinen, Johan Henrik",
"Keskinen, Kaarlo Elias",
"Keskinen, Kari Mikael",
"Keskinen, Martti Mikael",
"Keskinen, Siiri Matilda",
"Kiesinen, Anders Andersson",
"Kiesinen, Anders Jacobsson",
"Kiesinen, Brita Ericsdotter",
"Kiesinen, Eric Henricsson",
"Kiesinen, Henrich J\u00f6ransson",
"Kiesinen, J\u00f6ran Andersson",
"Kinnari, Eric Henricsson",
"Kinnari, Eric Henricsson",
"Kinnari, Henric Ericsson",
"Kinnari, Hindrich Hindrichsson",
"Kinnari, Kreeta Kaisa Yrj\u00e4n\u00e4ntyt\u00e4r",
"Kinnari, Maria Erici",
"Kirves, Karin Olofsdotter",
"Kirves, Olof den \u00e4ldre",
"Klemola, Anna Georgii",
"Klemola, Elisabeth Marcusdotter",
"Klemola, J\u00f6ran Olai",
"Klemola, Olof Sigfridsson",
"Klemola, Sigfrid Escilsson",
"Koivisto, Anna Henrichsdotter",
"Kottila, Henric Mattsson",
"Kottila, J\u00f6ran Hendrichsson",
"Kottila, Matts J\u00f6ransson",
"Kratz, Marcus Johanis",
"Krognos, Axel Kjeldsen",
"Krognos, Cathrine Axelsdatter",
"Krumme, Jakob Nilsson",
"Krumme, Kerstin Jakobsdotter",
"Krumme, Nils",
"Krumme, Nils Nilsson",
"Krumme, Nils Svensson",
"Krummedige, Anne Eriksdatter",
"Krummedige, Ebba Eriksdatter",
"Krummedige, Erik Segebodsen",
"Krummedige, Margaretha Eriksdatter",
"Krummedige, Segebod",
"Kurki, Elin J\u00f6nsdotter",
"Kurki, Elin Klasdotter",
"Kurki, Jeppe",
"Kurki, J\u00f6ns Knutsson",
"Kurki, Klaus Jeppesson",
"Kurki, Kristina Knutsdotter",
"Kurvola, Henric Johansson",
"Kurvola, Johan Michelsson",
"Kurvola, Johan Olofsson",
"Kurvola, Michel Hendrichsson",
"Kurvola, Michel Johansson",
"Kyrning, Ingegerd Pedersdatter",
"Kyrning, Peder",
"K\u00e4r\u00e4v\u00e4, Eric Thomae",
"K\u00e4r\u00e4v\u00e4, Henric Thomasson",
"K\u00e4r\u00e4v\u00e4, Thomas Ericsson",
"K\u00e4r\u00e4v\u00e4, Thomas Henricsson",
"K\u00f6nigsmark, Bengt Henningsson",
"K\u00f6nigsmark, Henning Herbrechtsson",
"K\u00f6nigsmark, Herbrecht",
"K\u00f6nigsmark, Katarina Bengtsdotter",
"K\u00f6rning, Bengta Simonsdotter",
"K\u00f6rning, Simon Pedersson",
"Laatu, Hendrich Michelsson",
"Laatu, Henric M\u00e5rtensson",
"Laatu, M\u00e5rten Michelsson",
"Lagab\u00f8ter, Magnus VI H\u00e5konsson",
"Laurila, Anders Andersson",
"Laurila, Anna Mattsdotter",
"Laurila, Christina Paulsdotter",
"Laurila, Clemet Mattsson",
"Laurila, Eric Henricsson",
"Laurila, Hendric Ersson",
"Laurila, Henric Andersson",
"Laurila, Henric J\u00f6ransson",
"Laurila, Henric Pehrsson",
"Laurila, Jacob Ersson",
"Laurila, J\u00f6ran Thomasson",
"Laurila, Knut",
"Laurila, Lars Nilsson",
"Laurila, Lisa Clemetsdotter",
"Laurila, Marcus Henrici",
"Laurila, Matts Gustafsson",
"Laurila, Matts Jacobsson",
"Laurila, Michel Henricsson",
"Laurila, Paul Henrichsson",
"Laurila, Per Cnutsson",
"Laurila, Per Larsson",
"Laurila, Per Persson",
"Laurila, Thomas Henricsson",
"Lavard, Knut",
"Laxmand, Else Pedersdatter",
"Laxmand, Peder",
"Leijonhufvud, Abraham Kristiernsson",
"Leijonhufvud, Erik Abrahamsson",
"Leijonhufvud, Greger",
"Leijonhufvud, Kristiern",
"Leijonhufvud, Kristiern Gregersson",
"Leijonhufvud, M\u00e4rta Eriksdotter",
"Leistenia, Maria Jacobsdotter",
"Leistenius, Jacobus Olai",
"Leistenius, Olof Johannis",
"Lejonbj\u00e4lke, Birgitta Knutsdotter",
"Lejonbj\u00e4lke, Knut Matsson",
"Lind, Christina Erichsdotter",
"Lind, Erich",
"Lindroos, Juha Henrik Juhanpoika",
"Lindroos, Kustaava Matilda Juhantyt\u00e4r",
"Lindstr\u00f6m, Anders Johansson",
"Lindstr\u00f6m, Johan Thomasson",
"Lindstr\u00f6m, Sofia Vilhelmina",
"Lintula, Jacob Simonsson",
"Lintula, J\u00f6ran Simonsson",
"Lintula, Simon Thuresson",
"Liukko, Anna Thomasdotter",
"Liukko, J\u00f6ran Mathiae",
"Liukko, Matts Thomasson",
"Liukko, Thomas Henricsson",
"Liukko, Thomas Mattsson",
"Luikko, Anders",
"Luikko, Anders Thomasson",
"Luikko, Thomas Andersson",
"L\u00fctkens, Catharina",
"Malmberg, Maria Mattsdotter",
"Malmberg, Matts Mattsson",
"Marttila, Henric Mattsson",
"Marttila, Maria Mattsdotter",
"Marttila, Matts Erichsson",
"Marttila, Matts Henriksson",
"Mattila, Georgius Laurentii",
"Mattila, Johan Mattsson",
"Mattila, Margeta J\u00f6ransdotter",
"Mattila, Matts Michelsson",
"Mattila, Sofia Mattsdotter",
"Maunu, Jacob Eskilsson",
"Maunu, Lisa Jacobi",
"Mets\u00e4-Heikkil\u00e4, Gustaf Mattsson",
"Mets\u00e4-Heikkil\u00e4, Matts Simonis",
"Mikkola, Abraham Mathiae",
"Mikkola, Beata Jacobi",
"Mikkola, Clemet Samuelsson",
"Mikkola, Henric Olofsson",
"Mikkola, Lisa Mathia",
"Mikkola, Matts Clemetsson",
"Mikkola, Olof Michelsson",
"Mikkola, Samuel Mattsson",
"Moltke, Bertha Evertsdatter",
"Moltke, Evert Johansen",
"Moltke, Henneke Johan Evertsen",
"Moltke, Johan",
"Moltke, Margareta Johansdotter",
"Monnila, Caisa Pehrsdotter",
"Mukkula, Henric J\u00f6ransson",
"Mulli, Anders Nilsson",
"Mulli, Henric Andersson",
"Mulli, Nils Nilsson",
"Mutonen, Christina M\u00e5rtensdotter",
"Mutonen, J\u00f6ran Mattsson",
"Mutonen, Margeta Georgii",
"M\u00e4llinoja, Agnis Ericsdotter",
"M\u00e4llinoja, Beata Sigfredsdotter",
"M\u00e4llinoja, Bertil Eskilsson",
"M\u00e4llinoja, Erich Jacobsson",
"M\u00e4llinoja, Margeta Gabrielsdotter",
"M\u00e4llinoja, Sigfrid Bertilsson",
"M\u00f6hk\u00f6l\u00e4, Clemet Augustsson",
"M\u00f6hk\u00f6l\u00e4, Helena Henricsdotter",
"M\u00f6hk\u00f6l\u00e4, Henric Simonsson",
"M\u00f6hk\u00f6l\u00e4, Lisa Mattsdotter",
"M\u00f6hk\u00f6l\u00e4, Matts Michelsson",
"M\u00f6hk\u00f6l\u00e4, Matts Peersson",
"M\u00f6hk\u00f6l\u00e4, Michel Mattsson",
"M\u00f6hk\u00f6l\u00e4, Peer Peersson",
"M\u00f6hk\u00f6l\u00e4, Petter Clemetsson",
"M\u00f6hk\u00f6l\u00e4, Sigfrid Clemetsson",
"M\u00f6hk\u00f6l\u00e4, Simon Sigfridsson",
"M\u00f6rt, Matts Mattsson",
"M\u00f6rt, Walborg Mattsdotter",
"N, N",
"Natt och Dag, Bengt Stensson",
"Natt och Dag, Birgitta M\u00e5nsdotter",
"Natt och Dag, Bo Bosson",
"Natt och Dag, Bo Nilsson",
"Natt och Dag, Bo Stensson",
"Natt och Dag, Kerstin M\u00e5nsdotter",
"Natt och Dag, Magnus Bengtsson",
"Natt och Dag, Nils Sigridsson",
"Natt och Dag, Sten Bosson",
"Neulaniemi, Henrik",
"Niittum\u00e4ki, Erik Eriksson",
"Niittum\u00e4ki, Maria Lovisa Eriksdotter",
"Nikkil\u00e4, Anna Johannis",
"Nikkil\u00e4, Johan Mattsson",
"Nikula, Bertil Fransson",
"Nikula, Frans Mattsson",
"Nikula, Matts Bertilsson",
"Nikula, Matts Michelsson",
"Nikula, Thomas Mattsson",
"Nyman, Anders",
"Nyman, Maria Andersdotter",
"Ohralahti, Eeva Loviisa Kaarlentyt\u00e4r",
"Ohralahti, Kaarle Antinpoika",
"Orre, J\u00f6ran",
"Outinen, Lisa Simonsdotter",
"Outinen, Simon Mattsson",
"Pajunen, Hendrich Georgi",
"Pajunen, J\u00f6ran Jacobsson",
"Pajunen, Margeta Jacobsdotter",
"Pajunen, Staffan J\u00f6ransson",
"Peissu, Georgius Mattsson",
"Peissu, Henric Olofsson",
"Peissu, Lisa Georgii",
"Peissu, Matts Henricsson",
"Peissu, Matts M\u00e5rtensson",
"Peissu, M\u00e5rten Thomasson",
"Peissu, Olof Mattsson",
"Pekka, Anders Eskelsson",
"Pekka, Eskel Mattsson",
"Pekka, Johan Andersson",
"Pekka, Maria Johannis",
"Pekka, Susanna Thomasdotter",
"Pekka, Thomas Georgii",
"Pekka, Thomas Thomae",
"Penttil\u00e4, Henric J\u00f6ransson",
"Penttil\u00e4, J\u00f6ran Thomasson",
"Penttil\u00e4, Olof Olofsson",
"Penttil\u00e4, Thomas Olofsson",
"Perttula, Agnes Mattsdotter",
"Perttula, Anders J\u00f6ransson",
"Perttula, Bertil Ericsson",
"Perttula, Erich Simonsson",
"Perttula, Johan Andersson",
"Perttula, Maria Johanis",
"Perttula, Matts Bertillsson",
"Perttula, M\u00e5rten Larsson",
"Perttula, Simon M\u00e5rtensson",
"Plata, Claus",
"Plata, M\u00e4rta Klausdotter",
"Plovpenning, Erik IV",
"Puke, Cathrine Eriksdatter",
"Puke, Erik Kettilsson",
"Puke, Kettil Ragvaldsson",
"Puke, Ragnvald",
"Punala, Anders Andersson",
"Punala, Anders Ericsson",
"P\u00e4ilahti, Jacob Nilsson",
"P\u00e4ilahti, J\u00f6ran Jacobsson",
"P\u00f6yh\u00f6, Olof Henricsson",
"Rahm, Rinchel",
"Rasila, Cnut Rasmusson",
"Rasila, Eric Sigfridsson",
"Rasila, Lisa Ericsdotter",
"Rasila, Sigfrid Cnutsson",
"Raud, Hafthor Jonsson",
"Raud, Jon Hafthorsson",
"Raud, Jon Ivarsson",
"Raukola, Brita Andersdotter",
"Raukola, Henric Mattsson",
"Raukola, Johanna Leenantyt\u00e4r",
"Raukola, Lena Simonsdotter",
"Raukola, Matts Henriksson",
"Raukola, Simon Henrici",
"Raumensis, Michael Michaelis",
"Revelsta, Kristina Nilsdotter",
"Revelsta, Nils Jonsson",
"Riippa, Clemet Nilsson",
"Riippa, Eric Nilsson",
"Riippa, Nils Clemetsson",
"Romu, Anna Lyyli",
"Roos af Ervalla, Katarina Ulvsdotter",
"Roos af Ervalla, Ulv Jonsson",
"Rooseli, Clemet Olofsson",
"Rooseli, Matts Clemetsson",
"Rooseli, Nils Olofsson",
"Rooseli, Olof Nilsson",
"Roseli, Erasmus Thomasson",
"Roseli, Sigfrid Andersson",
"Roseli, Sofia Erasmusdotter",
"Roseli, Thomas Sigfridsson",
"Rosell, Clemet Nilsson",
"Rosell, Nils Olofsson",
"Rosell, Olof Clemetsson",
"Rossi, Beata Mattsdotter",
"Rossi, Mats Matsson",
"Ruotsila, Johan Pehrsson",
"Ryss, Isac Mattsson",
"R\u00f8nnow, Beate",
"Sahraj\u00e4rvi, Erich J\u00f6ransson",
"Sahraj\u00e4rvi, J\u00f6ran Ericsson",
"Sahraj\u00e4rvi, J\u00f6ran J\u00f6ransson",
"Savola, Gustav Zachrisson",
"Savola, Hans Henricsson",
"Savola, Henric Ericsson",
"Savola, Zacharias Hansson",
"Schartoff, Frans",
"Schartoff, Maria Fransdotter",
"Seiv\u00e4s, Caisa M\u00e5rtensdotter",
"Seiv\u00e4s, Eric M\u00e5rtensson",
"Seiv\u00e4s, Eric M\u00e5rtensson",
"Seiv\u00e4s, J\u00f6ran Ericsson",
"Seiv\u00e4s, Lisa M\u00e5rtensdotter",
"Seiv\u00e4s, M\u00e5rten Ericsson",
"Seiv\u00e4s, M\u00e5rten J\u00f6ransson",
"Seiv\u00e4s, M\u00e5rten Sigfridsson",
"Semenius, Eric Johansson",
"Semenius, Helena Ericsdotter",
"Sepp\u00e4, Eric",
"Sepp\u00e4, Sigfrid Ericsson",
"Sepp\u00e4l\u00e4, Elin Michelsdotter",
"Sepp\u00e4l\u00e4, Elin M\u00e5rtensdotter",
"Sepp\u00e4l\u00e4, Georg Mathiae",
"Sepp\u00e4l\u00e4, Henric M\u00e5rtensson",
"Sepp\u00e4l\u00e4, Henric Olsson",
"Sepp\u00e4l\u00e4, Kaisa Isacsdotter",
"Sepp\u00e4l\u00e4, Matts Johansson",
"Sepp\u00e4l\u00e4, M\u00e5rten Henricsson",
"Sepp\u00e4l\u00e4, M\u00e5rten Henricsson",
"Sepp\u00e4l\u00e4, Olof Sigfridsson",
"Sipil\u00e4, Henrik J\u00f6ransson",
"Sipil\u00e4, J\u00f6ran J\u00f6ransson",
"Sipil\u00e4, Margareta Henricsdotter",
"Siurola, Thure Thomasson",
"Skram, C\u00e6cilie Pedersdatter",
"Skytte, J\u00f6ns",
"Sk\u00e4nkare, Birger",
"Sk\u00e4nkare, N Birgersdotter",
"Sorri, Carl Henrici",
"Sorri, Eric Caroli",
"Sorri, Henric",
"Sorri, Maria Ericsdotter",
"Sparre af Ellinge, Katarina Nilsdotter",
"Sparre af Ellinge, Klaus Nilsson",
"Sparre af Ellinge, Nils Klausson",
"Sparre af Ellinge, Nils Svensson",
"Sparre af Rossvik, Ingeborg Siggesdotter",
"Sparre af Rossvik, Laurens Siggesson",
"Sparre af Rossvik, Sigge Larsson",
"Sparre af Rossvik, Sigge Laurensson",
"Sparre av Aspn\u00e4s, Gisle Elinasson",
"Sparre av Aspn\u00e4s, Helena Magnusdotter",
"Sparre av Aspn\u00e4s, Magnus Gisleson",
"Sparre av Aspn\u00e4s, M\u00e4rta Gislesdotter",
"Sparre av Tofta, Abj\u00f6rn Sixtensson",
"Sparre av Tofta, Karl Ulfsson",
"Sparre av Tofta, Margareta Karlsdotter",
"Sparre av Tofta, Ulf Abj\u00f6rnsson",
"Sparre av Vik, Arvid Gustavsson",
"Sparre av Vik, Arvid Gustavsson",
"Sparre av Vik, Gustav Arvidsson",
"Sparre av Vik, Margareta Arvidsdotter",
"Stangenberg, Cecilia Staffansdotter",
"Stangenberg, Staffan",
"Stenbock, Elin J\u00f6nsdotter",
"Stenbock, J\u00f6ns Olofsson",
"Stenbock, Olof J\u00f6nsson",
"Stierna, Jon Nilsson",
"Stiernkors, Botilla Nilsdotter",
"Stiernkors, Ingeborg Ivarsdotter",
"Stiernkors, Ivar M\u00e5nsson",
"Stiernkors, Magnus Nilsson",
"Stiernkors, Marta Nilsdotter",
"Stiernkors, Nils Olofsson",
"Stiernkors, Olof Persson",
"Stiernsk\u00f6ld, G\u00f6ran Hansson",
"Sture, Katarina Svensdotter",
"Sture, Nils",
"Sture, Nils Bosson",
"Sture, Sigrid Svantesdotter",
"Sture, Sten Svantesson den yngre",
"Sture, Svante Nilsson",
"Sture, Svante Stensson",
"Sture, Sven Nilsson",
"St\u00e5larm, Arvid Eriksson",
"St\u00e5larm, Botvid",
"St\u00e5larm, Elin Arvidsdotter",
"St\u00e5larm, Erik Botvidsson",
"Sv\u00e4rd, Herman",
"Sv\u00e4rd, N",
"S\u00e4lli, Cnut Henricsson",
"S\u00e4lli, J\u00f6ran Cnutsson",
"S\u00e4lli, Lars J\u00f6ransson",
"S\u00e4rkilahti, Nils Pedersson",
"S\u00f6derstr\u00f6m, Isaac Johansson",
"S\u00f6derstr\u00f6m, Sofia Isacsdotter",
"Talola, Eric Nilsson",
"Talola, Gabriel Gabrielsson",
"Talola, Gabriel Michelsson",
"Talola, Michel Ericsson",
"Talvia, J\u00f6ran Thomasson",
"Talvia, Sophia Georgii",
"Tauranen, Henrik J\u00f6nsson",
"Tauranen, J\u00f6ns Henriksson",
"Tavast, Elin Nilsdotter",
"Tavast, Nils Olofsson",
"Tavast, Olof J\u00f6nsson",
"Tavast, Ranghild Olofsdotter",
"Thott, Absalon Axel Aagesen",
"Tiitola, Hendrich Mattsson",
"Tiitola, Henrich Henrichsson",
"Tiitola, Hindrich Hendersson",
"Tiitola, Lisa Hendricsson",
"Tiitola, Matts Henrichsson",
"til Clausholm, Jens Jensen",
"till Grevsj\u00f6, M\u00e4rta Pedersdotter",
"till Grevsj\u00f6, Peder Eriksson",
"till Nyn\u00e4s, Karin",
"till N\u00e4s, Knut Eriksson",
"Tjurhuvud, Abraham Brodersson",
"Tjurhuvud, Birgitta Abrahamsdotter",
"Toosi, Vilhelmiina Heikintyt\u00e4r",
"Tott, Anna Hansdotter",
"Tott, Axel Pedersen",
"Tott, Erik \u00c5kesson",
"Tott, Hans \u00c5kesson",
"Tott, Ingeborg T\u00f6nnesdotter",
"Tott, Peder Axelsen",
"Tott, Pernilla Pedersdatter",
"Tott, T\u00f6nne Eriksson",
"Tott, \u00c5ke Axelsson",
"Tott, \u00c5ke Klasson",
"Trolle, Birger",
"Trolle, Birger Knutsson",
"Trolle, Kerstin Birgersdotter",
"Trolle, Knut Birgersson",
"Tuhola, Caisa Henrici",
"Tuhola, Henric Henricsson",
"Tuhola, Henric J\u00f6ransson",
"Tuhola, Matts Henricsson",
"Tvesk\u00e6g, Svend",
"T\u00f6yr\u00e4niemi, Anna Mattsdotter",
"Uldsax, Ingeborg Saxesdatter",
"Uldsax, Sakse Pedersen",
"Ulv, Carin Holmgersdotter",
"Ulv, Holmger Karlsson",
"Ulv, Ingeborg Ulfsdotter",
"Ulv, Karl Karlsson",
"Ulv, Karl Philippusson",
"Ulv, Kristina Staffansdotter",
"Ulv, Philippus Ulfsson",
"Ulv, Staffan Ulfsson",
"Ulv, Ulf Karlsson",
"Ulv, Ulf Philippusson",
"Ulv\u00e5sa, Ingeborg Magnusdotter",
"Ulv\u00e5sa, Magnus Gudmarsson",
"Uotila, Erik Henriksson",
"Uotila, Olof Eriksson",
"Vasa, Cristiern Nilsson",
"Vasa, Ebba Eriksdotter",
"Vasa, Erik Karlsson",
"Vasa, Karl Christiernsson",
"Vasa, Nils Kettilsson",
"Vasa, Ramborg Nilsdotter",
"Vendelbo, Cecilia Pedersdatter",
"Vendelbo, Peder",
"Vesto, Anna Ericsdotter",
"Vesto, Maria M\u00e5rtensdotter",
"Vesto, M\u00e5rten Andersson",
"Vihtinen, Esterlunda Henrici",
"Vihtinen, Michel J\u00f6nsson",
"Vilppula, Lisa Ericsdotter",
"Vinstorp, Anna Karlsdotter",
"Vinstorp, Bengt Uddesson",
"Vinstorp, Karl Bengtsson",
"Vinstorp, M\u00e4rta Bengtsdotter",
"Vinstorp, Udd Matsson",
"Vispe, Tyge Jensen",
"von Sachsen, Jutta",
"von Thienen, Beata",
"von Thienen, Johan",
"von Vitzen, Sigrid Tomasdotter",
"von Vitzen, Tomas",
"von \u00d6sterreich, Agnes",
"V\u00e4nni, Heikki Matinpoika",
"Wallenius, Kirstin Michelsdotter",
"West\u00e5, Anna Hansdotter",
"Wirtenberg, Christence Pedersdotter",
"W\u00e4h\u00e4, Eskill",
"Ylinen, Eric Mattsson",
"Ylinen, Henric Olofsson",
"Ylinen, Jacob Johansson",
"Ylinen, Johan Henricsson",
"Ylinen, Maria Mattsdotter",
"Ylinen, Matthias Jacobsson",
"Ylinen, Olof J\u00f6ransson",
"Yrj\u00f6l\u00e4, Bengt J\u00f6ransson",
"Yrj\u00f6l\u00e4, Brita Michelsdotter",
"Yrj\u00f6l\u00e4, J\u00f6ran J\u00f6ransson",
"Yrj\u00f6l\u00e4, Karin Bengtsdotter",
"Yrj\u00f6l\u00e4, Maria Thomasdotter",
"Yrj\u00f6l\u00e4, Thomas Michelsson",
"\u00d6ra, Karl",
"\u00d6ra, N Karlsdotter",
"\u00d6sterberg, Ida Emilia",
"\u00d6sterberg, Johan Isaksson",
"\u00d6sterberg, Johan Fridolf",
"\u00d6sterberg, Matilda Sofia",
"\u00d6yr\u00e4, Caisa Henricsdotter",
"\u00d6yr\u00e4, Eric Olofsson",
"\u00d6yr\u00e4, Gertrud Ericsdotter",
"\u00d6yr\u00e4, Henric Andersson"
]
Dwr.ScriptLoaded('dwr_db_I_name_0.js');
