// This file is generated

F_name_0 = [
"Perhe is\u00e4lle , Aage",
"Perhe is\u00e4lle , Abj\u00f6rn",
", Abraham Abrahamsson ja , Helena Andersdotter muodostama perhe",
", Abraham Johan Abrahahamsson ja , Maria Elisabeth Lovisa Gabrielsdotter muodostama perhe",
", Abram Mortensson ja , Anna Andersdotter muodostama perhe",
", Afonso I ja , Mafalda muodostama perhe",
", Algot Brynolfsson ja , Margareta Pedersdotter muodostama perhe",
", Anders ja , Brita Thomasdotter muodostama perhe",
", Anders Marcusson ja West\u00e5, Anna Hansdotter muodostama perhe",
", Anders Michelsson ja , Greta Johansdotter muodostama perhe",
", Anders Thomasson ja , Christina Jacobsdotter muodostama perhe",
"Perhe is\u00e4lle , Anders Tomasson",
"Perhe is\u00e4lle , Bengt snivil Folkesson",
", Bernhard ja , Judith muodostama perhe",
", Birger brosa ja , Birgitta Haraldsdotter muodostama perhe",
"Perhe is\u00e4lle , Birger Karlsson",
"Perhe is\u00e4lle , Bo",
", B\u00e5rd Guttormsson ja , Ragnfrid Erlingsdatter muodostama perhe",
", Eric I Ejegod ja , Bodil Thrugotsdatter muodostama perhe",
", Eric Sigfridsson ja , Catharina Andersdotter muodostama perhe",
"Perhe is\u00e4lle , Erling",
", Filip ja , Cecilia Knutsdotter muodostama perhe",
", Folke Algotsson ja , Ingrid Svantepolksdotter muodostama perhe",
", Folke den tjocke ja , Ingerid Knudsdatter muodostama perhe",
"Perhe is\u00e4lle , Folke jarl",
"Perhe \u00e4idille , Gunhild",
"Perhe is\u00e4lle , Guttorm",
", Guttorm \u00c5solvsson ja , Sigrid Torkjellsdotter muodostama perhe",
", Hans Sigfridsson ja , Anna Bertilsdotter muodostama perhe",
"Perhe is\u00e4lle , Harald H\u00e5kansson",
", Hendrich Andersson ja , Elin Jacobsdotter muodostama perhe",
"Perhe is\u00e4lle , Henric",
", Henric Ericsson ja , Christina Jacobsdotter muodostama perhe",
", Henric Henricsson ja Herckman, Sara Hansdotter muodostama perhe",
", Henrik ja , Beata Hansdotter muodostama perhe",
", Henrik Mattsson ja , Helena Hermansdotter muodostama perhe",
", Henrik Mattsson ja Anttila, Lisa Pauli muodostama perhe",
", Herman Ericsson ja Boll, Eva Andersdotter muodostama perhe",
", Hindrich ja , Agneta muodostama perhe",
", Hindrich Hindrichsson ja , Sophia Eskilsdotter muodostama perhe",
", H\u00e5kan Magnusson ja Fr\u00f6svik, Birgitta Finvidsdotter muodostama perhe",
"Perhe is\u00e4lle , H\u00e5kon Finnsson",
", H\u00e5kon III Sverresson ja , Inga muodostama perhe",
"Perhe is\u00e4lle , H\u00e5kon V Magnusson den eldre",
", Inge I den \u00e4ldre ja , Helena muodostama perhe",
", Inge II den yngre ja , Ulvhild Haakonsdatter muodostama perhe",
"Perhe is\u00e4lle , Ingevald Estridsson",
"Perhe is\u00e4lle , Israel",
", Jacob Jacobsson ja , Maria Eriksdotter muodostama perhe",
", Jacob Johansson ja , Chirstin Hansdotter muodostama perhe",
", Jacob Thomasson ja , Maria Andersdotter muodostama perhe",
", Jacob Thomasson ja , N muodostama perhe",
", Johan Andersson ja Raukola, Johanna Leenantyt\u00e4r muodostama perhe",
", Johan Ericsson ja , Anna Mattsdotter muodostama perhe",
", Johan Filipsson ja , Ingeborg Svantepolksdotter muodostama perhe",
", Johan Jacobsson ja , Maria M\u00e5rtensdotter muodostama perhe",
", Johan Mathia ja Mikkola, Lisa Mathia muodostama perhe",
", Johan Mattsson ja Halvonoja, Hedvig Albertina Henricsdotter muodostama perhe",
", Johan Nilsson ja , Maria Eliasdotter muodostama perhe",
", Johan Henrik Johansson ja Niittum\u00e4ki, Maria Lovisa Eriksdotter muodostama perhe",
", Juho Vihtori Tuomaanpoika ja Toosi, Vilhelmiina Heikintyt\u00e4r muodostama perhe",
"Perhe is\u00e4lle , J\u00f6ns Nilsson",
", J\u00f6ran ja Perttula, Agnes Mattsdotter muodostama perhe",
", J\u00f6ran Jacobsson ja , Maria Simonsdotter muodostama perhe",
", J\u00f6ran J\u00f6nsson ja Arra, Margeta Ericsdotter muodostama perhe",
", J\u00f6ran J\u00f6ransson ja , Gertrud Eskilsdotter muodostama perhe",
"Perhe is\u00e4lle , J\u00f6ran M\u00e5rtensson",
", J\u00f6ran M\u00e5rtensson ja , Helena Jacobsdotter muodostama perhe",
", Karl Birgersson ja , Gertrud Gertsdotter muodostama perhe",
"Perhe is\u00e4lle , Karl den d\u00f6ve",
", Karl Sunesson ja , Birgitta Haraldsdotter muodostama perhe",
", Karl VII Sverkersson den yngre ja Hvide, Christine Stigsdatter muodostama perhe",
", Knud IV den Hellige ja af Flandern, Edel muodostama perhe",
"Perhe is\u00e4lle , Knut Abj\u00f6rnsson",
", Knut Folkesson ja , Margareta Torgilsdotter muodostama perhe",
", Knut jarl ja N, N muodostama perhe",
"Perhe is\u00e4lle , Knut Magnusson",
", Lage Gustavsson ja , Bothild Bengtsdotter muodostama perhe",
", Laurent ja , Elin H\u00e5kansdotter muodostama perhe",
", Lidinvard Haraldsson ja , Katarina Magnusdotter muodostama perhe",
"Perhe is\u00e4lle , Lydeke",
", Magnus H\u00e5kansson ja , Margareta Lidinvardsdotter muodostama perhe",
", Magnus II Henriksson ja , Birgitta Haraldsdotter muodostama perhe",
"Perhe is\u00e4lle , Magnus Ingevaldsson",
"Perhe is\u00e4lle , Magnus Marinasson",
", Magnus minnesk\u00f6ld Bengtsson ja , Ingrid muodostama perhe",
", Magnus Nilsson ja , Ingrid muodostama perhe",
", Mats Oddsson ja , Ingeborg Knutsdotter muodostama perhe",
"Perhe is\u00e4lle , Matts\u200e",
", Matts ja , Lisa muodostama perhe",
", Matts J\u00f6nsson ja , Margeta muodostama perhe",
", Matts Marci ja Heikkil\u00e4, Sophia Henricsdotter muodostama perhe",
", Michel Cnutsson ja , Sophia muodostama perhe",
", Michel Cnutsson ja Yrj\u00f6l\u00e4, Karin Bengtsdotter muodostama perhe",
", Michel Grelsson ja Karppi, Marja Mattsdotter muodostama perhe",
", Michel Mattsson ja , Carin Johansdotter muodostama perhe",
", Mstislav I ja , Kristina Ingesdotter muodostama perhe",
", M\u00e5rten Henricsson ja , Beata Bertilsdotter muodostama perhe",
", M\u00e5rten Henricsson ja , Maria muodostama perhe",
"Perhe is\u00e4lle , M\u00e5rten J\u00f6ransson",
", M\u00e5rten J\u00f6ransson ja Hampaala, Caisa muodostama perhe",
", N ja , Elin muodostama perhe",
"Perhe is\u00e4lle , Nils",
", Nils ja , Ulvhild Haakonsdatter muodostama perhe",
"Perhe is\u00e4lle , Nils Magnusson",
", Olof ja Garp, Kristina Jacobsdotter muodostama perhe",
", Olof Abelsson ja , Maria Mattsdotter muodostama perhe",
", Peer Hendersson ja , Brita muodostama perhe",
", Peter Ragnvaldsson ja , Birgitta Jonsdotter muodostama perhe",
", Petter J\u00f6ransson ja Huti, Lisa Thomasdotter muodostama perhe",
", Sancho I ja , Aldon\u00e7a muodostama perhe",
", Sigmund Keldorsson ja , Cecilia muodostama perhe",
", Simon Mattsson ja Heikkil\u00e4, Anna Andersdotter muodostama perhe",
", Sixten ja , Ingrid Abj\u00f6rnsdotter muodostama perhe",
", Skule B\u00e5rdsson ja , Ragnhild muodostama perhe",
"Perhe is\u00e4lle , Stenkil",
", Sune Folkesson ja , Helena Sverkersdotter muodostama perhe",
", Svantepolk Knudsen ja , Benedicta Sunesdotter muodostama perhe",
"Perhe is\u00e4lle , Svantopolk",
"Perhe is\u00e4lle , Sven Jonsson",
"Perhe is\u00e4lle , Svend II Estridsen",
", Sverker I den \u00e4ldre ja , Ulvhild Haakonsdatter muodostama perhe",
", Sverker I den \u00e4ldre ja av Polen, Rikissa muodostama perhe",
", Sverker II den yngre ja Hvide, Benedicta Ebbesdotter muodostama perhe",
"Perhe is\u00e4lle , Sverre",
"Perhe is\u00e4lle , Thomas Jacobsson",
"Perhe is\u00e4lle , Thomas Johansson",
", Thomas Michelsson ja , Maria Johansdotter muodostama perhe",
"Perhe is\u00e4lle , Torgil Knutsson",
", Uddorm Petersson ja , N Jonsdotter muodostama perhe",
", Ulf Torgilsen ja , Estrid Svensdatter muodostama perhe",
", Valdemar II sejr ja , Helena Guttormsdotter muodostama perhe",
", Valdemar II sejr ja af Portugal, Bereng\u00e1ria muodostama perhe",
"af Sachsen, Albrecht I ja von \u00d6sterreich, Agnes muodostama perhe",
"Alanen, Gustav Petersson ja Hettunen, Margeta Thomasdotter muodostama perhe",
"Alanen, Peter Thomasson ja M\u00f6hk\u00f6l\u00e4, Lisa Mattsdotter muodostama perhe",
"Alanen, Petter Gustafsson ja Hampaala, Maria J\u00f6ransdotter muodostama perhe",
"Alanen, Thomas Petersson ja Arra, Walborg Henricsdotter muodostama perhe",
"And, Anders ja Finsta, N Israelsdotter muodostama perhe",
"And, Israel Andersson ja , Ramfrid Gustavsdotter muodostama perhe",
"Anttila, Eric Johansson ja Ylinen, Maria Mattsdotter muodostama perhe",
"Anttila, Henrich Johansson ja , Brita Thomasdotter muodostama perhe",
"Anttila, Johan Ericsson ja Semenius, Helena Ericsdotter muodostama perhe",
"Anttila, Johan Henrichsson ja , Maria Mattsdotter muodostama perhe",
"Anttila, Johan Johansson ja Eerola, Anna Henrichsdotter muodostama perhe",
"Anttila, P\u00e5hl Thomasson ja , Beata Jacobsdotter muodostama perhe",
"Anttila, Thomas Johansson ja , Anna Stina Catharinasdotter muodostama perhe",
"Arctopolitanus, Gregorius Thomae ja , Agneta Mattsdotter muodostama perhe",
"Perhe is\u00e4lle Arra, Eric Larsson",
"Arra, Henric J\u00f6ransson ja H\u00f6lli, Brita Sigfridsdotter muodostama perhe",
"Arra, Johan J\u00f6ransson ja , Agnes Augustinusdotter muodostama perhe",
"Arra, Joseph Johansson ja , Susanna J\u00f6ransdotter muodostama perhe",
"Arra, J\u00f6ran Josephsson ja , Agneta J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle Arra, Lars M\u00e5rtensson",
"Aspen\u00e4s, Knut Jonsson ja Bj\u00e4lbo, Katarina Bengtsdotter muodostama perhe",
"av Minsk, Volodar ja av Polen, Rikissa muodostama perhe",
"av Reval, Knud ja , N Svantopolksdotter muodostama perhe",
"Perhe is\u00e4lle Balk, R\u00f6rik Birgersson",
"Ban\u00e9r, Eskil Isaksson ja Gren, Cecilia Haraldsdotter muodostama perhe",
"Ban\u00e9r, Isak Bj\u00f6rnsson ja , Gertrud Andersdotter muodostama perhe",
"Ban\u00e9r, Isak Isaksson ja , M\u00e4rta Siggesdotter muodostama perhe",
"Perhe is\u00e4lle Barun, Knut Erengislesson",
"Berg, Abel Olofsson ja Dickman, Catharina Jobstsdotter muodostama perhe",
"Berg, Erik Johan Abelsson ja Illman, Eva Andersdotter muodostama perhe",
"Berg, Erik Johan Eriksson ja Illander, Maria Nilsdotter muodostama perhe",
"Bese, Johan Stensson ja G\u00e4dda, Katarina Johansdotter muodostama perhe",
"Bese, J\u00f6nis Stensson ja Dj\u00e4ken, Cecilie J\u00f6nissadottir muodostama perhe",
"Perhe is\u00e4lle Bese, Sten",
"Bese, Sten J\u00f6nsson ja Hatt, Kristina Anundsdotter muodostama perhe",
"Beurr\u00e6us, Arvid Claesson ja Horn af \u00c5minne, Christina Arvidsdotter muodostama perhe",
"Bielke, Bengt Thuresson ja Ulv\u00e5sa, Ingeborg Magnusdotter muodostama perhe",
"Bielke, Erik Turesson ja Bese, Gunhild Johansdotter muodostama perhe",
"Perhe is\u00e4lle Bielke, K\u00e4ttil",
"Bielke, Peder Turesson ja Sparre af Ellinge, Katarina Nilsdotter muodostama perhe",
"Bielke, Sten Bengtsson ja Ulv, Carin Holmgersdotter muodostama perhe",
"Bielke, Sten Turesson ja Sparre av Tofta, Margareta Karlsdotter muodostama perhe",
"Bielke, Thure K\u00e4ttilsson ja , Sigrid muodostama perhe",
"Bielke, Thure Thuresson ja Kyrning, Ingegerd Pedersdatter muodostama perhe",
"Bielke, Ture Bengtsson ja Sparre av Vik, Margareta Arvidsdotter muodostama perhe",
"Bielke, Ture Pedersson ja Sture, Sigrid Svantesdotter muodostama perhe",
"Bielke, Ture Stensson ja Krummedige, Margaretha Eriksdatter muodostama perhe",
"Bielke, Ture Stensson ja Tjurhuvud, Birgitta Abrahamsdotter muodostama perhe",
"Birkman, Joachimus Sigfridi ja , Sofia muodostama perhe",
"Birkman, Sigfridus Olai ja , Gertrud Jakobsdotter muodostama perhe",
"Perhe is\u00e4lle Bj\u00e4lbo, Bengt Magnusson",
"Bj\u00e4lbo, Bengt Magnusson ja den Fagra, Sigrid muodostama perhe",
"Bj\u00e4lbo, Magnus Bengtsson ja , Ragnhild muodostama perhe",
"Blomberg, Olof ja , Brita Jakobsdotter muodostama perhe",
"Perhe is\u00e4lle Bl\u00e5tann, Harald",
"Bonde, Erengisle Petersson ja , Bengta muodostama perhe",
"Bonde, Karl Tordsson ja Dyre, Cecilia Bosdotter muodostama perhe",
"Bonde, Karl VIII Knutson ja Bielke, Birgitta Turesdotter muodostama perhe",
"Bonde, Knut Tordsson ja Sparre av Tofta, Margareta Karlsdotter muodostama perhe",
"Bonde, Peter Erengislesson ja , Ramborg Magnusdotter muodostama perhe",
"Bonde, R\u00f6rik Tordsson ja Sparre av Aspn\u00e4s, M\u00e4rta Gislesdotter muodostama perhe",
"Bonde, Tord Petersson ja Balk, Margareta R\u00f6riksdotter muodostama perhe",
"Bonde, Tord Petersson ja Roos af Ervalla, Katarina Ulvsdotter muodostama perhe",
"Bonde, Tord R\u00f6riksson ja Vasa, Ramborg Nilsdotter muodostama perhe",
"Perhe is\u00e4lle Borgare, Henrik",
"Perhe is\u00e4lle Borgare, Michel Henricsson",
"Bosson, Bengt ja , Ragnhild muodostama perhe",
"Bosson, Magnus Bengtsson ja Lejonbj\u00e4lke, Birgitta Knutsdotter muodostama perhe",
"Perhe is\u00e4lle Brock, Eske Jensen",
"Brock, Lave Eskelsen ja Laxmand, Else Pedersdatter muodostama perhe",
"Brun, Anders Andersson ja , Ingeborg Johansdotter muodostama perhe",
"Brun, Anders Andersson ja , Maria Danielsdotter muodostama perhe",
"Brun, Anders Andersson ja , N muodostama perhe",
"Brun, Sigge ja , Birgitta Nilsdotter muodostama perhe",
"Bydelsbach, Albrecht ja Krummedige, Anne Eriksdatter muodostama perhe",
"B\u00fclow, Ficke ja Bydelsbach, Hebbla Albrechtsdatter muodostama perhe",
"Perhe is\u00e4lle B\u00fclow, Johan",
"Perhe is\u00e4lle B\u00e4k, Sven",
"Perhe is\u00e4lle den Gamle, Gorm",
"den Gamle, H\u00e5kon IV H\u00e5konsson ja , Margareta Skulesdotter muodostama perhe",
"den store, Valdemar I ja , Sophia muodostama perhe",
"der B\u00e4r, Albrecht ja , Sophie muodostama perhe",
"Dickman, Jobst Jobstsson ja , Brita muodostama perhe",
"Dickman, Jobst Johansson ja , Anna Henriksdotter muodostama perhe",
"Dickman, Johan Jobstsson ja , Kirstin muodostama perhe",
"Perhe is\u00e4lle Dj\u00e4ken, J\u00f6nis",
"Perhe is\u00e4lle Dj\u00e4kn, Abraham",
"Dj\u00e4kn, Klaus Lydekesson ja Garp, Kristina J\u00f6nsdotter muodostama perhe",
"Dj\u00e4kn, M\u00e5rten Abrahamsson ja Tavast, Ranghild Olofsdotter muodostama perhe",
"Dyre, Bo Tygesen ja , Sigrid Uddormsdotter muodostama perhe",
"Eerola, Henric Henricsson ja , Maria Markusdotter muodostama perhe",
"Eerola, Henric Thomasson ja Heikkil\u00e4, Maria Marcusdotter muodostama perhe",
"Eerola, Thomas Henricsson ja , Walborg Clemetsdotter muodostama perhe",
"Eskola, Erich J\u00f6ransson ja Huuna, Elin Hendrichsdotter muodostama perhe",
"Perhe is\u00e4lle Eskola, Erik Eskilsson",
"Perhe is\u00e4lle Eskola, Eskil Eskilsson",
"Eskola, J\u00f6ran Thomasson ja , Walborg Thomasdotter muodostama perhe",
"Eskola, Lars Ericsson ja , Walborg M\u00e5rtensdotter muodostama perhe",
"Eskola, Thomas Larsson ja , Maisa Ericsdotter muodostama perhe",
"Feirich, M\u00e5rten ja Schartoff, Maria Fransdotter muodostama perhe",
"Finsta, Birger Persson ja Bj\u00e4lbo, Ingeborg Bengtsdotter muodostama perhe",
"Finsta, Peter Israelsson ja Sk\u00e4nkare, N Birgersdotter muodostama perhe",
"Perhe is\u00e4lle Frestadius, Olof Pettersson",
"Frestadius, Petrus Olofsson ja Feirich, Catharina M\u00e5rtensdotter muodostama perhe",
"Frestadius, Petter Petri ja Malmberg, Maria Mattsdotter muodostama perhe",
"Frille, Christer H\u00e5kansson ja , Elin Magnusdotter muodostama perhe",
"Frille, Christiern Frellavsen ja , N muodostama perhe",
"Frille, Christiern Frellavsen ja Altena, Ermegaard Eggartsdotter muodostama perhe",
"Perhe is\u00e4lle Frille, Frellav Hakonsen",
"Perhe is\u00e4lle Frille, Hakon Frellavsen",
"Frille, H\u00e5kan Christersen ja Dj\u00e4kn, N M\u00e5rtensdotter muodostama perhe",
"Perhe is\u00e4lle Frisern af Flandern, Robert",
"Perhe is\u00e4lle Fr\u00f6svik, Finvid Nilsson",
"F\u00e4lt, Alexander Viktor ja \u00d6sterberg, Matilda Sofia muodostama perhe",
"Perhe is\u00e4lle Garp, Anders",
"Garp, Jakob J\u00f6nsson ja , Ragnhild Eriksdotter muodostama perhe",
"Perhe is\u00e4lle Garp, J\u00f6ns Andersson",
"Perhe is\u00e4lle Gille, Harald IV",
"Glad, Carl ja \u00d6sterberg, Ida Emilia muodostama perhe",
"Glad, Jacob Jacobsson ja S\u00f6derstr\u00f6m, Sofia Isacsdotter muodostama perhe",
"Glad, Johannes Joel ja , Ulrika Vilhelmina Abrahamsdotter muodostama perhe",
"Gottleben, Gabriel ja Arctopolitana, Kristina Gregoriusdotter muodostama perhe",
"Gottleben, Valentin ja L\u00fctkens, Catharina muodostama perhe",
"Perhe is\u00e4lle Gren, Ernils Kettilbj\u00f6rnsson",
"Perhe is\u00e4lle Gren, Harald Ernilsson",
"Gren, Harald Stensson ja von Vitzen, Sigrid Tomasdotter muodostama perhe",
"Perhe is\u00e4lle Gren, Kettilbj\u00f6rn Knutsson",
"Gren, Sten Haraldsson ja , Cecilia Nilsdotter muodostama perhe",
"Grubbe, Peder Jensen ja Uldsax, Ingeborg Saxesdatter muodostama perhe",
"Gylden\u00e4r, Conrad ja Rahm, Rinchel muodostama perhe",
"Gylden\u00e4r, Johan Conradsson ja Horn af Kanckas, Elin Arvidsdotter muodostama perhe",
"Gyllenstierna, Erik Eriksson den \u00e4ldre ja Bonde, Kristina Karlsdotter muodostama perhe",
"Gyllenstierna, Nils Eriksson ja Ban\u00e9r, Sigrid Eskilsdotter muodostama perhe",
"Perhe is\u00e4lle Gyllenstierna af Svaneholm, Erik Nielsen",
"Gyllenstierna af Svaneholm, Erik Nilsen ja Vendelbo, Cecilia Pedersdatter muodostama perhe",
"Perhe is\u00e4lle Gyllenstierna af Svaneholm, Niels Eriksen",
"Gyllenstierna af Svaneholm, Niels Eriksen den h\u00f6ge ja af Aagaard, Christina muodostama perhe",
"G\u00e4dda, Erengisle Karlsson ja K\u00f6rning, Bengta Simonsdotter muodostama perhe",
"G\u00e4dda, Johan Nilsson ja K\u00f6nigsmark, Katarina Bengtsdotter muodostama perhe",
"Perhe is\u00e4lle G\u00e4dda, Jon",
"G\u00e4dda, Karl Nilsson ja \u00d6ra, N Karlsdotter muodostama perhe",
"G\u00e4dda, Nils Jonsson ja Hammersta, Kristina Magnusdotter muodostama perhe",
"Perhe is\u00e4lle Haapaniemi, M\u00e5rten Henricsson",
"Halvonoja, Henric J\u00f6ransson ja M\u00f6rt, Walborg Mattsdotter muodostama perhe",
"Hampaala, Jacob J\u00f6ransson ja , Anna Mattsdotter muodostama perhe",
"Hampaala, J\u00f6ran Jacobsson ja Kauppila, Walborg Mattsdotter muodostama perhe",
"Harkki, Jacob Pettersson ja Vesto, Maria M\u00e5rtensdotter muodostama perhe",
"Harola, Jacob J\u00f6ransson ja , Walborg Johansdotter muodostama perhe",
"Harola, J\u00f6ran Eskelsson ja , Maria Thomasdotter muodostama perhe",
"Perhe is\u00e4lle Hatt, Anund",
"Heikkil\u00e4, Anders Christersson ja , Maria J\u00f6ransdotter muodostama perhe",
"Heikkil\u00e4, Anders Henricsson ja , Brita Simonsdotter muodostama perhe",
"Heikkil\u00e4, Brusius Mattsson ja , Anna muodostama perhe",
"Heikkil\u00e4, Brusius Mattsson ja , Malin muodostama perhe",
"Heikkil\u00e4, Carl Pehrsson ja Laurila, Christina Paulsdotter muodostama perhe",
"Heikkil\u00e4, Christer Sigfridsson ja , Margetha Berendsdotter muodostama perhe",
"Heikkil\u00e4, Cnud Ericsson ja , Anna Cnudsdotter muodostama perhe",
"Heikkil\u00e4, Gabriel Michelsson ja Birkman, Elisabeth Joachimsdotter muodostama perhe",
"Heikkil\u00e4, Gabriel Michelsson ja Herckman, Hebla Henricsdotter muodostama perhe",
"Heikkil\u00e4, Hendrich Hendersson ja , Walborg Hendersdotter muodostama perhe",
"Heikkil\u00e4, Henric Mathiae ja Talvia, Sophia Georgii muodostama perhe",
"Perhe is\u00e4lle Heikkil\u00e4, Henric M\u00e5rtensson",
"Heikkil\u00e4, Henric Thomasson ja , Anna Larsdotter muodostama perhe",
"Heikkil\u00e4, Henric Thomasson ja , Walborg Michelsdotter muodostama perhe",
"Perhe is\u00e4lle Heikkil\u00e4, Henrik Olofsson",
"Heikkil\u00e4, Marcus Henricsson ja Yrj\u00f6l\u00e4, Maria Thomasdotter muodostama perhe",
"Heikkil\u00e4, Matts Mattsson ja Wallenius, Kirstin Michelsdotter muodostama perhe",
"Heikkil\u00e4, Matts M\u00e5rtensson ja , Gertrud Larsdotter muodostama perhe",
"Heikkil\u00e4, Michel Gabrielsson ja Herckman, Maria Henricsdotter muodostama perhe",
"Heikkil\u00e4, Michel Gabrielsson ja Leistenia, Maria Jacobsdotter muodostama perhe",
"Heikkil\u00e4, Michel Mattsson ja , Dorothea Larsdotter muodostama perhe",
"Perhe is\u00e4lle Heikkil\u00e4, M\u00e5rten Henricsson",
"Perhe is\u00e4lle Heikkil\u00e4, Olof Henriksson",
"Heikkil\u00e4, Simon Simonis ja Perttula, Maria Johanis muodostama perhe",
"Heikkil\u00e4, Thomas Brusiusson ja , Anna muodostama perhe",
"Heikkil\u00e4, Thomas Henricsson ja , Maria muodostama perhe",
"Herckman, Gustaf Henricsson ja , Maria Johansdotter muodostama perhe",
"Herckman, Hans Gustafsson ja Heikkil\u00e4, Maria Michelsdotter muodostama perhe",
"Hettunen, Eric Henricsson ja , Magdalena J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle Hettunen, Eric Larsson",
"Hettunen, Henric Ericsson ja , Margareta M\u00e5rtensdotter muodostama perhe",
"Perhe is\u00e4lle Hettunen, Lars Olsson",
"Perhe is\u00e4lle Hettunen, Olef Staffansson",
"Hettunen, Thomas Cnutsson ja , Karin muodostama perhe",
"Hiiri, Bertil Nilsson ja , Dorde J\u00f6ransdotter muodostama perhe",
"Hiiri, Bertil Nilsson ja , Karin Henrichsdotter muodostama perhe",
"Hiiri, Matts Bertilsson ja , Helga J\u00f6nsdotter muodostama perhe",
"Hiiri, Matts Bertilsson ja , Walborg muodostama perhe",
"Perhe is\u00e4lle Hiiri, Nils Larsson",
"Hinkka, Nils H\u00e5kansson ja , Anna Cnudsdotter muodostama perhe",
"Hinkka, Olof Nilsson ja , Walborg muodostama perhe",
"Hirvenoja, Johan Gustaf Thomasson ja , Hedvig Serafia Henriksdotter muodostama perhe",
"Hjorthuvud, Gudmar Magnusson ja , Margareta Ulfsdotter muodostama perhe",
"Hogenskild, Clemet Bengtsson ja Tott, Anna Hansdotter muodostama perhe",
"Horn af Kanckas, Arvid Henriksson ja Stiernkors, Ingeborg Ivarsdotter muodostama perhe",
"Horn af \u00c5minne, Arvid Mauritzson ja Gylden\u00e4r, Ingeborg Johansdotter muodostama perhe",
"Horn af \u00c5minne, Henrik Olofsson ja Dj\u00e4kn, N Klasdotter muodostama perhe",
"Horn af \u00c5minne, Klas Henriksson ja , Kristina muodostama perhe",
"Horn af \u00c5minne, Klas Henriksson ja Frille, Kristina Christersdotter muodostama perhe",
"Horn af \u00c5minne, Klas Kristersson ja Krumme, Kerstin Jakobsdotter muodostama perhe",
"Horn af \u00c5minne, Krister Klasson ja Bielke, Catharina Turesdotter muodostama perhe",
"Horn af \u00c5minne, Krister Klasson ja Sparre af Rossvik, Ingeborg Siggesdotter muodostama perhe",
"Horn af \u00c5minne, Mauritz Kristersson ja Horn af Kanckas, Ingeborg Arvidsdotter muodostama perhe",
"Horn af \u00c5minne, Olof Mattsson ja , Katarina muodostama perhe",
"Horn till Kanckas, Henrik Klasson ja St\u00e5larm, Elin Arvidsdotter muodostama perhe",
"Hultti, Olof Sigfridsson ja , Karin Larsdotter muodostama perhe",
"Perhe is\u00e4lle Hultti, Sigfred Simonsson",
"Huti, Lars Sigfridsson ja , Valborg Sigfridsdotter muodostama perhe",
"Huti, Sigfrid Michelsson ja , Margeta muodostama perhe",
"Huti, Thomas Larsson ja , Sophia M\u00e5rtensdotter muodostama perhe",
"Huuna, Henric Thomasson ja , Brita Klemetsdotter muodostama perhe",
"Huuna, Henrich J\u00f6ransson ja , Agnes Olofsdotter muodostama perhe",
"Huuna, J\u00f6ran Ericsson ja , Gertrud P\u00e5hlsdotter muodostama perhe",
"Huuna, Thomas Henrichsson ja , Walborg muodostama perhe",
"Perhe is\u00e4lle Hvide, Ebbe Skjalmsen",
"Perhe is\u00e4lle Hvide, Ebbe Sunesen",
"Perhe is\u00e4lle Hvide, Skjalm",
"Hvide, Stig ja , Margareta Knudsdatter muodostama perhe",
"Perhe is\u00e4lle Hvide, Sune Ebbesen",
"Perhe is\u00e4lle H\u00e4rtsi\u00e4, Marcus",
"Perhe is\u00e4lle H\u00e4rtsi\u00e4, Morthen Marcusson",
"H\u00f6gberg, Eric Henricsson ja Frestadius, Lena Pehrsdotter muodostama perhe",
"H\u00f6lli, Clemet Mattsson ja , Maisa muodostama perhe",
"Perhe is\u00e4lle H\u00f6lli, Henrik Henriksson",
"H\u00f6lli, J\u00f6ran J\u00f6ransson ja , Brita Mattsdotter muodostama perhe",
"H\u00f6lli, J\u00f6ran J\u00f6ransson ja Hakim\u00e4ki, Maria Henricsdotter muodostama perhe",
"H\u00f6lli, J\u00f6ran Mattsson ja , Elin Mattsdotter muodostama perhe",
"Perhe is\u00e4lle H\u00f6lli, Lars Henriksson",
"H\u00f6lli, Matts J\u00f6ransson ja Heikkil\u00e4, Ingeborg Carlsdotter muodostama perhe",
"H\u00f6lli, Matts Larsson ja , Sunniva Thomasdotter muodostama perhe",
"H\u00f6lli, Matts Mattsson ja \u00d6yr\u00e4, Caisa Henricsdotter muodostama perhe",
"H\u00f6lli, Sigfrid Clemetsson ja , Maria Mattsdotter muodostama perhe",
"Illander, Nicolaus Nielsson ja , Anna Hansdotter muodostama perhe",
"Illander, Nils ja , Carin Hansdotter muodostama perhe",
"Illman, Anders ja , Anna Henriksdotter muodostama perhe",
"Irjala, Johan Thomasson ja , Agnes muodostama perhe",
"Irjala, Johan Thomasson ja , Maria Johansdotter muodostama perhe",
"Irjala, Thomas J\u00f6ransson ja , Helga J\u00f6nsdotter muodostama perhe",
"Irjala, Thomas Pehrsson ja , Maria muodostama perhe",
"Perhe is\u00e4lle Iso-Kaulo, Marcus Nilsson",
"Perhe is\u00e4lle Iso-Kaulo, P\u00e5hl Marcusson",
"Iso-Kaulo, Simon P\u00e5hlsson ja , Margareta Ericsdotter muodostama perhe",
"Jaakkola, Michael Michaelis ja Mikkola, Beata Jacobi muodostama perhe",
"Jokela, Edvard Lauri ja Glad, Ester Sofia muodostama perhe",
"Jokela, Juha Kustaa Kustaanpoika ja Ohralahti, Eeva Loviisa Kaarlentyt\u00e4r muodostama perhe",
"Jokela, Leo Ensio ja Ahokas, Taimi Sivi\u00e4 muodostama perhe",
"Jokela, Leo Ensio ja Romu, Anna Lyyli muodostama perhe",
"Joppi, Johan Henricsson ja Raukola, Lena Simonsdotter muodostama perhe",
"Jussila, Eric Simonsson ja Nyman, Maria Andersdotter muodostama perhe",
"Jussila, Henric J\u00f6ransson ja Hettunen, Beata Ericsdotter muodostama perhe",
"Jussila, J\u00f6ran Thomasson ja , Helga Thomasdotter muodostama perhe",
"Jussila, Simon Mattsson ja , Brita Jakobsdotter muodostama perhe",
"Juusela, Eric Thomasson ja Hampaala, Sofia Jacobsdotter muodostama perhe",
"Juva, Erich Eskillsson ja , Brita Olofsdotter muodostama perhe",
"Juva, Erich Eskillsson ja , Brita Peersdotter muodostama perhe",
"Perhe is\u00e4lle Juva, Eskill",
"Juva, Peer Staffansson ja Irjala, Karin Johansdotter muodostama perhe",
"Juva, Staffan Ericsson ja , Agnes muodostama perhe",
"Karo, J\u00f6ran Nilsson ja , Anna Henrichsdotter muodostama perhe",
"Karo, Nisius Larsson ja , Margareta Mattsdotter muodostama perhe",
"Karo, Peer J\u00f6ransson ja Mattila, Sofia Mattsdotter muodostama perhe",
"Karppi, Eskell P\u00e5fwellsson ja , Anna Erichsdotter muodostama perhe",
"Perhe is\u00e4lle Karppi, Henric Larsson",
"Perhe is\u00e4lle Karppi, Lars Henricsson",
"Karppi, Matts Eskelsson ja , Sophia Josephsdotter muodostama perhe",
"Karppi, Matts Mattsson ja , Lisa Simonsdotter muodostama perhe",
"Karppi, Matts Michelsson ja Harola, Maria Jacobsdotter muodostama perhe",
"Karppi, P\u00e5fwell Larsson tai Jacobsson ja , Margetha Nisiusdotter muodostama perhe",
"Kauko, Anders Marcusson ja , Lisa Henricsdotter muodostama perhe",
"Kauko, Bertil Marcusson ja , Brita muodostama perhe",
"Perhe is\u00e4lle Kauko, Eric Mattsson",
"Kauko, Marcus Bertilssson ja Outinen, Lisa Simonsdotter muodostama perhe",
"Kauko, Marcus Ericsson ja , Gertrud J\u00f6nsdotter muodostama perhe",
"Perhe is\u00e4lle Kauko, Matts Pehrsson",
"Perhe is\u00e4lle Kaulo, Nils J\u00f6nsson",
"Perhe is\u00e4lle Kauppila, Jacob Olsson",
"Perhe is\u00e4lle Kauppila, Lasse Larsson",
"Perhe is\u00e4lle Kauppila, Lasse Persson",
"Kauppila, Matts Simonsson ja , Brita muodostama perhe",
"Perhe is\u00e4lle Kauppila, Olof Larsson",
"Kauppila, Simon Jacobsson ja , Brita muodostama perhe",
"Keskinen, Heikki Juhonpoika ja Lindroos, Kustaava Matilda Juhantyt\u00e4r muodostama perhe",
"Keskinen, Martti Mikael ja Jokela, Rauha Signe muodostama perhe",
"Kiesinen, Anders Andersson ja , Birith muodostama perhe",
"Perhe is\u00e4lle Kiesinen, Anders Jacobsson",
"Kiesinen, Eric Henricsson ja , Walborg Simonsdotter muodostama perhe",
"Kiesinen, Henrich J\u00f6ransson ja , Brita Larsdotter muodostama perhe",
"Kiesinen, J\u00f6ran Andersson ja , Margeta muodostama perhe",
"Kiesinen, J\u00f6ran Andersson ja , N muodostama perhe",
"Kinnari, Eric Henricsson ja , Britha J\u00f6ransdotter muodostama perhe",
"Kinnari, Eric Henricsson ja , Caisa muodostama perhe",
"Kinnari, Eric Henricsson ja , Maria Sigfridsdotter muodostama perhe",
"Kinnari, Eric Henricsson ja , Walborg muodostama perhe",
"Kinnari, Eric Henricsson ja Vesto, Anna Ericsdotter muodostama perhe",
"Kinnari, Henric Ericsson ja , Walborg Mattsdotter muodostama perhe",
"Kinnari, Hindrich Hindrichsson ja , Margareta muodostama perhe",
"Kirves, Olof den \u00e4ldre ja Stiernkors, Marta Nilsdotter muodostama perhe",
"Klemola, J\u00f6ran Olai ja , Maria Jacobsdotter muodostama perhe",
"Klemola, Olof Sigfridsson ja , Caisa Peersdotter muodostama perhe",
"Klemola, Sigfrid Escilsson ja , Brita muodostama perhe",
"Kottila, Henric Mattsson ja , Agnis Hendricsdotter muodostama perhe",
"Kottila, J\u00f6ran Hendrichsson ja , Ingeborg muodostama perhe",
"Kottila, Matts J\u00f6ransson ja Juusela, Maria Ericsdotter muodostama perhe",
"Kratz, Marcus Johanis ja , Lisa Georgii muodostama perhe",
"Krognos, Axel Kjeldsen ja Puke, Cathrine Eriksdatter muodostama perhe",
"Krumme, Jakob Nilsson ja Hogenskild, Anna Clemetsdotter muodostama perhe",
"Perhe is\u00e4lle Krumme, Nils",
"Perhe is\u00e4lle Krumme, Nils Nilsson",
"Perhe is\u00e4lle Krumme, Nils Svensson",
"Krummedige, Erik Segebodsen ja von Thienen, Beata muodostama perhe",
"Krummedige, Segebod ja Skram, C\u00e6cilie Pedersdatter muodostama perhe",
"Kurki, Jeppe ja Dj\u00e4kn, Karin Klasdotter muodostama perhe",
"Kurki, J\u00f6ns Knutsson ja Tott, Ingeborg T\u00f6nnesdotter muodostama perhe",
"Kurki, Klaus Jeppesson ja Stenbock, Elin J\u00f6nsdotter muodostama perhe",
"Perhe is\u00e4lle Kurvola, Henric Johansson",
"Perhe is\u00e4lle Kurvola, Johan Michelsson",
"Perhe is\u00e4lle Kurvola, Johan Olofsson",
"Perhe is\u00e4lle Kurvola, Michel Hendrichsson",
"Kurvola, Michel Johansson ja Hultti, Gertrud Ollsdotter muodostama perhe",
"Kyrning, Peder ja , Karin Bj\u00f6rnsdotter muodostama perhe",
"K\u00e4r\u00e4v\u00e4, Eric Thomae ja Harkki, Maria Jacobi muodostama perhe",
"K\u00e4r\u00e4v\u00e4, Henric Thomasson ja , Margareta Larsdotter muodostama perhe",
"K\u00e4r\u00e4v\u00e4, Thomas Ericsson ja \u00d6yr\u00e4, Gertrud Ericsdotter muodostama perhe",
"K\u00e4r\u00e4v\u00e4, Thomas Henricsson ja Lind, Christina Erichsdotter muodostama perhe",
"K\u00f6nigsmark, Bengt Henningsson ja Bonde, M\u00e4rta Tordsdotter muodostama perhe",
"Perhe is\u00e4lle K\u00f6nigsmark, Henning Herbrechtsson",
"Perhe is\u00e4lle K\u00f6nigsmark, Herbrecht",
"K\u00f6rning, Simon Pedersson ja Bydelsbach, Beate Albrechtsdatter muodostama perhe",
"Laatu, Hendrich Michelsson ja Hinkka, Walborg Olofsdotter muodostama perhe",
"Laatu, Henric M\u00e5rtensson ja Liukko, Anna Thomasdotter muodostama perhe",
"Laatu, Henric M\u00e5rtensson ja Vilppula, Lisa Ericsdotter muodostama perhe",
"Laatu, M\u00e5rten Michelsson ja , Margareta Sigfridsdotter muodostama perhe",
"Lagab\u00f8ter, Magnus VI H\u00e5konsson ja av Danmark, Ingeborg Eriksdatter muodostama perhe",
"Laurila, Anders Andersson ja , Brita Mattsdotter muodostama perhe",
"Laurila, Clemet Mattsson ja , Margeta Lukasdotter muodostama perhe",
"Laurila, Eric Henricsson ja Hinkka, Maria Hendrichsdotter muodostama perhe",
"Laurila, Hendric Ersson ja Tuhola, Caisa Henrici muodostama perhe",
"Laurila, Henric Andersson ja , Anna muodostama perhe",
"Laurila, Henric Andersson ja , Elin J\u00f6nsdotter muodostama perhe",
"Laurila, Henric J\u00f6ransson ja , Brita muodostama perhe",
"Laurila, Henric Pehrsson ja , Carin Mattsdotter muodostama perhe",
"Perhe is\u00e4lle Laurila, Jacob Ersson",
"Perhe is\u00e4lle Laurila, J\u00f6ran Thomasson",
"Perhe is\u00e4lle Laurila, Knut",
"Laurila, Lars Nilsson ja , Christina muodostama perhe",
"Laurila, Marcus Henrici ja Klemola, Anna Georgii muodostama perhe",
"Laurila, Matts Gustafsson ja Eskola, Brita Ericsdotter muodostama perhe",
"Laurila, Matts Jacobsson ja , Carin muodostama perhe",
"Laurila, Michel Henricsson ja Sepp\u00e4l\u00e4, Kaisa Isacsdotter muodostama perhe",
"Laurila, Paul Henrichsson ja , Walborg muodostama perhe",
"Perhe is\u00e4lle Laurila, Per Cnutsson",
"Laurila, Per Larsson ja , Ursula Mattsdotter muodostama perhe",
"Laurila, Per Persson ja Heikkil\u00e4, Margareta Cnudsdotter muodostama perhe",
"Laurila, Thomas Henricsson ja , Walborg Mattsdotter muodostama perhe",
"Lavard, Knut ja av Kiev, Ingeborg muodostama perhe",
"Perhe is\u00e4lle Laxmand, Peder",
"Leijonhufvud, Abraham Kristiernsson ja Natt och Dag, Birgitta M\u00e5nsdotter muodostama perhe",
"Leijonhufvud, Erik Abrahamsson ja Vasa, Ebba Eriksdotter muodostama perhe",
"Perhe is\u00e4lle Leijonhufvud, Greger",
"Perhe is\u00e4lle Leijonhufvud, Kristiern",
"Leijonhufvud, Kristiern Gregersson ja till Grevsj\u00f6, M\u00e4rta Pedersdotter muodostama perhe",
"Leistenius, Jacobus Olai ja Gottleben, Margareta Gabrielsdotter muodostama perhe",
"Leistenius, Olof Johannis ja , Anna M\u00e5rtensdotter muodostama perhe",
"Lejonbj\u00e4lke, Knut Matsson ja Ulv, Ingeborg Ulfsdotter muodostama perhe",
"Lind, Erich ja Horn af \u00c5minne, Christina Arvidsdotter muodostama perhe",
"Lindroos, Juha Henrik Juhanpoika ja Hirvenoja, Susanna Juhontyt\u00e4r muodostama perhe",
"Lindstr\u00f6m, Anders Johansson ja Berg, Eva Stina muodostama perhe",
"Lindstr\u00f6m, Johan Thomasson ja , Maria Johansdotter muodostama perhe",
"Lintula, Jacob Simonsson ja T\u00f6yr\u00e4niemi, Anna Mattsdotter muodostama perhe",
"Lintula, J\u00f6ran Simonsson ja , Lisa Samuelsdotter muodostama perhe",
"Lintula, J\u00f6ran Simonsson ja , Sofia Thomasdotter muodostama perhe",
"Lintula, J\u00f6ran Simonsson ja Sipil\u00e4, Margareta Henricsdotter muodostama perhe",
"Lintula, Simon Thuresson ja Hinkkala, Maria J\u00f6ransdotter muodostama perhe",
"Liukko, J\u00f6ran Mathiae ja Kinnari, Maria Erici muodostama perhe",
"Liukko, Matts Thomasson ja Mutonen, Margeta Georgii muodostama perhe",
"Liukko, Thomas Henricsson ja , Anna Henricsdotter muodostama perhe",
"Liukko, Thomas Henricsson ja , Juliana Bertilsdotter muodostama perhe",
"Liukko, Thomas Henricsson ja , Maria Matthiae muodostama perhe",
"Liukko, Thomas Henricsson ja F\u00e5ck, Walborg Georgii muodostama perhe",
"Liukko, Thomas Mattsson ja , Anna muodostama perhe",
"Liukko, Thomas Mattsson ja , Lastika Nilsdotter muodostama perhe",
"Luikko, Anders ja , Maisa muodostama perhe",
"Luikko, Anders Thomasson ja Seiv\u00e4s, Lisa M\u00e5rtensdotter muodostama perhe",
"Luikko, Thomas Andersson ja , Brita muodostama perhe",
"Malmberg, Matts Mattsson ja , Maria Johannis muodostama perhe",
"Marttila, Henric Mattsson ja , Walborg Philipsdotter muodostama perhe",
"Marttila, Matts Erichsson ja , Walborg Larsdotter muodostama perhe",
"Marttila, Matts Henriksson ja Kiesinen, Brita Ericsdotter muodostama perhe",
"Mattila, Georgius Laurentii ja , Lisa M\u00e5rtensdotter muodostama perhe",
"Mattila, Georgius Laurentii ja , Maria J\u00f6ransdotter muodostama perhe",
"Mattila, Johan Mattsson ja , Anna Johansdotter muodostama perhe",
"Mattila, Matts Michelsson ja , Agneta Thomasdotter muodostama perhe",
"Maunu, Jacob Eskilsson ja , Lisa Simonsdotter muodostama perhe",
"Mets\u00e4-Heikkil\u00e4, Gustaf Mattsson ja Raukola, Johanna Leenantyt\u00e4r muodostama perhe",
"Mets\u00e4-Heikkil\u00e4, Matts Simonis ja Vihtinen, Esterlunda Henrici muodostama perhe",
"Mikkola, Abraham Mathiae ja Sorri, Maria Ericsdotter muodostama perhe",
"Mikkola, Clemet Samuelsson ja , Caisa Hendricsdotter muodostama perhe",
"Mikkola, Henric Olofsson ja , Anna muodostama perhe",
"Mikkola, Matts Clemetsson ja Tiitola, Lisa Hendricsson muodostama perhe",
"Perhe is\u00e4lle Mikkola, Olof Michelsson",
"Mikkola, Samuel Mattsson ja , Ingeborg Mattsdotter muodostama perhe",
"Moltke, Evert Johansen ja R\u00f8nnow, Beate muodostama perhe",
"Perhe is\u00e4lle Moltke, Henneke Johan Evertsen",
"Moltke, Johan ja , Katarina muodostama perhe",
"Mukkula, Henric J\u00f6ransson ja , Elin muodostama perhe",
"Mulli, Anders Nilsson ja , Margareta Pehrsdotter muodostama perhe",
"Mulli, Henric Andersson ja , Kirstin Henricsdotter muodostama perhe",
"Perhe is\u00e4lle Mulli, Nils Nilsson",
"Mutonen, J\u00f6ran Mattsson ja Mattila, Margeta J\u00f6ransdotter muodostama perhe",
"M\u00e4llinoja, Bertil Eskilsson ja M\u00e4llinoja, Agnis Ericsdotter muodostama perhe",
"M\u00e4llinoja, Erich Jacobsson ja , Kirstin muodostama perhe",
"M\u00e4llinoja, Sigfrid Bertilsson ja , Margareta Johansdotter muodostama perhe",
"M\u00f6hk\u00f6l\u00e4, Clemet Augustsson ja , Kirstin muodostama perhe",
"M\u00f6hk\u00f6l\u00e4, Henric Simonsson ja Anttila, Elisabeth Jacobsdotter muodostama perhe",
"M\u00f6hk\u00f6l\u00e4, Matts Michelsson ja Laurila, Anna Mattsdotter muodostama perhe",
"M\u00f6hk\u00f6l\u00e4, Matts Peersson ja Hampaala, Lisa M\u00e5rtensdotter muodostama perhe",
"M\u00f6hk\u00f6l\u00e4, Michel Mattsson ja Eerola, Beata Henricsdotter muodostama perhe",
"M\u00f6hk\u00f6l\u00e4, Peer Peersson ja , Anna muodostama perhe",
"M\u00f6hk\u00f6l\u00e4, Petter Clemetsson ja , Euphemia muodostama perhe",
"M\u00f6hk\u00f6l\u00e4, Sigfrid Clemetsson ja , Maria Mattsdotter muodostama perhe",
"M\u00f6hk\u00f6l\u00e4, Simon Sigfridsson ja , Anna Mattsdotter muodostama perhe",
"M\u00f6rt, Matts Mattsson ja Marttila, Maria Mattsdotter muodostama perhe",
"Natt och Dag, Bengt Stensson ja , Kristina Magnusdotter muodostama perhe",
"Perhe is\u00e4lle Natt och Dag, Bo Bosson",
"Natt och Dag, Bo Nilsson ja Aspen\u00e4s, Cecilia Knutsdotter muodostama perhe",
"Natt och Dag, Bo Stensson ja Sture, Katarina Svensdotter muodostama perhe",
"Natt och Dag, Magnus Bengtsson ja B\u00fclow, Ermeg\u00e5rd Fickesdotter muodostama perhe",
"Natt och Dag, Magnus Bengtsson ja Plata, M\u00e4rta Klausdotter muodostama perhe",
"Perhe is\u00e4lle Natt och Dag, Nils Sigridsson",
"Natt och Dag, Sten Bosson ja , Ingeborg Karlsdotter muodostama perhe",
"Perhe is\u00e4lle Neulaniemi, Henrik",
"Niittum\u00e4ki, Erik Eriksson ja , Helena Mattsdotter muodostama perhe",
"Nikkil\u00e4, Johan Mattsson ja , Sofia Mattsdotter muodostama perhe",
"Nikula, Bertil Fransson ja , Margareta muodostama perhe",
"Nikula, Frans Mattsson ja , Margareta muodostama perhe",
"Nikula, Matts Bertilsson ja , Anna muodostama perhe",
"Nikula, Matts Michelsson ja , Gertrud Larsdotter muodostama perhe",
"Nikula, Thomas Mattsson ja , Sophia Sigfridsdotter muodostama perhe",
"Nyman, Anders ja , Caisa Johansdotter muodostama perhe",
"Ohralahti, Kaarle Antinpoika ja Kinnari, Kreeta Kaisa Yrj\u00e4n\u00e4ntyt\u00e4r muodostama perhe",
"Orre, J\u00f6ran ja , Maria Michelsdotter muodostama perhe",
"Outinen, Simon Mattsson ja , Brita Sigfridsdotter muodostama perhe",
"Pajunen, Hendrich Georgi ja Maunu, Lisa Jacobi muodostama perhe",
"Pajunen, J\u00f6ran Jacobsson ja , Maria Hendrichsdotter muodostama perhe",
"Pajunen, Staffan J\u00f6ransson ja , Maria Andersdotter muodostama perhe",
"Peissu, Georgius Mattsson ja Irjala, Maria J\u00f6ransdotter muodostama perhe",
"Peissu, Henric Olofsson ja , Margareta muodostama perhe",
"Peissu, Henric Olofsson ja , Maria Danielsdotter muodostama perhe",
"Peissu, Matts Henricsson ja Brun, Anna Andersdotter muodostama perhe",
"Peissu, Matts M\u00e5rtensson ja , Sofia J\u00f6ransdotter muodostama perhe",
"Peissu, Matts M\u00e5rtensson ja , Walborg muodostama perhe",
"Peissu, M\u00e5rten Thomasson ja , Margareta Larsdotter muodostama perhe",
"Peissu, Olof Mattsson ja , Margareta Grelsdotter muodostama perhe",
"Pekka, Anders Eskelsson ja , Anna Thomasdotter muodostama perhe",
"Pekka, Eskel Mattsson ja , Kirstin J\u00f6ransdotter muodostama perhe",
"Pekka, Johan Andersson ja Pajunen, Margeta Jacobsdotter muodostama perhe",
"Pekka, Thomas Georgii ja Klemola, Elisabeth Marcusdotter muodostama perhe",
"Pekka, Thomas Thomae ja Alanen, Anna Petri muodostama perhe",
"Penttil\u00e4, Henric J\u00f6ransson ja Jussila, Sofia Henricsdotter muodostama perhe",
"Penttil\u00e4, J\u00f6ran Thomasson ja , Gertrud Thomasdotter muodostama perhe",
"Penttil\u00e4, Olof Olofsson ja , Valborg Olofsdotter muodostama perhe",
"Penttil\u00e4, Thomas Olofsson ja , Margareta Marcusdotter muodostama perhe",
"Perttula, Anders J\u00f6ransson ja , Sophia Thomasdotter muodostama perhe",
"Perttula, Bertil Ericsson ja , Brita muodostama perhe",
"Perttula, Bertil Ericsson ja , Walborg Sigfridsdotter muodostama perhe",
"Perttula, Erich Simonsson ja , Euphemia muodostama perhe",
"Perttula, Erich Simonsson ja , Johanna Sigfridsdotter muodostama perhe",
"Perttula, Johan Andersson ja Nikkil\u00e4, Anna Johannis muodostama perhe",
"Perttula, Matts Bertillsson ja , Margetha muodostama perhe",
"Perhe is\u00e4lle Perttula, M\u00e5rten Larsson",
"Perhe is\u00e4lle Perttula, Simon M\u00e5rtensson",
"Plata, Claus ja , Cecilia Nilsdotter muodostama perhe",
"Plovpenning, Erik IV ja von Sachsen, Jutta muodostama perhe",
"Perhe is\u00e4lle Puke, Erik Kettilsson",
"Perhe is\u00e4lle Puke, Kettil Ragvaldsson",
"Perhe is\u00e4lle Puke, Ragnvald",
"Punala, Anders Andersson ja Sorri, Maria Ericsdotter muodostama perhe",
"Punala, Anders Ericsson ja Monnila, Caisa Pehrsdotter muodostama perhe",
"Perhe is\u00e4lle P\u00e4ilahti, Jacob Nilsson",
"P\u00e4ilahti, J\u00f6ran Jacobsson ja , Sunniva Larsdotter muodostama perhe",
"Perhe is\u00e4lle P\u00f6yh\u00f6, Olof Henricsson",
"Rasila, Cnut Rasmusson ja , Brita J\u00f6ransdotter muodostama perhe",
"Rasila, Eric Sigfridsson ja , Ingeborg muodostama perhe",
"Rasila, Sigfrid Cnutsson ja , Brita J\u00f6ransdotter muodostama perhe",
"Raud, Hafthor Jonsson ja , Agnes H\u00e5konsdatter muodostama perhe",
"Raud, Jon Hafthorsson ja , Birgitta Knutsdotter muodostama perhe",
"Perhe is\u00e4lle Raud, Jon Ivarsson",
"Raukola, Henric Mattsson ja Rossi, Beata Mattsdotter muodostama perhe",
"Perhe \u00e4idille Raukola, Lena Simonsdotter",
"Raukola, Matts Henriksson ja , Maria J\u00f6ransdotter muodostama perhe",
"Raukola, Simon Henrici ja Peissu, Lisa Georgii muodostama perhe",
"Raumensis, Michael Michaelis ja , Gertrudh Erichsdotter muodostama perhe",
"Revelsta, Nils Jonsson ja , N Magnusdotter muodostama perhe",
"Perhe is\u00e4lle Riippa, Clemet Nilsson",
"Riippa, Eric Nilsson ja , Caisa Simonsdotter muodostama perhe",
"Perhe is\u00e4lle Riippa, Nils Clemetsson",
"Roos af Ervalla, Ulv Jonsson ja , M\u00e4rta muodostama perhe",
"Rooseli, Clemet Olofsson ja , Beata muodostama perhe",
"Rooseli, Matts Clemetsson ja Mutonen, Christina M\u00e5rtensdotter muodostama perhe",
"Rooseli, Nils Olofsson ja , Margareta Ericsdotter muodostama perhe",
"Rooseli, Olof Nilsson ja , Anna Thomasdotter muodostama perhe",
"Roseli, Erasmus Thomasson ja , Lisa muodostama perhe",
"Roseli, Sigfrid Andersson ja , Margeta Mattsdotter muodostama perhe",
"Roseli, Thomas Sigfridsson ja , Agnes Mattsdotter muodostama perhe",
"Perhe is\u00e4lle Rosell, Clemet Nilsson",
"Perhe is\u00e4lle Rosell, Nils Olofsson",
"Perhe is\u00e4lle Rosell, Olof Clemetsson",
"Rossi, Mats Matsson ja , Elin Jacobsdotter muodostama perhe",
"Ruotsila, Johan Pehrsson ja , Elin Mattsdotter muodostama perhe",
"Ryss, Isac Mattsson ja Sepp\u00e4l\u00e4, Elin M\u00e5rtensdotter muodostama perhe",
"Sahraj\u00e4rvi, Erich J\u00f6ransson ja , Maria Hindrichsdotter muodostama perhe",
"Sahraj\u00e4rvi, J\u00f6ran Ericsson ja Koivisto, Anna Henrichsdotter muodostama perhe",
"Sahraj\u00e4rvi, J\u00f6ran J\u00f6ransson ja , Kirstin Henricsdotter muodostama perhe",
"Savola, Gustav Zachrisson ja Laurila, Lisa Clemetsdotter muodostama perhe",
"Savola, Hans Henricsson ja , Brita J\u00f6ransdotter muodostama perhe",
"Perhe is\u00e4lle Savola, Henric Ericsson",
"Savola, Zacharias Hansson ja , Anna muodostama perhe",
"Perhe is\u00e4lle Schartoff, Frans",
"Seiv\u00e4s, Eric M\u00e5rtensson ja , Anna Mattsdotter muodostama perhe",
"Seiv\u00e4s, Eric M\u00e5rtensson ja , Margareta muodostama perhe",
"Perhe is\u00e4lle Seiv\u00e4s, J\u00f6ran Ericsson",
"Seiv\u00e4s, M\u00e5rten Ericsson ja , Agneta muodostama perhe",
"Seiv\u00e4s, M\u00e5rten Ericsson ja , Anna muodostama perhe",
"Seiv\u00e4s, M\u00e5rten J\u00f6ransson ja , Anna Sigfridsdotter muodostama perhe",
"Seiv\u00e4s, M\u00e5rten J\u00f6ransson ja , Caisa Michelsdotter muodostama perhe",
"Perhe is\u00e4lle Seiv\u00e4s, M\u00e5rten Sigfridsson",
"Semenius, Eric Johansson ja Karppi, Maria Mattsdotter muodostama perhe",
"Perhe is\u00e4lle Sepp\u00e4, Eric",
"Perhe is\u00e4lle Sepp\u00e4, Sigfrid Ericsson",
"Sepp\u00e4l\u00e4, Georg Mathiae ja Pekka, Maria Johannis muodostama perhe",
"Perhe is\u00e4lle Sepp\u00e4l\u00e4, Henric M\u00e5rtensson",
"Perhe is\u00e4lle Sepp\u00e4l\u00e4, Henric Olsson",
"Sepp\u00e4l\u00e4, Matts Johansson ja , Walborg Johansdotter muodostama perhe",
"Perhe is\u00e4lle Sepp\u00e4l\u00e4, M\u00e5rten Henricsson",
"Perhe is\u00e4lle Sepp\u00e4l\u00e4, M\u00e5rten Henricsson",
"Sepp\u00e4l\u00e4, Olof Sigfridsson ja , Walborg Knutsdotter muodostama perhe",
"Sipil\u00e4, Henrik J\u00f6ransson ja , Lisa muodostama perhe",
"Sipil\u00e4, J\u00f6ran J\u00f6ransson ja Irjala, Kirstin Johansdotter muodostama perhe",
"Siurola, Thure Thomasson ja , Maria J\u00f6ransdotter muodostama perhe",
"Skytte, J\u00f6ns ja Trolle, Kerstin Birgersdotter muodostama perhe",
"Perhe is\u00e4lle Sk\u00e4nkare, Birger",
"Sorri, Carl Henrici ja Kauko, Walborg Andersdotter muodostama perhe",
"Sorri, Eric Caroli ja H\u00f6lli, Maria Mathiae muodostama perhe",
"Sorri, Henric ja , Brita Thomasdotter muodostama perhe",
"Sorri, Henric ja , Maria muodostama perhe",
"Sparre af Ellinge, Klaus Nilsson ja Bielke, Katarina Stensdotter muodostama perhe",
"Sparre af Ellinge, Nils Klausson ja Brock, Margareta Lagesdotter muodostama perhe",
"Sparre af Ellinge, Nils Svensson ja Tott, Pernilla Pedersdatter muodostama perhe",
"Sparre af Rossvik, Laurens Siggesson ja , Ingeborg Bengtsdotter muodostama perhe",
"Sparre af Rossvik, Sigge Larsson ja Natt och Dag, Kerstin M\u00e5nsdotter muodostama perhe",
"Sparre af Rossvik, Sigge Laurensson ja , Margareta Bengtsdotter muodostama perhe",
"Sparre av Aspn\u00e4s, Gisle Elinasson ja , Ingeborg Barnamsdotter muodostama perhe",
"Sparre av Aspn\u00e4s, Gisle Elinasson ja Bosson, Margareta Bengtsdotter muodostama perhe",
"Sparre av Aspn\u00e4s, Magnus Gisleson ja , Birgitta Knutsdotter muodostama perhe",
"Sparre av Tofta, Abj\u00f6rn Sixtensson ja Ulv, Ingeborg Ulfsdotter muodostama perhe",
"Perhe is\u00e4lle Sparre av Tofta, Karl Ulfsson",
"Sparre av Tofta, Ulf Abj\u00f6rnsson ja , Cristina Sigmundsdtr muodostama perhe",
"Sparre av Vik, Arvid Gustavsson ja And, Ramborg Israelsdotter muodostama perhe",
"Sparre av Vik, Arvid Gustavsson ja Sparre av Aspn\u00e4s, Helena Magnusdotter muodostama perhe",
"Sparre av Vik, Gustav Arvidsson ja , Kristina Petersdotter muodostama perhe",
"Perhe is\u00e4lle Stangenberg, Staffan",
"Perhe is\u00e4lle Stenbock, J\u00f6ns Olofsson",
"Stenbock, Olof J\u00f6nsson ja Barun, Estrid Knutsdotter muodostama perhe",
"Perhe is\u00e4lle Stierna, Jon Nilsson",
"Stiernkors, Ivar M\u00e5nsson ja Kurki, Elin J\u00f6nsdotter muodostama perhe",
"Stiernkors, Magnus Nilsson ja , Carin muodostama perhe",
"Stiernkors, Nils Olofsson ja Tavast, Elin Nilsdotter muodostama perhe",
"Stiernkors, Olof Persson ja till Nyn\u00e4s, Karin muodostama perhe",
"Stiernsk\u00f6ld, G\u00f6ran Hansson ja Sparre af Rossvik, Ingeborg Siggesdotter muodostama perhe",
"Perhe is\u00e4lle Sture, Nils",
"Sture, Nils Bosson ja Bonde, Birgitta Karlsdotter muodostama perhe",
"Sture, Sten Svantesson den yngre ja Gyllenstierna, Christina Nilsdotter muodostama perhe",
"Sture, Svante Nilsson ja G\u00e4dda, Iliana Erengislesdotter muodostama perhe",
"Sture, Svante Stensson ja Leijonhufvud, M\u00e4rta Eriksdotter muodostama perhe",
"Sture, Sven Nilsson ja , Gunhild Matsdotter muodostama perhe",
"St\u00e5larm, Arvid Eriksson ja Kurki, Kristina Knutsdotter muodostama perhe",
"St\u00e5larm, Botvid ja Stiernkors, Botilla Nilsdotter muodostama perhe",
"St\u00e5larm, Erik Botvidsson ja Garp, Karin Olofsdotter muodostama perhe",
"Perhe is\u00e4lle Sv\u00e4rd, Herman",
"Perhe \u00e4idille Sv\u00e4rd, N",
"S\u00e4lli, Cnut Henricsson ja , Gertrud Pehrsdotter muodostama perhe",
"S\u00e4lli, J\u00f6ran Cnutsson ja , Carin Olofsdotter muodostama perhe",
"S\u00e4lli, Lars J\u00f6ransson ja , Margaretha Matthiae muodostama perhe",
"S\u00e4rkilahti, Nils Pedersson ja Kirves, Karin Olofsdotter muodostama perhe",
"S\u00f6derstr\u00f6m, Isaac Johansson ja , Anna Johansdotter muodostama perhe",
"Talola, Eric Nilsson ja , Gertrud Sigfridsdotter muodostama perhe",
"Talola, Gabriel Gabrielsson ja M\u00e4llinoja, Beata Sigfredsdotter muodostama perhe",
"Talola, Gabriel Michelsson ja Sepp\u00e4l\u00e4, Elin Michelsdotter muodostama perhe",
"Talola, Michel Ericsson ja , Carin Sigfridsdotter muodostama perhe",
"Talvia, J\u00f6ran Thomasson ja M\u00e4llinoja, Margeta Gabrielsdotter muodostama perhe",
"Perhe is\u00e4lle Tauranen, Henrik J\u00f6nsson",
"Perhe is\u00e4lle Tauranen, J\u00f6ns Henriksson",
"Tavast, Nils Olofsson ja , N Knutsdotter muodostama perhe",
"Tavast, Olof J\u00f6nsson ja , Karin muodostama perhe",
"Thott, Absalon Axel Aagesen ja Wirtenberg, Christence Pedersdotter muodostama perhe",
"Tiitola, Hendrich Mattsson ja , Anna Mattsdotter muodostama perhe",
"Tiitola, Henrich Henrichsson ja , Anna muodostama perhe",
"Tiitola, Hindrich Hendersson ja , Anna Andersdotter muodostama perhe",
"Tiitola, Matts Henrichsson ja , Lisa muodostama perhe",
"til Clausholm, Jens Jensen ja , Ide Lagesdatter muodostama perhe",
"till Grevsj\u00f6, Peder Eriksson ja , Kristina Toresdotter muodostama perhe",
"till N\u00e4s, Knut Eriksson ja Kurki, Elin Klasdotter muodostama perhe",
"Tjurhuvud, Abraham Brodersson ja , Margareta Petersdotter muodostama perhe",
"Tott, Axel Pedersen ja Krognos, Cathrine Axelsdatter muodostama perhe",
"Tott, Erik \u00c5kesson ja Moltke, Bertha Evertsdatter muodostama perhe",
"Tott, Hans \u00c5kesson ja Gyllenstierna, Kerstin Eriksdotter muodostama perhe",
"Tott, Peder Axelsen ja Grubbe, Juliane Pedersdatter muodostama perhe",
"Tott, T\u00f6nne Eriksson ja Bielke, Karin Eriksdotter muodostama perhe",
"Tott, \u00c5ke Axelsson ja Vinstorp, M\u00e4rta Bengtsdotter muodostama perhe",
"Tott, \u00c5ke Klasson ja Sparre af Rossvik, Ingeborg Siggesdotter muodostama perhe",
"Perhe is\u00e4lle Trolle, Birger",
"Trolle, Birger Knutsson ja , Katarina V\u00e4stensdotter muodostama perhe",
"Perhe is\u00e4lle Trolle, Knut Birgersson",
"Tuhola, Henric Henricsson ja Roseli, Sofia Erasmusdotter muodostama perhe",
"Tuhola, Henric J\u00f6ransson ja , Anna muodostama perhe",
"Tuhola, Matts Henricsson ja Anttila, Maria Henricsdotter muodostama perhe",
"Perhe is\u00e4lle Tvesk\u00e6g, Svend",
"Perhe is\u00e4lle Uldsax, Sakse Pedersen",
"Ulv, Holmger Karlsson ja Revelsta, Kristina Nilsdotter muodostama perhe",
"Perhe is\u00e4lle Ulv, Karl Karlsson",
"Perhe is\u00e4lle Ulv, Karl Philippusson",
"Perhe is\u00e4lle Ulv, Philippus Ulfsson",
"Ulv, Staffan Ulfsson ja , Iliana \u00c5kesdotter muodostama perhe",
"Perhe is\u00e4lle Ulv, Ulf Karlsson",
"Perhe is\u00e4lle Ulv, Ulf Philippusson",
"Ulv\u00e5sa, Magnus Gudmarsson ja Finsta, Katerina Birgersdotter muodostama perhe",
"Perhe is\u00e4lle Uotila, Erik Henriksson",
"Perhe is\u00e4lle Uotila, Olof Eriksson",
"Vasa, Cristiern Nilsson ja Moltke, Margareta Johansdotter muodostama perhe",
"Vasa, Erik Karlsson ja Vinstorp, Anna Karlsdotter muodostama perhe",
"Vasa, Karl Christiernsson ja Krummedige, Ebba Eriksdatter muodostama perhe",
"Vasa, Nils Kettilsson ja , Christina Jonsdotter muodostama perhe",
"Perhe is\u00e4lle Vendelbo, Peder",
"Vesto, M\u00e5rten Andersson ja Rasila, Lisa Ericsdotter muodostama perhe",
"Perhe is\u00e4lle Vihtinen, Michel J\u00f6nsson",
"Vinstorp, Bengt Uddesson ja Ulv, Kristina Staffansdotter muodostama perhe",
"Vinstorp, Karl Bengtsson ja , Katarina Lagesdotter muodostama perhe",
"Vinstorp, Udd Matsson ja , Ingrid Karlsdotter muodostama perhe",
"Vispe, Tyge Jensen ja , Cecilia muodostama perhe",
"Perhe is\u00e4lle von Thienen, Johan",
"Perhe is\u00e4lle von Vitzen, Tomas",
"V\u00e4nni, Heikki Matinpoika ja Pekka, Susanna Thomasdotter muodostama perhe",
"Perhe is\u00e4lle W\u00e4h\u00e4, Eskill",
"Ylinen, Eric Mattsson ja Peissu, Lisa Georgii muodostama perhe",
"Ylinen, Henric Olofsson ja , Sara Bertilsdotter muodostama perhe",
"Ylinen, Jacob Johansson ja Raukola, Brita Andersdotter muodostama perhe",
"Ylinen, Johan Henricsson ja Yrj\u00f6l\u00e4, Brita Michelsdotter muodostama perhe",
"Ylinen, Matthias Jacobsson ja M\u00f6hk\u00f6l\u00e4, Helena Henricsdotter muodostama perhe",
"Ylinen, Olof J\u00f6ransson ja , Valborg muodostama perhe",
"Yrj\u00f6l\u00e4, Bengt J\u00f6ransson ja , Sunniva Sigfridsdotter muodostama perhe",
"Yrj\u00f6l\u00e4, J\u00f6ran J\u00f6ransson ja , Gertrud J\u00f6ransdotter muodostama perhe",
"Yrj\u00f6l\u00e4, Thomas Michelsson ja , Brita Eskilsdotter muodostama perhe",
"\u00d6ra, Karl ja Stangenberg, Cecilia Staffansdotter muodostama perhe",
"\u00d6sterberg, Johan Isaksson ja Bergman, Anna Sofia muodostama perhe",
"\u00d6sterberg, Johan Fridolf ja Lindstr\u00f6m, Sofia Vilhelmina muodostama perhe",
"\u00d6yr\u00e4, Eric Olofsson ja , Caisa Johansdotter muodostama perhe",
"\u00d6yr\u00e4, Henric Andersson ja Seiv\u00e4s, Caisa M\u00e5rtensdotter muodostama perhe"
]
Dwr.ScriptLoaded('dwr_db_F_name_0.js');
