// This file is generated

I_death_place_0 = [
"",
"",
"Nybacka torp, Laakspohja, Lohja, Suomi",
"Paradis torp, Veijola, Lohja, Suomi",
"Paradis torp, Veijola, Lohja, Suomi",
"Portugali",
"",
"",
"",
"",
"",
"",
"Kinnari, Hinsala, Vesilahti, Suomi",
"",
"Moltsia, Sahalahti, Kangasala, Suomi",
"Pori, Suomi",
"P\u00e4tsiniemi, Toijala, Akaa, Suomi",
"Paatiala, Sahalahti, Kangasala, Suomi",
"",
"",
"Vesilahti, Suomi",
"",
"Haittola torp, Veijola, Lohja, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Savolan rustholli, Pakkala, Sahalahti, Kangasala, Suomi",
"",
"",
"Paradis torp, Veijola, Lohja, Suomi",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"",
"",
"",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Fagervik, Inkoo, Suomi",
"Haudanniemi, Toijala, Akaa, Suomi",
"Liukon rustholli, J\u00e4rvenranta, Vesilahti, Suomi",
"Fagervik, Inkoo, Suomi",
"Fagervik, Inkoo, Suomi",
"Sonasund, Inkoo, Suomi",
"Mattila, Paatiala, Sahalahti, Kangasala, Suomi",
"Heikkil\u00e4, Neulaniemi, Kangasala, Suomi",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"",
"",
"Pakkala, Sahalahti, Kangasala, Suomi",
"Rauma, Suomi",
"",
"",
"Pekka, Vatiala, Kangasala, Suomi",
"Mattila, Suomasema, Orivesi, Suomi",
"",
"",
"Fagervik, Inkoo, Suomi",
"Anttila, Raronsalo, Kangasala, Suomi",
"",
"",
"",
"Bernburg, Sachsen, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"",
"",
"Ruotsi",
"",
"Huseby, Ons\u00f8y, Fredrikstad, Norja",
"",
"",
"",
"",
"\u00d6ljym\u00e4ki, It\u00e4-Jerusalem",
"",
"",
"",
"",
"",
"Ohtola, Kangasala, Suomi",
"",
"",
"",
"",
"Yrj\u00f6l\u00e4, Vihasj\u00e4rvi, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Jussila, Mierola, Hattula, Suomi",
"",
"",
"Savolan rustholli, Pakkala, Sahalahti, Kangasala, Suomi",
"Kuhmalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"Sorri, Hinsala, Vesilahti, Suomi",
"",
"Florv\u00e5g, Ask\u00f8y, Norja",
"",
"Mattila, Ihari, Kangasala, Suomi",
"",
"Jaakkola, Nihattula, Hattula, Suomi",
"",
"Klemola, Ohtola, Kangasala, Suomi",
"",
"",
"",
"",
"Dragon torp, Laakspohja, Lohja, Suomi",
"",
"",
"",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"",
"",
"",
"",
"",
"Lillungs, \u00d6stersolberg, Inkoo, Suomi",
"",
"Raukola, Varala, Kangasala, Suomi",
"",
"",
"",
"",
"",
"Vehkalahti, Orivesi, Suomi",
"",
"Rossi, Epaala, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"P\u00e1fos, Kypros",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Slaget vid Gestilren, G\u00e4stre, Fr\u00f6sthults socken, Uppland, Ruotsi",
"",
"",
"",
"",
"",
"",
"",
"Nikula, Tiihala, Kangasala, Suomi",
"",
"",
"",
"Luikala, P\u00e4lk\u00e4ne, Suomi",
"",
"Sauvo, Immula, Lohja, Suomi",
"",
"",
"",
"",
"",
"",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Vreta kloster, \u00d6sterg\u00f6tland, Ruotsi",
"Paradis torp, Veijola, Lohja, Suomi",
"",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"",
"",
"",
"",
"",
"Jussilan rustholli, Rautio, Sahalahti, Kangasala, Suomi",
"Turva, Kuuliala, P\u00e4lk\u00e4ne, Suomi",
"",
"Raukola, Varala, Kangasala, Suomi",
"Vihtinen, Kangasala, Suomi",
"",
"Toosila, Kangasala, Suomi",
"",
"J\u00e4rvenp\u00e4\u00e4, Laurila, Haapaniemi, Kangasala, Suomi",
"",
"Saviniemi torp, Orivesi, Suomi",
"",
"",
"",
"Tunsberghus, T\u00f8nsberg, Norja",
"",
"",
"Norja",
"",
"",
"Haihunkoski, Viiala, Akaa, Suomi",
"Paatiala, Sahalahti, Kangasala, Suomi",
"",
"",
"Korpiniemi, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"Lillungs, \u00d6stersolberg, Inkoo, Suomi",
"",
"Joutsiniemi, Kangasala, Suomi",
"Estb\u00f6le, \u00c5minne s\u00e4teri, Pohja, Raasepori, Suomi",
"Norrbro, Tukholma, Ruotsi",
"\u00d6stersolberg, Inkoo, Suomi",
"",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"Koivisto, Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"Keskinen, Liuksiala, Kangasala, Suomi",
"",
"",
"",
"H\u00e4meenlinna, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Lihulan taistelu, Lihulan linna, P\u00e4rnumaa, Viro",
"",
"Visings\u00f6, Sm\u00e5land, Ruotsi",
"",
"",
"",
"",
"",
"",
"",
"",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"Pekka, Vatiala, Kangasala, Suomi",
"Odense, Syddanmark, Tanska",
"",
"",
"slaget vid Lena, Kungslena socken, V\u00e4sterg\u00f6tland, Ruotsi",
"",
"",
"Kiev",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Raikku, Kangasala, Suomi",
"",
"Mattilan rustholli, Per\u00e4l\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Sipil\u00e4n rustoholli, Vehoniemi, Kangasala, Suomi",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Maunu, Luukkaala, Kangasala, Suomi",
"",
"Portugali",
"Hettusen rustholli, Tursola, Sahalahti, Kangasala, Suomi",
"",
"\u00d6rebro, Ruotsi",
"",
"",
"",
"",
"",
"",
"",
"Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"M\u00e4llinoja, M\u00e4lkil\u00e4, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Laatu, Saviniemi, Kylm\u00e4koski, Akaa, Suomi",
"Reins kloster, Rissa, Tr\u00f8ndelag, Norja",
"",
"",
"Mattilan rustholli, Per\u00e4l\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"",
"",
"",
"Taustiala, Sahalahti, Kangasala, Suomi",
"",
"",
"Rautio, Sahalahti, Kangasala, Suomi",
"",
"",
"Sorri, Hinsala, Vesilahti, Suomi",
"",
"",
"Vatiala, Kangasala, Suomi",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"Estb\u00f6le, \u00c5minne s\u00e4teri, Pohja, Raasepori, Suomi",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"Pajunen, Raikku, Kangasala, Suomi",
"",
"Klemola, Ohtola, Kangasala, Suomi",
"Str\u00f6mb\u00e4ck, Laukko, Vesilahti, Suomi",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Irjalan rustholli, Takahuhti, Messukyl\u00e4, Tampere, Suomi",
"Sahalahti, Kangasala, Suomi",
"Kittfall, Lohja, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"Mattilan rustholli, Per\u00e4l\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Heikkil\u00e4, Rautio, Sahalahti, Kangasala, Suomi",
"Eerola, Vehkalahti, Orivesi, Suomi",
"Liukon rustholli, J\u00e4rvenranta, Vesilahti, Suomi",
"",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"T\u00f6yk\u00e4n\u00e4, Sahalahti, Kangasala, Suomi",
"Fagervik, Inkoo, Suomi",
"Vehoniemi, Kangasala, Suomi",
"Lillungs, \u00d6stersolberg, Inkoo, Suomi",
"",
"",
"Harola, Talviainen, Orivesi, Suomi",
"Paradis torp, Veijola, Lohja, Suomi",
"",
"",
"",
"Kottila, Paatiala, Sahalahti, Kangasala, Suomi",
"V\u00e4nni, V\u00e4nninsalo, Kangasala, Suomi",
"Yrj\u00f6l\u00e4, Vihasj\u00e4rvi, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Karppi, S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Haittola torp, Veijola, Lohja, Suomi",
"Kiev",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Fagervik, Inkoo, Suomi",
"",
"",
"Monnila, Pikku-Parola, H\u00e4meenlinna, Suomi",
"",
"",
"",
"",
"",
"Vadstena kloster, Vadstena, \u00d6sterg\u00f6tland, Ruotsi",
"",
"Portugali",
"Ylinen, Kautiala, Kangasala, Suomi",
"",
"",
"",
"",
"Mets\u00e4-Heikkil\u00e4, Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"",
"Helgeseter kloster, Trondheim, Norja",
"",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"Nikkil\u00e4, K\u00f6yr\u00e4, Kangasala, Suomi",
"",
"Tanska",
"Yrj\u00f6l\u00e4, Vihasj\u00e4rvi, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"Karppi, S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Huti, Sauvala, Kalvola, H\u00e4meenlinna, Suomi",
"Talvia, Tiihala, Kangasala, Suomi",
"Perttula, Siitama, Orivesi, Suomi",
"Sachsen, Pyh\u00e4 saksalais-roomalainen keisarikunta",
"",
"",
"",
"Yrj\u00f6l\u00e4, Vihasj\u00e4rvi, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"Arran rustoholi, Moltsia, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"V\u00e4stra Tollstads socken, \u00d6sterg\u00f6tland, Ruotsi",
"Slaget vid Gestilren, G\u00e4stre, Fr\u00f6sthults socken, Uppland, Ruotsi",
"Bergen, Norja",
"Kittfall, Lohja, Suomi",
"Sahalahti, Kangasala, Suomi",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Tukholma, Ruotsi",
"",
"Roskilde, Sj\u00e6lland, Tanska",
"",
"Ruotsi",
"",
"",
"",
"",
"Vordingborg slot, Vordingborg, Sj\u00e6lland, Tanska",
"Kinnari, Hinsala, Vesilahti, Suomi",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"",
"Vehkalahti, Orivesi, Suomi",
"",
"R\u00e4ih\u00e4l\u00e4, Pakkala, Sahalahti, Kangasala, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kinnari, Hinsala, Vesilahti, Suomi",
"",
"Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"",
"Kiesil\u00e4, Niemenkyl\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"Haapasaari, Kuhmalahti, Kangasala, Suomi",
"",
"",
"Tanska",
"",
"",
"Pekka, Vatiala, Kangasala, Suomi",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"Isolahti, Sahalahti, Kangasala, Suomi",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Heikkil\u00e4, Hyk\u00f6nsalo, Kangasala, Suomi",
"Heikkil\u00e4, Hyk\u00f6nsalo, Kangasala, Suomi",
"Anttila, Raronsalo, Kangasala, Suomi",
"Siuro, Oriveden kyl\u00e4, Orivesi, Suomi",
"Pori, Suomi",
"",
"",
"Iso-Arran rustholli, Moltsia, Sahalahti, Kangasala, Suomi",
"",
"Arran rustoholi, Moltsia, Sahalahti, Kangasala, Suomi",
"Iso-Arran rustholli, Moltsia, Sahalahti, Kangasala, Suomi",
"",
"",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"Puola",
"Tanska",
"",
"",
"",
"",
"",
"",
"",
"",
"Fagervik, Inkoo, Suomi",
"Fagervik, Inkoo, Suomi",
"B\u00e4cks torparen, Myrans, Siuntio, Suomi",
"Mangs, J\u00f6nsb\u00f6le, Lohja, Suomi",
"",
"Benhamra, Vada socken, Uppland, Ruotsi",
"",
"",
"",
"",
"",
"",
"Tukholma, Ruotsi",
"",
"Viipuri, Luovutettu Karjala",
"",
"",
"",
"",
"Marieborg slott, Enk\u00f6ping, Uppland, Ruotsi",
"",
"",
"",
"",
"G\u00e4ddeholm, S\u00f6dermanland, Ruotsi",
"",
"Vesilahti, Suomi",
"Pirkkala, Suomi",
"Pirkkala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"J\u00e4rvenp\u00e4\u00e4, Laurila, Haapaniemi, Kangasala, Suomi",
"",
"",
"",
"Tukholma, Ruotsi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Sankt J\u00f8rgensbjerg",
"",
"",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kirkwall, Orkneysaaret, Skotlanti",
"Vordingborg slot, Vordingborg, Sj\u00e6lland, Tanska",
"",
"Fagervik, Inkoo, Suomi",
"Svart\u00e5, Raasepori, Suomi",
"Fagervik, Inkoo, Suomi",
"Fagervik, Inkoo, Suomi",
"",
"",
"",
"",
"Turku, Suomi",
"Suomi",
"Parainen, Suomi",
"",
"",
"Vadstena, \u00d6sterg\u00f6tland, Ruotsi",
"",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"M\u00f6hk\u00f6l\u00e4, Taustiala, Sahalahti, Kangasala, Suomi",
"Vehkalahti, Orivesi, Suomi",
"Eerola, Vehkalahti, Orivesi, Suomi",
"Eerola, Vehkalahti, Orivesi, Suomi",
"Sepp\u00e4l\u00e4, Pakkala, Sahalahti, Kangasala, Suomi",
"Eskola, Haapasaari, Kuhmalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"Sarvanta, Vehmainen, Messukyl\u00e4, Tampere, Suomi",
"",
"",
"",
"",
"",
"Paukkala, Ohtola, Kangasala, Suomi",
"Messukyl\u00e4, Tampere, Suomi",
"Messukyl\u00e4, Tampere, Suomi",
"Str\u00f6mb\u00e4ck, Laukko, Vesilahti, Suomi",
"",
"Tanska",
"",
"",
"Haapaniemi, Kisko, Salo, Suomi",
"",
"",
"",
"",
"",
"Tampere, Suomi",
"",
"",
"",
"",
"",
"",
"Norja",
"",
"",
"Glads rakuunatorppa, Veijola, Lohja, Suomi",
"Glads rakuunatorppa, Veijola, Lohja, Suomi",
"Pori, Suomi",
"Pyh\u00e4maa, Uusikaupunki, Suomi",
"Lyypekki, Saksan liittotasavalta",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"H\u00f6rningsholms slott, M\u00f6rk\u00f6 socken, S\u00f6dermanland, Ruotsi",
"",
"",
"Viipuri, Luovutettu Karjala",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"Pakkala, Sahalahti, Kangasala, Suomi",
"Pakkala, Sahalahti, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4, Taustiala, Sahalahti, Kangasala, Suomi",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"Juusela, Ilola, Sahalahti, Kangasala, Suomi",
"Harkki, Haihunkoski, Viiala, Akaa, Suomi",
"Vesto, Narva, Vesilahti, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"Harola, Talviainen, Orivesi, Suomi",
"Karppi, S\u00e4yn\u00e4joki, Orivesi, Suomi",
"",
"",
"Heikkil\u00e4, Rautio, Sahalahti, Kangasala, Suomi",
"Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"Mets\u00e4-Heikkil\u00e4, Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"",
"Heikkil\u00e4, Sarkkila, Viiala, Akaa, Suomi",
"Rautio, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"Heikkil\u00e4, Hyk\u00f6nsalo, Kangasala, Suomi",
"",
"Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"Heikkil\u00e4, Neulaniemi, Kangasala, Suomi",
"",
"H\u00f6llil\u00e4, V\u00e4nnil\u00e4, Vesilahti, Suomi",
"Heikkil\u00e4, Neulaniemi, Kangasala, Suomi",
"",
"Eerola, Vehkalahti, Orivesi, Suomi",
"Kangasala, Suomi",
"Vesilahti, Suomi",
"",
"Heikkil\u00e4n rustholli, Ania, Pirkkala, Suomi",
"",
"",
"",
"Mets\u00e4-Heikkil\u00e4, Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"V\u00e4nni, V\u00e4nninsalo, Kangasala, Suomi",
"",
"",
"Sahalahti, Kangasala, Suomi",
"Vihtinen, Kangasala, Suomi",
"",
"",
"Paavola, Haviseva, Kangasala, Suomi",
"Rautio, Sahalahti, Kangasala, Suomi",
"Hettusen rustholli, Tursola, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"",
"Tursola, Sahalahti, Kangasala, Suomi",
"",
"Hiiren rustholli, Miemola, Lemp\u00e4\u00e4l\u00e4, Suomi",
"",
"Laurila, Haapaniemi, Kangasala, Suomi",
"",
"",
"Hinkkalan rustholli, Vedentaka, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"Lintulan rustholli, Paalila, Kangasala, Suomi",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Karuna, Sauvo, Suomi",
"K\u00e4r\u00e4v\u00e4, Vuoltee, Kylm\u00e4koski, Akaa, Suomi",
"",
"",
"\u00c5by pr\u00e4stg\u00e5rd, Norrk\u00f6ping, \u00d6sterg\u00f6tland, Ruotsi",
"",
"",
"",
"",
"Suomi",
"Saviniemi, Kylm\u00e4koski, Akaa, Suomi",
"",
"",
"",
"Monnila, Pikku-Parola, H\u00e4meenlinna, Suomi",
"",
"",
"Eskola, Haapasaari, Kuhmalahti, Kangasala, Suomi",
"Kuhmalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"slaget vid Lena, Kungslena socken, V\u00e4sterg\u00f6tland, Ruotsi",
"",
"Slaget ved Viborg, Jylland, Tanska",
"",
"",
"",
"Kustaa III:n sota",
"Iso-Arran rustholli, Moltsia, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"H\u00f6llil\u00e4, V\u00e4nnil\u00e4, Vesilahti, Suomi",
"",
"Sorri, Hinsala, Vesilahti, Suomi",
"H\u00f6llil\u00e4, V\u00e4nnil\u00e4, Vesilahti, Suomi",
"",
"H\u00f6llil\u00e4, V\u00e4nnil\u00e4, Vesilahti, Suomi",
"H\u00f6lli, T\u00f6yk\u00e4n\u00e4, Sahalahti, Kangasala, Suomi",
"B\u00e4cks torparen, Myrans, Siuntio, Suomi",
"Inkoo, Suomi",
"Herdedal, Inkoo, Suomi",
"Fagervik, Inkoo, Suomi",
"",
"",
"",
"",
"Irjalan rustholli, Takahuhti, Messukyl\u00e4, Tampere, Suomi",
"Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"",
"",
"Jaakkola, Kuru, Kangasala, Suomi",
"Tampere, Suomi",
"Kaakila, Vesilahti, Suomi",
"Tampere, Suomi",
"Hervanta, Tampere, Suomi",
"",
"Hattula, Suomi",
"Rautio, Sahalahti, Kangasala, Suomi",
"Rautio, Sahalahti, Kangasala, Suomi",
"",
"Eerolan rustholli, Rautio, Sahalahti, Kangasala, Suomi",
"Juusela, Ilola, Sahalahti, Kangasala, Suomi",
"Kottila, Paatiala, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"",
"",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Karppi, S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Karppi, S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Karppi, S\u00e4yn\u00e4joki, Orivesi, Suomi",
"Karppi, S\u00e4yn\u00e4joki, Orivesi, Suomi",
"",
"",
"",
"",
"",
"",
"Sorri, Hinsala, Vesilahti, Suomi",
"",
"",
"",
"",
"Pakkala, Sahalahti, Kangasala, Suomi",
"",
"",
"Pakkala, Sahalahti, Kangasala, Suomi",
"Tampere, Suomi",
"Tampere, Suomi",
"",
"",
"Tampere, Suomi",
"",
"",
"",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Kiesil\u00e4, Niemenkyl\u00e4, M\u00e4ntt\u00e4-Vilppula, Suomi",
"",
"",
"Kinnari, Hinsala, Vesilahti, Suomi",
"Kinnari, Hinsala, Vesilahti, Suomi",
"Kinnari, Hinsala, Vesilahti, Suomi",
"",
"Ohralahti, S\u00e4ij\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Kinnari, Hinsala, Vesilahti, Suomi",
"",
"",
"Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Klemola, Ohtola, Kangasala, Suomi",
"Klemola, Ohtola, Kangasala, Suomi",
"",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Paatiala, Sahalahti, Kangasala, Suomi",
"Kottila, Paatiala, Sahalahti, Kangasala, Suomi",
"Kottila, Paatiala, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Hov, Hovs socken i \u00d6sterg\u00f6tland, G\u00f6strings h\u00e4rad, \u00d6sterg\u00f6tland, Ruotsi",
"",
"",
"",
"",
"",
"",
"",
"",
"Grabbacka, Karjaa, Raasepori, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Vesto, Narva, Vesilahti, Suomi",
"K\u00e4r\u00e4v\u00e4, Vuoltee, Kylm\u00e4koski, Akaa, Suomi",
"",
"K\u00e4r\u00e4v\u00e4, Vuoltee, Kylm\u00e4koski, Akaa, Suomi",
"",
"",
"",
"",
"",
"",
"Vedentaka, S\u00e4\u00e4ksm\u00e4ki, Valkeakoski, Suomi",
"",
"Saviniemi, Kylm\u00e4koski, Akaa, Suomi",
"Bergen, Norja",
"",
"M\u00f6hk\u00f6l\u00e4, Taustiala, Sahalahti, Kangasala, Suomi",
"",
"",
"Laurila, Haapaniemi, Kangasala, Suomi",
"Laurila, Haapaniemi, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Laurilan rustholli, Taustiala, Sahalahti, Kangasala, Suomi",
"Smeds torpet, Liuksiala, Kangasala, Suomi",
"Laurilan rustholli, Taustiala, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"",
"Sarkkila, Viiala, Akaa, Suomi",
"",
"Haraldsted skog, Ringsted, Sj\u00e6lland, Tanska",
"",
"",
"",
"Tukholman veril\u00f6yly, Stortorget, Tukholma, Ruotsi",
"",
"",
"",
"Stegeholm, V\u00e4stervik, Sm\u00e5land, Ruotsi",
"Vesilahti, Suomi",
"Pyh\u00e4maa, Uusikaupunki, Suomi",
"Rauma, Suomi",
"",
"",
"K\u00e4r\u00e4v\u00e4, Vuoltee, Kylm\u00e4koski, Akaa, Suomi",
"Vuoltee, Kylm\u00e4koski, Akaa, Suomi",
"Ojala, Liuksiala, Kangasala, Suomi",
"Nekala, Tampere, Suomi",
"Mangs, J\u00f6nsb\u00f6le, Lohja, Suomi",
"Lassa, Kittfall, Lohja, Suomi",
"",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"Sipil\u00e4n rustoholli, Vehoniemi, Kangasala, Suomi",
"",
"Liukon rustholli, J\u00e4rvenranta, Vesilahti, Suomi",
"Kinnari, Hinsala, Vesilahti, Suomi",
"Liukon rustholli, J\u00e4rvenranta, Vesilahti, Suomi",
"Liukon rustholli, J\u00e4rvenranta, Vesilahti, Suomi",
"",
"",
"",
"Luikko, Kaltsila, Vesilahti, Suomi",
"Lyypekki, Saksan liittotasavalta",
"Str\u00f6mb\u00e4ck, Laukko, Vesilahti, Suomi",
"",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Ala-Siukola, Suinula, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Marttila, Liponsalmi, Kuorevesi, J\u00e4ms\u00e4, Suomi",
"Mattilan rustholli, Per\u00e4l\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Mattila, Paatiala, Sahalahti, Kangasala, Suomi",
"",
"P\u00e4tsiniemi, Toijala, Akaa, Suomi",
"Harkki, Haihunkoski, Viiala, Akaa, Suomi",
"Maunu, Luukkaala, Kangasala, Suomi",
"Pajunen, Raikku, Kangasala, Suomi",
"Joutsiniemi, Kangasala, Suomi",
"Mets\u00e4-Heikkil\u00e4, Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"Ohralahti, S\u00e4ij\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Jaakkola, Kuru, Kangasala, Suomi",
"Mattila, Ihari, Kangasala, Suomi",
"",
"",
"Mikkola, Monikkala, Kangasala, Suomi",
"",
"Monikkala, Kangasala, Suomi",
"",
"",
"",
"",
"Uppsala, Uppland, Ruotsi",
"Sikkinen, Haurala, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Vehkalahti, Orivesi, Suomi",
"",
"",
"",
"",
"Mutonen, Riiti\u00e4l\u00e4, Viiala, Akaa, Suomi",
"Liukon rustholli, J\u00e4rvenranta, Vesilahti, Suomi",
"",
"M\u00e4llinoja, M\u00e4lkil\u00e4, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"Talvia, Tiihala, Kangasala, Suomi",
"",
"",
"Ylinen, Kautiala, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4, Taustiala, Sahalahti, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4, Taustiala, Sahalahti, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4, Taustiala, Sahalahti, Kangasala, Suomi",
"Taustiala, Sahalahti, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4, Taustiala, Sahalahti, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"Suomi",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Niittum\u00e4ki, Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"",
"Perttula, Siitama, Orivesi, Suomi",
"Nikkil\u00e4, K\u00f6yr\u00e4, Kangasala, Suomi",
"",
"",
"",
"",
"Talvia, Tiihala, Kangasala, Suomi",
"Monnila, Pikku-Parola, H\u00e4meenlinna, Suomi",
"",
"Vesilahti, Suomi",
"Ohralahti, S\u00e4ij\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Vehoniemi, Kangasala, Suomi",
"",
"",
"Kangasala, Suomi",
"Pajunen, Raikku, Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Pajunen, Raikku, Kangasala, Suomi",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"",
"Raukola, Varala, Kangasala, Suomi",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"",
"Peissun rustholli, Salmentaka, P\u00e4lk\u00e4ne, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Toosi, Vatiala, Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Eerolan rustholli, Rautio, Sahalahti, Kangasala, Suomi",
"Uotila, Luikala, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"Perttula, Siitama, Orivesi, Suomi",
"",
"Perttula, Siitama, Orivesi, Suomi",
"Perttula, Siitama, Orivesi, Suomi",
"Mets\u00e4-Heikkil\u00e4, Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"",
"",
"",
"",
"",
"Schlei, Schleswig, S\u00f8nderjylland, Tanska",
"",
"",
"",
"",
"Ohralahti, S\u00e4ij\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"Lemp\u00e4\u00e4l\u00e4, Suomi",
"",
"",
"",
"",
"",
"Haihunkoski, Viiala, Akaa, Suomi",
"",
"",
"",
"",
"",
"Ylinen, Kautiala, Kangasala, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"Joutsiniemi, Kangasala, Suomi",
"",
"Raukola, Varala, Kangasala, Suomi",
"Raukola, Varala, Kangasala, Suomi",
"Naantali, Suomi",
"",
"",
"",
"",
"",
"Hervanta, Tampere, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"Tuhola, Apajapohja, Kangasala, Suomi",
"",
"Rooseli, Lohnattila, Vesilahti, Suomi",
"",
"",
"Raukola, Varala, Kangasala, Suomi",
"Rossi, Epaala, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Laurilan rustholli, Taustiala, Sahalahti, Kangasala, Suomi",
"",
"",
"Savolan rustholli, Pakkala, Sahalahti, Kangasala, Suomi",
"",
"Suorama, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"Seiv\u00e4s, Onkem\u00e4ki, Vesilahti, Suomi",
"",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"",
"",
"Pekka, Vatiala, Kangasala, Suomi",
"",
"",
"",
"Sepp\u00e4l\u00e4, Keljo, Sahalahti, Kangasala, Suomi",
"",
"",
"",
"",
"Takahuhti, Messukyl\u00e4, Tampere, Suomi",
"",
"Raukola, Varala, Kangasala, Suomi",
"",
"",
"",
"",
"Sorri, Hinsala, Vesilahti, Suomi",
"Sorri, Hinsala, Vesilahti, Suomi",
"",
"Ohralahti, S\u00e4ij\u00e4, Lemp\u00e4\u00e4l\u00e4, Suomi",
"",
"",
"",
"",
"",
"Vadstena, \u00d6sterg\u00f6tland, Ruotsi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Nyk\u00f6pingshus, Nyk\u00f6ping, S\u00f6dermanland, Ruotsi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Turun linna, Turku, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"M\u00e4laren, S\u00f6dermanland, Ruotsi",
"V\u00e4ster\u00e5s, V\u00e4stmanland, Ruotsi",
"Uppsala, Uppland, Ruotsi",
"",
"",
"",
"Kankaisten kartano, Masku, Suomi",
"",
"",
"",
"",
"S\u00e4llin rustholli, Sotavalta, Lemp\u00e4\u00e4l\u00e4, Suomi",
"S\u00e4llin rustholli, Sotavalta, Lemp\u00e4\u00e4l\u00e4, Suomi",
"",
"Gr\u00f6nkulla torp, Utan\u00e5ker, Inkoo, Suomi",
"Glads rakuunatorppa, Veijola, Lohja, Suomi",
"",
"M\u00e4llinoja, M\u00e4lkil\u00e4, P\u00e4lk\u00e4ne, Suomi",
"K\u00e4rv\u00e4nt\u00e4l\u00e4, P\u00e4lk\u00e4ne, Suomi",
"",
"Talvia, Tiihala, Kangasala, Suomi",
"Heikkil\u00e4, Hyk\u00f6nsalo, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Mikkola, Monikkala, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"Tanska",
"",
"",
"Ruotsi",
"Varbergs f\u00e4stning, Varberg, Halland, Ruotsi",
"",
"Bosg\u00e5rden, M\u00f6lneby, \u00d6stra Fr\u00f6lunda socken, Kinds h\u00e4rad, V\u00e4sterg\u00f6tland, Ruotsi",
"",
"",
"",
"Turku, Suomi",
"",
"",
"",
"",
"",
"",
"Laurila, Haapaniemi, Kangasala, Suomi",
"Tuhola, Apajapohja, Kangasala, Suomi",
"",
"Heikkil\u00e4, Hyk\u00f6nsalo, Kangasala, Suomi",
"Gainsborough, Lincolnshire, Englanti",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"V\u00e4sterg\u00f6tland, Ruotsi",
"",
"",
"Viipurin linna, Viipuri, Luovutettu Karjala",
"Vreta kloster, \u00d6sterg\u00f6tland, Ruotsi",
"\u00d6versel\u00f6 socken, S\u00f6dermanland, Ruotsi",
"Tallinna, Harjumaa, Viro",
"",
"",
"",
"",
"Kinnari, Hinsala, Vesilahti, Suomi",
"Harkki, Haihunkoski, Viiala, Akaa, Suomi",
"",
"Mets\u00e4-Heikkil\u00e4, Heikkil\u00e4, Haapaniemi, Kangasala, Suomi",
"",
"",
"",
"V\u00e4sterg\u00f6tland, Ruotsi",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Toosi, Vatiala, Kangasala, Suomi",
"",
"",
"",
"",
"Sepp\u00e4l\u00e4, Pispala, Kangasala, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"Yrj\u00f6l\u00e4, Vihasj\u00e4rvi, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"",
"Yrj\u00f6l\u00e4, Vihasj\u00e4rvi, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Heikkil\u00e4, Neulaniemi, Kangasala, Suomi",
"Yrj\u00f6l\u00e4, Vihasj\u00e4rvi, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"",
"",
"Vohloinen, Lohja, Suomi",
"Risstens torp, Kirkniemi, Lohja, Suomi",
"",
"",
"H\u00f6llil\u00e4, V\u00e4nnil\u00e4, Vesilahti, Suomi",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_I_death_place_0.js');
