// This file is generated

F_marr_place_0 = [
"",
"Lohjan Pyh\u00e4n Laurin kirkko, Lohja, Suomi",
"",
"",
"",
"Ylinen, Kautiala, Kangasala, Suomi",
"",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Eskola, Vehkalahti, Orivesi, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"Vihtinen, Ohtola, Kangasala, Suomi",
"Savola, Kuru, Kangasala, Suomi",
"",
"",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"Kangasala, Suomi",
"\u00d6stersolberg, Inkoo, Suomi",
"T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"",
"",
"",
"Vehkalahti, Orivesi, Suomi",
"Ihari, Kangasala, Suomi",
"",
"",
"Niittum\u00e4ki, Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Pynn\u00f6l\u00e4, Riku, Kangasala, Suomi",
"Sukkila, Juupajoki, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"",
"Vehoniemi, Kangasala, Suomi",
"",
"Heikkil\u00e4, Hyk\u00f6nsalo, Kangasala, Suomi",
"",
"",
"Anttila, P\u00e4ilahti, Orivesi, Suomi",
"Klemola, Ohtola, Kangasala, Suomi",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"",
"Vohloinen, Lohja, Suomi",
"",
"Glads rakuunatorppa, Veijola, Lohja, Suomi",
"Str\u00f6mb\u00e4ck, Laukko, Vesilahti, Suomi",
"Tampere, Suomi",
"Tampere, Suomi",
"Keskinen, Liuksiala, Kangasala, Suomi",
"Tampere, Suomi",
"Vehoniemi, Kangasala, Suomi",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Vehoniemi, Kangasala, Suomi",
"",
"",
"Inkoo, Suomi",
"Lohjan Pyh\u00e4n Laurin kirkko, Lohja, Suomi"
]
Dwr.ScriptLoaded('dwr_db_F_marr_place_0.js');
