// This file is generated

I_short_name_0 = [
", Abraham Abrahamsson",
", Abraham Johan Abrahahamsson",
", Abram Mortensson",
", Anders Michelsson",
", Anna",
", Anna Andersdotter",
", Anna Andersdotter",
", Anna Henrichsdotter",
", Anna Henrichsdotter",
", Anna Mattsdotter",
", Anna Mattsdotter",
", Anna Petri",
", Anna Stina Catharinasdotter",
", Brita Andersdotter",
", Brita Thomasdotter",
", Caisa Hendricsdotter",
", Carin Johansdotter",
", Catharina Andersdotter",
", Chirstin Hansdotter",
", Clemet Samuelsson",
", Elisabeth Jacobsdotter",
", Eric Johansson",
", Eric Sigfridsson",
", Erich J\u00f6ransson",
", Erik Eriksson",
", Greta Johansdotter",
", Hedvig Albertina Henricsdotter",
", Hedvig Serafia Henriksdotter",
", Heikki Matinpoika",
", Helena Andersdotter",
", Helena Ericsdotter",
", Helena Henricsdotter",
", Helena Hermansdotter",
", Helena Mattsdotter",
", Hendrich Mattsson",
", Henric J\u00f6ransson",
", Henric Simonsson",
", Henrich Henrichsson",
", Henrich Johansson",
", Henrik Mattsson",
", Herman Ericsson",
", Hindrich Hindrichsson",
", Hindrich Hindrichsson",
", Ingeborg Mattsdotter",
", Jacob Jacobsson",
", Jacob Johansson",
", Jacob Johansson",
", Jacob Simonsson",
", Johan Ericsson",
", Johan Henrichsson",
", Johan Jacobsson",
", Johan Johansson",
", Johan Mathia",
", Johan Mattsson",
", Johan Gustaf Thomasson",
", Johan Henrik Johansson",
", Juho Vihtori Tuomaanpoika",
", J\u00f6ran Ericsson",
", J\u00f6ran J\u00f6ransson",
", Kirstin Henricsdotter",
", Lisa",
", Lisa",
", Lisa Georgii",
", Lisa Hendricsson",
", Lisa Mathia",
", Maria Eriksdotter",
", Maria Hindrichsdotter",
", Maria Johansdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Mattsdotter",
", Maria Michelsdotter",
", Maria M\u00e5rtensdotter",
", Maria Elisabeth Lovisa Gabrielsdotter",
", Maria Lovisa Eriksdotter",
", Matthias Jacobsson",
", Matts",
", Matts Clemetsson",
", Matts Henrichsson",
", Matts Marci",
", Michel Mattsson",
", Samuel Mattsson",
", Sophia Eskilsdotter",
", Sophia Henricsdotter",
", Susanna Juhontyt\u00e4r",
", Susanna Thomasdotter",
", Thomas Johansson",
", Thomas Michelsson",
", Thomas Thomae",
", Ulrika Vilhelmina Abrahamsdotter",
", Valborg Mattsdotter",
"Bergman, Anna Sofia",
"Boll, Eva Andersdotter",
"Frestadius, Lena Pehrsdotter",
"F\u00e4lt, Alexander Viktor",
"Glad, Carl",
"Glad, Ester Sofia",
"Glad, Jacob Jacobsson",
"Glad, Johannes Joel",
"H\u00f6gberg, Eric",
"Jokela, Edward Lauri",
"Jokela, Leo Ensio",
"Jokela, Rauha Signe",
"Keskinen, Heikki Juhonpoika",
"Keskinen, Johan Henrik",
"Keskinen, Kaarlo Elias",
"Keskinen, Kari",
"Keskinen, Martti Mikael",
"Keskinen, Siiri Matilda",
"Kratz, Marcus Johanis",
"Lindroos, Juha Henrik Juhanpoika",
"Lindroos, Kustaava Matilda Juhantyt\u00e4r",
"Lindstr\u00f6m, Sofia Vilhelmina",
"Orre, J\u00f6ran",
"Romu, Anna Lyyli",
"Semenius, Eric Johansson",
"S\u00f6derstr\u00f6m, Anna Johansdotter",
"S\u00f6derstr\u00f6m, Isaac Johansson",
"S\u00f6derstr\u00f6m, Sofia Isacsdotter",
"Toosi, Vilhelmiina Heikintyt\u00e4r",
"\u00d6sterberg, Ida Emilia",
"\u00d6sterberg, Johan Isaksson",
"\u00d6sterberg, Johan Fridolf",
"\u00d6sterberg, Matilda Sofia"
]
Dwr.ScriptLoaded('dwr_db_I_short_name_0.js');
