// This file is generated

I_birth_place_0 = [
"Paradis torp, Veijola, Lohja, Suomi",
"Veijola, Lohja, Suomi",
"",
"Kirkniemi, Lohja, Suomi",
"",
"",
"",
"Eerola, Vehkalahti, Orivesi, Suomi",
"",
"T\u00f6yr\u00e4niemi, P\u00e4lk\u00e4ne, Suomi",
"",
"Alanen, Isolahti, Sahalahti, Kangasala, Suomi",
"",
"Raukola, Varala, Kangasala, Suomi",
"",
"",
"",
"",
"",
"",
"",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"Orivesi, Suomi",
"",
"Orivesi, Suomi",
"Vihtinen, Ohtola, Kangasala, Suomi",
"V\u00e4nni, V\u00e4nninsalo, Kangasala, Suomi",
"Haittola torp, Veijola, Lohja, Suomi",
"Karppila, S\u00e4yn\u00e4joki, Orivesi, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"Savola, Kuru, Kangasala, Suomi",
"Orivesi, Suomi",
"",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"",
"",
"",
"Paukkala, Ohtola, Kangasala, Suomi",
"",
"",
"",
"Lillungs, \u00d6stersolberg, Inkoo, Suomi",
"",
"Ylinen, Kautiala, Kangasala, Suomi",
"Lintulan rustholli, Paalila, Kangasala, Suomi",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"Oriveden kyl\u00e4, Orivesi, Suomi",
"",
"",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Vetterkulla, Er\u00e4j\u00e4rvi, Orivesi, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Suomasema, Orivesi, Suomi",
"",
"",
"",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Mikkola, Monikkala, Kangasala, Suomi",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"",
"Keljo, Ihari, Kangasala, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"S\u00e4yn\u00e4joki, Orivesi, Suomi",
"",
"",
"",
"Lohja, Suomi",
"Niittum\u00e4ki, Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"",
"",
"",
"Raikku, Kangasala, Suomi",
"",
"",
"",
"Heikkil\u00e4, Hyk\u00f6nsalo, Kangasala, Suomi",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Anttila, Oriveden kyl\u00e4, Orivesi, Suomi",
"Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Sauvo, Immula, Lohja, Suomi",
"",
"Karjaa, Raasepori, Suomi",
"",
"Ojoinen, Vesilahti, Suomi",
"Pohja, Raasepori, Suomi",
"Veijola, Lohja, Suomi",
"Vohloinen, Lohja, Suomi",
"Siuntio, Suomi",
"Glads rakuunatorppa, Veijola, Lohja, Suomi",
"Raikku, Kangasala, Suomi",
"",
"Onkiniemi, Tampere, Suomi",
"Tampere, Suomi",
"Toosi, Vatiala, Kangasala, Suomi",
"Keskinen, Liuksiala, Kangasala, Suomi",
"Kangasala, Suomi",
"Tampere, Suomi",
"Suorama, Kangasala, Suomi",
"Ilkko, Kangasala, Suomi",
"Suomela, Kangasala, Suomi",
"Niittum\u00e4ki, Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Paukkala, Ohtola, Kangasala, Suomi",
"Lohja, Suomi",
"",
"P\u00f6ll\u00e4kk\u00e4l\u00e4, \u00c4yr\u00e4p\u00e4\u00e4, Luovutettu Karjala",
"Mattila, Paatiala, Sahalahti, Kangasala, Suomi",
"Lohja, Suomi",
"",
"Vihtij\u00e4rvi, Vihti, Suomi",
"Toosi, Vatiala, Kangasala, Suomi",
"Langi, J\u00f6nsb\u00f6le, Lohja, Suomi",
"Lohja, Suomi",
"V\u00e4lli, V\u00e4h\u00e4-Teutari, Lohja, Suomi",
"Bredvik torp, Bredvik, Karjaa, Raasepori, Suomi"
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
