// This file is generated

I_death_place_0 = [
"Nybacka torp, Laakspohja, Lohja, Suomi",
"Paradis torp, Veijola, Lohja, Suomi",
"Paradis torp, Veijola, Lohja, Suomi",
"Haittola torp, Veijola, Lohja, Suomi",
"",
"Paradis torp, Veijola, Lohja, Suomi",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Anttila, Orivesi, Orivesi, Suomi",
"Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"Mattila, Suomasema, Orivesi, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"Orivesi, Orivesi, Suomi",
"Mattila, Ihari, Kangasala, Suomi",
"Dragon torp, Laakspohja, Lohja, Suomi",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"Lillungs, \u00d6stersolberg, Inkoo, Suomi",
"Mattila, Ihari, Kangasala, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"Anttila, Orivesi, Orivesi, Suomi",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Niittum\u00e4ki, Sepp\u00e4l\u00e4, Hirvij\u00e4rvi, Juupajoki, Suomi",
"Sauvo, Immula, Lohja, Suomi",
"",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Toosi, Vatiala, Kangasala, Suomi",
"Paradis torp, Veijola, Lohja, Suomi",
"Anttila, Orivesi, Orivesi, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"M\u00f6hk\u00f6l\u00e4n rustholli, K\u00f6yr\u00e4, Kangasala, Suomi",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Anttila, Orivesi, Orivesi, Suomi",
"Toosila, Kangasala, Suomi",
"J\u00e4rvenp\u00e4\u00e4, Laurila, Haapaniemi, Kangasala, Suomi",
"Tiitola, Vehoniemi, Kangasala, Suomi",
"Saviniemi torp, Orivesi, Suomi",
"",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"Lillungs, \u00d6stersolberg, Inkoo, Suomi",
"Ylinen, Kautiala, Kangasala, Suomi",
"Anttilan rustholli, Onkkaala, P\u00e4lk\u00e4ne, Suomi",
"Anttila, Orivesi, Orivesi, Suomi",
"Orivesi, Orivesi, Suomi",
"\u00d6stersolberg, Inkoo, Suomi",
"Anttila, Orivesi, Orivesi, Suomi",
"",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Koivisto, Erkkil\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Keskinen, Liuksiala, Kangasala, Suomi",
"Sahraj\u00e4rvi, Juupajoki, Suomi",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"",
"Raikku, Kangasala, Suomi",
"Mikkola, Monikkala, Kangasala, Suomi",
"",
"Amsterdam torp, Sjundbyn kartano, Siuntio, Suomi",
"",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Anttila, Orivesi, Orivesi, Suomi",
"Anttila, Orivesi, Orivesi, Suomi",
"",
"Vehoniemi, Kangasala, Suomi",
"Lillungs, \u00d6stersolberg, Inkoo, Suomi",
"Paradis torp, Veijola, Lohja, Suomi",
"",
"Ylinen, Kautiala, Kangasala, Suomi",
"",
"Mikkola, Monikkala, Kangasala, Suomi",
"",
"V\u00e4nni, V\u00e4nninsalo, Kangasala, Suomi",
"Haittola torp, Veijola, Lohja, Suomi",
"Monikkala, Kangasala, Suomi",
"",
"V\u00e4nni, V\u00e4nninsalo, Kangasala, Suomi",
"",
"Toosi, Vatiala, Kangasala, Suomi",
"Siuro, Orivesi, Orivesi, Suomi",
"Hirvenoja, Liuksiala, Kangasala, Suomi",
"Pekka, Vatiala, Kangasala, Suomi",
"",
"Halvonoja, Yrj\u00f6l\u00e4, Sahraj\u00e4rvi, Juupajoki, Suomi",
"",
"J\u00e4rvenp\u00e4\u00e4, Laurila, Haapaniemi, Kangasala, Suomi",
"Paukkala, Ohtola, Kangasala, Suomi",
"Tampere, Suomi",
"",
"",
"Glads rakuunatorppa, Veijola, Lohja, Suomi",
"Glads rakuunatorppa, Veijola, Lohja, Suomi",
"Kustaa III:n sota",
"",
"Tampere, Suomi",
"Hervanta, Tampere, Suomi",
"Tampere, Suomi",
"Tampere, Suomi",
"",
"",
"Tampere, Suomi",
"",
"",
"Ojala, Liuksiala, Kangasala, Suomi",
"Nekala, Tampere, Suomi",
"",
"Vehoniemi, Kangasala, Suomi",
"Hervanta, Tampere, Suomi",
"Anttila, Orivesi, Orivesi, Suomi",
"Sonasund, Inkoo, Suomi",
"Gr\u00f6nkulla torp, Utan\u00e5ker, Inkoo, Suomi",
"Glads rakuunatorppa, Veijola, Lohja, Suomi",
"",
"Vohloinen, Lohja, Suomi",
"Risstens torp, Kirkniemi, Lohja, Suomi",
"",
""
]
Dwr.ScriptLoaded('dwr_db_I_death_place_0.js');
